### PR TITLE
CI: minor updates

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.almalinux-8, line 2 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210#-Mkvwg_ID-Swhp_vNhi9:-Mkvwg_ID-Swhp_vNhiA:b8fv324) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05b5a66a669827dda667da378d791f41daf89f86/utils/docker/images/Dockerfile.almalinux-8#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2021, Intel Corporation
> ```

If file have changes it's a new file, so the license should be `2021`

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.almalinux-8, line 2 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210#-Mkvwg_ID-Swhp_vNhi9:-Mkw61Kl4QK2ccJY8eTr:b-e0idv7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05b5a66a669827dda667da378d791f41daf89f86/utils/docker/images/Dockerfile.almalinux-8#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If file have changes it's a new file, so the license should be `2021`
</blockquote></details>

nope, as usual - this is copy-pasted from another file (CentOS image recipe), so the original license has to stay in place.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210#-:-MkwQGLMCxTdh5Rj0AHc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.almalinux-8, line 2 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1210#-Mkvwg_ID-Swhp_vNhi9:-Ml93S842DVRTag70Ldv:b5v40sk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/05b5a66a669827dda667da378d791f41daf89f86/utils/docker/images/Dockerfile.almalinux-8#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope, as usual - this is copy-pasted from another file (CentOS image recipe), so the original license has to stay in place.
</blockquote></details>

I thought about:
```cpp
# Dockerfile - a 'recipe' for Docker to build an image of almalinux-based
#              environment prepared for running libpmemobj-cpp tests.

```
It's not purely copy-paste, but I don't care

**Pull request merged**
