### PR TITLE
add readme to benchmarks and fix dividing by zero in radix bench

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @JanDorniak99)

___
*[benchmarks/readme.md, line 6 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT-4yV30nx6f-thijh:-MZT-4yV30nx6f-thiji:b-975qx9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L6)):*
> ```Markdown
> 
> Currently following benchmarks are available:
> - **concurrent_hash_map_insert_open**: this benchmark is used to measure time of inserting specified number of elements and time of runtime_initialize() in concurrent hash map.
> ```

add ` for runtime_initialize()
___
*[benchmarks/readme.md, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT-_oPB38YzvstIbD9:-MZT-_oPB38YzvstIbDA:b-508skj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L9)):*
> ```Markdown
> - **radix_tree**: this benchmark is used to compare times of basic operations in radix_tree and std::map.
> - **self_relative_pointer_assignment**: this benchmark is used to measure time of the assignment operator and the swap function for persistent_ptr and self_relative_ptr.
> - **self_relative_pointer_get**: this benchmark is used to measure time of getting and changing a specified number of elements from a persistent array using self_relative_ptr and persistent_ptr.
> ```

perhaps `getting` -> `accessing` 
___
*[benchmarks/readme.md, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT--Q1DgCMn9cgIqGJ:-MZT--Q1DgCMn9cgIqGK:bmu81an) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L11)):*
> ```Markdown
> - **self_relative_pointer_get**: this benchmark is used to measure time of getting and changing a specified number of elements from a persistent array using self_relative_ptr and persistent_ptr.
> 
> # Running
> ```

how to compile these benchmarks?
___
*[benchmarks/readme.md, line 14 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSywp33wL5xdlu6ivH:-MZSywp33wL5xdlu6ivI:b-u6pt8s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L14)):*
> ```Markdown
> 
> **Warning:**
> >All benchmarks shouldn't be run in a production environment, because they can cause problems with the content of the tested containers.
> ```

`All` -> `These`
___
*[benchmarks/readme.md, line 14 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSzK_IAgnUwq0sY7ua:-MZSzK_IAgnUwq0sY7ub:b-gjqfbd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L14)):*
> ```Markdown
> 
> **Warning:**
> >All benchmarks shouldn't be run in a production environment, because they can cause problems with the content of the tested containers.
> ```

`can cause problems with the content of the...` -> `can remove/modify existing data of the...`
___
*[benchmarks/readme.md, line 16 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSykqS2apjkhvMbFMm:-MZSykqS2apjkhvMbFMn:bcddsf6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L16)):*
> ```Markdown
> >All benchmarks shouldn't be run in a production environment, because they can cause problems with the content of the tested containers.
> 
> Each benchmark can need other input parameters. If you want to see usage of the certain benchmark, just run this benchmark's binary without any parameters, e.g.
> ```

`need other` -> `require various`
___
*[benchmarks/readme.md, line 17 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSy27H0pFt7A_DaDZ6:-MZSy27H0pFt7A_DaDZ7:b-gc7p74) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L17)):*
> ```Markdown
> 
> Each benchmark can need other input parameters. If you want to see usage of the certain benchmark, just run this benchmark's binary without any parameters, e.g.
> ```
> ```

pls make it
```
 ```sh
```
___
*[benchmarks/readme.md, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSxRsW29r0oDF71yQb:-MZSxRsW29r0oDF71yQc:by2mmc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L19)):*
> ```Markdown
> ```
> ./benchmark-self_relative_pointer_get
> ```
> ```

no EOF - add extra "enter" here
___
*[benchmarks/readme.md, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSzpL3Ao75f8U5VqNm:-MZSzpL3Ao75f8U5VqNn:b-9td2qb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L19)):*
> ```Markdown
> ```
> ./benchmark-self_relative_pointer_get
> ```
> ```

perhaps add an example of proper execution of some benchmark
___
*[benchmarks/radix/radix_tree.cpp, line 136 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT07xF2aJns7VXCYKv:-MZT07xF2aJns7VXCYKw:bwhcpd5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/radix/radix_tree.cpp#L136)):*
> ```cpp
> 	});
> 	print_time_per_element("Average access time (persistent radix tree): ",
> 			       radix_time, params.count / params.sample_size);
> ```

if sample size is 0 we also get the error
___
*[benchmarks/radix/radix_tree.cpp, line 214 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT0LMr8tHkr_4INano:-MZT0LMs8lmTCDLs0gwK:brhkqrg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/radix/radix_tree.cpp#L214)):*
> ```cpp
> 	if (argc > 4)
> 		params.sample_size = std::stoul(argv[4]);
> ```

maybe we actually should check some values here, right after reading the params

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[benchmarks/readme.md, line 6 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT-4yV30nx6f-thijh:-MZWrKDE6_WZNpngqivt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L6)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add ` for runtime_initialize()
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT-_oPB38YzvstIbD9:-MZWrQLcEZhcRHL-43OD:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps `getting` -> `accessing` 
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT--Q1DgCMn9cgIqGJ:-MZve0452xd--4qpB_1-:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

how to compile these benchmarks?
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 14 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSywp33wL5xdlu6ivH:-MZWrT4-4Hf8mmNVejdU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`All` -> `These`
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 14 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSzK_IAgnUwq0sY7ua:-MZWrhxW2tLeUmjV6g3t:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`can cause problems with the content of the...` -> `can remove/modify existing data of the...`
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 16 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSykqS2apjkhvMbFMm:-MZWro-1E08ofKw7SzNz:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`need other` -> `require various`
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 17 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSy27H0pFt7A_DaDZ6:-MZWrqwr0OxPfe6mbUEq:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it
```
 ```sh
```
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSxRsW29r0oDF71yQb:-MZWrsaN35skswOOpgFm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

no EOF - add extra "enter" here
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZSzpL3Ao75f8U5VqNm:-MZve12K8mt2Q9PRXqHa:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/readme.md#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add an example of proper execution of some benchmark
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 136 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT07xF2aJns7VXCYKv:-MZWyskCBb0y26Mi0UbH:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/radix/radix_tree.cpp#L136)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if sample size is 0 we also get the error
</blockquote></details>

Done.
___
*[benchmarks/radix/radix_tree.cpp, line 214 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZT0LMr8tHkr_4INano:-MZWyt-TC-_euCp7VDm1:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/50fef198466f2c017487495c8698a637d58d3179/benchmarks/radix/radix_tree.cpp#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe we actually should check some values here, right after reading the params
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[benchmarks/readme.md, line 11 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvrez921RZdRdGOTi4:-MZvrez921RZdRdGOTi5:bvgpyci) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L11)):*
> ```Markdown
> - **self_relative_pointer_get**: this benchmark is used to measure time of accessing and changing a specified number of elements from a persistent array using self_relative_ptr and persistent_ptr.
> 
> # Compiling
> ```

I guess these sections should be "##" instead of top-level "#"
___
*[benchmarks/readme.md, line 14 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvtpWS2xMQoi0gYHdB:-MZvtpWS2xMQoi0gYHdC:bmbvuzr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L14)):*
> ```Markdown
> 
> ```sh
> $ mkdir build
> ```

you want to do this step within this dir? (because it's not going to work I believe) If you want to run this in root dir, pls specify.
You can alternatively just specify to build as described in the top-level readme (but with assurance `BUILD_BENCHMARKS` option is ON)
___
*[benchmarks/readme.md, line 17 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvtxd875VGdyyhVuHo:-MZvtxd875VGdyyhVuHp:bghwses) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L17)):*
> ```Markdown
> $ cd build
> $ cmake ..
> $ make benchmarks
> ```

I'm not sure we have such target (we could add this target, but for now we have only per benchmark target, like `make benchmark-radix_tree`).
Alternatively you can enter benchmarks dir and then just run `make`

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[benchmarks/readme.md, line 11 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvrez921RZdRdGOTi4:-MZvyEzQ9mDGTvRFRa95:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess these sections should be "##" instead of top-level "#"
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 14 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvtpWS2xMQoi0gYHdB:-MZw2hs93wA1rRJCXvpa:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you want to do this step within this dir? (because it's not going to work I believe) If you want to run this in root dir, pls specify.
You can alternatively just specify to build as described in the top-level readme (but with assurance `BUILD_BENCHMARKS` option is ON)
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 17 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvtxd875VGdyyhVuHo:-MZw-T116q1FMYyWbBa9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure we have such target (we could add this target, but for now we have only per benchmark target, like `make benchmark-radix_tree`).
Alternatively you can enter benchmarks dir and then just run `make`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[benchmarks/readme.md, line 14 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvtpWS2xMQoi0gYHdB:-MZwM4sC8orUvmPeQ-dE:b-or3fz2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L14)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You didn't mention you have to be in the build dir. Now some random `cd benchmarks` may be confusing.
___
*[benchmarks/readme.md, line 13 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZwLVnd2fq_7ecwP-FH:-MZwLVnd2fq_7ecwP-FI:b-crc7w9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42f7cb6985f24d604e84c3fc3bd508460d5daff3/benchmarks/readme.md#L13)):*
> ```Markdown
> ## Compiling
> 
> Follow build steps for your OS (as described in top-level README), just make sure that the BUILD_BENCHMARKS options is ON.
> ```

`option` singular ;)
___
*[benchmarks/readme.md, line 24 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZwMJ3X0ooaE9OJViMd:-MZwMJ3X0ooaE9OJViMe:b86bo3k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42f7cb6985f24d604e84c3fc3bd508460d5daff3/benchmarks/readme.md#L24)):*
> ```Markdown
> ```sh
> $ cd benchmarks
> $ make benchmark-name_of_benchmark
> ```

perhaps make it `benchmark-<name_of...>`
___
*[benchmarks/readme.md, line 32 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZwMX3MAESIoARZu3-r:-MZwMX3MAESIoARZu3-s:b-cv6c3o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42f7cb6985f24d604e84c3fc3bd508460d5daff3/benchmarks/readme.md#L32)):*
> ```Markdown
> >These benchmarks shouldn't be run in a production environment, because they can remove/modify existing data in the tested containers.
> 
> Each benchmark can require various input parameters. If you want to see the usage of the certain benchmark, just run this benchmark's binary without any parameters, e.g.
> ```

of **a** certain benchmark

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[benchmarks/readme.md, line 14 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZvtpWS2xMQoi0gYHdB:-M_-wiRJ4q6U8Gl1C4uN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d598b73e29e56459bc949ca96b720cd3219e8321/benchmarks/readme.md#L14)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

You didn't mention you have to be in the build dir. Now some random `cd benchmarks` may be confusing.
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 13 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZwLVnd2fq_7ecwP-FH:-M_-wVjl7Oeokp7RGw1q:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42f7cb6985f24d604e84c3fc3bd508460d5daff3/benchmarks/readme.md#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`option` singular ;)
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 24 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZwMJ3X0ooaE9OJViMd:-M_-wnYD3GqU_-dKA7qg:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42f7cb6985f24d604e84c3fc3bd508460d5daff3/benchmarks/readme.md#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make it `benchmark-<name_of...>`
</blockquote></details>

Done.
___
*[benchmarks/readme.md, line 32 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-MZwMX3MAESIoARZu3-r:-M_-wx8kD-WC5uU8wdns:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/42f7cb6985f24d604e84c3fc3bd508460d5daff3/benchmarks/readme.md#L32)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of **a** certain benchmark
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-:-M_01t2LCg6q5xpKO4gt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[benchmarks/radix/radix_tree.cpp, line 208 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-M_049o0D6R1DYLYddwR:-M_049o0D6R1DYLYddwS:b3p7k05) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88d424588b0622bfd23d3d824775e8c61f4a5d14/benchmarks/radix/radix_tree.cpp#L208)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
> 	if (argc > 2) {
> 		params.count = std::stoul(argv[2]);
> 		if (params.count == 0) {
> 			std::cerr << "Number of the elements must be > 0"
> 				  << std::endl;
> 			return 1;
> 		}
> 	}
> 	if (argc > 3) {
> 		params.batch_size = std::stoul(argv[3]);
> 		if (params.batch_size == 0) {
> 			std::cerr << "Batch size must be > 0" << std::endl;
> 			return 1;
> 		}
> 	}
> 	if (argc > 4) {
> 		params.sample_size = std::stoul(argv[4]);
> 		if (params.sample_size == 0) {
> 			std::cerr << "Sample size must be > 0" << std::endl;
> 			return 1;
> 		}
> 	}
> ```
</details>

It will produce 3 times the same message when argc=5?
I think it should be simpler.
`file-name [count] [batch_size] [sample_size]`
Maybe:
`params.count = std::stoul(argv[argc-1])`
or something simpler

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[benchmarks/radix/radix_tree.cpp, line 208 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-M_049o0D6R1DYLYddwR:-M_0lCje8OXY_oIIXTXC:bfjl0j8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88d424588b0622bfd23d3d824775e8c61f4a5d14/benchmarks/radix/radix_tree.cpp#L208)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	if (argc > 2) {
> 		params.count = std::stoul(argv[2]);
> 		if (params.count == 0) {
> 			std::cerr << "Number of the elements must be > 0"
> 				  << std::endl;
> 			return 1;
> 		}
> 	}
> 	if (argc > 3) {
> 		params.batch_size = std::stoul(argv[3]);
> 		if (params.batch_size == 0) {
> 			std::cerr << "Batch size must be > 0" << std::endl;
> 			return 1;
> 		}
> 	}
> 	if (argc > 4) {
> 		params.sample_size = std::stoul(argv[4]);
> 		if (params.sample_size == 0) {
> 			std::cerr << "Sample size must be > 0" << std::endl;
> 			return 1;
> 		}
> 	}
> ```
It will produce 3 times the same message when argc=5?
I think it should be simpler.
`file-name [count] [batch_size] [sample_size]`
Maybe:
`params.count = std::stoul(argv[argc-1])`
or something simpler

</blockquote></details>

it will return right after any issue is found

and `if`s are required because you may omit any of the optional arguments

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-:-M_0s0rg7YXmD3jJL19D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

___
*[benchmarks/radix/radix_tree.cpp, line 208 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1070#-M_049o0D6R1DYLYddwR:-M_0rkuo0PIotXMIh2sP:b-edw654) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/88d424588b0622bfd23d3d824775e8c61f4a5d14/benchmarks/radix/radix_tree.cpp#L208)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it will return right after any issue is found

and `if`s are required because you may omit any of the optional arguments
</blockquote></details>

Right, my fault, I didn't see this small difference, thanks

**Pull request merged**
