### PR TITLE
Radix tree concurrent fix

### LINKED ISSUE #1091: radix_concurrent_iterate_0_pmemcheck fail
# ISSUE: 

## Environment Information

- libpmemobj-cpp version(s):                                         
- PMDK (libpmemobj) package version(s):                              
- OS(es) version(s):                                                 
- kernel version(s):                                                 
- compiler, libraries, packaging and other related tools version(s): 

and possibly:
- TBB version(s):                                                    
- ndctl version(s):                                                  

## How often bug is revealed:

rare 

## Details

https://github.com/igchor/libpmemobj-cpp/runs/2874671479?check_suite_focus=true
[LOG.txt](https://github.com/pmem/libpmemobj-cpp/files/6686253/LOG.txt)

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

### PR DESCRIPTION
**Pull request by igchor**
closes #1091

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3021 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md13PBg0wSnWTSfD29k:-Md13PBg0wSnWTSfD29l:b9spgcw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3021)):*
> ```cpp
> radix_tree<Key, Value, BytesView>::radix_tree_iterator<IsConst>::operator--()
> {
> 	while (!try_decrement()) {
> ```

why you have `if` for `operator++` and here you have `while` loop?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3123 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md0wGYf0bkQeWsm-qz0:-Md0wGYg-XZnlk8pzgII:bpudrhv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3123)):*
> ```cpp
> 
> /*
>  * Returns next leaf (either with smaller or larger key than k, depending on
> ```

pls extend 'returns'

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3021 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md13PBg0wSnWTSfD29k:-Md1GzpB2hmOQCmVa_ET:b-pyrt6y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3021)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why you have `if` for `operator++` and here you have `while` loop?
</blockquote></details>

Because in operator++ if upper_bound succeds we don;t need to do anything else - we got the element.
In operator-- we need to basically call `--lower_bound()` - so call try_decrement also AFTER lower_bound()
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3123 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md0wGYf0bkQeWsm-qz0:-Md1IRsdBlIW3M6c6_Oc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3123)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls extend 'returns'
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3021 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md13PBg0wSnWTSfD29k:-Md26MJ30OHBoET6RqvK:bmxsfyx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3021)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Because in operator++ if upper_bound succeds we don;t need to do anything else - we got the element.
In operator-- we need to basically call `--lower_bound()` - so call try_decrement also AFTER lower_bound()
</blockquote></details>

hmm.. then why the `while` loop? shouldn't be just `try_decrement` called twice..?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3123 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md25bXWE7vvMyFEM0YX:-Md25bXWE7vvMyFEM0YY:bos6s2b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c5f88d838904e58efaf94363e3346b8bfdb7a31a/include/libpmemobj++/experimental/radix_tree.hpp#L3123)):*
> ```cpp
> 
> /*
>  * Returns a pair consiting of a bool and leaf pointer pointing to
> ```

1. `consiting` misspell
2. I'd rewrite this e.g. like: and **a** leaf pointer to **the** next leaf (... - it omits the "pointing" part :wink:

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3021 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md13PBg0wSnWTSfD29k:-MdGfbz64ia7A14XoT59:b-s5dw16) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3021)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. then why the `while` loop? shouldn't be just `try_decrement` called twice..?
</blockquote></details>

What if the try_decrement fails in this second call? In that case we need to start over by calling lower_bound again.
The code is equivalent to:

```
if (!try_decrement)
loop until try_decrement succeeds {
    lower_bound()  
    try_decrement  // if this fails, 
}
```
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3123 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md25bXWE7vvMyFEM0YX:-MdGh8L51VOhMMjbYN-y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c5f88d838904e58efaf94363e3346b8bfdb7a31a/include/libpmemobj++/experimental/radix_tree.hpp#L3123)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. `consiting` misspell
2. I'd rewrite this e.g. like: and **a** leaf pointer to **the** next leaf (... - it omits the "pointing" part :wink: 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3021 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-Md13PBg0wSnWTSfD29k:-MdGwLwwA0jaTCUpG34n:b-3n0tfj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2dfc0fe652050a4200b0f625f358138e7f0149b6/include/libpmemobj++/experimental/radix_tree.hpp#L3021)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What if the try_decrement fails in this second call? In that case we need to start over by calling lower_bound again.
The code is equivalent to:

```
if (!try_decrement)
loop until try_decrement succeeds {
    lower_bound()  
    try_decrement  // if this fails, 
}
```

</blockquote></details>

ok, that makes sense, thx

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1099#-:-MdSWUEY1YEwQ6FokqXA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
