### PR TITLE
Fix CI scripts

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
// preview with all OSes: https://github.com/lukaszstolarczuk/libpmemobj-cpp/actions/runs/1023340220
// + https://github.com/lukaszstolarczuk/libpmemobj-cpp/runs/3053876363?check_suite_focus=true

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[utils/docker/run-build.sh, line 213 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152#-MeTKrVY2Rmj2AQ69rfh:-MeTKrVY2Rmj2AQ69rfi:b-j2j5bf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f9d1d1cd4c9469d29bef63cec066ddd4c6a7a046/utils/docker/run-build.sh#L213)):*
> ```Shell
> # BUILD tests_package
> ###############################################################################
> function tests_package() {
> ```

It may be out of scope of this PR, but we should also test if package dependencies are generated properly.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/run-build.sh, line 213 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152#-MeTKrVY2Rmj2AQ69rfh:-MeTT8JiCthyGf2IkGev:bygpcla) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f9d1d1cd4c9469d29bef63cec066ddd4c6a7a046/utils/docker/run-build.sh#L213)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It may be out of scope of this PR, but we should also test if package dependencies are generated properly. 
</blockquote></details>

hmm and how would you like to do this? check if each req. package is there, in the dir?

we prepare these packages within our docker images, so if anything changed in dependencies' make/cmake scripts we will notice that (at least in this build) and we can update it...

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152#-:-MeUBviG8Bze-VbW_d5A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1152#-:-MeYaCKxEcGLetfyRGMd:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
