### PR TITLE
Map example fix

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 152 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLNG3FL7Yv8KcwRWEyX:-MLNG3FL7Yv8KcwRWEyY:b-xzy6gt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L152)):*
> ```cpp
> 		/* If hash map is to be removed, free_data() method should be
> 		 * called first. Otherwise, if deallocating internal hash map
> 		 * metadata in a destructor fail program might terminate. */
> ```

fail -> fails
___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 154 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLNHJbL9ZJg0SoFHbGp:-MLNHJbL9ZJg0SoFHbGq:b-yni1bb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L154)):*
> ```cpp
> 		 * metadata in a destructor fail program might terminate. */
> 		if (remove_hashmap) {
> 			/* Erase remaining itemes in map. This function is not
> ```

I'd change it to `Erase remaining items in map, first.` (misspell in items, BTW) and then add some info below what `map.free_data()` does
___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 169 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLNH-deBAF3qNkxpFjy:-MLNH-deBAF3qNkxpFjz:bng52pd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L169)):*
> ```cpp
> 			}
> 
> 			map.free_data();
> ```

actually, BTW, doxygen docs doesn't say what this function does exactly, you can fix that too, I guess

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 83 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLSAOoFD1flNRosDKpB:-MLSAOoFD1flNRosDKpC:bdaalq4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L83)):*
> ```cpp
> 
> 		auto &map = *r;
> 		std::cout << map.size() << std::endl;
> ```

Is it necessary? Consider some information what value is printed

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 153 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLvt0NdDgl7WfgYK6CK:-MLvt0NdDgl7WfgYK6CL:bnhfrdb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L153)):*
> ```cpp
> 		 * called first. Otherwise, if deallocating internal hash map
> 		 * metadata in a destructor fail program might terminate. */
> 		if (remove_hashmap) {
> ```

nit: 
Probably, the example may be little bit more user friendly, if user may play with remove_hashap paramater without recompiling.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969)* status: all files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 83 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLSAOoFD1flNRosDKpB:-MLwHN2q1ApeZfRHpMep:bkgsh3s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L83)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Is it necessary? Consider some information what value is printed
</blockquote></details>

This is just to show that after restart there are some elements (possibly).
___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 152 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLNG3FL7Yv8KcwRWEyX:-MLwHhHT5wAsRr-bQOb2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L152)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

fail -> fails
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 153 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLvt0NdDgl7WfgYK6CK:-MLwJLgPDcoZqGT_RWwu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L153)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

nit: 
Probably, the example may be little bit more user friendly, if user may play with remove_hashap paramater without recompiling.
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 154 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLNHJbL9ZJg0SoFHbGp:-MLwI4Us0GkOPH6UK66D:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L154)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd change it to `Erase remaining items in map, first.` (misspell in items, BTW) and then add some info below what `map.free_data()` does
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map.cpp, line 169 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-MLNH-deBAF3qNkxpFjy:-MLwI6lIA_XIadQH3M0t:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c0aac90ebb1fed18458765cd9f4705ab3215d153/examples/concurrent_hash_map/concurrent_hash_map.cpp#L169)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, BTW, doxygen docs doesn't say what this function does exactly, you can fix that too, I guess
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/969#-:-MLwct9p3TaDfE-_Igwk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Comment by karczex** [comment]
:lgtm:

**Pull request merged**
