### PR TITLE
fix issue from coverity

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893)

### CODE REVIEW

**Comment by KFilipek** [comment]
This description don't make any sense, please describe what kind of issue. In "git log" this commit name mean nothing.

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[benchmarks/self_relative_pointer/get.cpp, line 128 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893#-MI3P3DA2G0EasRZ-wb5:-MI3P3DB9M3MAkBj8Wlp:b-8a6nhl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/09b6dac90ec1678c77261619f546d121f1dbabab/benchmarks/self_relative_pointer/get.cpp#L128)):*
> ```cpp
> 	} catch (const std::exception &e) {
> 		std::cerr << "!exception: " << e.what() << std::endl;
> 		try {
> ```

you can merge it with below try-catch

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[benchmarks/self_relative_pointer/get.cpp, line 128 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893#-MI3P3DA2G0EasRZ-wb5:-MIIV02y0R520KbIQros:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/09b6dac90ec1678c77261619f546d121f1dbabab/benchmarks/self_relative_pointer/get.cpp#L128)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can merge it with below try-catch
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/893#-:-MIIpm8w9XaG_Bjg1fko:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
