### PR TITLE
Make exception_with_errormsg take arbitrary num of params

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189)

### CODE REVIEW

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/pexceptions.hpp, line 43 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189#-MgBKS2nBGCXOrmnpIZs:-MgBKS2nBGCXOrmnpIZt:b-8jd30k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/df1ddf75ea77d16e009f6aeb875be3b7aa84da65/include/libpmemobj++/pexceptions.hpp#L43)):*
> ```
> template <typename ExcT, size_t... I, typename Tuple>
> ExcT
> exception_with_errormsg_helper(index_sequence<I...>, Tuple &&args)
> ```
Maybe just short description for future documentation

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/pexceptions.hpp, line 43 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189#-MgBKS2nBGCXOrmnpIZs:-MgFGoae8sljfnVJznE9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/df1ddf75ea77d16e009f6aeb875be3b7aa84da65/include/libpmemobj++/pexceptions.hpp#L43)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> template <typename ExcT, size_t... I, typename Tuple>
> ExcT
> exception_with_errormsg_helper(index_sequence<I...>, Tuple &&args)
> ```
Maybe just short description for future documentation
</blockquote></details>

Done.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189#-:-MgFQKNdDxX4_1tsgZrq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1189#-:-MgG7atu6hJm8nB9y5qz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
