### PR TITLE
mpsc_queue: improvements needed by multi-tier engine

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 266 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-Mcwcdq88YprewcFwseY:-Mcwcdq88YprewcFwseZ:b-1srcch) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ea3c2323b7aae1f83b326016c045dc0bfbb07f48/include/libpmemobj++/experimental/mpsc_queue.hpp#L266)):*
> ```cpp
> 			"Function called inside a transaction scope.");
> 
> 	for (int i = 0; i < 2; i++) {
> ```

magic number 2 ;) perhaps add a short comment here

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-McxDSKu2WERlzZjVsKn:-McxDSKv1pm2gBvRsgXr:b-kjt7of) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/045e7b5cde72e9774ef2a87647f1861e9a5df3a2/include/libpmemobj++/experimental/mpsc_queue.hpp#L49)):*
> ```cpp
> 		static constexpr size_t CAPACITY =
> 			pmem::detail::CACHELINE_SIZE - sizeof(size_t);
> 		static constexpr size_t DIRTY_FLAG = (1ULL << 63);
> ```

I knew there's something wrong with this `63` :wink: :smile:

you can do this like Janek did in his PR:
`static_cast<size_t>(1) << (sizeof(size_t) * 8 - 1);`

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 266 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-Mcwcdq88YprewcFwseY:-McyLNIn5Is1OqYTe6-i:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ea3c2323b7aae1f83b326016c045dc0bfbb07f48/include/libpmemobj++/experimental/mpsc_queue.hpp#L266)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

magic number 2 ;) perhaps add a short comment here
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-McxDSKu2WERlzZjVsKn:-McyLNZx06Wg-1HJVK4q:bnzumot) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/045e7b5cde72e9774ef2a87647f1861e9a5df3a2/include/libpmemobj++/experimental/mpsc_queue.hpp#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I knew there's something wrong with this `63` :wink: :smile:

you can do this like Janek did in his PR:
`static_cast<size_t>(1) << (sizeof(size_t) * 8 - 1);`
</blockquote></details>

Ok, you got me now ;d Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 266 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-Mcwcdq88YprewcFwseY:-McyT72hBs8VDs_KP2wd:b2nid0f) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ea3c2323b7aae1f83b326016c045dc0bfbb07f48/include/libpmemobj++/experimental/mpsc_queue.hpp#L266)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 271 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-McyT35q1mFTKJDfFdQ6:-McyT35q1mFTKJDfFdQ7:bfbvm1o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ce7f04ddecf21f6b251caea4de37d07e79eecc20/include/libpmemobj++/experimental/mpsc_queue.hpp#L271)):*
> ```cpp
> 	/* Need to call try_consume twice, as some data may be at the end
> 	 * of buffer, and some may be at the beginning. Ringbuffer does not
> 	 * merge those two pats into one try_consume. If all data was
> ```

`pats` -> `parts`
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 272 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-McyUXogCAHn2nRlmqdi:-McyUXogCAHn2nRlmqdj:bla0xho) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ce7f04ddecf21f6b251caea4de37d07e79eecc20/include/libpmemobj++/experimental/mpsc_queue.hpp#L272)):*
> ```cpp
> 	 * of buffer, and some may be at the beginning. Ringbuffer does not
> 	 * merge those two pats into one try_consume. If all data was
> 	 * consumed during first try_consume, second would fail. */
> ```

second would fail? it won't just return 0? (it will just have nothing to do, I believe)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 271 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-McyT35q1mFTKJDfFdQ6:-Md1Pa8s3abD24tHCMb9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ce7f04ddecf21f6b251caea4de37d07e79eecc20/include/libpmemobj++/experimental/mpsc_queue.hpp#L271)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`pats` -> `parts`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 272 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-McyUXogCAHn2nRlmqdi:-Md1PRjV6-32hO7uPKIw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ce7f04ddecf21f6b251caea4de37d07e79eecc20/include/libpmemobj++/experimental/mpsc_queue.hpp#L272)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

second would fail? it won't just return 0? (it will just have nothing to do, I believe)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-:-Md1TU7HENtnJeadaAAs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 131 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-Md1xywiA1MBWiekfa6v:-Md1xywjATZXkKO5ndyA:b-y91jzt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/877f6076f44ff7275448eea5cdd6808b1bd7cc82/include/libpmemobj++/experimental/mpsc_queue.hpp#L131)):*
> ```cpp
> 
> 	private:
> 		pmem::obj::vector<char> data_;
> ```

Why `data_` and `written` without a `_`?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/experimental/mpsc_queue.hpp, line 131 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-Md1xywiA1MBWiekfa6v:-MdGmMSl6KlH3P0D57RY:bt5bs88) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/877f6076f44ff7275448eea5cdd6808b1bd7cc82/include/libpmemobj++/experimental/mpsc_queue.hpp#L131)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Why `data_` and `written` without a `_`?
</blockquote></details>

I use the version without `_` whenever it's possible but here `data` would collide with function `data()` and I don't think there's better name for the variable ;d

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1096#-:-MdHW3hYEOIPMgfM_216:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
