### PR TITLE
[string_view] add description for methods in string_view

### PR DESCRIPTION
**Pull request by KFilipek**
Added missing description for methods and comment fix.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 70 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfgrsLx2drc3246HSW-:-MfgrsLx2drc3246HSW0:bq8a2g2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/512427e803491b1cc9b0ced8843e35fb949958d1/include/libpmemobj++/string_view.hpp#L70)):*
> ```cpp
> 	constexpr basic_string_view(const CharT *data);
> 
> 	/** Constructor initialized with the basic string *s*.
> ```

"basic string *s*"?  it's basic_string_view, and the *s* should probably be replaced with *rhs*
___
*[include/libpmemobj++/string_view.hpp, line 78 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-Mfgs-nkBSpH8X5VYp3U:-Mfgs-nkBSpH8X5VYp3V:bzi17nw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/512427e803491b1cc9b0ced8843e35fb949958d1/include/libpmemobj++/string_view.hpp#L78)):*
> ```cpp
> 
> 	/**
> 	 * Replaces the view with that of view.
> ```

of what view? either change `rhs` to view or add a reference to the parameter name
___
*[include/libpmemobj++/string_view.hpp, line 270 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfgstFq79I7vJvh9Hf8:-MfgstFq79I7vJvh9Hf9:bk7umn4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/512427e803491b1cc9b0ced8843e35fb949958d1/include/libpmemobj++/string_view.hpp#L270)):*
> ```cpp
> 
> /**
>  * Returns an reverse_iterator to the character following the last character of the
> ```

an -> a
___
*[include/libpmemobj++/string_view.hpp, line 284 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfgsuDr5etT-PJrIiVu:-MfgsuDr5etT-PJrIiVv:bk7umn4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/512427e803491b1cc9b0ced8843e35fb949958d1/include/libpmemobj++/string_view.hpp#L284)):*
> ```cpp
> 
> /**
>  * Returns an reverse_iterator to the character following the last character of the
> ```

an -> a

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-:-MfhYCVwCSYsQAV3E4n5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 280 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfhmHE1B57tEFsIQ7p_:-MfhmHE1B57tEFsIQ7pa:bhh3g0x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78755cfd6cc920aba245b87437509bdc5ff99d17/include/libpmemobj++/string_view.hpp#L280)):*
> ```cpp
> basic_string_view<CharT, Traits>::rbegin() const noexcept
> {
> 	return reverse_iterator(cend());
> ```

in our implementation rbegin == cend, so it's not a dereferenceable iterator, right? we should write it down

(or fix it? isn't it inconsistent with std::string_view? https://en.cppreference.com/w/cpp/string/basic_string_view/rbegin )
___
*[include/libpmemobj++/string_view.hpp, line 298 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfhjlpU7LzmfWnB9gim:-MfhjlpU7LzmfWnB9gin:brb7s44) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78755cfd6cc920aba245b87437509bdc5ff99d17/include/libpmemobj++/string_view.hpp#L298)):*
> ```cpp
> 
> /**
>  * Returns an iterator to the first character of the view.
> ```

perhaps make this description a little more descriptive (like for `rbegin`)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-Mfhomur4vfcbZt1gYun:-Mfhomur4vfcbZt1gYuo:b-d4g69z) (no related file):*
plus, CI seems to yell about cppformat :wink: 

---

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-Mfhomur4vfcbZt1gYun:-MflerR64bkFy6exXKWO:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

plus, CI seems to yell about cppformat :wink: 
</blockquote></details>

Done.

---
___
*[include/libpmemobj++/string_view.hpp, line 280 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfhmHE1B57tEFsIQ7p_:-MfleB2J7msp4Zi6oJ-4:b-9g7fwh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78755cfd6cc920aba245b87437509bdc5ff99d17/include/libpmemobj++/string_view.hpp#L280)):*
> so it's not a dereferenceable iterator, right? we should write it down
It's consistent with std::string view, we use std::reverse iterator which will points to the next element, so: rbegin == cend - 1;
___
*[include/libpmemobj++/string_view.hpp, line 298 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-MfhjlpU7LzmfWnB9gim:-MflepXv2YiPyFjjAm_l:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78755cfd6cc920aba245b87437509bdc5ff99d17/include/libpmemobj++/string_view.hpp#L298)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make this description a little more descriptive (like for `rbegin`)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1181#-:-MfmS3hpDSh15g0cujf_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
