### PR TITLE
tests: string_view_assignment

### PR DESCRIPTION
**Pull request by KFilipek**
- basic_string: nullptr as parameter to constructor fix
- external tests: port the string_view_assignment test

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @KFilipek)

___
*[tests/external/CMakeLists.txt, line 710 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiJUx-9n7DRt6JcwQ:-MIJiJUy1ZuSW_nqhv65:bt6yan0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/CMakeLists.txt#L710)):*
> ```CMake
> 
> 	# XXX: port libcxx test basic_string/string.capacity/max_size.pass
> 	# XXX: port libcxx test basic_string/string.cons/string_view_assignment.pass
> ```

Outdated now?
___
*[tests/external/CMakeLists.txt, line 715 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiLSR3urIiEYPsVhE:-MIJiLSR3urIiEYPsVhF:b-ykt7sl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/CMakeLists.txt#L715)):*
> ```CMake
> 
> 	# XXX: port libcxx test basic_string/string.cons/T_size_size.pass
> ```

Will you also port this one?
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 34 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJjzGy06Lw4Vk402GX:-MIJjzGy06Lw4Vk402GY:b-e717ee) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L34)):*
> ```cpp
> struct root {
> 	nvobj::persistent_ptr<S> s1;
> 	nvobj::persistent_ptr<SV> sv;
> ```

You should not store it on pmem.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 42 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJjZKY-4lDHH8efPl5:-MIJjZKY-4lDHH8efPl6:b6utc5g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L42)):*
> ```cpp
> {
> 	typedef typename S::element_type::traits_type T;
> 	*s1 = *sv;
> ```

Either change it to `s1 = sv` and pass reference to a string instead of a pointer or renames the template parameters to something like S_Ptr, SV_Ptr 
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJias60wkBKd43ewQ6:-MIJias60wkBKd43ewQ7:bzbe37d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L71)):*
> ```cpp
> 				auto ns = nvobj::make_persistent<S>(
> 					str_sv_pair.first);
> 				(void)ns;
> ```

What is this for?
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJivvi6V6sjxjao_rZ:-MIJivvi6V6sjxjao_r_:btibqna) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L72)):*
> ```cpp
> 					str_sv_pair.first);
> 				(void)ns;
> 				auto nsv = nvobj::make_persistent<SV>(
> ```

You don't have to allocate string_view on pmem. It can be created on stack. TBH, storing string_view on pmem is wrong, because you have a normal volatile pointer there.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiu5s4_baKxYCOOcm:-MIJiu5s4_baKxYCOOcn:b3kre) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L74)):*
> ```cpp
> 				auto nsv = nvobj::make_persistent<SV>(
> 					str_sv_pair.second);
> 				(void)nsv;
> ```

?
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 75 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJjmE34OMTcPGaIrBx:-MIJjmE48k5qYuvH_pJO:bh63fj9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L75)):*
> ```cpp
> 					str_sv_pair.second);
> 				(void)nsv;
> 				test(ns, nsv, pop);
> ```

This could be just test(ns, SV(pair.second), pop);

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/external/CMakeLists.txt, line 710 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiJUx-9n7DRt6JcwQ:-MIK7NhZCgWtbeJZgAlM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/CMakeLists.txt#L710)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Outdated now?
</blockquote></details>

Done.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 34 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJjzGy06Lw4Vk402GX:-MIK7PS8AxqbjVIwX4G_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You should not store it on pmem.
</blockquote></details>

Done.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 42 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJjZKY-4lDHH8efPl5:-MIK7QbM01yaPFaEM9em:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L42)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Either change it to `s1 = sv` and pass reference to a string instead of a pointer or renames the template parameters to something like S_Ptr, SV_Ptr 
</blockquote></details>

Done.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJias60wkBKd43ewQ6:-MIK7S5XBHzcLMwEFVln:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Done.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJivvi6V6sjxjao_rZ:-MIK7SkJAGnxLVTnXR7w:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L72)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You don't have to allocate string_view on pmem. It can be created on stack. TBH, storing string_view on pmem is wrong, because you have a normal volatile pointer there.
</blockquote></details>

Done.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiu5s4_baKxYCOOcm:-MIK7TCm60AQOTRiM8hL:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L74)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 75 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJjmE34OMTcPGaIrBx:-MIK7Tm15tdQjg4K2B_3:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L75)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This could be just test(ns, SV(pair.second), pop);
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 563 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIKAyV47kzCIiMPU1CV:-MIKAyV5BbaDetlhhGMz:b-capem2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/include/libpmemobj++/container/basic_string.hpp#L563)):*
> ```cpp
> 
> 	if (s) {
> 		auto length = traits_type::length(s);
> ```

As we discussed, please remove this commit for now.
___
*[tests/external/CMakeLists.txt, line 710 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiJUx-9n7DRt6JcwQ:-MIKB3j579di7SUL0BeY:b-q7ki7q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/CMakeLists.txt#L710)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you push the changes?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/external/CMakeLists.txt, line 710 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiJUx-9n7DRt6JcwQ:-MIKES5nDQW7-iTegqe6:b-tz2i9u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/CMakeLists.txt#L710)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Did you push the changes?
</blockquote></details>

I will push with next test. Temporarily I've checked this issues for my convenience :)   
___
*[tests/external/CMakeLists.txt, line 715 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIJiLSR3urIiEYPsVhE:-MIKEgC_4m5UWEn8-VGs:b-n8lcq2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77ed833cb14f3db17aa0b6078e4ff32373443b83/tests/external/CMakeLists.txt#L715)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Will you also port this one?
</blockquote></details>

Yes, I'm working on it

**Comment by KFilipek** [comment]
I saw that was conflict with CMakeLists.txt after merging previous PR, now should be okay.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 4 of 5 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-:-MIP5Lmd9Wu2Zna01tKV:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp, line 38 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897#-MIP4Dlz03ZhXqggii-G:-MIP4Dm-8hRduFGdDqSP:bmmky0b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c72da0cbf7a82931c494bc5e2c889a0813610a/tests/external/libcxx/basic_string/string.cons/string_view_assignment.pass.cpp#L38)):*
> ```cpp
> template <class S, class SV>
> void
> test(S &s1, const SV &sv, pmem::obj::pool<root> &pop)
> ```

do you even need pop here?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by KFilipek** [comment]
@igchor Now should be okey

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/897)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
