### PR TITLE
example: add radix_tree example with complex value type

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 17 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdLlG2DU8wOPpQfeIo:-MRdLlG2DU8wOPpQfeIp:b-rsczs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3aa71b7fca188b80ea0bf1842d3ca437dff533cf/examples/radix_tree/radix_tree_complex_value.cpp#L17)):*
> ```cpp
> 
> #include <iostream>
> ```

perhaps make a snippet to docs
___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdLrdTE8rGtpZbCNDV:-MRdLrdTE8rGtpZbCNDW:b2xprln) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3aa71b7fca188b80ea0bf1842d3ca437dff533cf/examples/radix_tree/radix_tree_complex_value.cpp#L28)):*
> ```cpp
> 	{
> 	}
> ```

maybe add a comment that this is pmemobj string/p since it will be created only in root (on pmem)
___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 42 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdLe31BVSHYrnt1ywp:-MRdLe31BVSHYrnt1ywq:b-3nt5kf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3aa71b7fca188b80ea0bf1842d3ca437dff533cf/examples/radix_tree/radix_tree_complex_value.cpp#L42)):*
> ```cpp
> 
> void
> show_usage(char *argv[])
> ```

consider moving this into the main.. it's used only once

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 17 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdLlG2DU8wOPpQfeIo:-MRdQU6Z0zlWgm9VXzxj:blkyydf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3aa71b7fca188b80ea0bf1842d3ca437dff533cf/examples/radix_tree/radix_tree_complex_value.cpp#L17)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps make a snippet to docs
</blockquote></details>

I'm not sure if all examples should be snippets, we don't have annotation for most of the other radix examples.
___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdLrdTE8rGtpZbCNDV:-MRdQvtE5OUrL9MQ-3Xc:b-r9ncwc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3aa71b7fca188b80ea0bf1842d3ca437dff533cf/examples/radix_tree/radix_tree_complex_value.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe add a comment that this is pmemobj string/p since it will be created only in root (on pmem)
</blockquote></details>

I added a comment that this structure is pmem-resident
___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 42 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdLe31BVSHYrnt1ywp:-MRdQzia3onFBs_-b0b0:b-ghqkh4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3aa71b7fca188b80ea0bf1842d3ca437dff533cf/examples/radix_tree/radix_tree_complex_value.cpp#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

consider moving this into the main.. it's used only once
</blockquote></details>

Well yes, but it's consistent with other examples, and I think one extra function is not a big problem

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-:-MRdUB8J32BnyJUAGpeQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
if (consider my comment)
then
:lgtm:
fi

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-:-MRdVVSqAfApQnucAU8f:b-51e0df)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 83 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdUttJBDUlkT6FNmun:-MRdUttKB16kH5f_1AcO:bi5ujs1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f1df81e2b447c04b37875fe3cb08a170d76dc49c/examples/radix_tree/radix_tree_complex_value.cpp#L83)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	// it->value().population += 20000;
> 	// pop.persist(it->value().population);
> 	// it->value().area_in_sqr_km += 20;
> 	// pop.persist(it->value().population);
> ```
</details>

Maybe another block comment? It will look like "uncomment all or nothing"

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 83 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdUttJBDUlkT6FNmun:-MRdWXFW7sd4xCuvB1bH:b-oow8i7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f1df81e2b447c04b37875fe3cb08a170d76dc49c/examples/radix_tree/radix_tree_complex_value.cpp#L83)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	// it->value().population += 20000;
> 	// pop.persist(it->value().population);
> 	// it->value().area_in_sqr_km += 20;
> 	// pop.persist(it->value().population);
> ```
Maybe another block comment? It will look like "uncomment all or nothing"
</blockquote></details>

Ok, I actually made it a part of a single block comment

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 53 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdWG_n5rhNxB3iAqiw:-MRdWG_n5rhNxB3iAqix:b-np5xo3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f1df81e2b447c04b37875fe3cb08a170d76dc49c/examples/radix_tree/radix_tree_complex_value.cpp#L53)):*
> ```cpp
> 	auto r = pop.root();
> 
> 	/* Insert 3 kv pairs transactionally */
> ```

You may mention, that in case of failure of any step, whole  transaction would be reverted. 
You may also write, why you do not put it in a loop with one try_emplace in each transaction.
___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 60 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdX0dQ3g0sYxne-q4E:-MRdX0dQ3g0sYxne-q4F:b5uo93s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f1df81e2b447c04b37875fe3cb08a170d76dc49c/examples/radix_tree/radix_tree_complex_value.cpp#L60)):*
> ```cpp
> 	});
> 
> 	auto it = r->kv->find("Gdansk");
> ```

Using of auto in examples is tricky. I know we use it all over our examples. :)
It would be more descriptive if you would specify types here and there instead of auto.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 53 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-MRdWG_n5rhNxB3iAqiw:-MRd_S3t12cO4QM3GwTu:bu6kpbn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f1df81e2b447c04b37875fe3cb08a170d76dc49c/examples/radix_tree/radix_tree_complex_value.cpp#L53)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may mention, that in case of failure of any step, whole  transaction would be reverted. 
You may also write, why you do not put it in a loop with one try_emplace in each transaction.
</blockquote></details>

Done, I extended the comment.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015#-:-MRdaziP6air0DKkjiGw:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1015)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
