### PR TITLE
CI: add new workflow with more jobs

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
With USAN, UBSAN and valgrind tests using upstream package of valgrind.
And, I rename "other_OSes" to "nightly" - it seems a bit better :wink:

// example run:
https://github.com/lukaszstolarczuk/libpmemobj-cpp/runs/2905296781?check_suite_focus=true

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
Is there any reason why we cannot run the weekend jobs nightly? Are they much longer?

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098#-:-McyhWU46QK3EbQsKU8x:ble2ofs)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
> Is there any reason why we cannot run the weekend jobs nightly? Are they much longer?
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098#-:-McyhWU46QK3EbQsKU8x:ble2ofs)_ status: 0 of 5 files reviewed, all discussions resolved

I just don't think there are going to be many changes around these executions and they will most likely break (a lot) and it would constantly mark nightly builds red.
I believe we can run them more often, that's no biggie, I just don't think they'll bring us much value on a day-to-day basis.

**Review by karczex — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.github/workflows/weekend.yml, line 2 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098#-Md20YNA8TJQ4QcrfRO-:-Md20YNA8TJQ4QcrfRO0:ba7cvh5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7f1c5c5cec44370c8d57d41961d7c5cb23be21fb/.github/workflows/weekend.yml#L2)):*
> ```YAML
> 
> name: CPP-weekend
> ```

Maybe cpp-weekly? Current name indicate that, you need to change the file name if change running this workflow from Saturday to Tuesday for some reason :)
___
*[.github/workflows/weekend.yml, line 28 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098#-Md21HTpBrdyp8rwsBMP:-Md21HTpBrdyp8rwsBMQ:b-1x4lre) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7f1c5c5cec44370c8d57d41961d7c5cb23be21fb/.github/workflows/weekend.yml#L28)):*
> ```
>                  "TYPE=debug OS=ubuntu OS_VER=20.04 TESTS_UBSAN=ON",
>                  "TYPE=valgrind OS=fedora OS_VER=rawhide TESTS_PMREORDER=0",
> ```
`ON, OFF` or `0, 1` probably should be used consistently

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[.github/workflows/weekend.yml, line 2 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098#-Md20YNA8TJQ4QcrfRO-:-Md23SzcBsCQw_8mDO9V:bvbqyaf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7f1c5c5cec44370c8d57d41961d7c5cb23be21fb/.github/workflows/weekend.yml#L2)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Maybe cpp-weekly? Current name indicate that, you need to change the file name if change running this workflow from Saturday to Tuesday for some reason :)
</blockquote></details>

Definitely agreed! Done.
___
*[.github/workflows/weekend.yml, line 28 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1098#-Md21HTpBrdyp8rwsBMP:-Md23WRh5Rt0GzMqjxCD:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7f1c5c5cec44370c8d57d41961d7c5cb23be21fb/.github/workflows/weekend.yml#L28)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
>                  "TYPE=debug OS=ubuntu OS_VER=20.04 TESTS_UBSAN=ON",
>                  "TYPE=valgrind OS=fedora OS_VER=rawhide TESTS_PMREORDER=0",
> ```
`ON, OFF` or `0, 1` probably should be used consistently
</blockquote></details>

Done.

**Pull request merged**
