### PR TITLE
[stable-1.6] Ubsan fixes

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/persistent_ptr.hpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdR4Tul1z2JH7chXwTZ:-MdR4Tul1z2JH7chXwT_:b-u3mdas) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f9b143fd8b66e38bdc00d1b7820761b33ca82b8/include/libpmemobj++/persistent_ptr.hpp#L2)):*
> ```cpp
> /*
>  * Copyright 2015-2021, Intel Corporation
> ```

this is not needed...?
___
*[include/libpmemobj++/detail/persistent_ptr_base.hpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdR4WRECfjnICNaDwA2:-MdR4WRECfjnICNaDwA3:b-rnnobx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f9b143fd8b66e38bdc00d1b7820761b33ca82b8/include/libpmemobj++/detail/persistent_ptr_base.hpp#L2)):*
> ```cpp
> /*
>  * Copyright 2016-2018, Intel Corporation
> ```

this should be updated, I guess :wink:
___
*[tests/ptr/ptr.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdR4dFB4qV5gxsWcuNe:-MdR4dFB4qV5gxsWcuNf:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f9b143fd8b66e38bdc00d1b7820761b33ca82b8/tests/ptr/ptr.cpp#L2)):*
> ```cpp
> /*
>  * Copyright 2015-2019, Intel Corporation
> ```

.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/persistent_ptr.hpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdR4Tul1z2JH7chXwTZ:-MdR5RIdEQ-5XzJgvvbF:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f9b143fd8b66e38bdc00d1b7820761b33ca82b8/include/libpmemobj++/persistent_ptr.hpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this is not needed...?
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/persistent_ptr_base.hpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdR4WRECfjnICNaDwA2:-MdR5RXe66CdiUypNBcv:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f9b143fd8b66e38bdc00d1b7820761b33ca82b8/include/libpmemobj++/detail/persistent_ptr_base.hpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this should be updated, I guess :wink:
</blockquote></details>

Done.
___
*[tests/ptr/ptr.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdR4dFB4qV5gxsWcuNe:-MdR5RwIBEGHC8vMfGDD:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f9b143fd8b66e38bdc00d1b7820761b33ca82b8/tests/ptr/ptr.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/detail/persistent_ptr_base.hpp, line 375 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWgCJY1L-DSTYaJCPF:-MdWgCJY1L-DSTYaJCPG:bnv2wnw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/detail/persistent_ptr_base.hpp#L375)):*
> ```cpp
> 	calculate_offset() const
> 	{
> 		static const ptrdiff_t ptr_offset_magic = 0xF00000000000000;
> ```

What idea stands behind this assignment? I'm sure that PTRDIFF_MAX is lower than the right operand. 
___
*[include/libpmemobj++/experimental/contiguous_iterator.hpp, line 248 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWhiH61B9PA_E-KpWI:-MdWhiH61B9PA_E-KpWJ:b-mpsptb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/experimental/contiguous_iterator.hpp#L248)):*
> ```cpp
> 		assert(data <= ptr);
> 
> 		if (snapshot_size > 0 && ptr)
> ```

Default parameters says: you can invoke me without any parameter passed by you and everything will be fine, but it's not true: assert(data<=ptr) will fail with default parameters.
2. This assert mean: you must pass ptr and data.
3. '&& ptr' is always true, it will fail with assert, maybe we should throw error or denied passing wrong argument and control execution flow by assert (works only in debug)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/detail/persistent_ptr_base.hpp, line 375 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWgCJY1L-DSTYaJCPF:-MdWzU7P5t8A9Fq-_zzV:bij3ik0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/detail/persistent_ptr_base.hpp#L375)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

What idea stands behind this assignment? I'm sure that PTRDIFF_MAX is lower than the right operand. 
</blockquote></details>

It's not, ptrdiff_t is at least 64 bit signed integer (for platforms we care about).
___
*[include/libpmemobj++/experimental/contiguous_iterator.hpp, line 248 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWhiH61B9PA_E-KpWI:-MdWzlpkDmTgA0fNOYH0:b-bvntw1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/experimental/contiguous_iterator.hpp#L248)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Default parameters says: you can invoke me without any parameter passed by you and everything will be fine, but it's not true: assert(data<=ptr) will fail with default parameters.
2. This assert mean: you must pass ptr and data.
3. '&& ptr' is always true, it will fail with assert, maybe we should throw error or denied passing wrong argument and control execution flow by assert (works only in debug)
</blockquote></details>

1. It will not fail, nullptr <= nullptr is `true`
2. Not true, as above
3. Why it's always true? Imo it's not (otherwise I wouldn't make this change ;d)

**Comment by karczex** [comment]
___
*[include/libpmemobj++/experimental/contiguous_iterator.hpp, line 248 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWhiH61B9PA_E-KpWI:-MdXAVEB2tIIoQjrXj68:bbhdt1x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/experimental/contiguous_iterator.hpp#L248)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

1. It will not fail, nullptr <= nullptr is `true`
2. Not true, as above
3. Why it's always true? Imo it's not (otherwise I wouldn't make this change ;d)
</blockquote></details>

Please add brackets to avoid forcing poor human beings  to reading through this really educational materials about operator precedence in C++ https://en.cppreference.com/w/cpp/language/operator_precedence

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/experimental/contiguous_iterator.hpp, line 248 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWhiH61B9PA_E-KpWI:-MdXHgZaA-V7XBo2XRfa:bz0mvf4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/experimental/contiguous_iterator.hpp#L248)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please add brackets to avoid forcing poor human beings  to reading through this really educational materials about operator precedence in C++ https://en.cppreference.com/w/cpp/language/operator_precedence
</blockquote></details>

Oh right, forget about it. @karczex this should be equivalent
`if (snapshot_size && ptr)  `
does the same job (size_t is unsigned type as I remember)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/contiguous_iterator.hpp, line 248 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-MdWhiH61B9PA_E-KpWI:-MdXKgzM6SBRp9_wPa9N:bs7wumx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4381d9c06dd3a3bd2908efe1a0a3c3967578f14a/include/libpmemobj++/experimental/contiguous_iterator.hpp#L248)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Oh right, forget about it. @karczex this should be equivalent
`if (snapshot_size && ptr)  `
does the same job (size_t is unsigned type as I remember)
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-:-MdXXy_LEZcfq_3h0wyv:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @KFilipek and @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1113#-:-MdXlHr2CwR-LHUhm0nd:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @KFilipek and @lukaszstolarczuk)

**Pull request merged**
