### PR TITLE
Mpsc queue remove overload with copying data in lambda function

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125)* status: 5 of 11 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[tests/mpsc_queue/queue.hpp, line 17 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-Mdr6ivAC5mBg1dFU--C:-Mdr6ivBDe3Ep5328YGB:b-7hnuwn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2a9936ca23d1535db75e71b0814371cb9d8a7551/tests/mpsc_queue/queue.hpp#L17)):*
> ```cpp
> 
> 	size_t capacity = 0;
> 	auto e = std::string("b");
> ```

what is `e` for if you use "b" directly?
___
*[tests/mpsc_queue/recovery_order.cpp, line 33 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-Mdr6tU86o0AIpcAZa3c:-Mdr6tU86o0AIpcAZa3d:b-irlfkm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2a9936ca23d1535db75e71b0814371cb9d8a7551/tests/mpsc_queue/recovery_order.cpp#L33)):*
> ```cpp
> 	auto proot = pop.root();
> 
> 	auto queue = queue_type(*proot->log, 2);
> ```

why 2?

**Comment by karczex** [comment]
___
*[tests/mpsc_queue/recovery_order.cpp, line 33 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-Mdr6tU86o0AIpcAZa3c:-Mdr86N_4M4kT130VyQC:bdr8mmf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2a9936ca23d1535db75e71b0814371cb9d8a7551/tests/mpsc_queue/recovery_order.cpp#L33)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why 2?
</blockquote></details>

Currently one is created in make_queue_with_first_half_empty(), and second in get_queue_capacity().  As   get_queue_capacity() is called in make_queue_with_first_half_empty() 2 workers are needed. Those two functions are much simpler to use this way. 

I hope we may get maximum number of workers soon :)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/mpsc_queue/pmreorder/recovery_after_consume.cpp, line 41 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-MdrFUml1nx-g9o_MaEB:-MdrFUml1nx-g9o_MaEC:b-ih2yjq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/54084077da8e19c79fbac6d54ade477b93fe5c53/tests/mpsc_queue/pmreorder/recovery_after_consume.cpp#L41)):*
> ```
> 	const auto produce_size = 128ULL;
> 	const size_t concurrency = 4;
> 	const auto fill_pattern = std::string(produce_size, 'x');
> ```
10 lines above there are the same lines, what for?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[tests/mpsc_queue/recovery_order.cpp, line 33 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-Mdr6tU86o0AIpcAZa3c:-MdrG68e8tW1HYlwfAdR:b-o35jkb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2a9936ca23d1535db75e71b0814371cb9d8a7551/tests/mpsc_queue/recovery_order.cpp#L33)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Currently one is created in make_queue_with_first_half_empty(), and second in get_queue_capacity().  As   get_queue_capacity() is called in make_queue_with_first_half_empty() 2 workers are needed. Those two functions are much simpler to use this way. 

I hope we may get maximum number of workers soon :) 
</blockquote></details>

But the worker in make_queue_first_half_empty is unregistered before we create the new worker - one should be enough.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-:-MdzrRvHC7qMvv0T4eJX:bnfp4nl)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-:-Me-C3yY8Qqj9g5BhzFP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1125#-:-Me0LP0j-Mp-RciTbzUN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
