### PR TITLE
[TO DISCUSS] Revert "cmake: use SRCVERSION in package name, instead of VERSION"

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
It is broken in case of shallow clones - git describe reports commit sha
and it cannot be used as a package version on Debian, as reported by CPack:
"version number does not start with digit".

This reverts commit b7dc434d8d5720d302bef8c7ab98d432284d2e96.

**TO DISCUSS**: with current approach, if shallow clone, the CPack creates package with a warning, as you can see here: https://github.com/pmem/libpmemobj-cpp/runs/1627275113?check_suite_focus=true#step:4:5397
We may:
1. fix it like in this PR and don't have current version in the package (e.g. master will always report as the most recent release, which is inaccurate), or
2. try to fix is somehow with a logic to recognize if it's a shallow clone (if sha commit was returned from git describe), or
3. ignore this problem and assume it does not hurt us that much 😉 

see also: https://github.com/pmem/libpmemobj-cpp/pull/1004 (to fix current builds we introduced unshallow clones on CI).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1008)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
we can alternatively just add hardcoded version ahead of commit sha (e.g. when git describe returns sha commit, just set SRC_VERSION to "<version>-g<sha_commit>")

**Comment by igchor** [comment]
I think we can ignore this issue - we don't have to support creating packages for shallow clones I belive. But maybe it would be good to write it somewhere?

**Comment by lukaszstolarczuk** [comment]
Last suggestion is to put a proper comment (when `git describe` is used for establishing the srcversion), with information that shallow clone is bad when preparing packages.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1008)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
fixed by a warning ;)
ref. #1026

maybe some day we could extend cmake with applying hard-coded version in front of sha, but it seems ok to just warn with proper information. It's not suppose to be very common issue.

**Pull request closed without merging**
