### PR TITLE
add pool_invalid_argument exception

### PR DESCRIPTION
**Pull request by JanDorniak99**
This modification will allow us to better handle exceptions in pmemkv. https://github.com/pmem/pmemkv/pull/942

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/pool.hpp, line 117 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEOQma3Y6LC0EVQ5It:-MUEOQmb1-_kxSrn3pH2:bvdex94) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L117)):*
> ```cpp
> 				throw pmem::pool_invalid_argument(
> 					"Failed opening pool")
> 					.with_pmemobj_errormsg();
> ```

Can you please paste the example of full message of this exception, when thrown...? 
___
*[include/libpmemobj++/pool.hpp, line 157 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEPGP8CYpXCQBEwOgE:-MUEPGP8CYpXCQBEwOgF:b-f0h53b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L157)):*
> ```cpp
> #endif
> 		if (pop == nullptr) {
> 			if (errno == EINVAL || errno == EFBIG ||
> ```

can we avoid copy-pasting these if's..?
___
*[tests/pool/pool.cpp, line 26 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUETgZO7ZrwK_wIAYlk:-MUETgZO7ZrwK_wIAYll:b-q87ld1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/tests/pool/pool.cpp#L26)):*
> ```cpp
> };
> 
> /* emulate no more space in the memory */
> ```

do we have test for too small pool size? Actually, pls verify if we have enough tests for pool create/open right now; perhaps we're already missing some..
___
*[tests/pool/pool.cpp, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUESaDj5CaThK_LdDMJ:-MUESaDk-5sYPYj0xz6C:b-cfv1s1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/tests/pool/pool.cpp#L86)):*
> ```cpp
> 		UT_OUT("%s: pool::open: %s", path, e.what());
> 		return;
> 	}
> ```

shouldn't we have here tests for both exceptions?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: all files reviewed, 5 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/pool.hpp, line 115 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUETktJ5XjJ1m5OhEiR:-MUETktJ5XjJ1m5OhEiS:b-yggxx3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L115)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 		if (pop == nullptr) {
> 			if (errno == EINVAL || errno == EFBIG ||
> 			    errno == ENOENT) {
> 				throw pmem::pool_invalid_argument(
> 					"Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			} else {
> 				throw pmem::pool_error("Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			}
> 		}
> ```
</details>

Every errno code has own meaning, in this case we get new exception with the same effect, but only change is an exclusion the case "internal pool error". Can we add reason why it failed to string? "Failed opening pool: no such file or directory" in ENOENT etc.
___
*[include/libpmemobj++/pool.hpp, line 215 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEV3ME8MI_sVC5yc4c:-MUEV3MFEcO2AwTwe48e:b-ittflb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L215)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 		if (pop == nullptr) {
> 			if (errno == EINVAL || errno == EFBIG ||
> 			    errno == ENOENT) {
> 				throw pmem::pool_invalid_argument(
> 					"Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			} else {
> 				throw pmem::pool_error("Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			}
> 		}
> ```
</details>

Duplicated 4 times code should be moved to function

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: all files reviewed, 5 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[include/libpmemobj++/pool.hpp, line 115 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUETktJ5XjJ1m5OhEiR:-MUIN8xd248-nzG7z_zr:b1mjacj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L115)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 		if (pop == nullptr) {
> 			if (errno == EINVAL || errno == EFBIG ||
> 			    errno == ENOENT) {
> 				throw pmem::pool_invalid_argument(
> 					"Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			} else {
> 				throw pmem::pool_error("Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			}
> 		}
> ```
Every errno code has own meaning, in this case we get new exception with the same effect, but only change is an exclusion the case "internal pool error". Can we add reason why it failed to string? "Failed opening pool: no such file or directory" in ENOENT etc.
</blockquote></details>

It will be added automatically by the pmemobj_errormsg()
___
*[include/libpmemobj++/pool.hpp, line 215 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEV3ME8MI_sVC5yc4c:-MUINGQW-hl98ymzymhu:b32v57) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L215)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 		if (pop == nullptr) {
> 			if (errno == EINVAL || errno == EFBIG ||
> 			    errno == ENOENT) {
> 				throw pmem::pool_invalid_argument(
> 					"Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			} else {
> 				throw pmem::pool_error("Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			}
> 		}
> ```
Duplicated 4 times code should be moved to function
</blockquote></details>

+1

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/pool.hpp, line 115 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUETktJ5XjJ1m5OhEiR:-MUIJz_W8w2zaNsNQHbW:b4augkp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L115)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 		if (pop == nullptr) {
> 			if (errno == EINVAL || errno == EFBIG ||
> 			    errno == ENOENT) {
> 				throw pmem::pool_invalid_argument(
> 					"Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			} else {
> 				throw pmem::pool_error("Failed opening pool")
> 					.with_pmemobj_errormsg();
> 			}
> 		}
> ```
Every errno code has own meaning, in this case we get new exception with the same effect, but only change is an exclusion the case "internal pool error". Can we add reason why it failed to string? "Failed opening pool: no such file or directory" in ENOENT etc.
</blockquote></details>

I think that is already included in pmemobj_errormsg(). Example msg after not catching pool_invalid_argument exception: Failed creating pool: open "/home/nvms/Work/libpmemobj-cpp/build/test/pool_4_none/non-existent-dir/testfile": No such file or directory
___
*[include/libpmemobj++/pool.hpp, line 117 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEOQma3Y6LC0EVQ5It:-MUIJuCR11kdwgObCsx1:bowgunh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L117)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Can you please paste the example of full message of this exception, when thrown...? 
</blockquote></details>

Failed creating pool: open "/home/nvms/Work/libpmemobj-cpp/build/test/pool_4_none/non-existent-dir/testfile": No such file or directory
___
*[include/libpmemobj++/pool.hpp, line 157 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEPGP8CYpXCQBEwOgE:-MUIO4BJ-aVO1QQXpMqY:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L157)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can we avoid copy-pasting these if's..?
</blockquote></details>

Done.
___
*[include/libpmemobj++/pool.hpp, line 215 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUEV3ME8MI_sVC5yc4c:-MUIO56w3lJtRtbknUZD:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L215)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tests/pool/pool.cpp, line 26 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUETgZO7ZrwK_wIAYlk:-MUJDhveB3t0a2lMJGiT:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/tests/pool/pool.cpp#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we have test for too small pool size? Actually, pls verify if we have enough tests for pool create/open right now; perhaps we're already missing some..
</blockquote></details>

Done.
___
*[tests/pool/pool.cpp, line 86 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUESaDj5CaThK_LdDMJ:-MUJOR_y3KNdNtR0l1SZ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/tests/pool/pool.cpp#L86)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we have here tests for both exceptions?
</blockquote></details>

Done.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/pool.hpp, line 115 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUETktJ5XjJ1m5OhEiR:-MUJPQ7W4lLOvLMJpece:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c86a7400f0c2d576ebb2d8a7e4e1d5beae16ef2e/include/libpmemobj++/pool.hpp#L115)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

I think that is already included in pmemobj_errormsg(). Example msg after not catching pool_invalid_argument exception: Failed creating pool: open "/home/nvms/Work/libpmemobj-cpp/build/test/pool_4_none/non-existent-dir/testfile": No such file or directory
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/pool/pool_9.cmake, line 10 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUJV-gy2GC4BZVZXNUr:-MUJV-gy2GC4BZVZXNUs:b-819bit) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f858271dbbf26bab61ec7c9ff00e79cdc4536765/tests/pool/pool_9.cmake#L10)):*
> ```CMake
> # test for opening pool without access
> execute(${TEST_EXECUTABLE} c ${DIR}/testfile "test" 20 0600)
> execute_process(COMMAND chmod 000 ${DIR}/testfile)
> ```

does this work on windows? if not, I guess it should be disabled

**Review by KFilipek — COMMENTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: all files reviewed, 5 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[include/libpmemobj++/pool.hpp, line 191 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUJb0jz1TCkoKZrkgce:-MUJb0jz1TCkoKZrkgcf:bl2yyu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f858271dbbf26bab61ec7c9ff00e79cdc4536765/include/libpmemobj++/pool.hpp#L191)):*
> ```cpp
> 	{
> 		pmemobjpool *pop = pmemobj_openW(path.c_str(), layout.c_str());
> ```

empty line, that nothing improves in general
___
*[include/libpmemobj++/pool.hpp, line 223 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUJaxH61bLJPhKnZiTH:-MUJaxH61bLJPhKnZiTI:bh3o6fy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f858271dbbf26bab61ec7c9ff00e79cdc4536765/include/libpmemobj++/pool.hpp#L223)):*
> ```cpp
> 						   size, mode);
> 
> 		check_pool(pop, "creating");
> ```

remove empty line

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/pool.hpp, line 191 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUJb0jz1TCkoKZrkgce:-MUN84FJ37Q_r8XtMAxl:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f858271dbbf26bab61ec7c9ff00e79cdc4536765/include/libpmemobj++/pool.hpp#L191)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

empty line, that nothing improves in general
</blockquote></details>

Done.
___
*[include/libpmemobj++/pool.hpp, line 223 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUJaxH61bLJPhKnZiTH:-MUN83WY8nP_BTy8ybm2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f858271dbbf26bab61ec7c9ff00e79cdc4536765/include/libpmemobj++/pool.hpp#L223)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 9 files at r2, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99 and @KFilipek)

___
*[tests/CMakeLists.txt, line 164 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUNNDoqDPeUJMb7I5Z3:-MUNNDor7b_QdhhmG-Xt:b4mb842) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4c013e362a2ad8ae0d9fe1466bf4476b7f7cb082/tests/CMakeLists.txt#L164)):*
> ```CMake
> add_test_generic(NAME pool CASE 4 TRACERS none)
> add_test_generic(NAME pool CASE 5 TRACERS none)
> add_test_generic(NAME pool CASE 7 TRACERS none)
> ```

why 7 not 6? ;)

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 164 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-MUNNDoqDPeUJMb7I5Z3:-MUNRW8W7N-nAjL7YVzI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4c013e362a2ad8ae0d9fe1466bf4476b7f7cb082/tests/CMakeLists.txt#L164)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why 7 not 6? ;)
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-:-MUNVJJf6SCeP2cRqB3t:bnfp4nl)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-:-MUOFvHdCW0yXBuFtiaY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Comment by JanDorniak99** [comment]
Pls don't merge this now, I probably found one missing check.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1047#-:-MUP-6ofBLEXySGalfm_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Pull request merged**
