### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/transaction.hpp, line 456 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVKv7FzCza5t5Yzb4A3:-MVKv7G-C41Exav8WsLz:b-9fktq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ace28c409df1950a83ff0c53b6f59b0bfb6c37bd/include/libpmemobj++/transaction.hpp#L456)):*
> ```cpp
> 		https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3
> 	 */
> 	enum class stage {
> ```

actually I can see we only use it in `register_callback`... why not elsewhere?

**Comment by karczex** [comment]
___
*[include/libpmemobj++/transaction.hpp, line 456 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVKv7FzCza5t5Yzb4A3:-MV_PyU4Bw-kU9pguFaB:bdxxudv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ace28c409df1950a83ff0c53b6f59b0bfb6c37bd/include/libpmemobj++/transaction.hpp#L456)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually I can see we only use it in `register_callback`... why not elsewhere?
</blockquote></details>

that's really good point :) 
and it seems, such change would be pretty simple sed

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-:-MVa18xQ2AIFInxMNR1r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/transaction.hpp, line 456 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVKv7FzCza5t5Yzb4A3:-MVpNhP245LTXVqMkpv9:b-jvt6kn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ace28c409df1950a83ff0c53b6f59b0bfb6c37bd/include/libpmemobj++/transaction.hpp#L456)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

that's really good point :) 
and it seems, such change would be pretty simple sed
</blockquote></details>

@igchor, what do you think? Do you know if there was a reason for not using this...?
___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1968 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVpNpuDAIQTxy4Yc38S:-MVpNpuDAIQTxy4Yc38T:b-s3x79t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4fbb2736b890457c23b39d1171b805bd074a460/include/libpmemobj++/container/concurrent_hash_map.hpp#L1968)):*
> ```cpp
> 		if (layout_features.incompat != header_features().incompat)
> 			throw pmem::layout_error(
> 				"Incompat flags mismatch, for more details go to: https://pmem.io/libpmemobj-cpp\n");
> ```

hmm I tried to find some better link - what you think, should we put here something more precise...?

**Comment by karczex** [comment]
___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1968 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVpNpuDAIQTxy4Yc38S:-MVquUUkEs3TVbAZK9LY:b5797ev) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4fbb2736b890457c23b39d1171b805bd074a460/include/libpmemobj++/container/concurrent_hash_map.hpp#L1968)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm I tried to find some better link - what you think, should we put here something more precise...?
</blockquote></details>

Are you sure it's good idea to put link to documentation in error in low level library?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1968 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVpNpuDAIQTxy4Yc38S:-MVrBGRSEsfZU7pfNK9d:b-wkij0y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4fbb2736b890457c23b39d1171b805bd074a460/include/libpmemobj++/container/concurrent_hash_map.hpp#L1968)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Are you sure it's good idea to put link to documentation in error in low level library? 
</blockquote></details>

maybe you're right, maybe we should remove this and we have no problem...? :)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[include/libpmemobj++/pool.hpp, line 457 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MW--Yj9CgsDJwugpEaf:-MW--Yj9CgsDJwugpEag:b-hh69h6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/051c6961c08c8bf20c2e6a375b04bd80cd25e290/include/libpmemobj++/pool.hpp#L457)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> #ifndef _WIN32
> 	/**
> 	 * Default create mode
> 	 */
> 	static const int DEFAULT_MODE = S_IWUSR | S_IRUSR;
> #else
> 	/**
> 	 * Default create mode
> 	 */
> ```
</details>

IMO useless change, like this comments which only duplicate variable name.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[include/libpmemobj++/pool.hpp, line 457 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MW--Yj9CgsDJwugpEaf:-MW-0xF1-d2p0cM18E_p:bcl0wjb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/051c6961c08c8bf20c2e6a375b04bd80cd25e290/include/libpmemobj++/pool.hpp#L457)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #ifndef _WIN32
> 	/**
> 	 * Default create mode
> 	 */
> 	static const int DEFAULT_MODE = S_IWUSR | S_IRUSR;
> #else
> 	/**
> 	 * Default create mode
> 	 */
> ```
IMO useless change, like this comments which only duplicate variable name.
</blockquote></details>

without this change all user can see is in our docs is that we use some `DEFAULT_MODE` (see: https://pmem.io/libpmemobj-cpp/master/doxygen/classpmem_1_1obj_1_1pool.html#a8c7a780cfb3bc6c708856783938a9e8c ).
With this change they know exactly what this const equals to.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-:-MW3PxB95eiK7iyvRd1B:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/transaction.hpp, line 456 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVKv7FzCza5t5Yzb4A3:-MW3OsvG82IoAo9mIHZN:bevzno0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ace28c409df1950a83ff0c53b6f59b0bfb6c37bd/include/libpmemobj++/transaction.hpp#L456)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@igchor, what do you think? Do you know if there was a reason for not using this...?
</blockquote></details>

You mean in places where we for example check `pmemobj_tx_stage() == TX_STAGE_WORK`? It's beacuse pmemobj_tx_stage reutrns an int and we would have to cast the enum. In general, we should implement some C++ method like `stage()` within the transaction class.
___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1968 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVpNpuDAIQTxy4Yc38S:-MW3PM5DCFw18DD7lgwf:bzft3qz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4fbb2736b890457c23b39d1171b805bd074a460/include/libpmemobj++/container/concurrent_hash_map.hpp#L1968)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe you're right, maybe we should remove this and we have no problem...? :)
</blockquote></details>

This was done so that to offer some kind of information for users of older libraries. If there is new incompat flag introduced we can add some meanigful message in the new version of the library but for older versions, we cannot - we can only point to some external documenation.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/container/concurrent_hash_map.hpp, line 1968 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-MVpNpuDAIQTxy4Yc38S:-MW3dpf42jGQycHntgKI:bbdbyq7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4fbb2736b890457c23b39d1171b805bd074a460/include/libpmemobj++/container/concurrent_hash_map.hpp#L1968)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This was done so that to offer some kind of information for users of older libraries. If there is new incompat flag introduced we can add some meanigful message in the new version of the library but for older versions, we cannot - we can only point to some external documenation.
</blockquote></details>

ok, thx

**Review by KFilipek — COMMENTED** [review]
Once again :lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1054#-:-MW3vyj2EvHGHsLDF9QN:bauh5ae)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
