### PR TITLE
Import c++ bindings

### PR DESCRIPTION
**Pull request by igchor**
This is initial PR which imports all c++ bindings, examples and tests to this repo. Next PRs will remove
unnecessary files and setup a build system for tests and examples.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1)

### CODE REVIEW

**Comment by pbalcer** [comment]
we should still follow the same contributing guidelines in this repo ;)

**Comment by marcinslusarz** [comment]
BTW, "move" means "copy" and "remove source". This PR does only the "copy" part.

**Comment by igchor** [comment]
Done. Is 'tests' (as subfolder and area name) ok, or would you prefer to have 'test' like in pmdk?

**Comment by marcinslusarz** [comment]
I never liked "test" prefix, so I think this is fine.

**Pull request merged**
