### PR TITLE
string_view: implement iterator API for string_view

### PR DESCRIPTION
**Pull request by KFilipek**
This PR introduce iterator API for string_view class.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @KFilipek)

___
*[tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwhym-UWRMMMmnfiI:-MKJwhym-UWRMMMmnfiJ:bog9vxu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp#L8)):*
> ```cpp
> //
> //===----------------------------------------------------------------------===//
> ```

Intel license
___
*[tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwlnX904i9qHsSUdu:-MKJwlnX904i9qHsSUdv:b-xaxpmp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp#L52)):*
> ```cpp
> 	test(string_view("123"));
> 	test(wstring_view(L"123"));
> #if TEST_STD_VER >= 11
> ```

ifdef not needed
___
*[tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp, line 57 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwnsK4R2vLIDVn2tB:-MKJwnsK4R2vLIDVn2tC:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp#L57)):*
> ```cpp
> #endif
> 
> #if TEST_STD_VER > 11
> ```

.
___
*[tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwsHYCibgIB_C3Tii:-MKJwsHYCibgIB_C3Tij:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp#L8)):*
> ```cpp
> //
> //===----------------------------------------------------------------------===//
> ```

.
___
*[tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwqwI6liYAsgbaTGS:-MKJwqwI6liYAsgbaTGT:bfcm7qw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp#L50)):*
> ```cpp
> {
> 	typedef pmem::obj::string_view string_view;
> #if defined(__cpp_lib_char8_t) && __cpp_lib_char8_t >= 201811L
> ```

not needed?
___
*[tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwtuh6Unb0Nvg3Khm:-MKJwtuh6Unb0Nvg3Khn:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp#L71)):*
> ```cpp
> #endif
> 
> #if TEST_STD_VER > 11
> ```

.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwhym-UWRMMMmnfiI:-MKKAw2X5xM2YdpjDQZP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Intel license
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwlnX904i9qHsSUdu:-MKKAwXY2MuU-ku-3Bi0:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp#L52)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

ifdef not needed
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp, line 57 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwnsK4R2vLIDVn2tB:-MKKAx344PbSEKkss-Xr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/begin.pass.cpp#L57)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwsHYCibgIB_C3Tii:-MKKAxr03Py2wTmN1Wep:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp#L8)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp, line 50 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwqwI6liYAsgbaTGS:-MKKAyFH2W19JKUACHQP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp, line 71 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKJwtuh6Unb0Nvg3Khm:-MKKAypWAuVsPsot2-xA:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7b67a38e9bdf4ffb8046750d9526387fb266454b/tests/external/libcxx/string.view/string.view.iterators/end.pass.cpp#L71)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-:-MKKLKFhCmkjTC1cZr0Y:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @igchor)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 73 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-MKKPOuj81CVLS-8HeiU:-MKKPOuj81CVLS-8HeiV:b30qumv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/196ac2199d7462be59364d74a007e62d1480b451/include/libpmemobj++/string_view.hpp#L73)):*
> ```cpp
> 	constexpr const_iterator end() const noexcept;
> 	constexpr const_iterator cend() const noexcept;
> #ifdef XXX
> ```

You can add support for it in this PR, it;s quite trivial

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/948#-:-MKKTKa87loDxRHq8hwh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
