### PR TITLE
radix_tree: fix internal find

### PR DESCRIPTION
**Pull request by igchor**
Found by @kilobyte on fedora rawhide

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/928)

### CODE REVIEW

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/928#-:-MJ7-aXN1vsKrk28PepD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by kilobyte** [comment]
I've applied this fix in Fedora packaging.  This allowed me to push out cpp 1.11 — which built ok on all Fedora branches.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/928)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/928#-:-MJR4JeDBcrD5jXs4MaW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kilobyte — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/928#-:-MJR7PGQ95lAh_hFZqJb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
