### PR TITLE
Make index_sequence helpers compatible with std versions

### PR DESCRIPTION
**Pull request by igchor**
This change enables creating index_sequences from single number.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 38 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg68skc27zv5su0yx8r:-Mg68skc27zv5su0yx8s:bywbx14) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L38)):*
> ```cpp
> 
> /*
>  * Helper for make_integer_sequence, specialization for N == 0 (end of
> ```

helper for `make_integer_sequence_impl`
___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6B0jx32dlioxNEetj:-Mg6B0jx32dlioxNEetk:b-ueh2sy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L58)):*
> ```cpp
> 
> /*
>  * C++11 implementation of std::make_index_sequence.
> ```

`11`? if this is not a mistake, then why do we have this implementation here?
___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 68 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg68oiz8YOPq3STSMYv:-Mg68oiz8YOPq3STSMYw:bnjzv2g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L68)):*
> ```cpp
>  *
>  * A helper alias template to convert any type parameter pack into an index
>  * sequence of the same length. Analog of std::index_sequence_for.
> ```

pls drop `Analog of ...`
___
*[include/libpmemobj++/detail/pair.hpp, line 7 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6Bp4x99M73KzkjmF8:-Mg6Bp4x99M73KzkjmF9:borsaf0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8404149506d240ac9673fedd6f24f1523506eed4/include/libpmemobj++/detail/pair.hpp#L7)):*
> ```cpp
>  * @file
>  * Pair implementation.
>  */
> ```

why removed?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 38 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg68skc27zv5su0yx8r:-Mg6CZ9h9pgXjvumbxZ6:b-nu5kx4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

helper for `make_integer_sequence_impl`
</blockquote></details>

Actually, this is a helper for make_integer_sequnce (it is used by make_interger_sequence). But... I realized there is no make_integer_sequence implemented ;d Done.
___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6B0jx32dlioxNEetj:-Mg6D29C5n8XDzavMfPZ:b-iwdlu8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`11`? if this is not a mistake, then why do we have this implementation here?
</blockquote></details>

Yes, this is an implementation of std::make_index_sequnce (which was introduces in C++14) which works with C++11. Any ideas how to rephrase it?
___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 68 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg68oiz8YOPq3STSMYv:-Mg6DGtt5DDirZ7j2arL:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L68)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls drop `Analog of ...`
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/pair.hpp, line 7 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6Bp4x99M73KzkjmF8:-Mg6DHO5BMs6VeDcmmqL:b-nwffx5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8404149506d240ac9673fedd6f24f1523506eed4/include/libpmemobj++/detail/pair.hpp#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why removed?
</blockquote></details>

Ups, rebase conflict.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 38 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg68skc27zv5su0yx8r:-Mg6G7-i4nryG7yFjOwH:bqmbobz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L38)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually, this is a helper for make_integer_sequnce (it is used by make_interger_sequence). But... I realized there is no make_integer_sequence implemented ;d Done.
</blockquote></details>

haha :smile:, :+1: 
___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6B0jx32dlioxNEetj:-Mg6FgXVEgYemxJwCyCx:b-ptueaq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L58)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, this is an implementation of std::make_index_sequnce (which was introduces in C++14) which works with C++11. Any ideas how to rephrase it?
</blockquote></details>

hmm ok, I get it - all these helpers were introduced in c++14. I just thought these 2 were introduced earlier. 
I'd write something like `Implementation of std::make_index_sequence working with C++11`.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/integer_sequence.hpp, line 58 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6B0jx32dlioxNEetj:-Mg6HWil9g3Nc8xsEmiq:b12vda4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6682bc38885aaf408f6b6053ea6edcc2adc6d6c8/include/libpmemobj++/detail/integer_sequence.hpp#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm ok, I get it - all these helpers were introduced in c++14. I just thought these 2 were introduced earlier. 
I'd write something like `Implementation of std::make_index_sequence working with C++11`.
</blockquote></details>

Done. (slighly reworded)

**Review by KFilipek — COMMENTED** [review]
Generally looks okey

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-:-Mg6MWdk8vd58aCVULZ_:brscnu4)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/life.hpp, line 9 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-Mg6H96q3AluOBKVB5RL:-Mg6H96q3AluOBKVB5RM:b-9balrt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dc9b66f4e28c3f1cc3f969ca663132b73fd733d1/include/libpmemobj++/detail/life.hpp#L9)):*
> ```
> DESTROYER
> ```
I believe it was from the previous file.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1185#-:-Mg9kpLl1pBiz8Gzctv4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
