### PR TITLE
Add ChangeLog 1.12-rc1

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[ChangeLog, line 22 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020#-MSYU15mA1o3_qOq_GXT:-MSYU15mA1o3_qOq_GXU:b-8i8n76) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/65911adbef30e514eb3e0acf64e31b1507dd8bec/ChangeLog#L22)):*
> ```
> 	- fix assign_val function in radix tree which incorrectly handled
> 		inline_string<CharT> for CharT != char
> 	- fix use after in radix_tree::erase method
> ```

use after in...? is it something wrong or it's just me ;)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[ChangeLog, line 22 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020#-MSYU15mA1o3_qOq_GXT:-MSatSenE3fziV5DIlG7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/65911adbef30e514eb3e0acf64e31b1507dd8bec/ChangeLog#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

use after in...? is it something wrong or it's just me ;)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020#-:-MSawWIn6aDpEXD3uzba:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1020#-:-MSgqYMV97Jc8I1QXkXM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
