### PR TITLE
cmake: look for libpmemobj also when building benchmarks

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
rather than just for tests and examples.

ref. https://github.com/microsoft/vcpkg/blob/master/ports/libpmemobj-cpp/fixlibpmemobj-cpp.patch

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904)

### CODE REVIEW

**Review by szyrom — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 146 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904#-MIToAqR6VcJhop_Ko3-:-MIToAqSEvuScbFwFSau:b-k13v9k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f4768cd53d7a17a80edb71d0092ca3d17efd3a88/CMakeLists.txt#L146)):*
> ```CMake
> endif()
> 
> if(PKG_CONFIG_FOUND)
> ```

Hm, what about doc?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 146 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904#-MIToAqR6VcJhop_Ko3-:-MIToFFe9U5Q9raMNsgZ:bpuvuwa) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f4768cd53d7a17a80edb71d0092ca3d17efd3a88/CMakeLists.txt#L146)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, what about doc?
</blockquote></details>

For now, we do not need to have libpmemobj if we only want to build documentation. I think I would prefer to have a similar if as in vcpkg (for examples, tests and benchmarks).
___
*[CMakeLists.txt, line 154 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904#-MIToXS5E31LdFBLfakC:-MIToXS5E31LdFBLfakD:b-39x6q6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f4768cd53d7a17a80edb71d0092ca3d17efd3a88/CMakeLists.txt#L154)):*
> ```CMake
> endif()
> 
> if(BUILD_TESTS OR BUILD_EXAMPLES)
> ```

should this also include benchmarks?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[CMakeLists.txt, line 146 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904#-MIToAqR6VcJhop_Ko3-:-MITrhkhETSOLJaDaifq:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f4768cd53d7a17a80edb71d0092ca3d17efd3a88/CMakeLists.txt#L146)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

For now, we do not need to have libpmemobj if we only want to build documentation. I think I would prefer to have a similar if as in vcpkg (for examples, tests and benchmarks).
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 154 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904#-MIToXS5E31LdFBLfakC:-MITrby-4JUc09qaEqpV:brmt2z0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f4768cd53d7a17a80edb71d0092ca3d17efd3a88/CMakeLists.txt#L154)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

should this also include benchmarks?
</blockquote></details>

Done. I've added all of them under the same if

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/904#-:-MITrshVEGrwY10aGoAL:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @szyrom)

**Pull request merged**
