### PR TITLE
common: add script for performing releases

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @igchor)

___
*[utils/make_release.sh, line 5 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShUANIBHSZA1-vFqNF:-MShUANIBHSZA1-vFqNG:b-ijvtyt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L5)):*
> ```Shell
> # Copyright 2021, Intel Corporation
> 
> if [ -z "$VERSION_MAJOR" ]; then
> ```

you could rename it to e.g. `NEW_MAJOR`.
___
*[utils/make_release.sh, line 33 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShTjGxAhMgxU7kLHgC:-MShTjGxAhMgxU7kLHgD:b-bhtuiv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L33)):*
> ```Shell
> echo "VERSION: $VERSION"
> 
> ROOT_DIR=..
> ```

it's much safer to use `$(dirname $0)/..`. If you run this like `cd libpmemobj-cpp && ./utils/make_release` then it will fail (at best ;) )
___
*[utils/make_release.sh, line 44 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShV7Pn0TqFKfTDanur:-MShV7Pn0TqFKfTDanus:b3p1t83) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L44)):*
> ```Shell
>     sed -i -r "s/set\(VERSION_PATCH [0-9]+\)/set\(VERSION_PATCH $VERSION_PATCH\)/g" $ROOT_DIR/CMakeLists.txt
> else
>     sed -i -r "s/set\(VERSION_PATCH [0-9]+\)/set\(VERSION_PATCH 0\)/g" $ROOT_DIR/CMakeLists.txt
> ```

don't duplicate this, just set VERSION_PATCH to 0 if not set by env var, I guess
___
*[utils/make_release.sh, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShW6BWE56Gm2i2rmm7:-MShW6BWE56Gm2i2rmm8:bfmgfw5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L48)):*
> ```Shell
> if [ -n "$VERSION_PRERELEASE" ]; then
>     sed -i -r "s/(set\(VERSION_PATCH [0-9]+\))/\1\nset\(VERSION_PRERELEASE $VERSION_PRERELEASE\)/g" $ROOT_DIR/CMakeLists.txt
> fi
> ```

we should also update the date of CMake file, if needed
___
*[utils/make_release.sh, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShUtQaDfOzs6VLOfnR:-MShUtQaDfOzs6VLOfnS:b-v5ub8t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L52)):*
> ```Shell
> # Create commit and tag
> git add $ROOT_DIR/CMakeLists.txt
> git commit -S -m "common: $VERSION release"
> ```

`-S` is for signing, I'm not sure if we use it
___
*[utils/make_release.sh, line 57 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShWda76StCjyrGZk5X:-MShWda76StCjyrGZk5Y:b-gxoeb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L57)):*
> ```Shell
> # Undo temporary release changes
> git rm $ROOT_DIR/.version
> if [ -n "$VERSION_PRERELEASE" ]; then
> ```

pls update the RELEASE_STEPS with this step
___
*[utils/make_release.sh, line 58 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShWiQV-w3_QfBPj6kN:-MShWiQV-w3_QfBPj6kO:btr4n2d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L58)):*
> ```Shell
> git rm $ROOT_DIR/.version
> if [ -n "$VERSION_PRERELEASE" ]; then
>     sed -i -r "/(set\(VERSION_PRERELEASE [0-9a-z]+\))/d" $ROOT_DIR/CMakeLists.txt
> ```

`0-9a-zA-Z` we may use e.g. `Beta` for a reason... or actually you can catch anything `.*` (?)
___
*[utils/make_release.sh, line 64 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShX9OL6M-sV9bvEUCu:-MShX9OL6M-sV9bvEUCv:b-ae0rc3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L64)):*
> ```Shell
> 
> # XXX: check generated rpm/deb
> ```

we could add `echo` for manual steps, like `echo 'Verify the generated package - content, naming, etc...'`
___
*[utils/make_release.sh, line 78 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShXxgf4XBe6koVeVsI:-MShXxgf4XBe6koVeVsJ:b-qllsso) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L78)):*
> ```Shell
> 
> # XXX for major/minor releses: ask for vcpg update
> ```

we could also add in RELEASE_STEPS info

`<!-- if you're updating this file, please remember to update also utils/make_release.sh`

**Review by KFilipek — COMMENTED** [review]
Also we can use:
https://cli.github.com/manual/gh_release_create
gh release create v1.2.3 -F changelog.md

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-:-MShZpIo2WVi-E59jUGD:bxdzhkm)* status: all files reviewed, 10 unresolved discussions (waiting on @igchor)

___
*[utils/make_release.sh, line 79 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShXnwVApV0Jzqi4D4u:-MShXnwVApV0Jzqi4D4v:b-mypiny) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L79)):*
> ```Shell
> # XXX for major/minor releses: ask for vcpg update
> 
> # XXX generate compatibiity test
> ```

no EOF

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor)

___
*[utils/make_release.sh, line 37 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MTLSiSz4C9Uz301arKt:-MTLSiSz4C9Uz301arKu:b-bw169x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L37)):*
> ```Shell
> echo $VERSION > $ROOT_DIR/.version
> git add $ROOT_DIR/.version
> ```

Probably we should also check/modify ChangeLog

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[utils/make_release.sh, line 5 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShUANIBHSZA1-vFqNF:-MTuCVaNA9n5BKiLqnhd:b-arp20z) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could rename it to e.g. `NEW_MAJOR`.
</blockquote></details>

This was done to be compatible with our cmake versioning -  think VERSION_MAJOR in context of this script is rather clear
___
*[utils/make_release.sh, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShUtQaDfOzs6VLOfnR:-MTuCfZZ9YNEqqO31if-:b-7hcwy0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`-S` is for signing, I'm not sure if we use it
</blockquote></details>

we do
___
*[utils/make_release.sh, line 78 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShXxgf4XBe6koVeVsI:-MTuClIq0Z1RW_3cE304:b-c4n8e5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we could also add in RELEASE_STEPS info

`<!-- if you're updating this file, please remember to update also utils/make_release.sh`
</blockquote></details>

I would say this would replace relese_steps

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor)

___
*[utils/make_release.sh, line 78 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShXxgf4XBe6koVeVsI:-MU7rIlv2SmhmHN1hfsd:b-9wf09i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L78)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would say this would replace relese_steps
</blockquote></details>

there still will be some manual steps to do, I guess... so it will still be needed, I guess (and it can contain step called: 'run make_release.sh' ;) )

**Review by lukaszstolarczuk — COMMENTED** [review]
I believe, with few minor tweaks we can merge it as is.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-:-N8c9IrF1rnS2FtdlTPb:be1wux)* status: all files reviewed, 9 unresolved discussions (waiting on @igchor)

___
*[`utils/make_release.sh` line 37 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MTLSiSz4C9Uz301arKt:-N8c8zHC2L4BTIx6AyUn:b7gemn5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L37)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Probably we should also check/modify ChangeLog
</blockquote></details>

you can just set an XXX comment for that - to do that manually, before running the script
___
*[`utils/make_release.sh` line 3 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N8c9H_dEZUxz8f6Pswy:-N8c9H_dEZUxz8f6Pswz:b-8mxyka) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0f5e5255eb5bdaf56f8d482c5cc4fb0c69805b62/utils/make_release.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2021, Intel Corporation
> ```

-2022
___
*[`utils/make_release.sh` line 23 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N8c96Na4BSfm2nfIdrl:-N8c96Na4BSfm2nfIdrm:buxkbmp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0f5e5255eb5bdaf56f8d482c5cc4fb0c69805b62/utils/make_release.sh#L23)):*
> ```Shell
> VERSION=$VERSION_MAJOR.$VERSION_MINOR
> 
> if [ -n "$VERSION_PATCH" ]; then
> ```

instead of this, you can just set `VERSION_PATCH=0` if `-z "$VERSION_PATCH"` (if not set)... 

and move this `if` above setting VERSION

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`utils/make_release.sh` line 33 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShTjGxAhMgxU7kLHgC:-N926bvm0uM8f2wezMVt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L33)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's much safer to use `$(dirname $0)/..`. If you run this like `cd libpmemobj-cpp && ./utils/make_release` then it will fail (at best ;) )
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 44 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShV7Pn0TqFKfTDanur:-N926vW832eyaZ6LNQKE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

don't duplicate this, just set VERSION_PATCH to 0 if not set by env var, I guess
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShW6BWE56Gm2i2rmm7:-N9271mxCjOKxTevnrh6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we should also update the date of CMake file, if needed
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 58 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShWiQV-w3_QfBPj6kN:-N927YrA8sHVc5uhEdgM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`0-9a-zA-Z` we may use e.g. `Beta` for a reason... or actually you can catch anything `.*` (?)
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 78 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShXxgf4XBe6koVeVsI:-N92AvX493l4k_iF0M_6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

there still will be some manual steps to do, I guess... so it will still be needed, I guess (and it can contain step called: 'run make_release.sh' ;) )
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 79 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-MShXnwVApV0Jzqi4D4u:-N927gmpBjnO27tDGAWQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/621363581926a18c00baaa9bb12c6f4d0adc5f05/utils/make_release.sh#L79)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

no EOF
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 3 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N8c9H_dEZUxz8f6Pswy:-N926TYI8pXoLFHCG2kQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0f5e5255eb5bdaf56f8d482c5cc4fb0c69805b62/utils/make_release.sh#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2022
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 23 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N8c96Na4BSfm2nfIdrl:-N926Tko4TbhqnLOOHhX:biyq3nc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0f5e5255eb5bdaf56f8d482c5cc4fb0c69805b62/utils/make_release.sh#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

instead of this, you can just set `VERSION_PATCH=0` if `-z "$VERSION_PATCH"` (if not set)... 

and move this `if` above setting VERSION
</blockquote></details>

Done. If not needed anymore since we always have patch version now.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[`doc/RELEASE_STEPS.md` line 10 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N95jS_bCFCE6wP3r1f7:-N95jS_bCFCE6wP3r1f8:b569q6p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2e1d7d93f9a3328c7e85933b7ef570244bb550dd/doc/RELEASE_STEPS.md#L10)):*
> ```Markdown
> - add an entry to ChangeLog, remember to change the day of the week in the release date
>   - for major/minor releases mention compatibility with the previous release
>   - for major/minor releases add new ChangeLog template (for $VER+1)
> ```

I'd leave these 3 lines, about ChangeLog - that info is not ported into the script
___
*[`utils/make_release.sh` line 23 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N8c96Na4BSfm2nfIdrl:-N95k7KR3scYp4WVxJR7:b90diqv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0f5e5255eb5bdaf56f8d482c5cc4fb0c69805b62/utils/make_release.sh#L23)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done. If not needed anymore since we always have patch version now.
</blockquote></details>

that's what I meant, in my twisted wording :smile: 
___
*[`utils/make_release.sh` line 4 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N95l6qLBfBHSK5y2hDW:-N95l6qLBfBHSK5y2hDX:b-qqioa8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/24abc8229cca64a8f49420e5ef6d1266d75b1287/utils/make_release.sh#L4)):*
> ```Shell
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2022, Intel Corporation
> ```

you can mention in some short description this script is not complete :smile: 
___
*[`utils/make_release.sh` line 29 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N95jrnH1HvXZT9dz3c6:-N95jrnH1HvXZT9dz3c7:bauwdt9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/24abc8229cca64a8f49420e5ef6d1266d75b1287/utils/make_release.sh#L29)):*
> ```Shell
> fi
> 
> if [ -z "$REMOTE" ]; then
> ```

it's not used anywhere

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[`doc/RELEASE_STEPS.md` line 10 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N95jS_bCFCE6wP3r1f7:-N96bKnv5wgIKUiLoj3M:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2e1d7d93f9a3328c7e85933b7ef570244bb550dd/doc/RELEASE_STEPS.md#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd leave these 3 lines, about ChangeLog - that info is not ported into the script
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 4 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N95l6qLBfBHSK5y2hDW:-N96bvw91b6sSdHzw5i5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/24abc8229cca64a8f49420e5ef6d1266d75b1287/utils/make_release.sh#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can mention in some short description this script is not complete :smile: 
</blockquote></details>

Done.
___
*[`utils/make_release.sh` line 29 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-N95jrnH1HvXZT9dz3c6:-N96bv5e3SVdHJZp_m6Y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/24abc8229cca64a8f49420e5ef6d1266d75b1287/utils/make_release.sh#L29)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not used anywhere
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1029#-:-N96hISm7w0vjLlR90Jr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
