### PR TITLE
CI: always build and push docker images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
On stable branches we don't commit much, so this will hardly impact
usage of our CI, and since we always rebuild, script 'pull-or-rebuild.sh'
is no longer necessary.

It's an alternative for #929 :
- it removes dead code from the stable branch,
- it simplifies read of the workload,
- **but** it will require to clean stable branch each time after release (RELEASE_STEPS.md will be updated if we choose this option).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/935)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/935#-:-MJadrglBFCkLRb3dN8p:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by karczex** [comment]
@lukaszstolarczuk 
It should be possible to trigger server-side post-receive hook to cherry-pick some patches (like this one) on stable branch creation.

**Review by igchor — COMMENTED** [review]
TBH, I'd prefer https://github.com/pmem/libpmemobj-cpp/pull/929/files

With this approach we'll have to resolve merge conflicts for each new stable branch when merging with master.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/935#-:-MJl9qYXEpwf6FFlyAjK:bs96qys)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
#929 is most likely the way we go to solve our problem.

**Pull request closed without merging**
