### PR TITLE
string_view: implement reverse iterators and tests

### PR DESCRIPTION
**Pull request by KFilipek**
- string_view: implement reverse iterator
- string_view: add string_view reverse iterator API libcxx tests
- string_view: port reverse iterator tests from libcxx

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959#-:-ML6nvN32KCuJdPjzxdl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[tests/external/libcxx/string.view/string.view.iterators/rbegin.pass.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959#-ML6oAOB57ZOopSFgceS:-ML6oAOC5xmo5ppE7kDK:bpc6b5p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b5fce79d20a46ea4c5e3897cabee7134a590cb31/tests/external/libcxx/string.view/string.view.iterators/rbegin.pass.cpp#L31)):*
> ```cpp
> 	typename S::const_reverse_iterator cb2 = s.crbegin();
> 	if (!s.empty()) {
> 		volatile size_t last = s.size() - 1;
> ```

Imho it would be cleaner to just split this function into two functions (for empty and non-empty strnigs) and just call appropiate one. If you want to leave it as it is, at least add some comment why this volatile is needed

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[tests/external/libcxx/string.view/string.view.iterators/rbegin.pass.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959#-ML6oAOB57ZOopSFgceS:-ML8MayZD7bw5mvm0_CE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b5fce79d20a46ea4c5e3897cabee7134a590cb31/tests/external/libcxx/string.view/string.view.iterators/rbegin.pass.cpp#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Imho it would be cleaner to just split this function into two functions (for empty and non-empty strnigs) and just call appropiate one. If you want to leave it as it is, at least add some comment why this volatile is needed
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/959#-:-MLCw0iH6qV6_8_aUrU8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
