### PR TITLE
Add deleted assignment operator for persistent_aware ptr

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
\+ add some missing Doxygen docs

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229#-:-Monm5Qz0o-9klisprZt:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/atomic_persistent_aware_ptr.hpp, line 175 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229#-Monn0NZ45FJB5JJpZ0t:-Monn0N_7jYUz7J1am4E:b8rujaj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b3585768e9909a7db1ca4733b4eca46b5d8c02b8/include/libpmemobj%2B%2B/experimental/atomic_persistent_aware_ptr.hpp#L175)):*
> ```
> return load();
> ```
Documentation for `load()`: 
`* @return the self_relative_ptr (no dirty flag)`

function `load()` returns: 
```cpp
typename std::enable_if<std::is_same<OPT, std::true_type>::value, value_type>::type
```
so:
```cpp
using value_type = pmem::obj::experimental::self_relative_ptr<T>;
```

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229#-:-Monoi8xDFkfS1-2CFY6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/experimental/atomic_persistent_aware_ptr.hpp, line 175 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229#-Monn0NZ45FJB5JJpZ0t:-MosPPG09zNM44-C0YeH:bdudl1o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b3585768e9909a7db1ca4733b4eca46b5d8c02b8/include/libpmemobj%2B%2B/experimental/atomic_persistent_aware_ptr.hpp#L175)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also, I guess other comments should also be improved - most of them contain implementation details (like dirty flag) and no info on paramers etc. But that's probably a task for another PR.
</blockquote></details>

Done. I moved the impl. details into comments within the function. I hope I didn't mix anything up while re-writing.

**Review by KFilipek — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1229#-:-Mp8E89xCYsp4wzFBZnm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
