### PR TITLE
doc: change maintainer contact info

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm: , but fix 2021 ;)

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025#-:-MSgQxVX3xX_z_wJEp07:b-32e44c)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025#-MSgQh6K8CiUEXMJWpdX:-MSgQh6K8CiUEXMJWpdY:bblhigc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e97ab9a63f4a62702666a13bf66f825c1723be1d/utils/docker/images/Dockerfile.archlinux-base-latest#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2020, Intel Corporation
> ```

2021 ;)
___
*[utils/docker/images/Dockerfile.debian-testing, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025#-MSgQodn-9uuENKNywyH:-MSgQodn-9uuENKNywyI:b58f59g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e97ab9a63f4a62702666a13bf66f825c1723be1d/utils/docker/images/Dockerfile.debian-testing#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2020, Intel Corporation
> ```

. (fix all)

**Review by KFilipek — COMMENTED** [review]
Same as Łukasz,
:lgtm:

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025#-:-MSgUbhO6MJvFwIkbXys:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025)* status: 2 of 14 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025#-MSgQh6K8CiUEXMJWpdX:-MSg_OqH8HDywj4S3X_e:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e97ab9a63f4a62702666a13bf66f825c1723be1d/utils/docker/images/Dockerfile.archlinux-base-latest#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021 ;)
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-testing, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025#-MSgQodn-9uuENKNywyH:-MSg_PB-911erXw1Qjdd:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e97ab9a63f4a62702666a13bf66f825c1723be1d/utils/docker/images/Dockerfile.debian-testing#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (fix all)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1025)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
