### PR TITLE
Add decoration to exceptions instead of calling method

### LINKED ISSUE #1146: Remove code duplication
Code multiplied 8 times.
```cpp
		if (ptr == nullptr) {
			if (errno == ENOMEM) {
				throw pmem::transaction_out_of_memory(
					"Failed to allocate persistent memory object")
					.with_pmemobj_errormsg();
			} else {
				throw pmem::transaction_alloc_error(
					"Failed to allocate persistent memory object")
					.with_pmemobj_errormsg();
			}
		}
```

This issue can be commented with other duplication found, I will fix it during another change, I don't prefer making just cleanup commits.

### PR DESCRIPTION
**Pull request by KFilipek**
This commit also removes code duplications.
Fixes #1146

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/detail/common.hpp, line 162 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MeVN8xz2lOFtg9JFXlE:-MeVN8xz2lOFtg9JFXlF:b-ub8okt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0e24140127965bb50806cb39f33855043ab3e110/include/libpmemobj++/detail/common.hpp#L162)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> template <class T1 /* in case of ENOMEM */, class T2 /* otherwise */>
> void
> throw_when_errno(std::string exception_msg)
> {
> 	if (errno == ENOMEM) {
> 		throw T1(exception_msg).with_pmemobj_errormsg();
> 	} else {
> 		throw T2(exception_msg).with_pmemobj_errormsg();
> 	}
> }
> ```
</details>

@igchor I wonder how to check in elegant way that T1/T2 has method `with_pmemobj_errormsg()` then call it, otherwise just construct the object.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/detail/common.hpp, line 162 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MeYXGne-uFAnceWcqOw:-MeYXGnfBvVVVIkXgaKE:b-gqoc41) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0e24140127965bb50806cb39f33855043ab3e110/include/libpmemobj++/detail/common.hpp#L162)):*
> ```cpp
> #endif
> 
> template <class T1 /* in case of ENOMEM */, class T2 /* otherwise */>
> ```

You may change T1 and T2 to If_ENOMEM and Otherwise instead of adding those comments.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/detail/common.hpp, line 162 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MeVN8xz2lOFtg9JFXlE:-MeYublsDwiiYWa98XXo:b-jn287b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0e24140127965bb50806cb39f33855043ab3e110/include/libpmemobj++/detail/common.hpp#L162)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> template <class T1 /* in case of ENOMEM */, class T2 /* otherwise */>
> void
> throw_when_errno(std::string exception_msg)
> {
> 	if (errno == ENOMEM) {
> 		throw T1(exception_msg).with_pmemobj_errormsg();
> 	} else {
> 		throw T2(exception_msg).with_pmemobj_errormsg();
> 	}
> }
> ```
@igchor I wonder how to check in elegant way that T1/T2 has method `with_pmemobj_errormsg()` then call it, otherwise just construct the object.
</blockquote></details>

I think we should be careful with such checks, ENOMEM can come from other sources, e.g. from`new`. If we allow any type to be passed as T1, user would have to make sure it passes pmem::transaction_out_of_memory for cases where error comes from libpmemobj and std::bad_alloc otherwise.

Maybe we should just hardcode the T1 to be pmem::transaction_out_of_memory and include `pmemobj` somewhere in the function name?
___
*[include/libpmemobj++/detail/common.hpp, line 167 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MeYuGoB1Y0SwaQuxfmb:-MeYuGoC0UyEEo172VyN:b-i3ckgq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0e24140127965bb50806cb39f33855043ab3e110/include/libpmemobj++/detail/common.hpp#L167)):*
> ```cpp
> {
> 	if (errno == ENOMEM) {
> 		throw T1(exception_msg).with_pmemobj_errormsg();
> ```

The name is a bit misleading. I would think that this function throws only if errno is set, but this function throws always.

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/detail/common.hpp, line 162 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MeYXGne-uFAnceWcqOw:-MfrEgLZDjyO68Un__Db:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0e24140127965bb50806cb39f33855043ab3e110/include/libpmemobj++/detail/common.hpp#L162)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You may change T1 and T2 to If_ENOMEM and Otherwise instead of adding those comments.
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/common.hpp, line 167 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MeYuGoB1Y0SwaQuxfmb:-MfrEg9S56KzMnhvCqnZ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0e24140127965bb50806cb39f33855043ab3e110/include/libpmemobj++/detail/common.hpp#L167)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The name is a bit misleading. I would think that this function throws only if errno is set, but this function throws always.
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/common.hpp, line 173 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MfrEyPE00uFtuQ8L21m:-MfrEyPE00uFtuQ8L21n:b-tzmsat) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1f77be74992d954b12041174135093099181793f/include/libpmemobj++/detail/common.hpp#L173)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> // /**
> // * Error message decorator for pmemobj exceptions.
> // */
> // template <>
> // auto &
> // exception_with_errormsg<pmem::lock_error>(pmem::lock_error &&obj)
> // {
> //	obj = std::move(pmem::lock_error(obj.code(),
> //					 obj.what() + std::string(": ") +
> //						 detail::errormsg()));
> //	return obj;
> // }
> ```
</details>

@igchor do you have any idea how to do it in more generic way? Mutex related exceptions have a little bit different object creation and I cannot trivially pass arguments.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/make_persistent.hpp, line 34 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5yKsd6-tZwT_fnlIB:-Mg5yKsd6-tZwT_fnlIC:b-btbubc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/make_persistent.hpp#L34)):*
> ```cpp
> namespace
> {
> using detail::exception_with_errormsg;
> ```

Is this really necessary? Why not just `throw detail::exception_with_errormsg(...)`?
___
*[include/libpmemobj++/make_persistent_array.hpp, line 231 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5zN94Co8J3qrtPjzL:-Mg5zN94Co8J3qrtPjzM:b-16vhm7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/make_persistent_array.hpp#L231)):*
> ```cpp
> 
> 	if (pmemobj_tx_stage() != TX_STAGE_WORK)
> 		throw exception_with_errormsg<pmem::transaction_scope_error>(
> ```

We don't want to decorate here (there was no with_pmemobj_errormsg).
___
*[include/libpmemobj++/pexceptions.hpp, line 83 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5yYJF1MnJOg3w2nex:-Mg5yYJF1MnJOg3w2ney:bgq5r0t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/pexceptions.hpp#L83)):*
> ```cpp
> public:
> 	using std::system_error::system_error;
> 	lock_error(std::error_code ec, const std::string &msg)
> ```

I think the using above makes this ctor visible already
___
*[include/libpmemobj++/pexceptions.hpp, line 195 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5ybe5A3w3dFmagPrP:-Mg5ybe5A3w3dFmagPrQ:bgom35f) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/pexceptions.hpp#L195)):*
> ```cpp
> 	 * @param msg error message
> 	 */
> 	defrag_error(const std::string &msg) : std::runtime_error(msg)
> ```

The using above should be enough
___
*[include/libpmemobj++/detail/common.hpp, line 167 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5z3mZ884KiSkyTAak:-Mg5z3mZ884KiSkyTAal:b2ok3fo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/detail/common.hpp#L167)):*
> ```cpp
> template <class ExcT, typename MsgT>
> ExcT
> exception_with_errormsg(MsgT msg)
> ```

`const MsgT& msg`
___
*[include/libpmemobj++/detail/common.hpp, line 177 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5zA8Q1goOAM09swg8:-Mg5zA8Q1goOAM09swg9:b1xpxk6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/detail/common.hpp#L177)):*
> ```cpp
> // template <>
> // auto &
> // exception_with_errormsg<pmem::lock_error>(pmem::lock_error &&obj)
> ```

Please remove this commented code

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/detail/common.hpp, line 173 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MfrEyPE00uFtuQ8L21m:-Mg6-OrV2_1TOV4D5G5E:b-watlm3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1f77be74992d954b12041174135093099181793f/include/libpmemobj++/detail/common.hpp#L173)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> // /**
> // * Error message decorator for pmemobj exceptions.
> // */
> // template <>
> // auto &
> // exception_with_errormsg<pmem::lock_error>(pmem::lock_error &&obj)
> // {
> //	obj = std::move(pmem::lock_error(obj.code(),
> //					 obj.what() + std::string(": ") +
> //						 detail::errormsg()));
> //	return obj;
> // }
> ```
@igchor do you have any idea how to do it in more generic way? Mutex related exceptions have a little bit different object creation and I cannot trivially pass arguments.
</blockquote></details>

Yes, we can use this approach: https://stackoverflow.com/questions/31255890/obtain-all-but-last-parameter-of-variadic-template once this PR is merged: https://github.com/pmem/libpmemobj-cpp/pull/1185

**Review by KFilipek — COMMENTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 6 of 9 files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[include/libpmemobj++/make_persistent.hpp, line 34 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5yKsd6-tZwT_fnlIB:-Mg617CmB8s7xy7ToC-U:bio4qsq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/make_persistent.hpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is this really necessary? Why not just `throw detail::exception_with_errormsg(...)`?
</blockquote></details>

It's for not using everywhere "detail::", this anonymous namespace allows to use `exception_with_errormsg(...)` exclusively in this file
___
*[include/libpmemobj++/make_persistent_array.hpp, line 231 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5zN94Co8J3qrtPjzL:-Mg62Hod9VTUpdBNYQkt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/make_persistent_array.hpp#L231)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We don't want to decorate here (there was no with_pmemobj_errormsg).
</blockquote></details>

Done.
___
*[include/libpmemobj++/pexceptions.hpp, line 83 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5yYJF1MnJOg3w2nex:-Mg63rw1Bh0aVVb9Mhyl:b7erxum) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/pexceptions.hpp#L83)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think the using above makes this ctor visible already
</blockquote></details>

Done. This is from time when I tried multiple approaches, mostly wrong xD
___
*[include/libpmemobj++/pexceptions.hpp, line 195 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5ybe5A3w3dFmagPrP:-Mg64Sz6224I_F_MZ6hc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/pexceptions.hpp#L195)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The using above should be enough
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/common.hpp, line 167 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5z3mZ884KiSkyTAak:-Mg65u6L38Bnu9aXsYYW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/detail/common.hpp#L167)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`const MsgT& msg`
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/common.hpp, line 177 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5zA8Q1goOAM09swg8:-Mg66mxCDPHQwFp8VE1d:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/detail/common.hpp#L177)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please remove this commented code
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/make_persistent.hpp, line 34 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5yKsd6-tZwT_fnlIB:-Mg69c-F1PjGWb16gEAO:b-viuirz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/make_persistent.hpp#L34)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's for not using everywhere "detail::", this anonymous namespace allows to use `exception_with_errormsg(...)` exclusively in this file
</blockquote></details>

Are you sure? I just tested this and it looks like every file which is including this one can use exception_with_errormsg without the `detail::`

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/make_persistent.hpp, line 34 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-Mg5yKsd6-tZwT_fnlIB:-Mg6F0KA4uca9ui-yavK:bkcydti) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e55504fe0ee5dd26c51f2d3b94c6dc7bc2baac19/include/libpmemobj++/make_persistent.hpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Are you sure? I just tested this and it looks like every file which is including this one can use exception_with_errormsg without the `detail::`
</blockquote></details>

Maybe it was my misunderstood, I reverted to `detail::`, generally all lines were wrapped, so it's don't changed style.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-:-Mg6Fxqs-vcYzNZDqd6m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/pexceptions.hpp, line 85 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1DH9EdK-ALj209v6:-MgA1DHAC1wc214Gjioh:bexp0vp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L85)):*
> ```cpp
> 
> 	/**
> 	 * @copydoc pool_error::with_pmemobj_errormsg();
> ```

pls fix this comment - we can't copy the docs since there's nothing to copy from :wink:
___
*[include/libpmemobj++/pexceptions.hpp, line 88 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1IEwCrz3iL2K7mpH:-MgA1IEwCrz3iL2K7mpI:b-kycz6s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L88)):*
> ```cpp
> 	 */
> 	lock_error &
> 	with_pmemobj_errormsg()
> ```

I guess we don't want to fix this, for now, so we should update/file an issue or just put some XXX comment here
___
*[include/libpmemobj++/pexceptions.hpp, line 201 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1ssN4qnK4D6Vb6Ig:-MgA1ssN4qnK4D6Vb6Ih:b-9plica) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L201)):*
> ```cpp
> 	 * Append partial results.
> 	 *
> 	 * @param result potientially partial results of the defragmentation
> ```

`potential partial results`
___
*[include/libpmemobj++/detail/common.hpp, line 163 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA4b0R6SKatvNGVINu:-MgA4b0SA4Du3PN6n0tw:bwmkpmh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/detail/common.hpp#L163)):*
> ```cpp
> 
> /**
>  * Generic error message decorator for pmemobj exceptions.
> ```

`pmemobj-based exceptions`

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[include/libpmemobj++/pexceptions.hpp, line 85 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1DH9EdK-ALj209v6:-MgAk8yC-6c4YgTIvABm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L85)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls fix this comment - we can't copy the docs since there's nothing to copy from :wink:
</blockquote></details>

Done.
___
*[include/libpmemobj++/pexceptions.hpp, line 88 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1IEwCrz3iL2K7mpH:-MgAkJqE3z1vC4F4CSdf:b-io0b14) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L88)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess we don't want to fix this, for now, so we should update/file an issue or just put some XXX comment here
</blockquote></details>

We want to remove it after merging @igchor PR.
___
*[include/libpmemobj++/pexceptions.hpp, line 201 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1ssN4qnK4D6Vb6Ig:-MgAkYF5DFtJucqsJ2iq:b-7syz5x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L201)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`potential partial results`
</blockquote></details>

Done. Changed 2 times.
___
*[include/libpmemobj++/detail/common.hpp, line 163 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA4b0R6SKatvNGVINu:-MgAkgxS65uRs1FzOQkd:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/detail/common.hpp#L163)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`pmemobj-based exceptions`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/pexceptions.hpp, line 201 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1ssN4qnK4D6Vb6Ig:-MgAp0vBE4XrTjUJBwS8:b-i8obme) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L201)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done. Changed 2 times.
</blockquote></details>

nope :wink: `c` -> `t`

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @igchor, @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/pexceptions.hpp, line 201 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-MgA1ssN4qnK4D6Vb6Ig:-MgB16YQ7AwEPpNGBtX6:b2nhswy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dcc69d308a3e93f45ca240a4ffcc2ad0ea7c5869/include/libpmemobj++/pexceptions.hpp#L201)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope :wink: `c` -> `t`
</blockquote></details>

Yes

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1157#-:-MgB6MFR7qDmeDdgIlsU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Pull request merged**
