### PR TITLE
Ubsan fixes

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
For future reference, please add errors you are fixing to commit messages.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112#-:-MdRfu3R3Egshw3leIp8:b-3ivbca)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Comment by karczex** [comment]
___
*[tests/external/libcxx/map/is_transparent.h, line 178 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112#-MdSBa05-BgICkZbXqZo:-MdSBa05-BgICkZbXqZp:btxv1cn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/243649c854fff2e12642a48ab010e4702561e2b5/tests/external/libcxx/map/is_transparent.h#L178)):*
> ```objc
> 	heterogeneous_bytes_view(const C2Int *value)
> 	{
> 		v = (unsigned)(value->get()) +
> ```

Wouldn't static_cast be better?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[tests/common/map_wrapper.hpp, line 56 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112#-MdSCfoG3u20OPdq4QIQ:-MdSCfoG3u20OPdq4QIR:b-ekhsj0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/243649c854fff2e12642a48ab010e4702561e2b5/tests/common/map_wrapper.hpp#L56)):*
> ```cpp
> struct test_bytes_view_int {
> 	test_bytes_view_int(const int *v)
> 	    : v((unsigned)(*v) + std::numeric_limits<int>::max() + 1)
> ```

static_cast?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[tests/common/map_wrapper.hpp, line 56 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112#-MdSCfoG3u20OPdq4QIQ:-MdWN4WX01IQ1xG0DICW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/243649c854fff2e12642a48ab010e4702561e2b5/tests/common/map_wrapper.hpp#L56)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

static_cast?
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/is_transparent.h, line 178 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112#-MdSBa05-BgICkZbXqZo:-MdWN4s6AuWPdXUepTPQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/243649c854fff2e12642a48ab010e4702561e2b5/tests/external/libcxx/map/is_transparent.h#L178)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Wouldn't static_cast be better?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1112#-:-MdXA-Wr6ME27vNaYUTD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
