### PR TITLE
Weekly fixes

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110)* status: 2 of 34 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[tests/CMakeLists.txt, line 983 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-MdNGDG23UonP9ouDIPA:-MdNGDG3AJSupD866QQG:b-yig29c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a4d958812268d5aaf578e4dba58cc453e3a768ad/tests/CMakeLists.txt#L983)):*
> ```CMake
> 	if(PMREORDER_SUPPORTED)
> 		build_test(mpsc_queue_recovery_pmreorder mpsc_queue/recovery_pmreorder.cpp)
> 		add_test_generic(NAME mpsc_queue_recovery_pmreorder CASE 0 SCRIPT mpsc_queue/recovery_pmreorder_0.cmake TRACERS none)
> ```

you can add a new sub-dir in the `mpsc_queue` called `pmreorder` to place all scripts there (we have this approach in pmemkv and it seems to shorten the name a little.
(`pmreorder` in the name is required, so only for scripts)
___
*[tests/external/libcxx/array/at.pass.cpp, line 10 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-MdNGnN84On2CtdGCqdk:-MdNGnN84On2CtdGCqdl:b-igi7sz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a4d958812268d5aaf578e4dba58cc453e3a768ad/tests/external/libcxx/array/at.pass.cpp#L10)):*
> ```cpp
> //===----------------------------------------------------------------------===//
> //
> // Copyright 2018-2020, Intel Corporation
> ```

pls bump the licenses

**Review by karczex — COMMENTED** [review]
> Reviewed 9 of 11 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/external/libcxx/array/at.pass.cpp, line 10 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-MdNGnN84On2CtdGCqdk:-MdRk20fCkRETBKOyxqX:b-qvw6wh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a4d958812268d5aaf578e4dba58cc453e3a768ad/tests/external/libcxx/array/at.pass.cpp#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls bump the licenses
</blockquote></details>

If you want, you may copy copyright-format target (and update check-headers.sh) from pmemkv https://github.com/pmem/pmemkv/blob/89744f5e627be5eaaa062b0c520eb23315c7a847/CMakeLists.txt#L317

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[tests/external/libcxx/array/at.pass.cpp, line 10 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-MdNGnN84On2CtdGCqdk:-MdRmLRR0ibZrlABu8fx:b-3xopkq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a4d958812268d5aaf578e4dba58cc453e3a768ad/tests/external/libcxx/array/at.pass.cpp#L10)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

If you want, you may copy copyright-format target (and update check-headers.sh) from pmemkv https://github.com/pmem/pmemkv/blob/89744f5e627be5eaaa062b0c520eb23315c7a847/CMakeLists.txt#L317
</blockquote></details>

the problem here is, I believe, that we don't check licenses at all in `tests/external` :wink:

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 983 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-MdNGDG23UonP9ouDIPA:-MdS8SCs9uoknlwIzCkH:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a4d958812268d5aaf578e4dba58cc453e3a768ad/tests/CMakeLists.txt#L983)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add a new sub-dir in the `mpsc_queue` called `pmreorder` to place all scripts there (we have this approach in pmemkv and it seems to shorten the name a little.
(`pmreorder` in the name is required, so only for scripts)
</blockquote></details>

Done.
___
*[tests/external/libcxx/array/at.pass.cpp, line 10 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-MdNGnN84On2CtdGCqdk:-MdS7hONDSV12bkL5sW_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a4d958812268d5aaf578e4dba58cc453e3a768ad/tests/external/libcxx/array/at.pass.cpp#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

the problem here is, I believe, that we don't check licenses at all in `tests/external` :wink:
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 33 of 33 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1110#-:-MdWPEbz-OoqDZ8KWBg7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
