### PR TITLE
radix_tree improvements

### PR DESCRIPTION
**Pull request by JanDorniak99**
#828
- optimize insert
- allow inline_string modifications (range/at methods in inline string)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 215 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIcv_HsAq2_X-q6_Gx8:-MIcv_HtBA-QbVe0F9kG:br6lq5s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/inline_string.hpp#L215)):*
> ```cpp
> template <typename CharT, typename Traits>
> typename basic_inline_string<CharT, Traits>::pointer
> basic_inline_string<CharT, Traits>::data() noexcept
> ```

that's not noexcept anymore
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 356 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIcw0DKAqCUK8oREHp4:-MIcw0DKAqCUK8oREHp5:b-16o6tf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/inline_string.hpp#L356)):*
> ```cpp
> typename basic_inline_string<CharT, Traits>::pointer
> basic_inline_string<CharT, Traits>::snapshotted_data(size_t p, size_t n)
> {
> ```

you could add some assert to make sure that p + n <= size()
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1369 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIczBab-IfuU2ezkvSN:-MIczBab-IfuU2ezkvSO:b-u092kl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/radix_tree.hpp#L1369)):*
> ```cpp
> template <typename Key, typename Value, typename BytesView>
> std::pair<typename radix_tree<Key, Value, BytesView>::iterator, bool>
> radix_tree<Key, Value, BytesView>::insert(const value_type &v)
> ```

Could you add for insert tests similar to the ones you made for try_emplace? (with Moveable and MoveableWrapper).

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 215 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIcv_HsAq2_X-q6_Gx8:-MIri_eFE3-MZgjogMIr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/inline_string.hpp#L215)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

that's not noexcept anymore
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 356 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIcw0DKAqCUK8oREHp4:-MIri_yk35jFfr1Z8rsh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/inline_string.hpp#L356)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you could add some assert to make sure that p + n <= size()
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1369 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIczBab-IfuU2ezkvSN:-MIriaqw7FrOPnfoYzD5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/radix_tree.hpp#L1369)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you add for insert tests similar to the ones you made for try_emplace? (with Moveable and MoveableWrapper).
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 308 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIrrcxy8iGis2fJML6I:-MIrrcxy8iGis2fJML6J:b-ar7mg2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/include/libpmemobj++/experimental/inline_string.hpp#L308)):*
> ```cpp
> /**
>  * Returns reference to a character at position @param[in] p with bounds
>  * checking
> ```

add '.' at the end of the sentence
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 352 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIrrY4q5gr5uUttDW3Y:-MIrrY4q5gr5uUttDW3Z:b-1qglgp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/include/libpmemobj++/experimental/inline_string.hpp#L352)):*
> ```cpp
>  * Return pointer to data at position p and if there is an active transaction
>  * snapshot elements from p to p + n.
>  */
> ```

params not described

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 308 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIrrcxy8iGis2fJML6I:-MIsHQzD3GKXRoTGfR4x:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/include/libpmemobj++/experimental/inline_string.hpp#L308)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add '.' at the end of the sentence
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 352 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIrrY4q5gr5uUttDW3Y:-MIsHRCJ60sv_Pzw-CzU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/include/libpmemobj++/experimental/inline_string.hpp#L352)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

params not described
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[tests/inline_string/inline_string.cpp, line 102 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt1pl_CnRT3RaWQqoA:-MIt1pl_CnRT3RaWQqoB:b-nz1446) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/tests/inline_string/inline_string.cpp#L102)):*
> ```cpp
> 	UT_ASSERT(nvobj::basic_string_view<T>(r->o2->s).data()[7] == '\0');
> 	UT_ASSERT(r->o1->s[4] == '\0');
> 	UT_ASSERT(r->o2->s[7] == '\0');
> ```

perhaps we can check for proper size here, instead
___
*[tests/inline_string/inline_string.cpp, line 189 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt1sSW5ck1Un4_A1wf:-MIt1sSW5ck1Un4_A1wg:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/tests/inline_string/inline_string.cpp#L189)):*
> ```cpp
> 	}
> 	UT_ASSERT(nvobj::basic_string_view<T>(r->o1->s).data()[0] == '\0');
> 	UT_ASSERT(r->o1->s[0] == '\0');
> ```

.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3102 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIczf1h-7R7NmhXhKPy:-MIczf1h-7R7NmhXhKPz:b-bx9d04) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/radix_tree.hpp#L3102)):*
> ```cpp
> {
> 	return make_internal(std::piecewise_construct,
> 			     std::forward_as_tuple(std::forward<K>(p.first)),
> ```

Could you also change this std::forward to std::move (similarly to the version with detail::pair). It won't affect the behavior but will be more readable I guess.
___
*[tests/external/libcxx/map/map.modifiers/insert_rv.pass.cpp, line 217 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt7IiE0AmanYMQmINa:-MIt7IiE0AmanYMQmINb:bndk7t4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6bf33d2fb0479809ad25a6e081aa9d3f0864e59d/tests/external/libcxx/map/map.modifiers/insert_rv.pass.cpp#L217)):*
> ```cpp
> 	UT_ASSERT(r.first->MAP_KEY.get().get() == 3);
> 	UT_ASSERT(r.first->MAP_VALUE.get().get() == 3);
> 	UT_ASSERT(v.first.moved() && v.second.moved());
> ```

Hm, why this is moved? We should call insert(key_type&&) and later try_empalce, right?

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3102 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIczf1h-7R7NmhXhKPy:-MJ1G0A81JnQEdZDNmYj:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4ba1976d7ccfa90f5463414f50cf5b7523a523d7/include/libpmemobj++/experimental/radix_tree.hpp#L3102)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you also change this std::forward to std::move (similarly to the version with detail::pair). It won't affect the behavior but will be more readable I guess.
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.modifiers/insert_rv.pass.cpp, line 217 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt7IiE0AmanYMQmINa:-MJ1G11p4bvoxxROzVCg:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6bf33d2fb0479809ad25a6e081aa9d3f0864e59d/tests/external/libcxx/map/map.modifiers/insert_rv.pass.cpp#L217)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, why this is moved? We should call insert(key_type&&) and later try_empalce, right?
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 102 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt1pl_CnRT3RaWQqoA:-MJ0mOlt2Ptjj4MYNg_R:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/tests/inline_string/inline_string.cpp#L102)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps we can check for proper size here, instead
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 189 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt1sSW5ck1Un4_A1wf:-MJ0mPGz0E1TcUrqu3Nd:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/tests/inline_string/inline_string.cpp#L189)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[tests/inline_string/inline_string.cpp, line 102 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-MIt1pl_CnRT3RaWQqoA:-MJ1GX9p2-M1jSdgK2fY:b-l2osh5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/52550c4f22761fa5b6db600615cd0d3bd9f23706/tests/inline_string/inline_string.cpp#L102)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually I meant to check for `r->o2->s` since for `o1->s` it's already checked few lines above ;)

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-:-MJ1MVhB6Tso_OAcOzO6:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/907#-:-MJ2lkP08Fmc_xw8-CDA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
