### PR TITLE
radix_tree: use std::atomic<tagged_pointer>

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: all files reviewed, 4 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 13 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSJec7BXcAJN-1Hj35:-MZSJec7BXcAJN-1Hj36:b-icojgl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L13)):*
> ```cpp
> #include <libpmemobj++/persistent_ptr.hpp>
> 
> // XXX use this from atomic_self_relative_ptr.hpp
> ```

Could you please move this code to some common file and use from here and self_relative_ptr?
___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 256 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSXQDr2K85DeeUISC0:-MZSXQDr2K85DeeUISC1:b-kn7fta) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L256)):*
> ```cpp
> 	store_with_snapshot(
> 		value_type desired,
> 		std::memory_order order = std::memory_order_seq_cst) noexcept
> ```

it's not noexcept unfortunately - transaction::snapshot can throw
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 298 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSXZ0E6HAmORFYcVfs:-MZSXZ0E6HAmORFYcVft:b-wb6es1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/experimental/radix_tree.hpp#L298)):*
> ```cpp
> 	struct node;
> 
> 	using pointer_type = std::atomic<detail::tagged_ptr<leaf, node>>;
> ```

I think the other way around would be more readable:
`atomic_pointer_type` and `pointer_type`
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 933 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSYDZ8CSK_rSZpOr_d:-MZSYDZ8CSK_rSZpOr_e:bqmdvap) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/experimental/radix_tree.hpp#L933)):*
> ```cpp
> 
> 	while (!is_leaf(n)) {
> 		if (n->embedded_entry.load() && n->byte >= min_depth)
> ```

All the loads should be called with `std::memory_order_acquire` and stores with `std::memory_order_release`.  Maybe it would make sense to implement some wrapper for load/store to avoid so much boilerplate? Something like load_acquire(...), store_release()

More info about those orders: https://en.cppreference.com/w/cpp/atomic/memory_order

Btw, in some places std::memory_order_relaxed would be enough but I'm not sure if it's worth complication the code and using different memor orders

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: all files reviewed, 7 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSjq4e3IouJxizgfVn:-MZSjq4e3IouJxizgfVo:bps8b30) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L49)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> namespace std
> {
> template <typename P1, typename P2>
> struct atomic<pmem::detail::tagged_ptr_impl<
> 	P1, P2, pmem::obj::experimental::self_relative_ptr<void>>>;
> }
> ```
</details>

Why not move it to below namespace pmem::detail, now we have splitted file four times: pmem::detail and again std
___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 218 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSyAWx1GgzGHUlu43S:-MZSyAWx1GgzGHUlu43T:bqh6wfr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L218)):*
> ```
> namespace std
> {
> ```
@igchor should we expose it in `std` namespace or in `pmem`?
___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 223 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSxto12AMqtftRU1-v:-MZSxto12AMqtftRU1-w:b-1qhgjn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L223)):*
> ```
> struct atomic<pmem::detail::tagged_ptr_impl<
> 	P1, P2, pmem::obj::experimental::self_relative_ptr<void>>> {
> ```
Is short version work either?:
`struct atomic<detail::pmem::tagged_ptr>`
Why not use what we defined earlier.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 936 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZTFNLO8Y7AxTMK9Dx6:-MZTFNLP6L5bXT1oer5j:b6tuvr2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/experimental/radix_tree.hpp#L936)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 		for (size_t i = 0; i < SLNODES; i++) {
> 			non_atomic_pointer_type m;
> 			if ((m = n->child[i].load())) {
> 				n = m;
> 				break;
> 			}
> 		}
> ```
</details>

`n, m, i` made this code unreadable

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: all files reviewed, 7 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 936 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZTFNLO8Y7AxTMK9Dx6:-MZWlmYR7_R4i4KR_aXu:b-tkwpv2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/experimental/radix_tree.hpp#L936)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 		for (size_t i = 0; i < SLNODES; i++) {
> 			non_atomic_pointer_type m;
> 			if ((m = n->child[i].load())) {
> 				n = m;
> 				break;
> 			}
> 		}
> ```
`n, m, i` made this code unreadable
</blockquote></details>

Probably we could just change this to:

```
if (n->child[i].load())
    return get_leaf(n->child[i].load())
```

As for `n` and `i` imo it's fine `n` is used throughout the entire implementation as pointer to node and `i` is just a standard choice for loops.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @igchor, @JanDorniak99, and @KFilipek)

___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 13 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSJec7BXcAJN-1Hj35:-M_-cmklEfI1nMa2HlCh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L13)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you please move this code to some common file and use from here and self_relative_ptr?
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 49 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSjq4e3IouJxizgfVn:-MZwkKe36XXvygZoFNFf:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L49)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> namespace std
> {
> template <typename P1, typename P2>
> struct atomic<pmem::detail::tagged_ptr_impl<
> 	P1, P2, pmem::obj::experimental::self_relative_ptr<void>>>;
> }
> ```
Why not move it to below namespace pmem::detail, now we have splitted file four times: pmem::detail and again std
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 223 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSxto12AMqtftRU1-v:-M_-ctl3CpCwXM8AJhKZ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L223)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> struct atomic<pmem::detail::tagged_ptr_impl<
> 	P1, P2, pmem::obj::experimental::self_relative_ptr<void>>> {
> ```
Is short version work either?:
`struct atomic<detail::pmem::tagged_ptr>`
Why not use what we defined earlier.
</blockquote></details>

Done.
___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 256 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSXQDr2K85DeeUISC0:-MZwkUpp7oFZ_IxIT1Bh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L256)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

it's not noexcept unfortunately - transaction::snapshot can throw
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 298 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSXZ0E6HAmORFYcVfs:-MZwnnc6C9ugXuLlz30_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/experimental/radix_tree.hpp#L298)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think the other way around would be more readable:
`atomic_pointer_type` and `pointer_type`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 933 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSYDZ8CSK_rSZpOr_d:-M_-ltCO-PPOoYhdUViB:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/experimental/radix_tree.hpp#L933)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

All the loads should be called with `std::memory_order_acquire` and stores with `std::memory_order_release`.  Maybe it would make sense to implement some wrapper for load/store to avoid so much boilerplate? Something like load_acquire(...), store_release()

More info about those orders: https://en.cppreference.com/w/cpp/atomic/memory_order

Btw, in some places std::memory_order_relaxed would be enough but I'm not sure if it's worth complication the code and using different memor orders
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @JanDorniak99)

**Review by igchor — COMMENTED** [review]
> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[include/libpmemobj++/detail/tagged_ptr.hpp, line 218 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-MZSyAWx1GgzGHUlu43S:-M_0PLXY-TXSPMdL1cbS:b33q1id) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ac8dca444d2d03e2c9e8abcf0cc1be903af2c2ae/include/libpmemobj++/detail/tagged_ptr.hpp#L218)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> namespace std
> {
> ```
@igchor should we expose it in `std` namespace or in `pmem`?
</blockquote></details>

In std, this is a common way of providing atomic stores/loads for custom data types. Btw, @jandorniak99  please look at this and see if we fulfill all requirements for specialization: https://en.cppreference.com/w/cpp/language/extending_std I mean those: "Specializations of std::atomic must have a deleted copy constructor, a deleted copy assignment operator, and a constexpr value constructor."
___
*[tests/radix_tree/radix_concurrent.cpp, line 18 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-M_0ZjYiA5qEhfcjbHJt:-M_0ZjYj2ygFo9nrjhA2:b-vvlboj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a9b5a0d54763ec4916c6243508bf48fd2bd385f2/tests/radix_tree/radix_concurrent.cpp#L18)):*
> ```cpp
> 		    size_t n_readers)
> {
> 	std::vector<std::thread> threads;
> ```

nit: you could probably just use parallel_exec here (`if (id == 0) WriteF(); else readers[id]();`) or even use parallel_exec directly in tests

**Comment by karczex** [comment]
___
*[include/libpmemobj++/experimental/self_relative_ptr.hpp, line 31 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-M_QQtk52_xTs5G3uX1t:-M_QQtk52_xTs5G3uX1u:bt4ncv9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b7d21a7f24b0e28b134e1536f345e4da8dc558c0/include/libpmemobj++/experimental/self_relative_ptr.hpp#L31)):*
> ```
> 	using base_type = self_relative_ptr_base;
> 	using this_type = self_relative_ptr;
> ```
What's the point of those two usings? Is it some part of API, which documentation I cannot find?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @KFilipek)

___
*[include/libpmemobj++/experimental/self_relative_ptr.hpp, line 31 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-M_QQtk52_xTs5G3uX1t:-M_QmJiE9b7xR3Q4LyRm:b6ivvxr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b7d21a7f24b0e28b134e1536f345e4da8dc558c0/include/libpmemobj++/experimental/self_relative_ptr.hpp#L31)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change, did you push changes?

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1069#-:-M_UU7rA9Y4QBZ8zeUyk:bnfp4nl)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

**Pull request merged**
