### PR TITLE
CI: use Fedora 34 instead of 32, since 32 is EOL now

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
as long as it's working it can run in the nightly build.

- [x] bump valgrind version (after rebase to 3.17) (wait for #1196)
- [x] fix issue with test `ringbuf_0_helgrind`
- [x] we need yet: #1204

// Extended log on my fork, with more builds: https://github.com/lukaszstolarczuk/libpmemobj-cpp/actions/runs/1135366660

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1173)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1173)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1173#-MgA6kXR0e000ON03V9P:-MgA6kXR0e000ON03V9Q:bcj309x) (no related file):*
perhaps we should push this to stable-1.9 - this is the first CI using GHA and it runs on F32, which may fail in some near(?) future (since it's EOL)...?

---

**Comment by lukaszstolarczuk** [comment]
@karczex can you please take a look at the failing `ringbuf_0_helgrind`?

**Comment by lukaszstolarczuk** [comment]
required changes were merged into stable-1.13, so this should be good to go now 😃

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1173#-:-MkBtW-j0X4x1k1hXAkX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1173#-:-MkGuRfz6E2DoDUNQtXW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
