### PR TITLE
Fix mpsc queue const

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[utils/docker/run-build.sh, line 214 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-Mdw1oO15kTNz1bKpmeS:-Mdw1oO15kTNz1bKpmeT:b3ywhnq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/911d7316ac6bd38df4cf58aac62df4ccb63db5c4/utils/docker/run-build.sh#L214)):*
> ```Shell
> ###############################################################################
> function build_clang_release_cpp20() {
> 	mkdir build
> ```

pls add `printf` here and at the end of the func.
___
*[utils/docker/run-build.sh, line 216 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-Mdw1dkaE9WscgNsOKw6:-Mdw1dkaE9WscgNsOKw7:b-qinw1m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/911d7316ac6bd38df4cf58aac62df4ccb63db5c4/utils/docker/run-build.sh#L216)):*
> ```Shell
> 	mkdir build
> 	cd build
> ```

should we add such check:

https://github.com/pmem/pmemkv/blob/master/utils/docker/run-build.sh#L167

?
___
*[utils/docker/run-build.sh, line 239 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-Mdw1u921mrZ1Gb3brLe:-Mdw1u921mrZ1Gb3brLf:bgs4rs5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/911d7316ac6bd38df4cf58aac62df4ccb63db5c4/utils/docker/run-build.sh#L239)):*
> ```Shell
> 
> 	make -j$(nproc)
> }
> ```

\+ `workspace_cleanup` at the end

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 214 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-Mdw1oO15kTNz1bKpmeS:-MdwHhg46KwgA1yMbY0_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/911d7316ac6bd38df4cf58aac62df4ccb63db5c4/utils/docker/run-build.sh#L214)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add `printf` here and at the end of the func.
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 216 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-Mdw1dkaE9WscgNsOKw6:-MdwHnTAAfZKgaOA8Ee6:b-g7bsct) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/911d7316ac6bd38df4cf58aac62df4ccb63db5c4/utils/docker/run-build.sh#L216)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

should we add such check:

https://github.com/pmem/pmemkv/blob/master/utils/docker/run-build.sh#L167

?
</blockquote></details>

Right, probably we should
___
*[utils/docker/run-build.sh, line 239 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-Mdw1u921mrZ1Gb3brLe:-MdwHtl80aVQnI1unU70:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/911d7316ac6bd38df4cf58aac62df4ccb63db5c4/utils/docker/run-build.sh#L239)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ `workspace_cleanup` at the end
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-:-MdwOdHO5pzutzM45fkh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1133#-:-MdzZgHp1yc_F08qOraX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
