### PR TITLE
Build examples

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Reviewed 29 of 41 files at r1.
Review status: 33 of 42 files reviewed at latest revision, all discussions resolved.

---

*[CMakeLists.txt, line 355 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPJCjIEP_hfHIa1M5R:-LEPJCjIEP_hfHIa1M5S:b-6v3q12) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/CMakeLists.txt#L355)):*
> ```CMake
> endif()
> 
> if(BUILD_EXAMPLES AND NO_GCC_VARIADIC_TEMPLATE_BUG)
> ```

Why do you use NO_GCC_VARIADIC_TEMPLATE_BUG? (missing comment)
Are all examples depending on this? Is it possible to add example which won't depend on it? If yes, then this check should be on the example level.

---

*[examples/CMakeLists.txt, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPiB2WEsP6PchURo80:-LEPiB2Y4SOR1ngDu4LI:b-m27nif) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/CMakeLists.txt#L48)):*
> ```CMake
> 	pkg_check_modules(CURSES QUIET ncurses)
> else()
> 	set(CURSES_NEED_NCURSES TRUE)
> ```

is this needed?

---

*[examples/CMakeLists.txt, line 76 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPiHxv6LzIv-95AiaS:-LEPiHxv6LzIv-95AiaT:bajzub0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/CMakeLists.txt#L76)):*
> ```CMake
> 	target_link_libraries(example-pmpong ${PMEMOBJ_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT} ${SFML_LIBRARIES})
> 
> 	execute_process(COMMAND uname -s OUTPUT_VARIABLE SYSTEM_TYPE)
> ```

At some point this will need to be fixed. There's no uname command on Windows.

---

*[examples/common.hpp, line 34 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPHDUx5IAxjEjJSLCd:-LEPHDUx5IAxjEjJSLCe:b9z6vzb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/common.hpp#L34)):*
> ```cpp
> 
> #ifndef COMMON_HPP
> #define COMMON_HPP
> ```

COMMON_HPP is pretty generic name. OBJCPP_EXAMPLES_COMMON_HPP?

---

*[examples/map_cli/ctree_map_persistent.hpp, line 35 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPHbz48nNI0EXQdJQP:-LEPHbz48nNI0EXQdJQQ:b23patb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/map_cli/ctree_map_persistent.hpp#L35)):*
> ```cpp
> #ifndef EXAMPLES_CTREE_MAP_PERSISTENT_HPP
> #define EXAMPLES_CTREE_MAP_PERSISTENT_HPP
> #include <common.hpp>
> ```

again, pretty generic name...

---

*[tests/CMakeLists.txt, line 130 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPx2MECzBG3_Ttibd6:-LEPx2MECzBG3_Ttibd7:baqkyyo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/tests/CMakeLists.txt#L130)):*
> ```CMake
> endif()
> 
> if(NO_GCC_VARIADIC_TEMPLATE_BUG)
> ```

 && BUILD_EXAMPLES?

---

*[tests/CMakeLists.txt, line 134 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPwrjd6g6hVhym1ui_:-LEPwrjd6g6hVhym1uia:bsioia4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/tests/CMakeLists.txt#L134)):*
> ```CMake
> 		pkg_check_modules(CURSES QUIET ncurses)
> 	else()
> 		set(CURSES_NEED_NCURSES TRUE)
> ```

What is it for?

---

*[utils/docker/images/Dockerfile.ubuntu-16.04, line 51 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPJ6h690z9-_krfTlf:-LEPJ6h690z9-_krfTlg:brzq4kj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/utils/docker/images/Dockerfile.ubuntu-16.04#L51)):*
> ```
> 	devscripts \
> 	doxygen \
> 	libncurses5-dev \
> ```

what about sfml?

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5)*

**Comment by igchor** [comment]
Review status: 33 of 55 files reviewed at latest revision, 8 unresolved discussions.

---

*[CMakeLists.txt, line 355 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPJCjIEP_hfHIa1M5R:-LEQbNqpBe0xPUVi0cXH:b79r0tj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/CMakeLists.txt#L355)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Why do you use NO_GCC_VARIADIC_TEMPLATE_BUG? (missing comment)
Are all examples depending on this? Is it possible to add example which won't depend on it? If yes, then this check should be on the example level.
</blockquote></details>

There were no comment about this in pmdk
(https://github.com/pmem/pmdk/blob/master/src/examples/Makefile#L42)
so I'm not sure if all examples cannot be build in such case. 

---

*[examples/CMakeLists.txt, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPiB2WEsP6PchURo80:-LEQbxMZ0vRmjABW-GfB:beszw46) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/CMakeLists.txt#L48)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

This was probably only tested with ncurses so I think it's safer that way.

---

*[examples/CMakeLists.txt, line 76 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPiHxv6LzIv-95AiaS:-LETBEEdCdecoDikmLxN:bnthj5s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/CMakeLists.txt#L76)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

At some point this will need to be fixed. There's no uname command on Windows.
</blockquote></details>

Actually, we only need to run this on linux, pmpong hash hardocded path to fonts on windows.

---

*[examples/map_cli/ctree_map_persistent.hpp, line 35 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPHbz48nNI0EXQdJQP:-LETGqnQ4aoXUaWgnkKp:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/map_cli/ctree_map_persistent.hpp#L35)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

again, pretty generic name...
</blockquote></details>

Done.

---

*[tests/CMakeLists.txt, line 130 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPx2MECzBG3_Ttibd6:-LEQe1Yy53If-mXFfiZ9:bxlodmz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/tests/CMakeLists.txt#L130)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

 && BUILD_EXAMPLES?
</blockquote></details>

It's not needed, this test will compile the example on it's own (but without style checkers). 

---

*[tests/CMakeLists.txt, line 134 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPwrjd6g6hVhym1ui_:-LEQePrD0BiOxp-l0q3M:b-lo3cl0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/tests/CMakeLists.txt#L134)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

What is it for?
</blockquote></details>

To specify that we specifically want ncurses and not just any curses library (in case there are many installed).  I'm not sure if this is really needed but README specifies (lib)ncurses as dependency.

---

*[utils/docker/images/Dockerfile.ubuntu-16.04, line 51 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPJ6h690z9-_krfTlf:-LEQgFIS4PBRJlXChrj1:b-6yht9b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/utils/docker/images/Dockerfile.ubuntu-16.04#L51)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

what about sfml?
</blockquote></details>

It looks like there is only SFML 2.3 package for ubuntu 16.04 and this example only compiles with >= 2.4

---

*[examples/common.hpp, line 34 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPHDUx5IAxjEjJSLCd:-LETGpPxAHHUGE9VI7RI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/common.hpp#L34)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

COMMON_HPP is pretty generic name. OBJCPP_EXAMPLES_COMMON_HPP?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5)*

**Comment by RobDickinson** [comment]
Just FYI it looks like these examples are still present in the main PMDK repo:  https://github.com/pmem/pmdk/tree/master/src/examples/libpmemobj%2B%2B

**Comment by marcinslusarz** [comment]
Review status: 33 of 55 files reviewed, 3 unresolved discussions (waiting on @marcinslusarz)

---

*[examples/CMakeLists.txt, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPiB2WEsP6PchURo80:-LEnYNWW-S56veirI-sz:bn5jcqs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/CMakeLists.txt#L48)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This was probably only tested with ncurses so I think it's safer that way.
</blockquote></details>

Please add a comment explaining why it's needed. I don't see it used in this file, so I assume it's used by FindCurses.cmake for something...

---

*[tests/CMakeLists.txt, line 134 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPwrjd6g6hVhym1ui_:-LEnZYYY2xSLw_AD_uaC:bagk57k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/tests/CMakeLists.txt#L134)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

To specify that we specifically want ncurses and not just any curses library (in case there are many installed).  I'm not sure if this is really needed but README specifies (lib)ncurses as dependency.
</blockquote></details>

Something like that should be put in the comment above.

---

*[utils/docker/images/Dockerfile.ubuntu-16.04, line 51 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPJ6h690z9-_krfTlf:-LEn_HmjEJZ25lID6L7p:b-mv17kt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/utils/docker/images/Dockerfile.ubuntu-16.04#L51)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It looks like there is only SFML 2.3 package for ubuntu 16.04 and this example only compiles with >= 2.4
</blockquote></details>

Please add commented out line with that information. It will be useful once we'll switch to the newer Ubuntu.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5)*

**Comment by igchor** [comment]
Review status: 33 of 55 files reviewed, 3 unresolved discussions (waiting on @marcinslusarz)

---

*[examples/CMakeLists.txt, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPiB2WEsP6PchURo80:-LF1Cg7D44b7unBMTq21:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/examples/CMakeLists.txt#L48)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please add a comment explaining why it's needed. I don't see it used in this file, so I assume it's used by FindCurses.cmake for something...
</blockquote></details>

Done.

---

*[tests/CMakeLists.txt, line 134 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPwrjd6g6hVhym1ui_:-LF1Ch2X75W8GIU2g4Wl:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/tests/CMakeLists.txt#L134)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Something like that should be put in the comment above.
</blockquote></details>

Done.

---

*[utils/docker/images/Dockerfile.ubuntu-16.04, line 51 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-LEPJ6h690z9-_krfTlf:-LF1DiIn4XUy68jsvIr1:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/475f680a4086dbdc95d7ba6ad20f0c18b69b8b24/utils/docker/images/Dockerfile.ubuntu-16.04#L51)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please add commented out line with that information. It will be useful once we'll switch to the newer Ubuntu.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 42 files at r1, 21 of 21 files at r2.
Review status: 54 of 55 files reviewed, all discussions resolved (waiting on @marcinslusarz)

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5#-:-LF2Vc6P8aZ-AzQZdhKP:bnfp4nl)*

**Comment by marcinslusarz** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/5)*

**Pull request merged**
