### PR TITLE
Increase ringbuf

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/mpsc_queue/ringbuf.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdIXg-77oGhItl1nKhO:-MdIXg-77oGhItl1nKhP:b-42t907) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/tests/mpsc_queue/ringbuf.cpp#L54)):*
> ```cpp
> 	size_t len, woff;
> 	ptrdiff_t off;
> 	std::cout << "test_wraparound " << n << std::endl;
> ```

if we want to keep that, pls write it e.g. like: `"test_wraparound for n=" << n`

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[include/libpmemobj++/detail/ringbuf.hpp, line 71 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdLlviLByEdQZ5q-Iit:-MdLlviLByEdQZ5q-Iiu:bn9du65) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/include/libpmemobj++/detail/ringbuf.hpp#L71)):*
> ```cpp
> typedef uint64_t ringbuf_off_t;
> 
> static constexpr ringbuf_off_t RBUF_OFF_MASK = UINT64_MAX >> 8;
> ```

Shouldn't you match RBUF_OFF_MASK with WRAP_COUNTER?
___
*[tests/mpsc_queue/ringbuf.cpp, line 333 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdLmNte6Ja0JB6Xgoxx:-MdLmNte6Ja0JB6Xgoxy:bpfqeey) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/tests/mpsc_queue/ringbuf.cpp#L333)):*
> ```cpp
> 	test_overlap(24_Peta);
> 
> 	test_wraparound(100_Giga);
> ```

Did those tests pass withouth the ringbuf change?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex)

___
*[include/libpmemobj++/detail/ringbuf.hpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdWlhqe8sJV_1xIcNTP:-MdWlhqe8sJV_1xIcNTQ:boco5gc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/include/libpmemobj++/detail/ringbuf.hpp#L72)):*
> ```cpp
> 
> static constexpr ringbuf_off_t RBUF_OFF_MASK = UINT64_MAX >> 8;
> static constexpr ringbuf_off_t WRAP_LOCK_BIT = 0x1ULL << 63;
> ```

these magic numbers could be actually calculated, I guess
___
*[tests/common/size_literals.hpp, line 4 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdWlUH3AdPyKaYE6Ik6:-MdWlUH3AdPyKaYE6Ik7:b-q9yxv8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/tests/common/size_literals.hpp#L4)):*
> ```cpp
> /* Copyright 2021, Intel Corporation */
> 
> #ifndef SIZE_LITERALS_HPP
> ```

maybe add `LIBPMEMOBJ_CPP_` prefix to this name

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[tests/common/size_literals.hpp, line 4 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdWlUH3AdPyKaYE6Ik6:-MdXIiQC3cG_LAgU9iBx:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/tests/common/size_literals.hpp#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe add `LIBPMEMOBJ_CPP_` prefix to this name
</blockquote></details>

Done.
___
*[tests/mpsc_queue/ringbuf.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdIXg-77oGhItl1nKhO:-MdXIeFqBRWPmVy7tV4S:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/tests/mpsc_queue/ringbuf.cpp#L54)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if we want to keep that, pls write it e.g. like: `"test_wraparound for n=" << n`
</blockquote></details>

Done.
___
*[tests/mpsc_queue/ringbuf.cpp, line 333 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1105#-MdLmNte6Ja0JB6Xgoxx:-MdM48u86R1ZR0qmiYXG:b32wsm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bf8a40ec7cc489369cd97bb58c7f2a325f5ade61/tests/mpsc_queue/ringbuf.cpp#L333)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Did those tests pass withouth the ringbuf change?
</blockquote></details>

no

**Comment by igchor** [comment]
For now, we'll go with: https://github.com/pmem/libpmemobj-cpp/pull/1121

**Pull request closed without merging**
