### PR TITLE
mpsc_queue: do not call ringbuf_consume/release with number of byte

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121#-:-Mdp_bSR9EVCXzk1NXyK:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/detail/ringbuf.hpp, line 121 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121#-MdquqjP3WYAJTGAw0Ur:-MdquqjP3WYAJTGAw0Us:b166135) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c722f0959c494dabd9df458deae115297466bbf4/include/libpmemobj++/detail/ringbuf.hpp#L121)):*
> ```cpp
> 	{
> 		if (length >= RBUF_OFF_MASK)
> 			throw std::out_of_range("ringbuf length too big");
> ```

we could add test for that

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121#-:-MdqzBFy2csiEkRX1BFr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/detail/ringbuf.hpp, line 121 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121#-MdquqjP3WYAJTGAw0Ur:-Mdr4fCjEy_W6ZmhiT3m:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c722f0959c494dabd9df458deae115297466bbf4/include/libpmemobj++/detail/ringbuf.hpp#L121)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we could add test for that
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
