### PR TITLE
inline_string: add missing specialization for total_sizeof

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 553 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-Mf8BiTL2J6YuRnXY70X:-Mf8BiTL2J6YuRnXY70Y:b5fis9o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7429648a2f4e6b30f7368900fcff20b79ed2cbee/include/libpmemobj++/experimental/inline_string.hpp#L553)):*
> ```cpp
>  * type.
>  *
>  * Inline_string requires capacity of sizeof(basic_inline_string<CharT>) + size
> ```

missing `dram_`
___
*[tests/inline_string/inline_string.cpp, line 294 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-Mf8Cz-85JUaKybdoYtR:-Mf8Cz-9065BTv1VQMp0:b-xb1rzg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7429648a2f4e6b30f7368900fcff20b79ed2cbee/tests/inline_string/inline_string.cpp#L294)):*
> ```cpp
> template <typename T>
> void
> test_pmem()
> ```

pls add a short description for this test (here and below, for the new test)
___
*[tests/inline_string/inline_string.cpp, line 316 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-Mf8Cu3U9cgjqgUFSI1H:-Mf8Cu3U9cgjqgUFSI1I:b4rgftp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7429648a2f4e6b30f7368900fcff20b79ed2cbee/tests/inline_string/inline_string.cpp#L316)):*
> ```cpp
> test_traits()
> {
> 	constexpr size_t string_size = 20;
> ```

you can test e.g. 2 various values

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 553 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-Mf8BiTL2J6YuRnXY70X:-Mf8EX6t1SEPrO-1OjtQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7429648a2f4e6b30f7368900fcff20b79ed2cbee/include/libpmemobj++/experimental/inline_string.hpp#L553)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing `dram_`
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 294 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-Mf8Cz-85JUaKybdoYtR:-Mf8EhrL6XmDgCh2JYc4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7429648a2f4e6b30f7368900fcff20b79ed2cbee/tests/inline_string/inline_string.cpp#L294)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a short description for this test (here and below, for the new test)
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 316 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-Mf8Cu3U9cgjqgUFSI1H:-Mf8EuOS2I-PE8KVn48p:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7429648a2f4e6b30f7368900fcff20b79ed2cbee/tests/inline_string/inline_string.cpp#L316)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can test e.g. 2 various values
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-:-Mf8HAWFBo0q2vsKnxWe:bnfp4nl)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1170#-:-Mf8HSq55IeEoQfohPoe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
