### PR TITLE
typo fixes

### PR DESCRIPTION
**Pull request by kilobyte**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233)* status: all files reviewed, 3 unresolved discussions (waiting on @kilobyte)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAMm9NDzbL0nJ_EfiI:-MuAMm9O6tgzzxKM3oTj:b2mq7ug) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/examples/radix_tree/radix_tree_complex_value.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021-2022, Intel Corporation */
> ```

why you updated only few dates? either all of them, or none :wink: 
___
*[include/libpmemobj++/experimental/atomic_persistent_aware_ptr.hpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAN3CW10Luhb9tJD8_:-MuAN3CW10Luhb9tJD8a:b-rf36dq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/atomic_persistent_aware_ptr.hpp#L40)):*
> ```cpp
>  *  - Write-optimized - data is lazily flushed with a read operation. In this
>  *		approach data storing is expected to be faster, but data is
>  * guaranteed to be flushed only after consequent read.
> ```

pls, perhaps, align this line with "approach" (so put 2 tabs before, pls)
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuANHPp0MazpohSYw5n:-MuANHPp0MazpohSYw5o:b-emfhkc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/concurrent_map.hpp#L48)):*
> ```cpp
>  * after process restart.
>  *
>  * Key, Value, Comp and Allocoator types should be persistent memory aware
> ```

still something's wrong - `Allocoator`? -> `Allocator`

**Review by KFilipek — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233)* status: all files reviewed, 3 unresolved discussions (waiting on @kilobyte)

**Review by KFilipek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233)* status: all files reviewed, 4 unresolved discussions (waiting on @kilobyte)

___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 49 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAiQLy1bCnTotacdmg:-MuAiQLzBkAA3yC7tVME:b-mu29ln) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/concurrent_map.hpp#L49)):*
> ```cpp
>  *
>  * Key, Value, Comp and Allocoator types should be persistent memory aware
>  * types. Allocator type should satisfies the named requirements
> ```

@lukaszstolarczuk Is it okey for you?



_Code quote:_
```cpp
should satisfies
```

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAMm9NDzbL0nJ_EfiI:-MuB3ys62atV_xrJ8MjG:b-xssm49) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/examples/radix_tree/radix_tree_complex_value.cpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why you updated only few dates? either all of them, or none :wink: 
</blockquote></details>

As the CI doesn't scream at me, I pick "none" :)
___
*[include/libpmemobj++/experimental/atomic_persistent_aware_ptr.hpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAN3CW10Luhb9tJD8_:-MuB4RvfAKZsAYOvEQVt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/atomic_persistent_aware_ptr.hpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls, perhaps, align this line with "approach" (so put 2 tabs before, pls)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 48 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuANHPp0MazpohSYw5n:-MuB4aoT8MnF8rKfkNxt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/concurrent_map.hpp#L48)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

still something's wrong - `Allocoator`? -> `Allocator`
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 49 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAiQLy1bCnTotacdmg:-MuB4rob53Un7L2IJIYm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/concurrent_map.hpp#L49)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@lukaszstolarczuk Is it okey for you?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-:-MuBOLptEU2vkhz2L7jj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[examples/radix_tree/radix_tree_complex_value.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAMm9NDzbL0nJ_EfiI:-MuBNotFCdnYJx5Lg57s:bcjmq8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/examples/radix_tree/radix_tree_complex_value.cpp#L2)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

As the CI doesn't scream at me, I pick "none" :)
</blockquote></details>

we didn't meet yesterday :smile: 
:+1: 
___
*[include/libpmemobj++/experimental/atomic_persistent_aware_ptr.hpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAN3CW10Luhb9tJD8_:-MuBO8vfByaQOjmbRapZ:bb74ptu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/atomic_persistent_aware_ptr.hpp#L40)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thx!
___
*[include/libpmemobj++/experimental/concurrent_map.hpp, line 49 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-MuAiQLy1bCnTotacdmg:-MuBOFXm1xC3b8gi7nYS:b-gf0noh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4b4bb48c67f1c1ad1466951e54bef1f1241beb3a/include/libpmemobj%2B%2B/experimental/concurrent_map.hpp#L49)):*
<details><summary><i>Previously, kilobyte (Adam Borowski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks just great :smile:

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1233#-:-MuKw9etCEugGyYzBykJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kilobyte)

**Pull request merged**
