### PR TITLE
tests: add compatibility test for 1.12

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
Maybe we could have this autogenerated? ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040#-:-MTfdoFfCMz3qfTs7RcG:b-hxioy7)* status: 0 of 2 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/compatibility/version/version_1.12.cpp, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040#-MTfomG5-IfDcAuAp6op:-MTfomG6Ex3edS9ym7G_:b-pc2yjf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb11a1a0f0911f778de568682582fc097b50406c/tests/compatibility/version/version_1.12.cpp#L9)):*
> ```
> 	static_assert(LIBPMEMOBJ_CPP_VERSION_MAJOR == 1, "");
> 	static_assert(LIBPMEMOBJ_CPP_VERSION_MINOR == 12, "");
> ```
With C++17 message it's not necessary, otherwise I'd prefer to have a proper message:
"Wrong major version"
"Wrong minor version"

**Comment by KFilipek** [comment]
> Maybe we could have this autogenerated? ;)

@igchor You mean release scripts? 😃

**Review by lukaszstolarczuk — COMMENTED** [review]
@igchor , I promise, when I have a spare time, I'll do that ;) we can merge the release script we have (on PR) and then work on extending it.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040#-:-MTjPQxc1yLyOYE-5B81:b-nxh52p)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[tests/compatibility/version/version_1.12.cpp, line 9 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040#-MTfomG5-IfDcAuAp6op:-MTjPOwn6q8ytiy91Rni:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eb11a1a0f0911f778de568682582fc097b50406c/tests/compatibility/version/version_1.12.cpp#L9)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 	static_assert(LIBPMEMOBJ_CPP_VERSION_MAJOR == 1, "");
> 	static_assert(LIBPMEMOBJ_CPP_VERSION_MINOR == 12, "");
> ```
With C++17 message it's not necessary, otherwise I'd prefer to have a proper message:
"Wrong major version"
"Wrong minor version"
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1040#-:-MTqAaon066two9oOsyS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]

**Pull request merged**
