### PR TITLE
Add packaging support and write basic README

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Review status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @igchor)

---

*[.travis.yml, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnbEnB52GlpPGyz6Td:-LEnbEnDAkNOm9oafqHu:bf3dsv4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/.travis.yml#L19)):*
> ```YAML
>     - TYPE=coverity OS=ubuntu OS_VER=16.04
>     - TYPE=package OS=ubuntu OS_VER=16.04
>     - TYPE=package OS=fedora OS_VER=25
> ```

do we need this as separate jobs?

---

*[libpmemobj-cpp.pc.in, line 6 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnaZji1QGEA27nUox4:-LEnaZji1QGEA27nUox5:b-6oes6k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L6)):*
> ```
> includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
> 
> Name: libpmobj-cpp
> ```

Please use the same name we used in PMDK.

---

*[libpmemobj-cpp.pc.in, line 7 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEna_VDCmVdn0AEev73:-LEna_VDCmVdn0AEev74:b-hvwfvy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L7)):*
> ```
> 
> Name: libpmobj-cpp
> Description: libpmobj-cpp - c++ bindings for libpmemobj library
> ```

libp**me**mobj

---

*[libpmemobj-cpp.pc.in, line 10 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnakaa5bl0MtSMuLyJ:-LEnakaa5bl0MtSMuLyK:bb76mu4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L10)):*
> ```
> Version: @VERSION@
> URL: http://github.com/pmem/libpmemobj-cpp
> Requires.private: libpmemobj
> ```

Why?

---

*[README.md, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnaoL75iEiKJAscje_:-LEnaoL75iEiKJAscjea:bu72icg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/README.md#L2)):*
> ```Markdown
> # libpmemobj-cpp
> C++ bindings to libpmemobj (https://github.com/pmem/pmdk)
> ```

"to"? "for" sounded more natural

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by igchor** [comment]
Review status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @igchor and @marcinslusarz)

---

*[libpmemobj-cpp.pc.in, line 6 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnaZji1QGEA27nUox4:-LEoi7xvC8dxHlavizaH:bwql94y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L6)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please use the same name we used in PMDK.
</blockquote></details>

Only here, or should I also change package names?

---

*[libpmemobj-cpp.pc.in, line 7 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEna_VDCmVdn0AEev73:-LF1FEso4vxojLesKtvM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L7)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

libp**me**mobj
</blockquote></details>

Done.

---

*[libpmemobj-cpp.pc.in, line 10 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnakaa5bl0MtSMuLyJ:-LF1I5w26goEpgYpT309:ba3dfob) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L10)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Removed

---

*[README.md, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnaoL75iEiKJAscje_:-LF1I9HU-QJn6jW8faRo:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/README.md#L2)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

"to"? "for" sounded more natural
</blockquote></details>

Done.

---

*[.travis.yml, line 19 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnbEnB52GlpPGyz6Td:-LF1Iz2oDdy-r1FA-r8P:b1lu0tj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/.travis.yml#L19)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

do we need this as separate jobs?
</blockquote></details>

Right, we can do that in 'normal' build

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
Reviewed 3 of 9 files at r1, 4 of 8 files at r2.
Review status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @marcinslusarz and @igchor)

---

*[CMakeLists.txt, line 271 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2XcJe7FqA63bfsObj:-LF2XcJe7FqA63bfsObk:boq2olg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L271)):*
> ```CMake
> 	FILES_MATCHING PATTERN "*.hpp")
> 
> configure_file(${CMAKE_CURRENT_SOURCE_DIR}/libpmemobj-cpp.pc.in
> ```

libpmemobj++.pc.in

---

*[libpmemobj-cpp.pc.in, line 6 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnaZji1QGEA27nUox4:-LF2Xfp13zPskqe1MNIP:b-qza4t1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L6)):*
<details><summary><i>Previously, igchor wrote…</i></summary><blockquote>

Only here, or should I also change package names?
</blockquote></details>

Please change package names too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
Review status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @igchor)

---

*[CMakeLists.txt, line 275 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2Y9712TS5vFtYQ7aT:-LF2Y9712TS5vFtYQ7aU:ba2mtz6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L275)):*
> ```CMake
> 
> install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libpmemobj-cpp.pc
> 	CONFIGURATIONS Relase Debug
> ```

Release

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
Review status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @igchor)

---

*[CMakeLists.txt, line 392 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YNf36OiS_f4MbZKK:-LF2YNf36OiS_f4MbZKL:b-7qqcti) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L392)):*
> ```CMake
> 	set(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
> 	set(CPACK_RPM_PACKAGE_LICENSE "BSD")
> 	set(CPACK_RPM_PACKAGE_RELEASE 1.fc25)
> ```

fc25?

---

*[CMakeLists.txt, line 394 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YOmNBMKkwdt9Kup2:-LF2YOmNBMKkwdt9Kup3:b-7qqcti) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L394)):*
> ```CMake
> 	set(CPACK_RPM_PACKAGE_RELEASE 1.fc25)
> 	set(CPACK_RPM_PACKAGE_ARCHITECTURE x86_64)
> 	set(CPACK_RPM_PACKAGE_REQUIRES "libpmemobj-devel >= 1.4-1.fc25")
> ```

fc25?

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
Review status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @igchor)

---

*[CMakeLists.txt, line 369 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YWNVBZXMJdIq9D-l:-LF2YWNX68bLu05CTeRo:b46h4fx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L369)):*
> ```CMake
> 	set(CPACK_COMPONENTS_ALL_IN_ONE)
> 
> 	# Filter out some of directories from %dir section, which are excpected
> ```

expected

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by igchor** [comment]
Review status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @marcinslusarz and @igchor)

---

*[CMakeLists.txt, line 271 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2XcJe7FqA63bfsObj:-LF3Azd64q41lecacILU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L271)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

libpmemobj++.pc.in
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 275 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2Y9712TS5vFtYQ7aT:-LF3CCf_3tr1omLJ0mPr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L275)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Release
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 369 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YWNVBZXMJdIq9D-l:-LF3CIji-JZ6Ysy_K36Y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L369)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

expected
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 392 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YNf36OiS_f4MbZKK:-LF3BIKf6kTbFDa8J-GG:b-etxvf9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L392)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

fc25?
</blockquote></details>

This was taken from pmdk naming convention, for example libpmemobj rpm has name:
'libpmemobj-1.4-1.fc25.x86_64.rpm'

---

*[CMakeLists.txt, line 394 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YOmNBMKkwdt9Kup2:-LF3BTZo8suW5GcKhUw-:b32wyo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L394)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

fc25?
</blockquote></details>

up

---

*[libpmemobj-cpp.pc.in, line 6 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LEnaZji1QGEA27nUox4:-LF3Bl9iBxHd0NyNUTpb:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53c34cb9efe2d90236a5c728aea7225fe93dc410/libpmemobj-cpp.pc.in#L6)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please change package names too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
Reviewed 4 of 5 files at r3.
Review status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @marcinslusarz)

---

*[CMakeLists.txt, line 392 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YNf36OiS_f4MbZKK:-LF3DmbkBD6tXPynsOAu:b-95dfin) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L392)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This was taken from pmdk naming convention, for example libpmemobj rpm has name:
'libpmemobj-1.4-1.fc25.x86_64.rpm'
</blockquote></details>

fc25 == fedora core 25, which means that the package was built on fc25 and is for fc25.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by igchor** [comment]
Review status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @igchor and @marcinslusarz)

---

*[CMakeLists.txt, line 392 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YNf36OiS_f4MbZKK:-LF3Ht9u2JY10WT8ooV9:b-fzpko9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L392)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

fc25 == fedora core 25, which means that the package was built on fc25 and is for fc25.
</blockquote></details>

So, should we remove fc25 and have just libpmemobj-1.4-1.x86_64.rpm ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
Review status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @marcinslusarz and @igchor)

---

*[CMakeLists.txt, line 392 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YNf36OiS_f4MbZKK:-LF3IdDX55rwYxcL796s:b-e6nf6v) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L392)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, should we remove fc25 and have just libpmemobj-1.4-1.x86_64.rpm ?
</blockquote></details>

Ideally we would put distribution name and its version here, but it's probably not easy to do with cpack, so for now I think we should remove it.

---

*[CMakeLists.txt, line 394 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YOmNBMKkwdt9Kup2:-LF3J2E12-0CoN9JxLA5:b69jf0v) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L394)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

up
</blockquote></details>

oh, "-1" should also be removed - we don't care about package release version.

---

*[CMakeLists.txt, line 423 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF3K48m8pEc0vBBTOs9:-LF3K48m8pEc0vBBTOsA:b-tc338l) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/01ca40d827b5972bf178aa67aa2d060f4c488d1f/CMakeLists.txt#L423)):*
> ```CMake
> 	set(CPACK_DEBIAN_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE})
> 	set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)
> 	set(CPACK_DEBIAN_PACKAGE_DEPENDS "libpmemobj-dev (>= 1.4-1)")
> ```

s/-1// 

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by igchor** [comment]
Review status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @marcinslusarz)

---

*[CMakeLists.txt, line 392 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YNf36OiS_f4MbZKK:-LF3M_uV9Xil_wVNeSt5:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L392)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Ideally we would put distribution name and its version here, but it's probably not easy to do with cpack, so for now I think we should remove it.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 394 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF2YOmNBMKkwdt9Kup2:-LF3MadM3Qy2eCX8mCGk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/00605f59c0fd9bb17170dc15516a16290a99f4f8/CMakeLists.txt#L394)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

oh, "-1" should also be removed - we don't care about package release version.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 423 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-LF3K48m8pEc0vBBTOs9:-LF3usZa5xp1qWXt7y1J:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/01ca40d827b5972bf178aa67aa2d060f4c488d1f/CMakeLists.txt#L423)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

s/-1// 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8)*

**Comment by marcinslusarz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/8#-:-LFIQtWwAL_qTFAgpaIk:bnfp4nl)*

**Pull request merged**
