### PR TITLE
fix default bytes_view in radix_tree

### PR DESCRIPTION
**Pull request by JanDorniak99**
#911

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3204 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916#-MIt9ZgX23MhY_QUr20e:-MIt9ZgX23MhY_QUr20f:boqo7nm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/85ee881045fd2ef7a43bc2b80cb83f1d25033c0d/include/libpmemobj++/experimental/radix_tree.hpp#L3204)):*
> ```cpp
> 	}
> 
> 	char operator[](std::size_t p) const
> ```

return type shouldn't be also CharT ...?

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99 and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916#-MItFv0V7_rGxYQ1nyl0:-MItFv0WBS0A3wEabk7r:b-cf5gmr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/85ee881045fd2ef7a43bc2b80cb83f1d25033c0d/include/libpmemobj++/experimental/radix_tree.hpp#L72)):*
> ```cpp
>  * sequences are compared using a function equivalent to std::string::compare.
>  *
>  * BytesView should accept a pointer to the key type in a constructor and
> ```

Could you also update this description please? We should say that the operator[] should return a byte at the specified position in the byte representation of value (or something like this).
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3204 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916#-MIt9ZgX23MhY_QUr20e:-MItEYZe678YCDroFGDZ:bkrzjm3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/85ee881045fd2ef7a43bc2b80cb83f1d25033c0d/include/libpmemobj++/experimental/radix_tree.hpp#L3204)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

return type shouldn't be also CharT ...?
</blockquote></details>

No, inside radix_tree we want to obtain a sequence of chars to index our child arrays in nodes. We specifically need to split the input sequence to sequence of chars.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916#-MItFv0V7_rGxYQ1nyl0:-MJ1UIDU8TYh960hhJKA:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/85ee881045fd2ef7a43bc2b80cb83f1d25033c0d/include/libpmemobj++/experimental/radix_tree.hpp#L72)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you also update this description please? We should say that the operator[] should return a byte at the specified position in the byte representation of value (or something like this).
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916#-:-MJ1mmaw1On2L-G15igR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/916#-:-MJ2ly-L6OWfutkk1RYe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
