### PR TITLE
basic_string: add constructor with view parameter

### PR DESCRIPTION
**Pull request by KFilipek**
- add constructor that passes basic_string_view parameter

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)

### CODE REVIEW

**Comment by KFilipek** [comment]
I will add test case to cover this constructor, but I'm open for suggestions.

**Review by karczex — COMMENTED** [review]
any tests?

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-:-MHRLwHm2XGbzuHAwbxv:bvpllmf)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by KFilipek** [comment]
I'm thinking about where is the best place to put some cases. Maybe string_view tests or create a new test suite for constructors?

**Review by igchor — CHANGES_REQUESTED** [review]
You can extend libcxx tests and out own tests.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-:-MHRXZY_4SvLj6OB6l64:b-nvs9gt)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHRXRA63KpIk5AWDEom:b-ecgwam) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):*
> ```cpp
> 	basic_string(basic_string &&other);
> 	basic_string(std::initializer_list<CharT> ilist);
> 	basic_string(const basic_string_view<CharT, Traits> &bsv);
> ```

As I said on our scrum, maybe it would be better to implement the templated version after all? https://stackoverflow.com/questions/57607823/why-is-there-a-constructor-of-the-class-stdbasic-string-with-a-parameter-of-th

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHRXhenDaHTWqS9crCr:b-w90d1r) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

As I said on our scrum, maybe it would be better to implement the templated version after all? https://stackoverflow.com/questions/57607823/why-is-there-a-constructor-of-the-class-stdbasic-string-with-a-parameter-of-th
</blockquote></details>

Or, alternatively, we could just remove the constructors which take `const basic_string&` (they will be covered by the string_view constructor).

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHV3fLs8exe1CbnbgxR:bxq8wlk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Or, alternatively, we could just remove the constructors which take `const basic_string&` (they will be covered by the string_view constructor). 
</blockquote></details>

However, the problem could remain for constructor for std::basic_string. We cannot remove it since there is no conversion from std;:string to our string_view (prec C++17).  We would have to also add ctor taking std::basic_string to our string_view.

**Comment by KFilipek** [comment]
> > _[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)
> 
> _[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHV3fLs8exe1CbnbgxR:bxq8wlk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):_
> 
> Previously, igchor (Igor Chorążewicz) wrote…
> However, the problem could remain for constructor for std::basic_string. We cannot remove it since there is no conversion from std;:string to our string_view (prec C++17). We would have to also add ctor taking std::basic_string to our string_view.

You mean: basic_string_view(const std::basic_string<CharT, Traits> &s);?
It's currently in our implementation of string_view.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHjor-rDGYlBe96FVep:b-1pgozr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

You mean: basic_string_view(const std::basic_string<CharT, Traits> &s);? It's currently in our implementation of string_view. 
</blockquote></details>

Hm, but still, we would have basically remove copy ctor which could lead to unwanted behaviors. I think that we should just implement it the same way as std does - with template.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHuQffC9OvOPL91sCcT:b-bxy4a6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, but still, we would have basically remove copy ctor which could lead to unwanted behaviors. I think that we should just implement it the same way as std does - with template.
</blockquote></details>

This one is not needed anymore once we have a templated version.
___
*[include/libpmemobj++/container/basic_string.hpp, line 701 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHuQk7sDGq1ekAhBgad:-MHuQk7sDGq1ekAhBgae:b8vbzav) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e442d7588682c18fb9cbdaa0c8ac29ebd09a93b/include/libpmemobj++/container/basic_string.hpp#L701)):*
> ```cpp
>  */
> template <typename CharT, typename Traits>
> template <class T>
> ```

You should use enable if to generate this ctor only for appropriates types (see cppreference for requirements).

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHvbLJK5JWna6dsEIRq:-MHvbLJK5JWna6dsEIRr:bzghjse) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8f8129e79a58fb13e3a1f3180e5cf4b6c7e86a14/include/libpmemobj++/container/basic_string.hpp#L85)):*
> ```cpp
> 	basic_string(basic_string &&other);
> 	basic_string(std::initializer_list<CharT> ilist);
> 	basic_string(const basic_string_view<CharT, Traits> &bsv);
> ```

I believe you could also add the last remaing ctor in this PR. I'm talking about the 11th one on cppreference) - (basic_string_view + pos + n). We will be fully compatible with std::string regarding ctors then.

But please prioritize proting libcxx tests before that.
___
*[include/libpmemobj++/container/basic_string.hpp, line 712 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHvbvL44ARkgsNqGZra:-MHvbvL44ARkgsNqGZrb:b-7ayasz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8f8129e79a58fb13e3a1f3180e5cf4b6c7e86a14/include/libpmemobj++/container/basic_string.hpp#L712)):*
> ```cpp
> {
> 	basic_string_view<CharT, Traits> sv = t;
> 	basic_string(sv.data(), sv.size());
> ```

I believe this will create a temporart unnamed object on stack (it will not delegate to another ctor).  You'll have to implement it in terms of allocate and initaialize().

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MHzZ-Ot3x7La2wsxTcD:b-5myrhr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
> ```cpp
> template <typename CharT, typename Traits>
> inline basic_string_view<CharT, Traits>::basic_string_view(const CharT *data)
>     : data_(data), size_(std::char_traits<CharT>::length(data))
> ```

Actually this should be Trats, not std::char_traits<CharT>. But anyway, this will be fixed here: https://github.com/pmem/libpmemobj-cpp/pull/885/commits/127864d75ae0af163ee44523eddfc1e0ad06bf4f (In Jan's PR) . Can you remove this change or it will break tests?
___
*[include/libpmemobj++/container/basic_string.hpp, line 723 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZPWaCiNsa5Yw0m0L:-MHzZPWaCiNsa5Yw0m0M:b-oegl6s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/container/basic_string.hpp#L723)):*
> ```cpp
> {
> 	// basic_string_view<CharT, Traits> sv = t;
> 	// basic_string(sv.data(), sv.size());
> ```

Please remove those comments.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MHzv6orB6Z3KOR4RPxD:b33xpvq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually this should be Trats, not std::char_traits<CharT>. But anyway, this will be fixed here: https://github.com/pmem/libpmemobj-cpp/pull/885/commits/127864d75ae0af163ee44523eddfc1e0ad06bf4f (In Jan's PR) . Can you remove this change or it will break tests?
</blockquote></details>

Tests cannot compile without this change. 
___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHRXRA63KpIk5AWDEol:-MHzvf8Q7cEdXExE6Vua:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5f4dea81dfd99356f4f8f3df3248175736b02a7e/include/libpmemobj++/container/basic_string.hpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This one is not needed anymore once we have a templated version.
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/basic_string.hpp, line 701 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHuQk7sDGq1ekAhBgad:-MHzw-DP6Vtd3DStgCkF:b-hi5p8n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e442d7588682c18fb9cbdaa0c8ac29ebd09a93b/include/libpmemobj++/container/basic_string.hpp#L701)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You should use enable if to generate this ctor only for appropriates types (see cppreference for requirements).
</blockquote></details>

I spent some times and I got it, now should be okey.
___
*[include/libpmemobj++/container/basic_string.hpp, line 85 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHvbLJK5JWna6dsEIRq:-MHzvhRhDkDK_m1vhCSI:b7lu4tn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8f8129e79a58fb13e3a1f3180e5cf4b6c7e86a14/include/libpmemobj++/container/basic_string.hpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I believe you could also add the last remaing ctor in this PR. I'm talking about the 11th one on cppreference) - (basic_string_view + pos + n). We will be fully compatible with std::string regarding ctors then.

But please prioritize proting libcxx tests before that.
</blockquote></details>

I've added test covering first constructor enabled from the libcxx. 
___
*[include/libpmemobj++/container/basic_string.hpp, line 712 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHvbvL44ARkgsNqGZra:-MHzw5AV80PDCRsL5u1x:b-zbdrqv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8f8129e79a58fb13e3a1f3180e5cf4b6c7e86a14/include/libpmemobj++/container/basic_string.hpp#L712)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I believe this will create a temporart unnamed object on stack (it will not delegate to another ctor).  You'll have to implement it in terms of allocate and initaialize().
</blockquote></details>

I've copied implementation from the constructor above. I wonder about move some code into function, at least 2-3 functions/constructors have similar implementation.
___
*[include/libpmemobj++/container/basic_string.hpp, line 723 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZPWaCiNsa5Yw0m0L:-MHzw4-NCcOSccPToPYF:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/container/basic_string.hpp#L723)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please remove those comments.
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/basic_string.hpp, line 116 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzvu3V71wgF6i3IN14:-MHzvu3WAh6aTXDkgs4z:b-22yiq7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78536243831a10223ec8c4832b8ac22adeca853e/include/libpmemobj++/container/basic_string.hpp#L116)):*
> ```cpp
> 						    CharT, Traits>>::value &&
> 			!std::is_convertible<const T &, const CharT *>::value>>
> 	basic_string &operator=(const T &t);
> ```

Covered by the ported test from libcxx.

**Review by igchor — APPROVED** [review]
> Reviewed 2 of 4 files at r5, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MHzxhKXAX7rifA76x9u:bk0ivr1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Tests cannot compile without this change. 
</blockquote></details>

It works for me. The test only works with char type form what I see. Anywa, you can leave it but you (or Jan) will have to rebase.
___
*[include/libpmemobj++/container/basic_string.hpp, line 712 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHvbvL44ARkgsNqGZra:-MHzxyvbDJMDdzehYo8D:bx21s7p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8f8129e79a58fb13e3a1f3180e5cf4b6c7e86a14/include/libpmemobj++/container/basic_string.hpp#L712)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I've copied implementation from the constructor above. I wonder about move some code into function, at least 2-3 functions/constructors have similar implementation.
</blockquote></details>

I believe you could use string_view ctors from other ctors by calling something like:

```
basic_string(const string& s, pos, n): basic_string(basic_string_view(s), pos, n) {}
```

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MHzz7zHDWE9jCUSQfE8:b7n3wvu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It works for me. The test only works with char type form what I see. Anywa, you can leave it but you (or Jan) will have to rebase.
</blockquote></details>

And if you want to have this fix on this PR please make it a separate commit and fix also other places (but I'd prefer if you just remove it, It's done on Jan's PR).

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-:-MI-MGwG0Sn2PlLsoSlC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/container/basic_string.hpp, line 116 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzvu3V71wgF6i3IN14:-MI-NFGj08pKsEkR0p4x:bhi7a3n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78536243831a10223ec8c4832b8ac22adeca853e/include/libpmemobj++/container/basic_string.hpp#L116)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Covered by the ported test from libcxx.
</blockquote></details>

Please also test the second ctor.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 4 files at r5, 1 of 2 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MI-MDgZ5x5P5f1C_R5P:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

And if you want to have this fix on this PR please make it a separate commit and fix also other places (but I'd prefer if you just remove it, It's done on Jan's PR).
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/basic_string.hpp, line 116 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzvu3V71wgF6i3IN14:-MI1D3mR1fNW10ralKDr:b-kff350) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/78536243831a10223ec8c4832b8ac22adeca853e/include/libpmemobj++/container/basic_string.hpp#L116)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please also test the second ctor.
</blockquote></details>

Done. 
./tests/external/string_libcxx_string_view tests:
basic_string(const T &t)
templated operator=
and ./tests/external/string_libcxx_cons_substr:
basic_string(const T &t, size_type pos, size_type n)
basic_string(const std::basic_string<CharT> &other, size_type pos, size_type count)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MI3BMzzBFzekr1ztvSi:b44rg38) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you rebase and remove this commit? This is already merged on master,

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-MHzZ-Ot3x7La2wsxTcC:-MI3Jgd286dz4p9p0esY:b6iaeg7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/9b725f350b89fc08038566f95c0bacc26653fdb5/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can you rebase and remove this commit? This is already merged on master,
</blockquote></details>

I rebased it

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/871#-:-MI3LHNy95GqhYxKH6ix:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
