### PR TITLE
Move Coverity job to GHA

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] wait for pmem/pmemkv#807 (until it's tested there)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
it works just fine on pmemkv, I believe: https://scan.coverity.com/projects/pmem-pmemkv

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917#-:-MJW75_v4-cj3jx3gw3N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[travis.yml, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917#-MJWVC2u00lm7iSbh4Bd:-MJWVC2u00lm7iSbh4Be:b8vzlr4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/af50f3fb7987e5e6592ad12bc42d67fa22bb83d5/travis.yml#L11)):*
> ```YAML
> 
> # currently, Travis is turned off - all jobs run on GHA
> if: false
> ```

pls, remove this file in separate commit, to  be able revert it easily, instead of making intentionally dead code.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[travis.yml, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917#-MJWVC2u00lm7iSbh4Bd:-MJYcn2y8-bcS6OjFhh4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/af50f3fb7987e5e6592ad12bc42d67fa22bb83d5/travis.yml#L11)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

pls, remove this file in separate commit, to  be able revert it easily, instead of making intentionally dead code. 
</blockquote></details>

Done.

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917#-:-MJ_vctH0AOpExzZXJz-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/917#-:-MJag7LJ-Gr0fMh9Tv4P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
