### PR TITLE
string_view: VS2015 build fix

### PR DESCRIPTION
**Pull request by KFilipek**
This PR fixes master branch, I believe. 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973#-MMVW1mh2q2d0ljPEEFx:-MMVW1mh2q2d0ljPEEFy:b3sfna3) (no related file):*
as for commit message:
- it's not for "function" - it's for args/params, I believe ;)
- you can add info "why" you're removing them

---
___
*[include/libpmemobj++/string_view.hpp, line 473 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973#-MMVVtSyBWn3yNM7U4ZE:-MMVVtSz8aWIQIVOdxzt:b60rsgj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/319e12aea661ccd27fc1a7d010dfd9795eaf0f83/include/libpmemobj++/string_view.hpp#L473)):*
> ```cpp
> inline int
> basic_string_view<CharT, Traits>::compare(
> 	size_type pos1, size_type n1, basic_string_view<CharT, Traits> sv) const
> ```

is this change needed, too?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973#-MMVW1mh2q2d0ljPEEFx:-MMVYFm6Cfqt2y3Hk7Vc:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as for commit message:
- it's not for "function" - it's for args/params, I believe ;)
- you can add info "why" you're removing them
</blockquote></details>

Done.

---
___
*[include/libpmemobj++/string_view.hpp, line 473 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973#-MMVVtSyBWn3yNM7U4ZE:-MMVXEykBgwcbT2L27Ys:b8ez75m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/319e12aea661ccd27fc1a7d010dfd9795eaf0f83/include/libpmemobj++/string_view.hpp#L473)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is this change needed, too?
</blockquote></details>

This change is needed to avoid "masło maślane" effect.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973#-:-MMVu9KiABvBrDVgOzJh:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/973#-:-MMWgWUzAHExVaLMwRpk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
