### PR TITLE
Fix argument parsing in examples/map_cli.

### PR DESCRIPTION
**Pull request by igchor**
argn was not incremented in case of get(). This resulted
in "invalid queue operation" message on every get.

Ref: #186

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/191)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
By reading the code I think "remove_free" operation is also buggy and "insert" command "usage" is incorrect. Can you fix these problems too and add test for this example?

**Comment by marcinslusarz** [comment]
Also, stable-1.5 material.

**Comment by igchor** [comment]
Done.

**Comment by marcinslusarz** [comment]
What about the missing test? :)

**Comment by marcinslusarz** [comment]
Ok, I opened #204 to not forget about it.

**Pull request merged**
