### PR TITLE
inline_string: disallow creating basic_inline_string on dram

### PR DESCRIPTION
**Pull request by igchor**
and create a separate type: baisc_dram_inline_string which
have no such limitation.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160)

### CODE REVIEW

**Comment by KFilipek** [comment]
Typo:
```
inline_string: disallow creating basic_inline_string on dram

and create a separate type: **baisc**_dram_inline_string which
have no such limitation.
```

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 29 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-MezepK0BPjitMML0jrp:-MezepK0BPjitMML0jrq:b-55d1st) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L29)):*
> ```cpp
>  * keeps the data within the same allocation as inline_string itself.
>  *
>  * Unlike other containers, it can be used on pmem and dram. Modifiers (like
> ```

pls update this description
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 113 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-MezervpCz0fAgpuxrsQ:-MezervpCz0fAgpuxrsR:b-y9ytl7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L113)):*
> ```cpp
> 
> template <typename CharT, typename Traits = std::char_traits<CharT>>
> using basic_dram_inline_string =
> ```

you can add short descriptions to these two `using`s (I think they'll appear somewhere in the Doxygen docs)
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 209 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-MezmnBb3mn2b9fZqPXR:-MezmnBb3mn2b9fZqPXS:b-uvs9jx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L209)):*
> ```cpp
> }
> 
> template <typename CharT, bool AllowDram, typename Traits>
> ```

pls add one sentence descr.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 237 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-Mezmqo06RZ5LIk88mii:-Mezmqo06RZ5LIk88mij:b-uvs9jx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L237)):*
> ```cpp
> }
> 
> template <typename CharT, bool AllowDram, typename Traits>
> ```

pls add one sentence descr.

**Review by igchor — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-:-Mf21hu79HS9SNyVRSq1:b-896fix)* status: all files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 29 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-MezepK0BPjitMML0jrp:-Mf21BPY2ba8mW9sYcS0:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L29)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update this description
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 113 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-MezervpCz0fAgpuxrsQ:-Mf21CM51-VzAXLxVw2u:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add short descriptions to these two `using`s (I think they'll appear somewhere in the Doxygen docs)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 209 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-MezmnBb3mn2b9fZqPXR:-Mf21F-U798lp9fhs_uZ:b-wdbta0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L209)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add one sentence descr.
</blockquote></details>

Do we really need a description for copy/default ctors?
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 237 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-Mezmqo06RZ5LIk88mii:-Mf21gqpAQy7t3wh0HYk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d71c388a5cbc1b1530d0444dc897f6f2ed958ec5/include/libpmemobj++/experimental/inline_string.hpp#L237)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add one sentence descr.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1160#-:-Mf2Ayh10I6qHIxXIDBU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request closed without merging**
