### PR TITLE
Turn libunwind off for valgrind tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
~~alternative approach to https://github.com/pmem/libpmemobj-cpp/pull/1224~~

@kilobyte's solution was not applicable, unfortunately. But a new piece of documentation is provided and this should be just fine... 😄 

Right now, the solution we already have, should be enough. We USE_LIBUNWIND set to ON, by default, and only turn it off in our CI. In case of any tests failures, there's this new readme note, how to handle these fails.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227)

### CODE REVIEW

**Review by KFilipek — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by kilobyte** [comment]
Is there a reason to leave the `TESTS_VALGRIND_UNWIND` variable at all?

**Review by lukaszstolarczuk — COMMENTED** [review]
good catch @kilobyte, done

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227#-:-MnzXs4aAOTLJe0Ma8l4:b3du3ks)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by KFilipek — APPROVED** [review]
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/test_backtrace.c, line 24 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227#-Mo3VQ9K9rrw8oecGR4h:-Mo3VQ9K9rrw8oecGR4i:b1dmslq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/68c83e15a412a7c8fda82fd7b34c5ff4a965e42a/tests/test_backtrace.c#L24)):*
> ```C
> #include <dlfcn.h>
> #include <libunwind.h>
> #include <valgrind.h>
> ```

in libpmemobj++/detail/common.hpp we use

```C++ 
   48 #if LIBPMEMOBJ_CPP_ANY_VG_TOOL_ENABLED                                                                        
   49 #include <valgrind.h>                                                                                         
   50 #endif  j++/detail/common.hpp we use
```
And probably we should use this macro here. As I can understand, we don't want to make 'valgrind.h' hard dependency for all tests always. 

Apart of this, I think it's very good approach :)

**Review by lukaszstolarczuk — COMMENTED** [review]
@kilobyte, after all, this is not a good approach. I mean, we could add this improvement, but it won't fix our problem.
I'd come back to the previous approach, see there (#1224) for my new comments.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227#-:-MoJQbgs-Zi0jGn2w2qo:by9dhle)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/test_backtrace.c, line 24 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227#-Mo3VQ9K9rrw8oecGR4h:-MoJQHna1W7r6D4Cf-RP:bgpcelw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/68c83e15a412a7c8fda82fd7b34c5ff4a965e42a/tests/test_backtrace.c#L24)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

in libpmemobj++/detail/common.hpp we use

```C++ 
   48 #if LIBPMEMOBJ_CPP_ANY_VG_TOOL_ENABLED                                                                        
   49 #include <valgrind.h>                                                                                         
   50 #endif  j++/detail/common.hpp we use
```
And probably we should use this macro here. As I can understand, we don't want to make 'valgrind.h' hard dependency for all tests always. 

Apart of this, I think it's very good approach :) 
 
</blockquote></details>

That's actually a good catch, thx! in `libpmemobj-cpp` we do NOT include valgrind, and thus we don't want to require valgrind for all tests. I will fix it, if we continue with this PR.

**Comment by lukaszstolarczuk** [comment]
It was completely re-designed, meaning almost no changes in the scripts. The main reason for this PR is now... just document the problem and add info on how to overcome this.

**Comment by lukaszstolarczuk** [comment]
> Is there a reason for me to test with libunwind during distro package builds? For now I have just valgrind on.

Valgrind ON is good. You can skip libunwind. In special cases, when we need better test output, we could re-run with libunwind.

**Review by karczex — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227#-:-MpesLOf2aUgfHAKCERk:bnfp4nl)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @karczex, @KFilipek, and @kilobyte)

**Review by KFilipek — APPROVED** [review]
> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1227#-:-MpfXy1FBzg_sD2rsXVT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
