### PR TITLE
examples: add simplekv_rebuild_string example

### PR DESCRIPTION
**Pull request by igchor**
It uses pmem::obj::string as a value type

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[examples/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQlitIR8b9AO3sYePWi:-MQlitIR8b9AO3sYePWj:b-uul3wy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/CMakeLists.txt#L2)):*
> ```CMake
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2018-2020, Intel Corporation
> ```

welcome 2021 ;)
___
*[examples/simplekv_rebuild/simplekv_rebuild_string.cpp, line 5 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQljCBf58yo1pswXEus:-MQljCBf58yo1pswXEut:b-lm5a6o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/simplekv_rebuild/simplekv_rebuild_string.cpp#L5)):*
> ```cpp
> 
> /*
>  * simplekv_rebuild.cpp -- example usage of simple kv which uses vector to hold
> ```

name update pls
___
*[examples/simplekv_rebuild/simplekv_rebuild_string.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQljhQC3ebq1m8fhX5B:-MQljhQC3ebq1m8fhX5C:bbmpyce) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/simplekv_rebuild/simplekv_rebuild_string.cpp#L31)):*
> ```cpp
> {
> 	if (argc < 2) {
> 		std::cerr << "usage: " << argv[0] << " file-name" << std::endl;
> ```

better `file-path` ..?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[examples/simplekv_rebuild/simplekv_rebuild_string.cpp, line 18 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQpzTok0shykIkOkbo0:-MQpzTol6BvkYZgZ8f7F:b5opgui) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/simplekv_rebuild/simplekv_rebuild_string.cpp#L18)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #include <libpmemobj++/make_persistent_atomic.hpp>
> #include <libpmemobj++/pool.hpp>
> #include <stdexcept>
> #include <string>
> #include "simplekv_rebuild.hpp"
> ```
</details>

Reorder according to this guideline:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009)* status: all files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/CMakeLists.txt, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQlitIR8b9AO3sYePWi:-MQqIEzv8zfs01fQr018:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/CMakeLists.txt#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

welcome 2021 ;)
</blockquote></details>

Done.
___
*[examples/simplekv_rebuild/simplekv_rebuild_string.cpp, line 5 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQljCBf58yo1pswXEus:-MQqIFVR3tTCkIFIarLW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/simplekv_rebuild/simplekv_rebuild_string.cpp#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

name update pls
</blockquote></details>

Done.
___
*[examples/simplekv_rebuild/simplekv_rebuild_string.cpp, line 18 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQpzTok0shykIkOkbo0:-MQqIooYAHrm3IsxVs7p:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/simplekv_rebuild/simplekv_rebuild_string.cpp#L18)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #include <libpmemobj++/make_persistent_atomic.hpp>
> #include <libpmemobj++/pool.hpp>
> #include <stdexcept>
> #include <string>
> #include "simplekv_rebuild.hpp"
> ```
Reorder according to this guideline:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
</blockquote></details>

Done.
___
*[examples/simplekv_rebuild/simplekv_rebuild_string.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-MQljhQC3ebq1m8fhX5B:-MQqIuI0BTz04uU4lFqO:bew4y0y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f690a6c8d8b24381942a34927544fd4fd39e3e37/examples/simplekv_rebuild/simplekv_rebuild_string.cpp#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

better `file-path` ..?
</blockquote></details>

We have file-name in all other example so I'd leave it for consistency

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-:-MQqcNzn-8cGpJrsfTVj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1009#-:-MQuhZg6BGQwS-Db44Fz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Pull request merged**
