### PR TITLE
cleanups in CMake files

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] wait for #913 to avoid merge conflicts

- add more comments,
- group commands,
- cleanup print messages,
- simplify code/commands.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[CMakeLists.txt, line 46 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIY4RIB0D6_n-d2A4s8:-MIY4RIB0D6_n-d2A4s9:bmurp0q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/CMakeLists.txt#L46)):*
> ```CMake
> set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_SOURCE_DIR}/cmake)
> 
> # Set ${SRCVERSION}
> ```

are we using this var somewhere?

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 46 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIY4RIB0D6_n-d2A4s8:-MIcs7EXEO1cc4QaCGn7:b-kq1xjc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/CMakeLists.txt#L46)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are we using this var somewhere?
</blockquote></details>

Hm, I think not, we could put this variable to our version.hpp file (for now we only pass major, minor and patch versions).
___
*[CMakeLists.txt, line 178 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIctTk58cLMZYDxKn_t:-MIctTk58cLMZYDxKn_u:buto1b8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/CMakeLists.txt#L178)):*
> ```CMake
> 
> 	# XXX: do we need this anymore?
> 	# set variable ${LIBPMEMOBJ_VERSION_NUM}; it's used in some tests
> ```

Yeah, I think we do not need it anymore (along with the ifdef in transaction.cpp test). However, maybe we should just move this to some helper cmake file (if we'll need it in future, we won't have to look through git history).
___
*[examples/CMakeLists.txt, line 130 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIcuF022pyuSbUKw0PD:-MIcuF022pyuSbUKw0PE:b-e3mlby) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/examples/CMakeLists.txt#L130)):*
> ```CMake
> endif()
> 
> if(TEST_ARRAY)
> ```

Should we add some checker for that? I don't want to spend time reviewing whitespaces so that everything is consistent in future PRs ;d
___
*[tests/CMakeLists.txt, line 556 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIcunk0CiHeN_LJFEQ2:-MIcunk0CiHeN_LJFEQ3:b4cvqwy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/tests/CMakeLists.txt#L556)):*
> ```CMake
> 	endif()
> 
> 	# XXX: move this check to the top of the file, to potentially fail build earlier
> ```

This would only speed up cmake (not make) step which is rather fast
___
*[tests/transaction/transaction.cpp, line 193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIcv6JO9RxuIKMSdEts:-MIcv6JO9RxuIKMSdEtt:bjowtra) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/tests/transaction/transaction.cpp#L193)):*
> ```cpp
> 	 *  - pmemobj prior to 1.5.1 has a bug (see pmem/pmdk#3536) which
> 	 *    corrupts mutex state by unlocking it when it shouldn't
> 	 *	XXX: can we even use libpmemobj++ with pmdk < 1.5.1 ?
> ```

not anymre

**Review by lukaszstolarczuk — COMMENTED** [review]
I'm keeping comments with TODOs to fix in other PR, so this one is not cluttered by various/complicated changes.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-:-MIdMsTz5deW-9mxL3qT:b-2hw54p)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[CMakeLists.txt, line 178 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIctTk58cLMZYDxKn_t:-MIdJsMl4lIMbEWPlmN7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/CMakeLists.txt#L178)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, I think we do not need it anymore (along with the ifdef in transaction.cpp test). However, maybe we should just move this to some helper cmake file (if we'll need it in future, we won't have to look through git history).
</blockquote></details>

Done.
___
*[examples/CMakeLists.txt, line 130 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIcuF022pyuSbUKw0PD:-MIdJv7pB6hZviC-fHkL:b-uzz7d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/examples/CMakeLists.txt#L130)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Should we add some checker for that? I don't want to spend time reviewing whitespaces so that everything is consistent in future PRs ;d
</blockquote></details>

I'm not sure if this is really needed. I did this, because most of the if's looked like this, but I'm not sure if this is worth to follow some specific rule.
___
*[tests/CMakeLists.txt, line 556 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIcunk0CiHeN_LJFEQ2:-MIdKHCSEmKOCD0aPEB2:bn51a3y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/tests/CMakeLists.txt#L556)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This would only speed up cmake (not make) step which is rather fast
</blockquote></details>

I'd do it also for us, it will be a bit easier to maintain or just read the file.
___
*[tests/transaction/transaction.cpp, line 193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MIcv6JO9RxuIKMSdEts:-MIdKV9n7JAZ1FrSa3O7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/63119ad83bede51a329f5069fab7603d65abf911/tests/transaction/transaction.cpp#L193)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

not anymre
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/helpers.cmake, line 378 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJ1N6VpAXWdGEhkznHy:-MJ1N6VqEPceuN7TdmLD:b-bv6dw0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6d248a59ab10a9997a67e64187ffb53f2ce0e8f1/tests/helpers.cmake#L378)):*
> ```CMake
> 
>     math(EXPR LIBPMEMOBJ_VERSION_NUM "${LIBPMEMOBJ_VERSION_PATCH} + ${LIBPMEMOBJ_VERSION_MINOR} * 100 + ${LIBPMEMOBJ_VERSION_MAJOR} * 10000")
> endfunction()
> ```

newline?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @igchor)

___
*[tests/helpers.cmake, line 378 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJ1N6VpAXWdGEhkznHy:-MJ1OMGK79LsFzyeVX3G:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6d248a59ab10a9997a67e64187ffb53f2ce0e8f1/tests/helpers.cmake#L378)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

newline?
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 9 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJW63RW1p_b11dIjTBu:-MJW63RW1p_b11dIjTBv:b3s7cf5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/26e529f665bc65e668c19fd3436532069f7f5efb/tests/CMakeLists.txt#L9)):*
> ```CMake
> add_custom_target(tests)
> 
> # Checks for when DEVELOPER_MODE is ON
> ```

Use the same, third form in all cases. I'm not sure that "checks for when" is a good translation, I think that: "Checks for DEVELOPER_MODE is ON" is enough.
___
*[tests/CMakeLists.txt, line 279 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJW6UP3-gHy7FmLeaNm:-MJW6UP3-gHy7FmLeaNn:bdmice0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/26e529f665bc65e668c19fd3436532069f7f5efb/tests/CMakeLists.txt#L279)):*
> ```CMake
> 
> # Containers tests
> ###################################### ARRAY ###################################
> ```

Two rows or one?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[tests/CMakeLists.txt, line 9 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJW63RW1p_b11dIjTBu:-MJWKfzO09MS3MkjZ2n2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/26e529f665bc65e668c19fd3436532069f7f5efb/tests/CMakeLists.txt#L9)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Use the same, third form in all cases. I'm not sure that "checks for when" is a good translation, I think that: "Checks for DEVELOPER_MODE is ON" is enough.
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 279 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJW6UP3-gHy7FmLeaNm:-MJWKjzx0mR-qhH6MsVH:bd5wa28) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/26e529f665bc65e668c19fd3436532069f7f5efb/tests/CMakeLists.txt#L279)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Two rows or one? 
</blockquote></details>

one on the beginning of a section and one for ending

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 54 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJWb6rO7YokeBDxRR_W:-MJWb6rP95z_YGKNlDK3:blvygms) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dbde6296d446243ab44e61945e8fc90a763716e0/CMakeLists.txt#L54)):*
> ```CMake
> 			OUTPUT_STRIP_TRAILING_WHITESPACE
> 			ERROR_QUIET)
> 	if(NOT SRCVERSION)
> ```

There is always something in SRCVERSION at this point.
In worst case, it you don't have defined any tags in repository, you will get "fatal: No names found, cannot describe anything.". You should rather check return value from previous execute_command.
___
*[CMakeLists.txt, line 61 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJWcPzFDzG2LEEddtl4:-MJWcPzFDzG2LEEddtl5:b-uavktd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dbde6296d446243ab44e61945e8fc90a763716e0/CMakeLists.txt#L61)):*
> ```CMake
> 	endif()
> else()
> 	execute_process(COMMAND cat .version
> ```

use native cmake file() function instead of execute_process? 

```
file(STRINGS .varsion SRCVERSION)
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[CMakeLists.txt, line 54 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJWb6rO7YokeBDxRR_W:-MJXgr_302jrm7-TYiju:by49s30) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dbde6296d446243ab44e61945e8fc90a763716e0/CMakeLists.txt#L54)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

There is always something in SRCVERSION at this point.
In worst case, it you don't have defined any tags in repository, you will get "fatal: No names found, cannot describe anything.". You should rather check return value from previous execute_command.
</blockquote></details>

nope, in case of e.g. missing tags you get (as you mentioned) `fatal: ...`, but it is delivered to stderr, so SRCVERSION will be empty at this point. I don't think we should change this piece of code.
___
*[CMakeLists.txt, line 61 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MJWcPzFDzG2LEEddtl4:-MJXimQZ5TtK4tJAO7G4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/dbde6296d446243ab44e61945e8fc90a763716e0/CMakeLists.txt#L61)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

use native cmake file() function instead of execute_process? 

```
file(STRINGS .varsion SRCVERSION)
```
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-:-MJadAwt86Jj2-x4jVRk:bnfp4nl)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-:-MJzevHO3I4bI7lMwXUt:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by igchor — COMMENTED** [review]
LGTM, just one question, did you move some of the tests to other build (or did not rebase on current master)? I see number of tests for fedora, release is lower in this build than on current master.

Also, the coverage dropped in some tests which are deterministic (like for make_persistent_array).

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-:-MK-0Huy7s60dotltJhx:bb71gh6)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

**Review by lukaszstolarczuk — COMMENTED** [review]
@igchor, you were right, I've misplaced "check_compiling_issues.cmake" it was supposed to be after finding LIBPMEMOBJ library and hence some tests were silently skipped. I've added some message info in CMake.

Now it should be fine (I've checked logs of Ubuntu and Fedora builds).

@ EDIT: it seems like there's still something weird with the coverage, I'm converting it into a draft again.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-:-MKFhtfI2T_6f8kn5CmY:bjvrm93)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @szyrom)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKKc_Cr249yicpg_9yF:bmqbr85) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
> ```CMake
> 
> 	# Check for issues with older clang compilers which assert on delete persistent<[][]>.
> 	set(CMAKE_REQUIRED_INCLUDES ${CMAKE_SOURCE_DIR}/include ${LIBPMEMOBJ_INCLUDE_DIRS} ${VALGRIND_INCLUDE_DIRS})
> ```

for a reason I had to add Valgrind includes here... and I'm a bit confused and not sure it this is correct...?
___
*[tests/CMakeLists.txt, line 231 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKd7ew0w2Ta3wie0Uv:-MKKd7ew0w2Ta3wie0Uw:blx89fm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/tests/CMakeLists.txt#L231)):*
> ```CMake
> 	build_test(make_persistent_array_atomic make_persistent_array_atomic/make_persistent_array_atomic.cpp)
> 	add_test_generic(NAME make_persistent_array_atomic TRACERS none pmemcheck)
> else()
> ```

shouldn't we skip these tests only if we run on clang?

The same for all these "GCC_*" bugs...

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKZdJvFA5FORLC3NSPq:bolhxhl) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

for a reason I had to add Valgrind includes here... and I'm a bit confused and not sure it this is correct...?
</blockquote></details>

Hm, this should not be needed. Can you check what is the compiler error of this CHECK_CXX_SOURCE_COMPILES without valgrind includes? I think the logs are saved to some file.
___
*[tests/CMakeLists.txt, line 231 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKd7ew0w2Ta3wie0Uv:-MKZd8_c5Y3zGAFFaEMP:bgrus70) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/tests/CMakeLists.txt#L231)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we skip these tests only if we run on clang?

The same for all these "GCC_*" bugs...
</blockquote></details>

Don't we?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKZgWYL2CexEo4kR8Vi:b-gzalzm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, this should not be needed. Can you check what is the compiler error of this CHECK_CXX_SOURCE_COMPILES without valgrind includes? I think the logs are saved to some file.
</blockquote></details>

here's whole log from CMakeError.log:
```
Run Build Command(s):/usr/bin/make cmTC_58c6b/fast && /usr/bin/make -f CMakeFiles/cmTC_58c6b.dir/build.make CMakeFiles/cmTC_58c6b.dir/build
make[1]: Entering directory '/home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_58c6b.dir/src.cxx.o
/usr/bin/c++   -I/home/luke/repos/luke/libpmemobj-cpp/include -I/home/luke/installed/pmdk-1.9+/include  -DLIBPMEMOBJ_CPP_VG_MEMCHECK_ENABLED=1 -DLIBPMEMOBJ_CPP_VG_DRD_ENABLED=1 -DLIBPMEMOBJ_CPP_VG_HELGRIND_ENABLED=1 -DLIBPMEMOBJ_CPP_VG_PMEMCHECK_ENABLED=1 -Werror -DNO_CLANG_TEMPLATE_BUG --std=c++11 -Wno-error -c   -o CMakeFiles/cmTC_58c6b.dir/src.cxx.o -c /home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp/src.cxx
In file included from /home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/persistent_ptr.hpp:17,
                 from /home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/detail/check_persistent_ptr_array.hpp:14,
                 from /home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/make_persistent_array.hpp:16,
                 from /home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp/src.cxx:1:
/home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/detail/common.hpp:49:10: fatal error: valgrind.h: No such file or directory
   49 | #include <valgrind.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_58c6b.dir/build.make:66: CMakeFiles/cmTC_58c6b.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_58c6b/fast] Error 2


Source file was:
#include <libpmemobj++/make_persistent_array.hpp>
                using namespace pmem::obj;
                int main() {
                        delete_persistent<int[][3]>(make_persistent<int[][3]>(2), 2);
                        return 0;
                }
```
___
*[tests/CMakeLists.txt, line 231 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKd7ew0w2Ta3wie0Uv:-MKZgilI4wXpzSO5CihR:b-66fjvt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/tests/CMakeLists.txt#L231)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Don't we?
</blockquote></details>

hm.. I never saw any checks for compiler, but actually... this variable just won't be set in current build if we use the *other* compiler, I guess. I'll double check it yet, but I guess it's ok.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKZnH8--sMkP__AB6oT:b-68yib6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

here's whole log from CMakeError.log:
```
Run Build Command(s):/usr/bin/make cmTC_58c6b/fast && /usr/bin/make -f CMakeFiles/cmTC_58c6b.dir/build.make CMakeFiles/cmTC_58c6b.dir/build
make[1]: Entering directory '/home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_58c6b.dir/src.cxx.o
/usr/bin/c++   -I/home/luke/repos/luke/libpmemobj-cpp/include -I/home/luke/installed/pmdk-1.9+/include  -DLIBPMEMOBJ_CPP_VG_MEMCHECK_ENABLED=1 -DLIBPMEMOBJ_CPP_VG_DRD_ENABLED=1 -DLIBPMEMOBJ_CPP_VG_HELGRIND_ENABLED=1 -DLIBPMEMOBJ_CPP_VG_PMEMCHECK_ENABLED=1 -Werror -DNO_CLANG_TEMPLATE_BUG --std=c++11 -Wno-error -c   -o CMakeFiles/cmTC_58c6b.dir/src.cxx.o -c /home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp/src.cxx
In file included from /home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/persistent_ptr.hpp:17,
                 from /home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/detail/check_persistent_ptr_array.hpp:14,
                 from /home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/make_persistent_array.hpp:16,
                 from /home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp/src.cxx:1:
/home/luke/repos/luke/libpmemobj-cpp/include/libpmemobj++/detail/common.hpp:49:10: fatal error: valgrind.h: No such file or directory
   49 | #include <valgrind.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_58c6b.dir/build.make:66: CMakeFiles/cmTC_58c6b.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/luke/repos/luke/libpmemobj-cpp/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_58c6b/fast] Error 2


Source file was:
#include <libpmemobj++/make_persistent_array.hpp>
                using namespace pmem::obj;
                int main() {
                        delete_persistent<int[][3]>(make_persistent<int[][3]>(2), 2);
                        return 0;
                }
```
</blockquote></details>

Hm, there should be no: -DLIBPMEMOBJ_CPP_VG_MEMCHECK_ENABLED=1 ... in this log. I don't know why it's there since CMAKE_REQUIRED_FLAGS is set correctly though...
___
*[tests/CMakeLists.txt, line 231 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKd7ew0w2Ta3wie0Uv:-MKZmvJA581UF19xi564:b1nlet7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/tests/CMakeLists.txt#L231)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hm.. I never saw any checks for compiler, but actually... this variable just won't be set in current build if we use the *other* compiler, I guess. I'll double check it yet, but I guess it's ok.
</blockquote></details>

Yeah, I think it should work that way, I'd say that CLANG_TEMPLATE_BUG just hints that the bug is known to exist in clang but may as well be present in other compilers.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MK_BU-eAH5kAFlOvGis:b-flzouq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, there should be no: -DLIBPMEMOBJ_CPP_VG_MEMCHECK_ENABLED=1 ... in this log. I don't know why it's there since CMAKE_REQUIRED_FLAGS is set correctly though...
</blockquote></details>

actually it's kind of funny, cmake_required_flags and cmake_required_includes are empty on entering this file. I've changed and fixed just this one check, but I guess I'll double check the rest of these checks here, with my future cmake fixes.

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKdhJ56DpeEepdiH71N:bhxvycn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually it's kind of funny, cmake_required_flags and cmake_required_includes are empty on entering this file. I've changed and fixed just this one check, but I guess I'll double check the rest of these checks here, with my future cmake fixes.
</blockquote></details>

Maybe you could move this at the beggining - so that all source_compiles use only what's in REQUIRED_FLAGS?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @KFilipek, @lukaszstolarczuk, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKdhTFK8CLhfukSMwQ4:bpbgck3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe you could move this at the beggining - so that all source_compiles use only what's in REQUIRED_FLAGS?
</blockquote></details>

I mean setting CMAKE_CXX_FLAGS to ""

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @szyrom)

___
*[cmake/check_compiling_issues.cmake, line 91 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-MKKc_Cr249yicpg_9yE:-MKehKNl1ft0S96WNFaQ:b-27m9jm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/035296b5f124d414013697a38a50487e56927311/cmake/check_compiling_issues.cmake#L91)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I mean setting CMAKE_CXX_FLAGS to ""
</blockquote></details>

Done \+ minor cleanups in other checks, as well.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r7, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/905#-:-MKioZLH-spp7Qx5eG2w:bnfp4nl)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @szyrom)

**Pull request merged**
