### PR TITLE
transaction: remove unnecessary return

### PR DESCRIPTION
**Pull request by igchor**
Reported by coverity

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/transaction.hpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019#-MSXqzNt20yv8Y25DOgU:-MSXqzNt20yv8Y25DOgV:bb6ht36) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4c4309febd64a1c65485f1655d50c1d8dcac7eed/include/libpmemobj++/transaction.hpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2016-2020, Intel Corporation */
> ```

2021

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/transaction.hpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019#-MSXqzNt20yv8Y25DOgU:-MSY8K6u2fNuQWAiCxPW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4c4309febd64a1c65485f1655d50c1d8dcac7eed/include/libpmemobj++/transaction.hpp#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019#-:-MSYBR2j2dT1olLBc_ii:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1019#-:-MSc6uuqDlpyWOI-xUr7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
