### PR TITLE
Fix windows warnings and enable WX

### PR DESCRIPTION
**Pull request by igchor**
Closes https://github.com/pmem/libpmemobj-cpp/issues/409

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857#-MGnTIXL3v28BLCZ0_Rp:-MGnTIXM0sMzL9zPCdFP:bj7svfb) (no related file):*
re-base it to stable-1.9..? at least defrag fix

---

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857#-MGnTIXL3v28BLCZ0_Rp:-MGraRQC-Uf3NGhg3TMb:b6mlon0) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

re-base it to stable-1.9..? at least defrag fix
</blockquote></details>

Done. https://github.com/pmem/libpmemobj-cpp/pull/860

This PR will fail for now, so let's merge the PR I linked first.

---

**Review by szyrom — APPROVED** [review]
> Reviewed 3 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/857#-:-MI3ygXoDxVQc2B8RKR2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
