### PR TITLE
Add example for usage cmap with pmem string

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 75 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2Bm33eaTZ8S398qD:-MQD2Bm33eaTZ8S398qE:bh3o6fy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L75)):*
> ```cpp
> 			 * function in order to recalculate mask and check for
> 			 * consistency. */
> ```

remove empty line
___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 98 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2IzC8ntQTTdZ2veT:-MQD2IzC8ntQTTdZ2veU:bm3s0g8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L98)):*
> ```cpp
> 		for (int i = 0; i < THREADS_NUM / 3; ++i) {
> 			threads.emplace_back([&]() {
> 				for (int i = 0; i < 10 * THREADS_NUM; ++i) {
> ```

I'm not sure that duplication of i variable is your intention.
Please make another variable name for nested for-loop.
___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 195 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2frM4KO_QkZJmvzE:-MQD2frM4KO_QkZJmvzF:bjkcdu2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L195)):*
> ```cpp
> 			});
> 		}
> 		pop.close();
> ```

remove this pop.close();
___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 198 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2kJC-rxYL0LdCcP3:-MQD2kJC-rxYL0LdCcP4:b-yvlz3n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L198)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 		try {
> 			pop.close();
> 		} catch (const std::logic_error &e) {
> 			std::cerr << "Exception: " << e.what() << std::endl;
> 		}
> ```
</details>

move it outside catch(){}

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 75 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2Bm33eaTZ8S398qD:-MQD6oZz2DfpGptLpTT-:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 98 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2IzC8ntQTTdZ2veT:-MQD9xlmETLlp9LLV3Ts:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L98)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I'm not sure that duplication of i variable is your intention.
Please make another variable name for nested for-loop.
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex)

___
*[examples/concurrent_hash_map/CMakeLists.txt, line 28 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDCR9A1tEVIrdc2ZOk:-MQDCR9A1tEVIrdc2ZOl:b-7x7qia) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/CMakeLists.txt#L28)):*
> ```CMake
> target_link_libraries(concurrent_hash_map ${LIBPMEMOBJ++_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
> 
> add_executable(concurrent_hash_map_string concurrent_hash_map_string.cpp)
> ```

please add this new example also in `examples/CMakeLists.txt` (this file is just for standalone example compilation)
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 5 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDCflw-nYcU7nU6PsH:-MQDCflw-nYcU7nU6PsI:b-xyty80) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L5)):*
> ```cpp
> 
> /*
>  * concurrent_hash_map_string.cpp -- C++ documentation snippets.
> ```

you can update this description a bit, I believe
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 8 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDCj6XEL73n_iWKVo0:-MQDCj6XEL73n_iWKVo1:bzfj3zt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L8)):*
> ```cpp
>  */
> 
> //! [concurrent_hash_map_string_ex]
> ```

you can use this snippet in the hashmap description doxygen comment
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 35 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDD9Ij91tIUUSfQgv1:-MQDD9Ij91tIUUSfQgv2:bufoa8p) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L35)):*
> ```cpp
> 
> /* Before running this example, run:
>  * pmempool create obj --layout="concurrent_hash_map_string" --size 1G
> ```

you can shorten the layout so this whole command will fit in one line (so the pool path is not in the line below)
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 146 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDDWwK3VmEqtaFLnUX:-MQDDWwK3VmEqtaFLnUY:bfg4zzv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L146)):*
> ```cpp
> 			throw;
> 		} catch (const pmem::lock_error &e) {
> 			std::cerr << "Defragmentation exception: " << e.what()
> ```

update these exceptions descriptions pls

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 198 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2kJC-rxYL0LdCcP3:-MQH-gL-8ibTEoSMRdNz:budyk4y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L198)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 		try {
> 			pop.close();
> 		} catch (const std::logic_error &e) {
> 			std::cerr << "Exception: " << e.what() << std::endl;
> 		}
> ```
move it outside catch(){}
</blockquote></details>

Current code is probably more readable then this: 

```c++
	} catch (std::exception &e) {
		std::cerr << "Exception occured: " << e.what() << std::endl;
		retval = -1;
	}
	try {
		pop.close();
	} catch (const std::logic_error &e) {
		std::cerr << "Exception: " << e.what() << std::endl;
		retval = -2;
	}

	return retval;
```

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 198 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2kJC-rxYL0LdCcP3:-MQHEz7-2OhD5Q4DGYxS:b3t2brc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L198)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Current code is probably more readable then this: 

```c++
	} catch (std::exception &e) {
		std::cerr << "Exception occured: " << e.what() << std::endl;
		retval = -1;
	}
	try {
		pop.close();
	} catch (const std::logic_error &e) {
		std::cerr << "Exception: " << e.what() << std::endl;
		retval = -2;
	}

	return retval;
```
</blockquote></details>

Notice that you will have then only one pop.close() in whole application at the end instead of nested try-catch block. Sometimes nested try-catch is unavoidable, but this time there is no reason to keep it inside and few lines above doing the same at the end of try block.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQH4cfQDZVX2PZ7tBRl:-MQH4cfQDZVX2PZ7tBRm:b-kuc22g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L18)):*
> ```cpp
> #include <vector>
> 
> /* In this example we will be using concurrent_hash_map with p<int> type for
> ```

simply `we use` instead of `we will be using`
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 100 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQHFhUt8jLK7AsjdY3l:-MQHFhUt8jLK7AsjdY3m:b-djyp2d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L100)):*
> ```cpp
> 		 * operation is thread-safe. */
> 		for (int i = 0; i < THREADS_NUM / 3; ++i) {
> 			std::string tmp_string = std::to_string(i);
> ```

you don't use `threads` in this loop and I believe you only put <0;threads_num/3) elements... and below you erase <0;threads_num*10) elements...
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 146 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDDWwK3VmEqtaFLnUX:-MQHG4mh1rNq7g2W6GE4:bjbkptd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L146)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update these exceptions descriptions pls
</blockquote></details>

I just saw we have the same descriptions in other example... so maybe leave it as is (but I must say, they are a little generic ;) )

**Comment by lukaszstolarczuk** [comment]
FYI, my fixes in the "original" example are here:
https://github.com/pmem/libpmemobj-cpp/pull/937/commits/be62f05a7f3b368f402c8a4034a884f69679c93a

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 11 unresolved discussions (waiting on @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 31 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqJOe95j6IxGmGq-2C:-MQqJOe95j6IxGmGq-2D:b9d0ysr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L31)):*
> ```cpp
>  * pointer to hasmap_type */
> struct root {
> 	pmem::obj::persistent_ptr<hashmap_type> pptr = nullptr;
> ```

Please do not initialize pptr to anything. It can be a bit misleading since it have no effect - root is always zeroed by the pmdk on first call to pmemobj_root().
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 103 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqK7mqCTvPMs3hG6dB:-MQqK7mqCTvPMs3hG6dC:b-xmvh65) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L103)):*
> ```cpp
> 			/* Implicit conversion from std::string to
> 			 * pmem::obj::string. */
> 			map.insert_or_assign(i, tmp_string);
> ```

Hm, I was thinking if we could show how to insert an element only if there is no entry with specified key but it seems it's not possible right now... I think we should probably add try_emplace function to hashmap
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 116 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqKfrZ14UTgK7ZVbrQ:-MQqKfrZ14UTgK7ZVbrR:b8kds4y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L116)):*
> ```cpp
> 					if (res) {
> 						assert(acc->first == i);
> 						const pmem::obj::string
> ```

why? can't you just write `std::cout << acc->second.c_str()`?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor and @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 116 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqKfrZ14UTgK7ZVbrQ:-MQuiCy6AptUJEmu_Q_e:b9d9ai) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L116)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why? can't you just write `std::cout << acc->second.c_str()`?
</blockquote></details>

Yes, I could just use `std::cout << acc->second.c_str()`, on the other hand I want to show, the user may create and use such pointer, and also show what is type of it. Maybe I should add some comment. 
In general, I think, we should (at least sometimes) use explicit types instead of auto in examples - just to show what is type of object.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 11 unresolved discussions (waiting on @igchor and @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 116 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqKfrZ14UTgK7ZVbrQ:-MQuu_vb-2zeQ4_IsMyx:b-p6c9ts) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L116)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Yes, I could just use `std::cout << acc->second.c_str()`, on the other hand I want to show, the user may create and use such pointer, and also show what is type of it. Maybe I should add some comment. 
In general, I think, we should (at least sometimes) use explicit types instead of auto in examples - just to show what is type of object. 
</blockquote></details>

\+1 for add a comment

and I believe I agree, we could use less `auto` (in some non-obvious cases) in examples

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 103 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqK7mqCTvPMs3hG6dB:-MSgXrkB9X-nw7WmjM8_:bcuavp0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L103)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I was thinking if we could show how to insert an element only if there is no entry with specified key but it seems it's not possible right now... I think we should probably add try_emplace function to hashmap
</blockquote></details>

maybe we should file an issue for this...?
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 21 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSgScxRB7PJGTNC_NdC:-MSgScxS9yzMF_dELGJq:b-raam8s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L21)):*
> ```cpp
> /* In this example we use concurrent_hash_map with p<int> type as
>  * keys and pmem::obj::string type for values. It shows, there is no need to
>  * explicitely use transacions if strings are stored in concurrent_hash_map. */
> ```

`explicitly`
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSgSleW4-YcClFBNC5S:-MSgSleW4-YcClFBNC5T:b-kdzhse) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L28)):*
> ```cpp
> const int THREADS_NUM = 30;
> 
> /* In this example and we only need place concurrent_hash_map in the pool. Hence
> ```

`and we only` there's something wrong with this sentence...(?)
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 122 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSgVhD88_KttTAK7YeS:-MSgVhD88_KttTAK7YeT:b-5n0bqv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L122)):*
> ```cpp
> 				for (int i = 0; i < 10 * THREADS_NUM; ++i) {
> 					/* Usage of const_accessor, indicates
> 					 * read-only access*/
> ```

please add a space after `access`

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @karczex)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 107 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSg_7lD-X7wbNqz_OSa:-MSg_7lE2EgyAKJOrqNk:b-u9kkqu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L107)):*
> ```
> std::to_string(i);
> ```
why not pass it directly to the function?
It will looks still obvious.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/concurrent_hash_map/CMakeLists.txt, line 28 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDCR9A1tEVIrdc2ZOk:-MScXWhK1_UASQD_OcNM:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/CMakeLists.txt#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add this new example also in `examples/CMakeLists.txt` (this file is just for standalone example compilation)
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp, line 195 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQD2frM4KO_QkZJmvzE:-MSgcUzS0RVlI4Hejdyg:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/32eb1cd88cdee77012d416ff966f4f5e9d0797bb/examples/concurrent_hash_map/concurrent_hash_map_complex_types.cpp#L195)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

remove this pop.close();
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 5 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDCflw-nYcU7nU6PsH:-MScRlSA-3_SeeVkwOXZ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can update this description a bit, I believe
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 8 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDCj6XEL73n_iWKVo0:-MScRmRY4a35AqbVNAqf:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can use this snippet in the hashmap description doxygen comment
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQH4cfQDZVX2PZ7tBRl:-MScRn4zEX1F5tvKEmuF:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

simply `we use` instead of `we will be using`
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 31 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqJOe95j6IxGmGq-2C:-MScRnva-q4TUWwVz4gm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L31)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please do not initialize pptr to anything. It can be a bit misleading since it have no effect - root is always zeroed by the pmdk on first call to pmemobj_root().
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 35 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDD9Ij91tIUUSfQgv1:-MScRqYF2eayCi283rj6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can shorten the layout so this whole command will fit in one line (so the pool path is not in the line below)
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 116 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqKfrZ14UTgK7ZVbrQ:-MScRtLH8cjGYKfz7mT7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L116)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+1 for add a comment

and I believe I agree, we could use less `auto` (in some non-obvious cases) in examples
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 146 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQDDWwK3VmEqtaFLnUX:-MScXio-9tHS2g1P7iXx:b-6hjp2c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L146)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I just saw we have the same descriptions in other example... so maybe leave it as is (but I must say, they are a little generic ;) )
</blockquote></details>

I agree it's little generic, I left it as is :) 
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 21 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSgScxRB7PJGTNC_NdC:-MSgvrgp0X-eiOHBvK2E:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`explicitly`
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 28 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSgSleW4-YcClFBNC5S:-MSgwXlE2n6Q6D5k3OJ8:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L28)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`and we only` there's something wrong with this sentence...(?)
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 107 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSg_7lD-X7wbNqz_OSa:-MSgwZN68877-slzWmqS:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L107)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> std::to_string(i);
> ```
why not pass it directly to the function?
It will looks still obvious.
</blockquote></details>

Done.
___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 122 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MSgVhD88_KttTAK7YeS:-MSgwdwX-m9yoUnCExI3:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/efa275b047c447a4f28284d244a93f66d5cc5e1b/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L122)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please add a space after `access`
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[examples/concurrent_hash_map/concurrent_hash_map_string.cpp, line 103 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-MQqK7mqCTvPMs3hG6dB:-MSh2zMz0sUeurVRCtFe:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8241dd0ba35447559e02a5353612a1b0df92e1b6/examples/concurrent_hash_map/concurrent_hash_map_string.cpp#L103)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe we should file an issue for this...?
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-:-MShBINQ3R5GKEMWeix2:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1002#-:-MShR9JG2RKYPyX7s_1N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
