### PR TITLE
[gh-pages] update index.md with latest patch releases

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] finish up with all planned patch releases

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[index.md, line 54 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107#-Mdv3x2_6dd7VkYfPNu2:-Mdv3x2_6dd7VkYfPNu3:bgrtmfy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/87623c484be8a710ab8b4eb0dab2e1c53c538fd6/index.md#L54)):*
> ```Markdown
> | stable-1.10 | May 28, 2020 | N/A | Full |
> | stable-1.9 | Jan 31, 2020 | N/A | Full |
> | stable-1.8 | Oct 3, 2019 | N/A | Limited |
> ```

It's not EOL? This change is just so that we can do path releases?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[index.md, line 54 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107#-Mdv3x2_6dd7VkYfPNu2:-Mdv6RLA-P0w7gka0Gle:b-pmvugi) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/87623c484be8a710ab8b4eb0dab2e1c53c538fd6/index.md#L54)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It's not EOL? This change is just so that we can do path releases?
</blockquote></details>

I've marked 1.7 and 1.8 as `Limited` since we only plan to do just one more release. And since we don't do that right now, I want to update the gh-pages (with the current state) and when we're ready with more releases we then update it once more (tbh, we don't know where this going to happen :smile: )

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107#-:-Mdv9rQl5nW8r68EgNax:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107#-:-MdvBxgd5jn3hRBtt0Bx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
