### PR TITLE
string_view: add relational operators for string_view class

### PR DESCRIPTION
**Pull request by KFilipek**
- add missing relational operators for string_view

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
It would be nice to have some tests for that

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-:-MIZFgnBBq4j_AW1RrY1:byp82qd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by KFilipek** [comment]
@igchor I started porting string_view tests from LIBCXX (operators)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[include/libpmemobj++/string_view.hpp, line 81 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MItBDxE7aDhtvZ6wGmk:-MIx3Sy47IUDX7piV0SH:bs7wumx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/df2624d79587dc03bc922af83e86fe02f8bef0ba/include/libpmemobj++/string_view.hpp#L81)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Shouldn't this be sv instead of _sv? Anyway, do we need it (do we test it anywhere)?
</blockquote></details>

Done. 
___
*[include/libpmemobj++/string_view.hpp, line 214 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MItD3N-94oQtPMf8rAW:-MIx3YvaAkkzvOZrz_4V:b-ucfknh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/df2624d79587dc03bc922af83e86fe02f8bef0ba/include/libpmemobj++/string_view.hpp#L214)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

FYI, https://stackoverflow.com/questions/25245453/what-is-a-nondeduced-context/25245676#25245676
</blockquote></details>

Thanks!

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 17 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 17 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 4 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 197 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxuJ0CatMQN2iGPYP:-MIxxuJ0CatMQN2iGPYQ:bcp5k0q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L197)):*
> ```cpp
> template <class CharT, class Traits>
> static bool
> operator==(basic_string_view<CharT, Traits> lhs,
> ```

Do we still need this function when we have the ones with std::common-type?
___
*[include/libpmemobj++/string_view.hpp, line 206 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxdoS567rKpu8tSaT:-MIxxdoS567rKpu8tSaU:ba00sq4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L206)):*
> ```cpp
> 
> template <class CharT, class Traits>
> static bool
> ```

Why static? I don't think it makes any difference for template functions
___
*[include/libpmemobj++/string_view.hpp, line 218 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxyT1JAhuWCLGBXN6n:-MIxyT1JAhuWCLGBXN6o:b-7uf7rw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L218)):*
> ```cpp
> template <class CharT, class Traits>
> static bool
> operator==(
> ```

I believe you should now be able to remove all the comparison functions from pmem::obj::string, right?
___
*[tests/external/libcxx/string.view/string.view.comparison/opge.string_view.pointer.pass.cpp, line 34 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxyId627XX0FM7OnmR:-MIxyId627XX0FM7OnmS:b-2h380x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/tests/external/libcxx/string.view/string.view.comparison/opge.string_view.pointer.pass.cpp#L34)):*
> ```cpp
> {
> 	{
> 		typedef pmem::obj::string_view S;
> ```

Could you maybe add at least one test for basic_string_view for some other char type?

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIy4_VG3CBIVMRR0oL2:-MIy4_VG3CBIVMRR0oL3:b4q2q5k) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp#L7)):*
> ```cpp
> // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
> //
> //===----------------------------------------------------------------------===//
> ```

\+ intel licenses

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIy4_VG3CBIVMRR0oL2:-MIy5yD0AWZinGguCfM6:bgxa5mg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ intel licenses
</blockquote></details>

Also, would be good to import and modify the tests in separate commits.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: 2 of 20 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 197 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxuJ0CatMQN2iGPYP:-MIyBj9_1pFCJ9SuuqS4:b-qtt2ex) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Do we still need this function when we have the ones with std::common-type?
</blockquote></details>

Yes, because of: opeq.string_view.string_view.pass.cpp
Here are the cases for this overload.
This "common_type" stuff with all overloads is a 1:1 port from LIBCXX.
___
*[include/libpmemobj++/string_view.hpp, line 206 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxdoS567rKpu8tSaT:-MIyBsTS6hHr30Q9K6bQ:bxe69nj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L206)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why static? I don't think it makes any difference for template functions
</blockquote></details>

I have the same way of thinking, but Microsoft compiler has own version of reality (vide errors with mangling).
___
*[include/libpmemobj++/string_view.hpp, line 218 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxyT1JAhuWCLGBXN6n:-MIyCZWY99jMzM6CbayA:b3k9pio) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L218)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I believe you should now be able to remove all the comparison functions from pmem::obj::string, right?
</blockquote></details>

No, string header has own overloads for relational operators, I believe we should be align with this API.
___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIy4_VG3CBIVMRR0oL2:-MIyMXMWDjviKvz12NAY:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp#L7)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also, would be good to import and modify the tests in separate commits.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.comparison/opge.string_view.pointer.pass.cpp, line 34 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxyId627XX0FM7OnmR:-MIyMc3rA8kfYFF1o5KM:bb74ce2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/tests/external/libcxx/string.view/string.view.comparison/opge.string_view.pointer.pass.cpp#L34)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you maybe add at least one test for basic_string_view for some other char type?
</blockquote></details>

Sure

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: 4 of 20 files reviewed, 2 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 206 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxdoS567rKpu8tSaT:-MIyWI2x3kV3-Tlhfc75:b-aq6m5y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L206)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I have the same way of thinking, but Microsoft compiler has own version of reality (vide errors with mangling).
</blockquote></details>

Right, but I thought it would be enough to just mark each function (test and run_test) inside tests as static. Is it not enough?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: 4 of 20 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp, line 30 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIyYp04AY2wWb3tzzru:-MIyYp04AY2wWb3tzzrv:b-xzrhod) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77a1f79b83059207f184dfbb4fed8fcbce48b797/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp#L30)):*
> ```cpp
> template <class S>
> void
> test(const std::basic_string<typename S::value_type> &lhs, S rhs, bool x)
> ```

Hm, we should probably test comparion between pmem::obj::string and string_view (unless we already have such test somewhere)?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: 3 of 20 files reviewed, 4 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp, line 29 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJ1M7zQ4-yxh0070V7s:-MJ1M7zQ4-yxh0070V7t:b-ac4n6t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/669b7278eed2a374f63ae998c63403ca93c6875c/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp#L29)):*
> ```cpp
> #include <libpmemobj++/container/basic_string.hpp>
> template <class S,
> 	  class P = typename pmem::obj::basic_string<typename S::value_type>>
> ```

To make this work you would also have to allocate the pmem obj string on pmem, right?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 13 of 18 files at r6, 1 of 3 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 206 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxdoS567rKpu8tSaT:-MJ27pwYEKT_nLFQSikx:bkquyy7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L206)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, but I thought it would be enough to just mark each function (test and run_test) inside tests as static. Is it not enough?
</blockquote></details>

I will check this and I will comment here what is the result.
___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp, line 30 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIyYp04AY2wWb3tzzru:-MJ27bmF5fQnZRhWTC5P:b-abyt3r) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/77a1f79b83059207f184dfbb4fed8fcbce48b797/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp#L30)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, we should probably test comparion between pmem::obj::string and string_view (unless we already have such test somewhere)?
</blockquote></details>

As I mentioned above, I will introduce this functionality separately
___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp, line 29 at r7](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJ1M7zQ4-yxh0070V7s:-MJ27LGS4kbSW_iRBpj1:bvsthgs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/669b7278eed2a374f63ae998c63403ca93c6875c/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.string.pass.cpp#L29)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

To make this work you would also have to allocate the pmem obj string on pmem, right?
</blockquote></details>

As we talk, I will split it into another PR. This PR will be only port from libcxx to pmem::obj::string_view without additional modifications.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 206 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIxxdoS567rKpu8tSaT:-MJQjPrlDjcu5oni0Dm4:bmetdat) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/include/libpmemobj++/string_view.hpp#L206)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I will check this and I will comment here what is the result.
</blockquote></details>

Done. Constexpr was necessary by C++ API, I removed static keyword from operator definitions.

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r8, 2 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 203 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJQtZ5TAqiWWGHf2PJn:-MJQtZ5UCzUyCWso-DNq:bk0l8rt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b/include/libpmemobj++/string_view.hpp#L203)):*
> ```cpp
> }
> 
> template <class CharT, class Traits>
> ```

missing comment (here and below)
___
*[tests/CMakeLists.txt, line 38 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJQwLjFBtrpFdsWEpiC:-MJQwLjFBtrpFdsWEpiD:b-tjyalg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b/tests/CMakeLists.txt#L38)):*
> ```CMake
> 	add_flag("-D_FORTIFY_SOURCE=2" RELEASE)
> 
> 	# ommit function name ambiguity under MSVC++ compiler
> ```

`omit`
___
*[tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp, line 7 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MIy4_VG3CBIVMRR0oL2:-MJQxVoc90cRGzblqu0z:b9q0cwo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/179519ff5885e1712ac8a8b811e8674cf17977e8/tests/external/libcxx/string.view/string.view.comparison/opeq.string_view.pointer.pass.cpp#L7)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no need to change this for now, I guess, but what Igor meant is that you simply import tests with no modification in one commit and in sep. one you enable them for testing (in CMake) and update them with pmemobj stuff ;) Right now they are imported already with pmemobj stuff in commit b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b (but as I said, I don't think you have to do it now, it may be tedious work now)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek)

___
*[tests/CMakeLists.txt, line 39 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJR4IIe84TOsXNbm7QK:-MJR4IIf4s30pavEKFZv:b-3lz0ih) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b/tests/CMakeLists.txt#L39)):*
> ```CMake
> 
> 	# ommit function name ambiguity under MSVC++ compiler
> 	if(MSVC_VERSION GREATER_EQUAL 1920)
> ```

And what if we're running on older msvc? I guess the comparison operator tests should be disabled then.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 203 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJQtZ5TAqiWWGHf2PJn:-MJRUfhY0Xh_sn1aWBzI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b/include/libpmemobj++/string_view.hpp#L203)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

missing comment (here and below)
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 38 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJQwLjFBtrpFdsWEpiC:-MJRTrLQ6E_r4XTdCTgk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b/tests/CMakeLists.txt#L38)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`omit`
</blockquote></details>

Done.
___
*[tests/CMakeLists.txt, line 39 at r9](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJR4IIe84TOsXNbm7QK:-MJRTrmoCTmh6KcKeojK:b-lxrkhz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b70ac7d0f7fb33f4ecc6d24f80714eb4bbb3800b/tests/CMakeLists.txt#L39)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

And what if we're running on older msvc? I guess the comparison operator tests should be disabled then.
</blockquote></details>

Done. I've disabled this tests too under older MSVC++ compiler.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 201 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJRVKoC2mIGPp4Ol1Q7:-MJRVKoC2mIGPp4Ol1Q8:b-8pnzqc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3afe5d77c4a8530b8db4413bc1d33a9e0a982a44/include/libpmemobj++/string_view.hpp#L201)):*
> ```cpp
> {
> 	if (lhs.size() != rhs.size())
> 		return false;
> ```

why did you remove this check?
___
*[include/libpmemobj++/string_view.hpp, line 211 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJRVNXI-FgZmX4bYG4n:-MJRVNXI-FgZmX4bYG4o:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3afe5d77c4a8530b8db4413bc1d33a9e0a982a44/include/libpmemobj++/string_view.hpp#L211)):*
> ```cpp
> 	typename std::common_type<basic_string_view<CharT, Traits>>::type rhs)
> {
> 	if (lhs.size() != rhs.size())
> ```

.
___
*[include/libpmemobj++/string_view.hpp, line 222 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJRVNtB0mjv5PwWKOME:-MJRVNtB0mjv5PwWKOMF:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3afe5d77c4a8530b8db4413bc1d33a9e0a982a44/include/libpmemobj++/string_view.hpp#L222)):*
> ```cpp
> 	basic_string_view<CharT, Traits> rhs)
> {
> 	if (lhs.size() != rhs.size())
> ```

.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 201 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-MJRVKoC2mIGPp4Ol1Q7:-MJRY3_Y7oSplSUIxt03:bbus5p1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3afe5d77c4a8530b8db4413bc1d33a9e0a982a44/include/libpmemobj++/string_view.hpp#L201)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why did you remove this check?
</blockquote></details>

AFAIK there was a problem with few return in a constexpr function (C++14 enhancement), but I pushed changes on CI to check this.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-:-MJRm_XAAmoCRxfk3V41:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 18 files at r6, 2 of 3 files at r8, 3 of 5 files at r9, 2 of 3 files at r10, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/913#-:-MJT33tZ7UDkw7gaMC0p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
