### PR TITLE
string_view: move find API implementation from string

### PR DESCRIPTION
**Pull request by KFilipek**
- string_view: implement find API
- basic_string: use string_view find API instead of own implementation

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 112 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhH9Qd6I0AFn6Zd-ro:-MLhH9Qd6I0AFn6Zd-rp:bp78jnd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L112)):*
> ```cpp
> 	int compare(const basic_string_view &other) const noexcept;
> 
> 	size_type find(const basic_string_view &str, size_type pos = 0) const
> ```

It would be better to just pass basic_string_view by value rather than by const reference (as in std). It allows for better optimizations.

The same for all other functions taking const ref

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970)* status: all files reviewed, 17 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 449 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLgnRl-3xLfeUxSffMO:-MLgnRl-3xLfeUxSffMP:bxitv3y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L449)):*
> ```cpp
> 
> /*
>  * Finds the first substring equal str.
> ```

`equal to`
___
*[include/libpmemobj++/string_view.hpp, line 542 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh7Qxr9d8tg6peD1-5:-MLh7Qxr9d8tg6peD1-6:b-289pnk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L542)):*
> ```cpp
>  * @param[in] pos position where the search starts from
>  *
>  * @return Position (as an offset from start of the string) of the first
> ```

`from the start` fix all occurrences 
___
*[include/libpmemobj++/string_view.hpp, line 566 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh1RLS9EXaOxMzJ7A2:-MLh1RLS9EXaOxMzJ7A3:bhf5v0a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L566)):*
> ```cpp
>  * @return Position (as an offset from start of the string) of the first
>  * character of the found substring or npos if no such substring is found. If
>  * searching for an empty string retrurn pos, if also pos is greater than the
> ```

`retrurn` -> `return`
___
*[include/libpmemobj++/string_view.hpp, line 567 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh49wY97F4KXT9FTp3:-MLh49wZ5PIN9V6QUri0:b9m8qnq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L567)):*
> ```cpp
>  * character of the found substring or npos if no such substring is found. If
>  * searching for an empty string retrurn pos, if also pos is greater than the
>  * size of the string - it returns size
> ```

are you sure it returns `size`? not `size - count`?
___
*[include/libpmemobj++/string_view.hpp, line 586 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh7CIa2PPV11-Avp5K:-MLh7CIa2PPV11-Avp5L:b77suzy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L586)):*
> ```cpp
> /**
>  * Finds the last substring equal to the C-style string pointed to by s.
>  * The length of the string is determined by the first null character
> ```

add `.` at the end of line
___
*[include/libpmemobj++/string_view.hpp, line 627 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh7vYqEV1fcPygG_nF:-MLh7vYqEV1fcPygG_nG:b673jfx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L627)):*
> ```cpp
>  * @param[in] pos position where the search starts from
>  *
>  * @return Position of the found character or npos if no such character is
> ```

perhaps better: `or npos if none of characters are found.` (?)
___
*[include/libpmemobj++/string_view.hpp, line 627 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh8xhN9XHWUtvKpSsn:-MLh8xhN9XHWUtvKpSso:b-qym3zt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L627)):*
> ```cpp
>  * @param[in] pos position where the search starts from
>  *
>  * @return Position of the found character or npos if no such character is
> ```

`of the first found character`, I believe
___
*[include/libpmemobj++/string_view.hpp, line 643 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh87-WCCNiAr4OYUHQ:-MLh87-WCCNiAr4OYUHR:b-pj01zj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L643)):*
> ```cpp
>  *
>  * @param[in] s pointer to the C-style string identifying characters to search
>  *for
> ```

add some whitespace before `for`
___
*[include/libpmemobj++/string_view.hpp, line 644 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBvMt4kxF-Wj6VBlf:-MLhBvMt4kxF-Wj6VBlg:b-evmics) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L644)):*
> ```cpp
>  * @param[in] s pointer to the C-style string identifying characters to search
>  *for
>  * @param[in] pos position at which to begin searching
> ```

perhaps, if possible, make this description the same in all functions, instead `position at which to begin searching` write everywhere `position where the search starts from` or the other way around
___
*[include/libpmemobj++/string_view.hpp, line 646 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh8E790Ygf7kti-Nh9:-MLh8E790Ygf7kti-NhA:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L646)):*
> ```cpp
>  * @param[in] pos position at which to begin searching
>  * @param[in] count length of the C-style string identifying characters to
>  *search for
> ```

.
___
*[include/libpmemobj++/string_view.hpp, line 708 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBQKQ-f0UddEmtP0W:-MLhBQKQ-f0UddEmtP0X:bykb99q) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L708)):*
> ```cpp
>  * @param[in] pos position where the search starts from
>  *
>  * @return Position of the found character or npos if no such character is
> ```

make it more precise, e.g. `Position of the first character not equal to any of characters in str or ...`
___
*[include/libpmemobj++/string_view.hpp, line 727 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBhr8D4TvwxUxoUcI:-MLhBhr8D4TvwxUxoUcJ:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L727)):*
> ```cpp
>  * @param[in] pos position at which to begin searching
>  * @param[in] count length of the C-style string identifying characters to
>  *search for
> ```

.
___
*[include/libpmemobj++/string_view.hpp, line 750 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhCKbeDVBcYWpHFpRx:-MLhCKbeDVBcYWpHFpRy:bdlnedf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L750)):*
> ```cpp
> /**
>  * Finds the first character equal to none of the characters in the C-style
>  *string pointed to by s. The length of the string is determined by the first
> ```

pls add whitespace at the beginning of the line
___
*[include/libpmemobj++/string_view.hpp, line 808 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhVPCx7GtzTsidNJ1L:-MLhVPCx7GtzTsidNJ1M:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L808)):*
> ```cpp
>  *
>  * @param[in] s pointer to the C-style string identifying characters to search
>  *for
> ```

.
___
*[include/libpmemobj++/string_view.hpp, line 811 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhVPxg7AUYH8MslLRp:-MLhVPxg7AUYH8MslLRq:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L811)):*
> ```cpp
>  * @param[in] pos position at which to begin searching
>  * @param[in] count length of the C-style string identifying characters to
>  *search for
> ```

.
___
*[include/libpmemobj++/string_view.hpp, line 925 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhW7h160_ne75xYIEk:-MLhW7h2EaTYSgNpZeYs:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L925)):*
> ```cpp
> /**
>  * Finds the last character equal to none of the characters in the C-style
>  *string pointed to by s. The length of the string is determined by the first
> ```

.

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970)* status: 1 of 2 files reviewed, 17 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 112 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhH9Qd6I0AFn6Zd-ro:-MMFUdj5Bg_0nqQmlu5s:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L112)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

It would be better to just pass basic_string_view by value rather than by const reference (as in std). It allows for better optimizations.

The same for all other functions taking const ref
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 449 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLgnRl-3xLfeUxSffMO:-MMFUxHw5P2rHkvnvlKA:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L449)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`equal to`
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 542 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh7Qxr9d8tg6peD1-5:-MMFVCAo-LD_BEgJPTrm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L542)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`from the start` fix all occurrences 
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 566 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh1RLS9EXaOxMzJ7A2:-MMFVINd8A9Ea2WM36fU:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L566)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`retrurn` -> `return`
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 567 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh49wY97F4KXT9FTp3:-MMFXcwq6BWOsZjw2zR7:b-ogevkb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L567)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you sure it returns `size`? not `size - count`?
</blockquote></details>

https://en.cppreference.com/w/cpp/string/basic_string/rfind
___
*[include/libpmemobj++/string_view.hpp, line 586 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh7CIa2PPV11-Avp5K:-MMFXlKF3ki1CrawuIJn:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L586)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add `.` at the end of line
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 627 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh7vYqEV1fcPygG_nF:-MMFYHgB8xL1WLqdEjUm:b-m1t3eg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L627)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps better: `or npos if none of characters are found.` (?)
</blockquote></details>

https://en.cppreference.com/w/cpp/string/basic_string_view/find_first_of
___
*[include/libpmemobj++/string_view.hpp, line 627 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh8xhN9XHWUtvKpSsn:-MMFYIYOCrckH_eC2SNX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L627)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`of the first found character`, I believe
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 643 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh87-WCCNiAr4OYUHQ:-MMFYvmaBC3DVxU0rjKW:b-7xww6x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L643)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add some whitespace before `for`
</blockquote></details>

I've found some others places.
Done.
___
*[include/libpmemobj++/string_view.hpp, line 644 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBvMt4kxF-Wj6VBlf:-MMFZKdi-9S6Aw-Ivleh:b-m1t3eg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L644)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps, if possible, make this description the same in all functions, instead `position at which to begin searching` write everywhere `position where the search starts from` or the other way around
</blockquote></details>

https://en.cppreference.com/w/cpp/string/basic_string_view/find_first_of
___
*[include/libpmemobj++/string_view.hpp, line 646 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh8E790Ygf7kti-Nh9:-MMFZ6ce04N0OqP0Oxux:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L646)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 708 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBQKQ-f0UddEmtP0W:-MMFZkLL7fxhs09kST7f:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L708)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make it more precise, e.g. `Position of the first character not equal to any of characters in str or ...`
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 727 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBhr8D4TvwxUxoUcI:-MMFawvFEBe8cm6667vZ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L727)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 808 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhVPCx7GtzTsidNJ1L:-MMFaxwJ11t9afHtAxAE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L808)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 811 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhVPxg7AUYH8MslLRp:-MMFayRz2HOrA_D2lt40:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L811)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 925 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhW7h160_ne75xYIEk:-MMFayto7Lv8wcWXH4Pd:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L925)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-:-MMFwLNoAyKsEVjHSPxD:bnfp4nl)* status: 1 of 2 files reviewed, 16 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 567 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLh49wY97F4KXT9FTp3:-MMG6wWW3kH9BaZ2P8aF:b-b0ayp0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L567)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://en.cppreference.com/w/cpp/string/basic_string/rfind
</blockquote></details>

ahaha, it does return `size - count`, but in this case `count = 0` (empty search) :smile: Sorry, I've looked at the code and didn't add it up.
___
*[include/libpmemobj++/string_view.hpp, line 644 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBvMt4kxF-Wj6VBlf:-MMGE5GDCryji-QqyZMM:by5laem) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L644)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

https://en.cppreference.com/w/cpp/string/basic_string_view/find_first_of
</blockquote></details>

That's great, I just wanted to have them unified for all instances, thanks!
___
*[include/libpmemobj++/string_view.hpp, line 708 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBQKQ-f0UddEmtP0W:-MMG7lea0EEe1Ia3T9tU:b-9qg1u4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L708)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 708 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-MLhBQKQ-f0UddEmtP0W:-MMKmz3b9E1Wlpidx11W:bkx05mv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0bf89c17072d01a23d323c604bdd707394e66b3c/include/libpmemobj++/string_view.hpp#L708)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

Copied from cppreference

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/970#-:-MMKoKwR2VrwnZNgvcj6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
