### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
two random fixes before rc 😉

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164#-:-MezWeBT6HqzrGMKrTF2:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/persistent_ptr.hpp, line 579 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164#-Meze7go24eqw5sIfy5x:-Meze7go24eqw5sIfy5y:b-h4bug0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/45a72a99b5dbc3ff88b77026a32aebf5bc0ccf4b/include/libpmemobj++/persistent_ptr.hpp#L579)):*
> ```
> 0xF00000000000000;
> ```
`0xFDEADBEEF000000;` still is a bit nerdy and better to debbuging

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/persistent_ptr.hpp, line 579 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164#-Meze7go24eqw5sIfy5x:-Mezw_GRCPHB_1l2JIdK:b7djccz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/45a72a99b5dbc3ff88b77026a32aebf5bc0ccf4b/include/libpmemobj++/persistent_ptr.hpp#L579)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 0xF00000000000000;
> ```
`0xFDEADBEEF000000;` still is a bit nerdy and better to debbuging
</blockquote></details>

It's a cherry-pick from a stable branch actually, so I'd leave it as is.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164#-:-Mf21o3D-JLU07nB3vtv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[include/libpmemobj++/persistent_ptr.hpp, line 579 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1164#-Meze7go24eqw5sIfy5x:-Mf21puZDhq6bgdf1HMv:b-qtegee) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/45a72a99b5dbc3ff88b77026a32aebf5bc0ccf4b/include/libpmemobj++/persistent_ptr.hpp#L579)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

It's a cherry-pick from a stable branch actually, so I'd leave it as is.
</blockquote></details>

That made me sad, but ok.

**Pull request merged**
