### PR TITLE
Remake tests dir (part 1)

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
in this PR I only group tests into sub-directories. Each container gets only one directory (excluding few cases for pmreorder tests, which may require bigger refactor).

I also fix examples' tests - dependency to `tests` target is required for proper build.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 107 of 107 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_erase.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-MQlOVpwDd2_V_0OnbIQ:-MQlOVpx8_qwXtT-KSsD:b-b21e80) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5269c232fa03fb4a0c7662c2287be8a12c8938b8/tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_erase.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2018-2020, Intel Corporation */
> ```

2021 if you change body of the file
___
*[tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_lookup.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-MQlOZYUCjFT97pTBjXl:-MQlOZYUCjFT97pTBjXm:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5269c232fa03fb4a0c7662c2287be8a12c8938b8/tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_lookup.cpp#L2)):*
> ```cpp
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2018-2020, Intel Corporation */
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_erase.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-MQlOVpwDd2_V_0OnbIQ:-MQlgM_d1COqD5G_zkfE:byq7gmo) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5269c232fa03fb4a0c7662c2287be8a12c8938b8/tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_erase.cpp#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

2021 if you change body of the file
</blockquote></details>

commit was created in 2020, so I don't think so... (CI build is green, incl. run of check-license.sh ;) )
___
*[tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_lookup.cpp, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-MQlOZYUCjFT97pTBjXl:-MQliKiFCh6BYnlXTSFC:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5269c232fa03fb4a0c7662c2287be8a12c8938b8/tests/concurrent_hash_map/concurrent_hash_map_tbb_insert_lookup.cpp#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-:-MQq-z0g2OBJjGwojtAO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

What about concurrent_hash_map and concurrent_map directories? Maybe if some tests require pmreorder and need several files we can just have them in subdirectory? Like:
```
tests/
     concurrent_map
          basic.cpp
          rehash_pmreoder/
                script.cmake
                test.cpp
```

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-:-MQqbizq9EwPt06_jtjh:b-sy22mw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
> What about concurrent_hash_map and concurrent_map directories? Maybe if some tests require pmreorder and need several files we can just have them in subdirectory? Like:
> 
> ```
> tests/
>      concurrent_map
>           basic.cpp
>           rehash_pmreoder/
>                 script.cmake
>                 test.cpp
> ```
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1003#-:-MQqbizq9EwPt06_jtjh:b-sy22mw)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

As I wrote in the description - some test scripts require refactor, e.g. place like this:
https://github.com/pmem/libpmemobj-cpp/blob/master/tests/ctest_helpers.cmake#L257
to handle custom paths to a pmreorder.conf file or cmake script.

**Pull request merged**
