### PR TITLE
inline_string reimplementation

### PR DESCRIPTION
**Pull request by KFilipek**
inline_string: test expansion

Add new cases to fully cover inline_string

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)

### CODE REVIEW

**Comment by igchor** [comment]
@KFilipek please rebase

**Review by igchor — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 55 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNi7rY89-Dua-b1pEK:-MGNi7rY89-Dua-b1pEL:bm3vne5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/include/libpmemobj++/experimental/inline_string.hpp#L55)):*
> ```cpp
> 	basic_inline_string(string_view v);
> 	basic_inline_string(size_type capacity);
> 	basic_inline_string(const basic_inline_string<CharT> &rhs);
> ```

You can just use basic_inline_string instead of basic_inline_string<CharT> here (it will just evaluate to the same type as this). It's FYI, you don't have to change it.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 64 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNi-pW8e1voYSlTetN:-MGNi-pW8e1voYSlTetO:by2sbgp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/include/libpmemobj++/experimental/inline_string.hpp#L64)):*
> ```cpp
> 	basic_inline_string(basic_inline_string<CharT> &&) = delete;
> 	basic_inline_string<CharT> &
> ```

Please remove this empty line and add one above basic_inline_string<CharT>&
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 80 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNiP1x4p6kxT4aJT9i:-MGNiP1x4p6kxT4aJT9j:b2j3er2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/include/libpmemobj++/experimental/inline_string.hpp#L80)):*
> ```cpp
> 	obj::p<uint64_t> size_;
> 	obj::p<uint64_t> capacity_;
> };
> ```

Please add some new line here.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 43 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNkpgo74eLPas8HnLP:-MGNkpgo74eLPas8HnLQ:b-um1w16) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/include/libpmemobj++/experimental/inline_string.hpp#L43)):*
> ```cpp
>  */
> template <typename CharT, typename Traits = std::char_traits<CharT>>
> class basic_inline_string {
> ```

It would be great if in this (or another?) PR, you could also extend radix_tree to support basic_inline_string for various character types (and add a test for that). The change in radix tree should be fairly simple. I think just chaning const_key_reference type should be enough.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 67 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNlBWl0ZiMzox9NTN6:-MGNlBWl0ZiMzox9NTN7:b-tbdunm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/include/libpmemobj++/experimental/inline_string.hpp#L67)):*
> ```cpp
> 	operator=(basic_inline_string<CharT> &&) = delete;
> 
> 	operator string_view() const;
> ```

This should probably be changed to operator basic_string_viw<CharT, Traits>() const;
___
*[tests/inline_string/inline_string.cpp, line 218 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNkUAW5njWLMKMSrrn:-MGNkUAW5njWLMKMSrro:boo834j) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/tests/inline_string/inline_string.cpp#L218)):*
> ```cpp
> 	}
> 
> 	test_inline_string(pop);
> ```

Please make those tests templated (test different character types - e.g. wchar and uint8_t).

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 43 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGNkpgo74eLPas8HnLP:-MGboIZh67V33Yl5U61y:b-4qpsa) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ff0eb6e88ec5828da709805129e66a26046e386b/include/libpmemobj++/experimental/inline_string.hpp#L43)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I will create separate PR when I return after my holidays
</blockquote></details>

Hm, after some thought, let's not do that for now. I believe we will be able to use basic_inline_string<whatever> through heterogeneous methods.
___
*[tests/inline_string/inline_string.cpp, line 117 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGbs6QuAOY8FxUIwWyv:-MGbs6QuAOY8FxUIwWyw:b-27451j) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2014a74dc6e3381a3e7a1eb87b9ed3e3ba4edf11/tests/inline_string/inline_string.cpp#L117)):*
> ```cpp
> 
> 	UT_ASSERT(nvobj::basic_string_view<T>(r->o1->s).compare(
> 			  bsv_test_string1) == 0);
> ```

Hm, why can't you just pass std::string (test_string1) instead of bsv_test_string1 (and in other places, instead of calling convert_to_basic_string_view)? It should work since there is an implicit conversion from std::string.

I don't think the convert_to_basic_string_view function is necessary at all - it only makes it more difficult to understand the test.

**Comment by KFilipek** [comment]
Temporary string will be destroyed after creating view, so pointer will be
invalid, I've created this workaround to had a valid pointer. Conversion
from string to basic_string<T> and then basic_string_view<T> need more
effort than just one function.

pon., 7 wrz 2020, 11:26 użytkownik Igor Chorążewicz <
notifications@github.com> napisał:

**Review by igchor — COMMENTED** [review]
That's not true. Temporary objects which are used as parameters will be destroyed only after the full expression is evaluated. This means that if you call `f(std::string(1024, 'a'))` while `f` accepts string_view, the string will be valid for the entire duration of `f`. https://stackoverflow.com/questions/2506793/c-life-span-of-temporary-arguments

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-:-MGhAwXBC_YtEN3f90WA:bl6321a)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[tests/inline_string/inline_string.cpp, line 117 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGbs6QuAOY8FxUIwWyv:-MGmwB6W-oHTwOgPbjve:ba51fd7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2014a74dc6e3381a3e7a1eb87b9ed3e3ba4edf11/tests/inline_string/inline_string.cpp#L117)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, why can't you just pass std::string (test_string1) instead of bsv_test_string1 (and in other places, instead of calling convert_to_basic_string_view)? It should work since there is an implicit conversion from std::string.

I don't think the convert_to_basic_string_view function is necessary at all - it only makes it more difficult to understand the test.
</blockquote></details>

We have different data types.
/opt/workspace/include/libpmemobj++/string_view.hpp:105:20: error: invalid conversion from 'const char*' to 'const value_type*' {aka 'const unsigned char*'} [-fpermissive]

It works only if there is a char template, in other cases we have type mismatch. Should reinterpret_cast be here a solution?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[tests/inline_string/inline_string.cpp, line 117 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGbs6QuAOY8FxUIwWyv:-MGrZ1Vm7XgK3V90sSvZ:b-z5j935) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/2014a74dc6e3381a3e7a1eb87b9ed3e3ba4edf11/tests/inline_string/inline_string.cpp#L117)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

We have different data types.
/opt/workspace/include/libpmemobj++/string_view.hpp:105:20: error: invalid conversion from 'const char*' to 'const value_type*' {aka 'const unsigned char*'} [-fpermissive]

It works only if there is a char template, in other cases we have type mismatch. Should reinterpret_cast be here a solution?
</blockquote></details>

It works now, right?
___
*[tests/inline_string/inline_string.cpp, line 4 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrUN7cECqHqtMzWAGB:-MGrUN7cECqHqtMzWAGC:b-ftmcr5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L4)):*
> ```cpp
> /* Copyright 2016-2020, Intel Corporation */
> 
> #include <map>
> ```

no longer necessary i believe
___
*[tests/inline_string/inline_string.cpp, line 148 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWDDt2k_JoW1YEJX9:-MGrWDDt2k_JoW1YEJXA:bjtpmle) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L148)):*
> ```cpp
> 		nvobj::basic_string_view<T> v1(bs.data(), bs.length());
> 
> 		nvobj::transaction::run(pop, [&] { r->o1->s = v1; });
> ```

If you want to verify that out_of_range is thrown, please add an assert also after transaction::run.
___
*[tests/inline_string/inline_string.cpp, line 175 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWMoO4J6Td_-sIJ7e:-MGrWMoO4J6Td_-sIJ7f:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L175)):*
> ```cpp
> 
> 			nvobj::transaction::abort(0);
> 		});
> ```

.
___
*[tests/inline_string/inline_string.cpp, line 207 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWcn14JeD9chJIK6Z:-MGrWcn14JeD9chJIK6_:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L207)):*
> ```cpp
> 		std::basic_string<T> bs(example_str.begin(), example_str.end());
> 		Object<T> o(
> 			1, nvobj::basic_string_view<T>(bs.data(), bs.length()));
> ```

.
___
*[tests/inline_string/inline_string.cpp, line 226 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWzOLBGRlJO4Jk0Bh:-MGrWzOLBGRlJO4Jk0Bi:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L226)):*
> ```cpp
> 
> 		try {
> 			Object<T> o(*r->o1);
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[tests/inline_string/inline_string.cpp, line 148 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWDDt2k_JoW1YEJX9:-MGrsyAgD6aLZRB286hh:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L148)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If you want to verify that out_of_range is thrown, please add an assert also after transaction::run.
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 175 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWMoO4J6Td_-sIJ7e:-MGrt9Gj9xAnY0NadRCN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L175)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 207 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWcn14JeD9chJIK6Z:-MGrtA4t0y1ecYTIdUV1:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L207)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/inline_string/inline_string.cpp, line 226 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-MGrWzOLBGRlJO4Jk0Bh:-MGrtJG63XZTia2FmZtw:b-kmnoez) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/cab2deda9c14a3ea48c9bad7882b0e3df3a16911/tests/inline_string/inline_string.cpp#L226)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done. I've added also few lines below.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-:-MGwOXlp9xTnjBNSb5HK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/848#-:-MHBfSZI2qXekIVFJXWP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
