### PR TITLE
Radix tree optimizations

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844)

### CODE REVIEW

**Comment by szyrom** [comment]
Ref #828

**Review by szyrom — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 278 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCPN_G0vWM18ftylC0:-MGCPN_G0vWM18ftylC1:b496yje) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L278)):*
> ```cpp
> 	template <typename K>
> 	std::tuple<const tagged_node_ptr *, tagged_node_ptr>
> 	descend(const K &key, byten_t diff, bitn_t sh) const;
> ```

s/&key/&k
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 704 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCNw-X6Br02gm6m8c2:-MGCNw-Y22j1A5wRshkL:bok6q2b) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L704)):*
> ```cpp
> template <typename Key, typename Value, typename BytesView>
> typename radix_tree<Key, Value, BytesView>::leaf *
> radix_tree<Key, Value, BytesView>::any_leaf(
> ```

any_lower_leaf ?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 857 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCQKdW84GY8qM2Y_Z-:-MGCQKdW84GY8qM2Y_Z0:bp56f43) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L857)):*
> ```cpp
> 	   typename radix_tree<Key, Value, BytesView>::tagged_node_ptr>
> radix_tree<Key, Value, BytesView>::descend(const K &key, byten_t diff,
> 					   bitn_t sh) const
> ```

is this possible to define const version of this method by wrapping and returning non-const? Like this:
return static_cast<const radix_tree<Key, Value, BytesView> &>(*this).descend(key, diff, sh));
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1349 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCQz62Eu-hgOIybf3k:-MGCQz638UyGzNN_7I8k:bi2xk9m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L1349)):*
> ```cpp
> 	 * represents a subtree that shares a common prefix with the key.
> 	 * This is needed to find out the actual labels between nodes (they
> 	 * are not known due to a possible path compression).
> ```

and for the second time?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1377 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCSn_p8kKfTbbx8VU3:-MGCSn_p8kKfTbbx8VU4:b-4jjb1o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L1377)):*
> ```cpp
> 	 * be the smallest leaf within *slot subtree. Key represented by a path
> 	 * from root to n is larger than the looked-for key. Additionally keys
> 	 * under right siblings of *slot
> ```

fix next line alignment

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @szyrom)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 278 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCPN_G0vWM18ftylC0:-MGCsfzuAr4fDng3Ywvc:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L278)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

s/&key/&k
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 704 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCNw-X6Br02gm6m8c2:-MGCt_spEazyeMd9Rtw2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L704)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

any_lower_leaf ?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 857 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCQKdW84GY8qM2Y_Z-:-MGCspwK1HBaq4YA17Bk:bonrkaz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L857)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

is this possible to define const version of this method by wrapping and returning non-const? Like this:
return static_cast<const radix_tree<Key, Value, BytesView> &>(*this).descend(key, diff, sh));
</blockquote></details>

You could do that by using const_cast, not static_cast and this is basically what I do when I need non-const ptr.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1349 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCQz62Eu-hgOIybf3k:-MGCtrAn9jU75FCNLpyG:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L1349)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

and for the second time?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1377 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-MGCSn_p8kKfTbbx8VU3:-MGCtrUpACyygRX0Iecl:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/bd49b567dcc141cea0f4ef9accc19a807c23189a/include/libpmemobj++/experimental/radix_tree.hpp#L1377)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

fix next line alignment
</blockquote></details>

Done.

**Review by szyrom — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/844#-:-MGEaRQa5ng0EgQt_Rb5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
