### PR TITLE
Radix tree assing val fix

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/918)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/918)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/918)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/918)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/918#-:-MIxEPEq9oM7by8RVZsl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
