### PR TITLE
[array] add c++20 initialization_list constructor

### PR DESCRIPTION
**Pull request by karczex**
Since C++20 classes with explicitly defaulted constructors are no more
aggregates, so constructor for initialization_list is needed.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
In future, we might think about implementing something like was proposed here: https://stackoverflow.com/questions/38932089/can-i-initialize-an-array-using-the-stdinitializer-list-instead-of-brace-enclo to avoid the limitations of std::initializer_list

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-:-Med0Tke7CDMHcurORrf:bm3fxuf)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[include/libpmemobj++/container/array.hpp, line 49 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Mecyr3q6f_UNnOGM6Mp:-Mecyr3r20bzOW91LzpL:bdj86gm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/include/libpmemobj++/container/array.hpp#L49)):*
> ```cpp
>  * aggregate since C++20.
>  *
>  * @note Since C++20 pmem::obj::array cannot be used for types with deleted
> ```

I don't think this is true - you can use array in that case, you just cannot initialize those values in a ctor. You can just do (if T has a default ctor):

```
pmem::obj::array<T, 3> arr;
arr[0] = ...;
```
___
*[include/libpmemobj++/container/array.hpp, line 52 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Mecz9at0vEogRSKczub:-Mecz9au1DG8PtgZddiM:b-t0lkh4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/include/libpmemobj++/container/array.hpp#L52)):*
> ```cpp
>  * copy constructor. This may change in the future.
>  *
>  * @note Since C++20 pmem::obj::array cannot be used for const types. This may
> ```

Well, it can, but you can't use any ctor different than a default one.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[include/libpmemobj++/container/array.hpp, line 46 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedotziAnxJksQfqIUt:-MedotziAnxJksQfqIUu:b-w9dywk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/include/libpmemobj++/container/array.hpp#L46)):*
> ```cpp
>  * to a transaction while traversing.
>  *
>  * @note Accordingly to changes in C++ standard, pmem::obj::array is not an
> ```

`According to`
___
*[tests/CMakeLists.txt, line 357 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medp461-gw3B3T0NJF9:-Medp461-gw3B3T0NJFA:bldoya8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/CMakeLists.txt#L357)):*
> ```CMake
> 		add_test_generic(NAME array_slice_pmreorder CASE 1 TRACERS none SCRIPT array/array_slice_pmreorder_1.cmake)
> 	endif()
> 	if(CXX_STANDARD GREATER_EQUAL 17)
> ```

`GREATER_EQUAL` is delivered in CMake >= 3.7, so please just use `CXX_STANDARD GREATER 14`
___
*[tests/array/array_is_aggregate.cpp, line 8 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedpJQO5yhzz2e6NjGH:-MedpJQO5yhzz2e6NjGI:bpk1kbw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/array/array_is_aggregate.cpp#L8)):*
> ```cpp
> 
> /* Test which checks if array behave in the same way as any structure with
>  * defaulted constructor - accordingly to used c++ standard */
> ```

`according to`
___
*[tests/external/CMakeLists.txt, line 108 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedpOFQ8vwJhTCcHThw:-MedpOFR2IcK1mDbGdjQ:b1oabhb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/CMakeLists.txt#L108)):*
> ```CMake
> 
> 
> 	if(CXX_STANDARD LESS_EQUAL 17)
> ```

. (`LESS 20`)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: all files reviewed, 13 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[include/libpmemobj++/container/array.hpp, line 15 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedfJco4janYiEO9GNR:-MedfJco4janYiEO9GNS:bnmcw3c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/include/libpmemobj++/container/array.hpp#L15)):*
> ```cpp
> #include <functional>
> 
> #include <initializer_list>
> ```

one block up:
```cpp
#include <algorithm>
#include <functional>
#include <initializer_list>
```
___
*[tests/CMakeLists.txt, line 357 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medp461-gw3B3T0NJF9:-Meduh679UeaJSDY23hu:b-645t78) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/CMakeLists.txt#L357)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`GREATER_EQUAL` is delivered in CMake >= 3.7, so please just use `CXX_STANDARD GREATER 14`
</blockquote></details>

or update README.md, on every supported OS this PR was built successfully
___
*[tests/array/array_is_aggregate.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medv4nvCQgI_l2JbL8x:-Medv4nvCQgI_l2JbL8y:b-d7k9gx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/array/array_is_aggregate.cpp#L4)):*
> ```
> #include "unittest.hpp"
> #include <libpmemobj++/container/array.hpp>
> ```
suparate this into 2 blocks
___
*[tests/array/array_is_aggregate.cpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedvAty0T-UXyQ9wOwA:-MedvAty0T-UXyQ9wOwB:b-kz2dlg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/array/array_is_aggregate.cpp#L21)):*
> ```cpp
> 		std::is_aggregate<struct_with_defaulted_constructor>::value;
> 
> 	UT_ASSERTeq(array_is_aggregate, cpp_standard_support);
> ```

@igchor is static_assert here better than UT_ASSERTeq?
___
*[tests/external/CMakeLists.txt, line 107 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medvcn3DdOC6zlM3lNL:-Medvcn3DdOC6zlM3lNM:bbqoph6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/CMakeLists.txt#L107)):*
> ```CMake
> 	add_test_generic(NAME array_get_const TRACERS none)
> ```

2 lines instead of 1
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 10 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedvpQ72e7C5EyyE1xY:-MedvpQ72e7C5EyyE1xZ:bdg3vuc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L10)):*
> ```cpp
> //===----------------------------------------------------------------------===//
> //
> // Copyright 2018-2021, Intel Corporation
> ```

If it's new file it should contain only 2021
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedvxVt8n92e9LtMmqj:-MedvxVt8n92e9LtMmqk:bxoaqnm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L54)):*
> ```cpp
> 	run()
> 	{
> 		((void)c2);
> ```

`(void)c2;` should be sufficient
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medw23A35lup4ZUad7z:-Medw23A35lup4ZUad8-:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L67)):*
> ```cpp
> 	run()
> 	{
> 		((void)c2);
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: all files reviewed, 13 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[tests/CMakeLists.txt, line 357 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medp461-gw3B3T0NJF9:-Meekzxt6-HYtokuLb7b:b2ba9ti) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/CMakeLists.txt#L357)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

or update README.md, on every supported OS this PR was built successfully
</blockquote></details>

it may break on OSes like RHEL - and what would be the gain...? I'd say, it's better to use as low version of CMake as possible :wink:
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 10 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedvpQ72e7C5EyyE1xY:-MeelK1g8F8OTtb41VIM:buwwefe) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L10)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If it's new file it should contain only 2021
</blockquote></details>

nope, as usual - we copy-pasted the content from previously existing file - hence both dates

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: 

> Reviewed 2 of 6 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-:-MehpTzbBaNRq79sQ6gK:b-8fx2u7)* status: all files reviewed, 10 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[utils/docker/run-build.sh, line 217 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Mehnaof5mrA1KWBjJ5M:-Mehnaof5mrA1KWBjJ5N:byzrck3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c1e331e7e8f996316c45f93c6bcdfac35ec17850/utils/docker/run-build.sh#L217)):*
> ```Shell
> 	printf "\n$(tput setaf 1)$(tput setab 7)BUILD ${FUNCNAME[0]} START$(tput sgr 0)\n"
> 	mkdir build && cd build
> ```

we may add here the check for support in CMake (like here: https://github.com/pmem/pmemkv/blob/master/utils/docker/run-build.sh#L168), but it will work on most OSes...

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex)

___
*[tests/CMakeLists.txt, line 357 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medp461-gw3B3T0NJF9:-Meip7C67xYTbSDr-a53:buketii) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/CMakeLists.txt#L357)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it may break on OSes like RHEL - and what would be the gain...? I'd say, it's better to use as low version of CMake as possible :wink:
</blockquote></details>

Indeed

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[tests/array/array_is_aggregate.cpp, line 21 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedvAty0T-UXyQ9wOwA:-MeixiWT-k4rNZ9cZHO_:b-x5l6by) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/array/array_is_aggregate.cpp#L21)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@igchor is static_assert here better than UT_ASSERTeq?
</blockquote></details>

I think it's fine both ways.
___
*[tests/external/CMakeLists.txt, line 107 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medvcn3DdOC6zlM3lNL:-Meiy7AC-W6uqJhaTwh4:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/CMakeLists.txt#L107)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

2 lines instead of 1
</blockquote></details>

Done.
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 54 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedvxVt8n92e9LtMmqj:-MeiyB99EjtipM8rt-9m:bs7wumx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L54)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

`(void)c2;` should be sufficient
</blockquote></details>

Done. 
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medw23A35lup4ZUad7z:-MeiyMgp35T8HuvNsW3X:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L67)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[utils/docker/run-build.sh, line 217 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Mehnaof5mrA1KWBjJ5M:-Mej-jvG2YBhWKQJlU5o:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c1e331e7e8f996316c45f93c6bcdfac35ec17850/utils/docker/run-build.sh#L217)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we may add here the check for support in CMake (like here: https://github.com/pmem/pmemkv/blob/master/utils/docker/run-build.sh#L168), but it will work on most OSes...
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/container/array.hpp, line 116 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MejO4DR42dCRpz6OnQm:-MejO4DS6ABWGCt1kUlv:b-8m1rkd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c85aff77c3df4dd00fb5ec1dba35b7951eee6ab8/include/libpmemobj++/container/array.hpp#L116)):*
> ```cpp
> 	 *
> 	 * It provides similar initialization semantics for
> 	 * C++20 (where pmem::obj::array is not longer an aggregate).
> ```

`no longer`
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medw23A35lup4ZUad7z:-MejOPsOAU5LQwMf7V7K:b-cb8t8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L67)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

nope..?
___
*[tests/external/libcxx/array/array.cons/initializer_list.pass.cpp, line 56 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MejPIoP4Qhgr0mrXYcD:-MejPIoP4Qhgr0mrXYcE:b-brzb60) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c85aff77c3df4dd00fb5ec1dba35b7951eee6ab8/tests/external/libcxx/array/array.cons/initializer_list.pass.cpp#L56)):*
> ```cpp
> 	C c = {1};
> #else
> 	/* This syntax casuse warning: braces around scalar initializer
> ```

`casuse` -> `causes`
___
*[utils/docker/run-build.sh, line 217 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MejP63q9yO6kiT1ykYJ:-MejP63q9yO6kiT1ykYK:bpb3ecw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c85aff77c3df4dd00fb5ec1dba35b7951eee6ab8/utils/docker/run-build.sh#L217)):*
> ```Shell
> 	printf "\n$(tput setaf 1)$(tput setab 7)BUILD ${FUNCNAME[0]} START$(tput sgr 0)\n"
> 
> 	if [ ${CMAKE_VERSION_NUMBER} -lt 312 ]; then
> ```

but we never set `CMAKE_VERSION_NUMBER` :wink:  (in pmemkv it's done in `prepare-for-build.sh`)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158)* status: 5 of 11 files reviewed, 9 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/container/array.hpp, line 15 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MedfJco4janYiEO9GNR:-Mexovnh5AIHsx232ou9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/include/libpmemobj++/container/array.hpp#L15)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

one block up:
```cpp
#include <algorithm>
#include <functional>
#include <initializer_list>
```
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/array.hpp, line 116 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MejO4DR42dCRpz6OnQm:-Mexoy9aC0VZHlp0cyt9:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c85aff77c3df4dd00fb5ec1dba35b7951eee6ab8/include/libpmemobj++/container/array.hpp#L116)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`no longer`
</blockquote></details>

Done.
___
*[tests/array/array_is_aggregate.cpp, line 4 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medv4nvCQgI_l2JbL8x:-MexpAKH4zMk8zKol7Ro:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/array/array_is_aggregate.cpp#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> #include "unittest.hpp"
> #include <libpmemobj++/container/array.hpp>
> ```
suparate this into 2 blocks
</blockquote></details>

Done.
___
*[tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp, line 67 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-Medw23A35lup4ZUad7z:-MexoaCd07FpFxO3h-lE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/46eeb0f973b0a7295e14008f249202d6a98f9b70/tests/external/libcxx/array/array.cons/implicit_copy_const.pass.cpp#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nope..?
</blockquote></details>

Done.
___
*[tests/external/libcxx/array/array.cons/initializer_list.pass.cpp, line 56 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MejPIoP4Qhgr0mrXYcD:-MexooZd1L4ByRzpaqHv:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c85aff77c3df4dd00fb5ec1dba35b7951eee6ab8/tests/external/libcxx/array/array.cons/initializer_list.pass.cpp#L56)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`casuse` -> `causes`
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 217 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-MejP63q9yO6kiT1ykYJ:-MexqMCA3PKYOVwgErtt:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c85aff77c3df4dd00fb5ec1dba35b7951eee6ab8/utils/docker/run-build.sh#L217)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

but we never set `CMAKE_VERSION_NUMBER` :wink:  (in pmemkv it's done in `prepare-for-build.sh`)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1158#-:-MexrUbN67mNPIir2ktS:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @KFilipek)

**Pull request merged**
