### PR TITLE
docs: update miscellaneous Doxygen comments

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- extend Transaction group/feature description,
- fix misspells,
- fix minor Doxygen warnings.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 12 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk1fzgAAVlvHkT33rEL:-Mk1fzgAAVlvHkT33rEM:bsxbt78) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L12)):*
> ```
>   * # General info about transactions
>   *
>   * The heart of the libpmemobj are transactions, and they are designed in C++ to be as developer-friendly as possible.
> ```

Do you really want to suggest, that this API is `not so much developer friendly`?

**Review by KFilipek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 12 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk1fzgAAVlvHkT33rEL:-Mk1zL0VC77nx_qNFet3:bvxro9f) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L12)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Do you really want to suggest, that this API is `not so much developer friendly`?
</blockquote></details>

libpmemobj-cpp is written in C++, so transactions obviously are `designed in C++`
___
*[doc/groups_definitions.dox, line 70 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2-CE83hmA2gDbQaEQ:-Mk2-CE83hmA2gDbQaER:b-q8i3ey) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L70)):*
> ```
>   * [pmemobj_tx_begin manpage](https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3.html),
> ```
*
___
*[doc/groups_definitions.dox, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2-2PHDkEEBwN8Dizs:-Mk2-2PI3zEMtW1bhEvn:bum29d3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L85)):*
> ```
> [pmemobj_tx_begin manpage with transaction description (C API)](https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3)
> ```
this link exists in description above so maybe you should update it and refer to `Additional resources`

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[doc/groups_definitions.dox, line 12 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk1fzgAAVlvHkT33rEL:-Mk26Joa4PR8d74jcmCx:b7uae40) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L12)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

libpmemobj-cpp is written in C++, so transactions obviously are `designed in C++`
</blockquote></details>

hmm... I guess, the phrasing wasn't ideal. It was inspired/copied from a blog post describing how Cpp bindings came to live :wink: 
see here we use "libpmemobj" name, not "-cpp".

I've re-wrote it a little - is it better now?

@karczex , I'm not sure how you read that it's "not so much" friendly :wink: I think this sentence doesn't say it isn't - it's just "as much as possible" :wink: 
___
*[doc/groups_definitions.dox, line 70 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2-CE83hmA2gDbQaEQ:-Mk28KeFEkyouCSTC8qG:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L70)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
>   * [pmemobj_tx_begin manpage](https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3.html),
> ```
*
</blockquote></details>

Done.
___
*[doc/groups_definitions.dox, line 85 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2-2PHDkEEBwN8Dizs:-Mk28xWP8X3vplsMXq_8:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L85)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> [pmemobj_tx_begin manpage with transaction description (C API)](https://pmem.io/pmdk/manpages/linux/master/libpmemobj/pmemobj_tx_begin.3)
> ```
this link exists in description above so maybe you should update it and refer to `Additional resources`
</blockquote></details>

Done.

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-:-Mk2D60h8u1mW88I8keI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 12 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk1fzgAAVlvHkT33rEL:-Mk2Cq0Q7lNuQcyaZyn8:blfc6dm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d4beeee0348fa91536d8447270f0b64f7dbe23b7/doc/groups_definitions.dox#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... I guess, the phrasing wasn't ideal. It was inspired/copied from a blog post describing how Cpp bindings came to live :wink: 
see here we use "libpmemobj" name, not "-cpp".

I've re-wrote it a little - is it better now?

@karczex , I'm not sure how you read that it's "not so much" friendly :wink: I think this sentence doesn't say it isn't - it's just "as much as possible" :wink: 
</blockquote></details>

For me: better

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2PHY26zLriwHGGh5f:-Mk2PHY26zLriwHGGh5g:b-n4u4ns) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/442bb3aac63b798fd2ce6f2b7baf9696774c4516/doc/groups_definitions.dox#L18)):*
> ```
>   * restoring the consistent state of the memory pool from the moment when the transaction was started.
>   * In C++ bindings (libpmemobj-cpp - this library) they were designed (in comparison to C API)
>   * to be as developer-friendly as possible.
> ```

"all the changes made as a part of the uncompleted transaction" - maybe it would be good to extend this? For example to mention that only changes done though libpmemobj-cpp API CAN be a part of the transaction (and simple modification is not).

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @KFilipek)

___
*[doc/groups_definitions.dox, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2PHY26zLriwHGGh5f:-Mk6UKyo8a9Q5r62eEUL:b-47a87h) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/442bb3aac63b798fd2ce6f2b7baf9696774c4516/doc/groups_definitions.dox#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

"all the changes made as a part of the uncompleted transaction" - maybe it would be good to extend this? For example to mention that only changes done though libpmemobj-cpp API CAN be a part of the transaction (and simple modification is not).
</blockquote></details>

I've added one more sentence, very general, but I hope it will be an eye-opener :wink:

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-:-MkBRMZ43vx4b7G9E-xL:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[doc/groups_definitions.dox, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2PHY26zLriwHGGh5f:-MkGteyg9QYGs-X2fatq:bxt917m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/442bb3aac63b798fd2ce6f2b7baf9696774c4516/doc/groups_definitions.dox#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I've added one more sentence, very general, but I hope it will be an eye-opener :wink: 
</blockquote></details>

Right, this is also important, but what I meant was to mention that normal operations (like int x = 5 or malloc()) are not a part of the transaction and they will not be rolled back on failure. Perhaps also some link to p<> property for how to modify pmem variables transactionally and to allocation methods.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[doc/groups_definitions.dox, line 18 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-Mk2PHY26zLriwHGGh5f:-MkGyC2P1UYsS5a8ynuh:bp8zwc8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/442bb3aac63b798fd2ce6f2b7baf9696774c4516/doc/groups_definitions.dox#L18)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Right, this is also important, but what I meant was to mention that normal operations (like int x = 5 or malloc()) are not a part of the transaction and they will not be rolled back on failure. Perhaps also some link to p<> property for how to modify pmem variables transactionally and to allocation methods.
</blockquote></details>

och, of course, good point. Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1200#-:-MkMlY8r6Qu2si17ZbJM:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
