### PR TITLE
Make syncthreads() in parallel_xexec multi-use

### PR DESCRIPTION
**Pull request by igchor**
Previously syncthreads could only be used once and this was not
documented. This patch allows for having multiple synchronization
points in a function. This might useful for testing hazard pointers.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[tests/common/helpers_test.cpp, line 12 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-MXClHYuEACFpjFNyKed:-MXClHYuEACFpjFNyKee:b-is0ktk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/98e990e2c29f03803e52233cb2532209d4393085/tests/common/helpers_test.cpp#L12)):*
> ```cpp
> 
> int
> main()
> ```

pls add a short comment what's in this test
___
*[tests/common/helpers_test.cpp, line 26 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-MXCo0Uj5ntyJlWYXvi3:-MXCo0Uj5ntyJlWYXvi4:b-455ikb) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/98e990e2c29f03803e52233cb2532209d4393085/tests/common/helpers_test.cpp#L26)):*
> ```cpp
> 
> 			       counter++;
> ```

you could add info that new latch is allocated here (if that's meaningful - I'm not sure... ;) )
___
*[tests/common/helpers_test.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-MXCnfp8Ae858ZZ4mIC_:-MXCnfp8Ae858ZZ4mICa:b-ugijof) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/98e990e2c29f03803e52233cb2532209d4393085/tests/common/helpers_test.cpp#L31)):*
> ```cpp
> 			       syncthreads();
> 		       });
> }
> ```

counter is still equal to `concurrency * 2` at the end of main..? maybe we could assert that too

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[tests/common/helpers_test.cpp, line 12 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-MXClHYuEACFpjFNyKed:-MXDDSHa8hTR43dAsOOn:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/98e990e2c29f03803e52233cb2532209d4393085/tests/common/helpers_test.cpp#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add a short comment what's in this test
</blockquote></details>

Done.
___
*[tests/common/helpers_test.cpp, line 26 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-MXCo0Uj5ntyJlWYXvi3:-MXDDTbSCVzvUSlj5s5s:b-ahcdyd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/98e990e2c29f03803e52233cb2532209d4393085/tests/common/helpers_test.cpp#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could add info that new latch is allocated here (if that's meaningful - I'm not sure... ;) )
</blockquote></details>

I think that should not matter here - the fact that we allocate new latch is an implementation detail, this should just work :)
___
*[tests/common/helpers_test.cpp, line 31 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-MXCnfp8Ae858ZZ4mIC_:-MXDDa8N6GbQEOvwAf9F:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/98e990e2c29f03803e52233cb2532209d4393085/tests/common/helpers_test.cpp#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

counter is still equal to `concurrency * 2` at the end of main..? maybe we could assert that too
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm: (just fix CI)

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-:-MXDTdPw-1H0Ux_MZA89:b-xt31nn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-:-MXDkHdO1mde3_wTgABM:b-896fix)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-:-MX_xMTpD1qbmkrudtLx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1062#-:-MYJCkofCsgyzrw2b__J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
