### PR TITLE
Radix tree improvements

### PR DESCRIPTION
**Pull request by JanDorniak99**
#828

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/896)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/896#-:-MIK-tEV3xqnaCX8cb7t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, 2 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/896)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
