### PR TITLE
add concurrent_hash_map concurrent erase defrag test

### PR DESCRIPTION
**Pull request by JanDorniak99**
#892

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaHW6FCyUlWGEM_tSO:-MJaHW6FCyUlWGEM_tSP:b-gzcvuo) (no related file):*
it's better to add `ref. #xyz` or `fixes #xyz` already in the commit message (see git workflow guideline)

---
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 79 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaJ1Lh-qPAzBH-goqd:-MJaJ1Lh-qPAzBH-goqe:b-lsihi9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L79)):*
> ```cpp
> 
> /*
>  * insert_and_erase_test_str -- (internal) test insert and erase operations
> ```

please fix this description and also add some to the new test
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 194 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaMu0zCsVoDJO8GU8B:-MJaMu0zCsVoDJO8GU8C:b1y1twq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L194)):*
> ```cpp
> 	}
> 
> 	if (reversed_order)
> ```

a short comment perhaps, why you do this, pls (unless it will be described in the test case description on top of this function)
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 195 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaM6ZZ2dPe2KhGjsDo:-MJaM6ZZ2dPe2KhGjsDp:bb1u7v0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L195)):*
> ```cpp
> 
> 	if (reversed_order)
> 		std::reverse(elements.begin() + 100, elements.end());
> ```

what's this magic number (100)?
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 200 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaMg0g9kleSlOifusd:-MJaMg0g9kleSlOifuse:b-9miwus) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L200)):*
> ```cpp
> 	for (ptrdiff_t i = 0; i < 10; i++) {
> 		threads.emplace_back([&, i]() {
> 			ptrdiff_t start_offset = i == 0 ? 100 : 0;
> ```

put this conditional if in parentheses to ease the reading
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 207 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaMTIG1D8gaNlT1_9M:-MJaMTIG1D8gaNlT1_9N:b-wwlsj2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L207)):*
> ```
> 						static_cast<ptrdiff_t>(
> 							NUMBER_ITEMS_INSERT) /
> 						10);
> ```
make this a const perhaps, like in the other test in this file

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)* status: all files reviewed, 8 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 204 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJa_3B_2GB9OprcE5wG:-MJa_3B_2GB9OprcE5wH:b26ocx4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L204)):*
> ```cpp
> 				elements.begin(),
> 				start_offset +
> 					i *
> ```

Shouldn't you also skip 100 first entries here? Anyway, I think it would be clearer to just remove the first 100 entries from elements (or just to store an iterator to the 100th element and use it here) instead of conditionally calculating `i`.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 236 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJa_Tv35bj1zi5kCJnj:-MJa_Tv35bj1zi5kCJnk:b46k9kt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L236)):*
> ```cpp
> 		}
> 	}
> ```

You can also verify size of the map here.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaHW6FCyUlWGEM_tSO:-MJak-VNATZ_Pe39fIHn:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's better to add `ref. #xyz` or `fixes #xyz` already in the commit message (see git workflow guideline)
</blockquote></details>

Done.

---
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 79 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaJ1Lh-qPAzBH-goqd:-MJaZXAY75DH4qB_e3Xl:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L79)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

please fix this description and also add some to the new test
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 194 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaMu0zCsVoDJO8GU8B:-MJa_brr2vES6n2N5qra:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L194)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a short comment perhaps, why you do this, pls (unless it will be described in the test case description on top of this function)
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 195 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaM6ZZ2dPe2KhGjsDo:-MJa_d44-tN2GQCueBcj:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L195)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what's this magic number (100)?
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 200 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaMg0g9kleSlOifusd:-MJags29BXJFVjxWgHBH:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L200)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put this conditional if in parentheses to ease the reading
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 204 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJa_3B_2GB9OprcE5wG:-MJagudgC2oSwifL7YYq:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L204)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Shouldn't you also skip 100 first entries here? Anyway, I think it would be clearer to just remove the first 100 entries from elements (or just to store an iterator to the 100th element and use it here) instead of conditionally calculating `i`.
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 207 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJaMTIG1D8gaNlT1_9M:-MJaiGMDDCJGTxIa514J:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L207)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> ```
> 						static_cast<ptrdiff_t>(
> 							NUMBER_ITEMS_INSERT) /
> 						10);
> ```
make this a const perhaps, like in the other test in this file
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 236 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJa_Tv35bj1zi5kCJnj:-MJagxJWBRrvIb17nSR7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8e41bc2b648c5030bf3d92833fe6bfcae2ab852b/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L236)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can also verify size of the map here.
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @igchor, @JanDorniak99, and @lukaszstolarczuk)

___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 177 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJauIu0Bo0ZtLu6xA4j:-MJauIu0Bo0ZtLu6xA4k:bsyq8e) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/406763060c9074202a3ca65c379b0ba4e78ab3bc/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L177)):*
> ```cpp
>  */
> void
> erase_defrag_concurrent_test(nvobj::pool<root> &pop, bool reversed_order)
> ```

Could you make number of thread some parameter to this test?

It would be good to have test where there are multiple threads erasing (like you have now) and a case, where there is only one thread erasing (especially for reverse order).

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 177 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJauIu0Bo0ZtLu6xA4j:-MJaz2Q673-KiYc9y9_X:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/406763060c9074202a3ca65c379b0ba4e78ab3bc/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L177)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you make number of thread some parameter to this test?

It would be good to have test where there are multiple threads erasing (like you have now) and a case, where there is only one thread erasing (especially for reverse order).
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-:-MJb-mFO0LPI-_vY4dfA:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
beside two small issues, it looks good to me ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-:-MJc5dcV0fm3sNVm7jZ8:b-6h70cx)* status: all files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 180 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJc4pwZEdCcC1BfRKdD:-MJc4pw_2KgeMDmITeML:b23c3zr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/203b918960b0df433be6d696cddca3695b4838ca/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L180)):*
> ```cpp
> 			     size_t erase_threads_n)
> {
> 	const size_t NUMBER_ITEMS_ERASE = 1000 * erase_threads_n;
> ```

shouldn't you use here BATCH_SIZE instead of a 1000?
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 190 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJc4NE5AxgmIf9vQSJB:-MJc4NE5AxgmIf9vQSJC:b6dl502) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/203b918960b0df433be6d696cddca3695b4838ca/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L190)):*
> ```cpp
> 
> 	std::string str = " ";
> 	for (size_t i = 0; i < NUMBER_ITEMS_ERASE + 100; i++) {
> ```

this `100` is still a magic number, make it const, pls

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 180 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJc4pwZEdCcC1BfRKdD:-MJf28PcBXRxmnAtm_pb:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/203b918960b0df433be6d696cddca3695b4838ca/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L180)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't you use here BATCH_SIZE instead of a 1000?
</blockquote></details>

Done.
___
*[tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp, line 190 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-MJc4NE5AxgmIf9vQSJB:-MJf28sPBinJxFA9pIzB:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/203b918960b0df433be6d696cddca3695b4838ca/tests/concurrent_hash_map_defrag/concurrent_hash_map_defrag.cpp#L190)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this `100` is still a magic number, make it const, pls
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/936#-:-MJf46Hi9dXSn6vXlnX3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
