### PR TITLE
Bump OSes versions

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] last commit to be dropped

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-:-MLw--neCIJXalvUmD3R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 259 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-MMF_MQp15qCUPFN3OD1:-MMF_MQp15qCUPFN3OD2:b-jok8ff) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c79bd59a966ceedeb2d6356885fa5c9d59bbeb/utils/docker/run-build.sh#L259)):*
> ```Shell
> 	printf "\n$(tput setaf 1)$(tput setab 7)BUILD ${FUNCNAME[0]} START$(tput sgr 0)\n"
> 
> 	if ! ls /opt/pmdk-pkg/libpmem* > /dev/null 2>&1; then
> ```

shouldn't this be an error? This way it will silently fail and we might not notice

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.fedora-33, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-MMFccI50WtB3D-97CDT:-MMFccI50WtB3D-97CDU:b-2gbvht) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c79bd59a966ceedeb2d6356885fa5c9d59bbeb/utils/docker/images/Dockerfile.fedora-33#L2)):*
> ```
> # Copyright 2016-2020, Intel Corporation
> ```
New file should have:
# Copyright 2020, Intel Corporation
Correct me if I'm wrong
___
*[utils/docker/images/Dockerfile.ubuntu-20.10, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-MMFcldM4aCNQJI7n2SM:-MMFcldM4aCNQJI7n2SN:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c79bd59a966ceedeb2d6356885fa5c9d59bbeb/utils/docker/images/Dockerfile.ubuntu-20.10#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2016-2020, Intel Corporation
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[utils/docker/run-build.sh, line 259 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-MMF_MQp15qCUPFN3OD1:-MMFfuC19JDCZvRcBMAy:b-kyjirp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c79bd59a966ceedeb2d6356885fa5c9d59bbeb/utils/docker/run-build.sh#L259)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't this be an error? This way it will silently fail and we might not notice
</blockquote></details>

I've added this check when a "package" build failed on OS, which don't support PMDK's rpm/deb. It should actually never happen on our regular CI, so I guess you're right. Fixed.
___
*[utils/docker/images/Dockerfile.fedora-33, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-MMFccI50WtB3D-97CDT:-MMFf_22B2ggYh499SC_:bixmldm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c79bd59a966ceedeb2d6356885fa5c9d59bbeb/utils/docker/images/Dockerfile.fedora-33#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> # Copyright 2016-2020, Intel Corporation
> ```
New file should have:
# Copyright 2020, Intel Corporation
Correct me if I'm wrong
</blockquote></details>

If you're copying a file and slightly modify for other use case it's not a new file ;) We tend to leave the original dates in such cases.
___
*[utils/docker/images/Dockerfile.ubuntu-20.10, line 2 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-MMFcldM4aCNQJI7n2SM:-MMFfoSFE5L1Mx5B4Ufe:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2c79bd59a966ceedeb2d6356885fa5c9d59bbeb/utils/docker/images/Dockerfile.ubuntu-20.10#L2)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-:-MMFo_zf9rdYLVynxk2r:bnfp4nl)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/965#-:-MMGGOLVBYiN2o-HRASA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
