### PR TITLE
Small fixes for coverity issues

### PR DESCRIPTION
**Pull request by KFilipek**
- [examples] Reduce scope of try-catch block
- [atomic_self_relative_ptr] Add try-catch to filfill noexcept requirement

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 93 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uC4X0bzd6usNV06c:-Me5uC4X0bzd6usNV06d:b-jsyjs8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L93)):*
> ```cpp
> 					expected_offset, ptr);
> 			} catch (...) {
> 				/* Supress all exceptions to fulfill noexcept
> ```

I think we should not suppress them here but just terminate - similarly as we do in dtors. If we suppress we might have silent failures in the future. 
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 117 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uPpvDHG8cofXf019:-Me5uPpvDHG8cofXf01A:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L117)):*
> ```cpp
> 					expected_offset, ptr);
> 			} catch (...) {
> 				/* Supress all exceptions to fulfill noexcept
> ```

.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 141 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uRSS64VAAopmQQf1:-Me5uRSS64VAAopmQQf2:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L141)):*
> ```cpp
> 					expected_offset, ptr);
> 			} catch (...) {
> 				/* Supress all exceptions to fulfill noexcept
> ```

.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 165 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uRpS3nqYa39ToVLn:-Me5uRpS3nqYa39ToVLo:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L165)):*
> ```cpp
> 					expected_offset, ptr);
> 			} catch (...) {
> 				/* Supress all exceptions to fulfill noexcept
> ```

.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 221 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uizNBji14GH7Y2Uq:-Me5uizNBji14GH7Y2Ur:bl8n4rm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L221)):*
> ```cpp
> 			return this->fetch_add(1) + 1;
> 		} catch (...) {
> 			/* Be sure that any exception will throw */
> ```

I don't understand the comment. Please add terminate here and a comment, that this should not happen under normal program execution (this applies to operator--/++ but not for compare_exchange)
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 238 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5v8wK9YQaVdF_10TD:-Me5v8wLDyRjf0Bf8jz2:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L238)):*
> ```cpp
> 			return this->fetch_sub(1) - 1;
> 		} catch (...) {
> 			/* Be sure that any exception will throw */
> ```

.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 255 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5v9JP1pmBXAZHXgty:-Me5v9JP1pmBXAZHXgtz:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L255)):*
> ```cpp
> 			return this->fetch_add(diff) + diff;
> 		} catch (...) {
> 			/* Be sure that any exception will throw */
> ```

.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 266 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5v9gPDsjwX37RYzO9:-Me5v9gPDsjwX37RYzOA:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L266)):*
> ```cpp
> 			return this->fetch_sub(diff) - diff;
> 		} catch (...) {
> 			/* Be sure that any exception will throw */
> ```

.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147)* status: 4 of 6 files reviewed, 8 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 93 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uC4X0bzd6usNV06c:-Me6Lu0X7elkD1futYyv:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L93)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think we should not suppress them here but just terminate - similarly as we do in dtors. If we suppress we might have silent failures in the future. 
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 117 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uPpvDHG8cofXf019:-Me6LuqB87LfvazE9jCm:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L117)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 141 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uRSS64VAAopmQQf1:-Me6LvF9E1nuzbPhjhKO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L141)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 165 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uRpS3nqYa39ToVLn:-Me6Lw__3KFYrKLT3IE8:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L165)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 221 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5uizNBji14GH7Y2Uq:-Me6MIFfBfpL49FTecLO:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L221)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't understand the comment. Please add terminate here and a comment, that this should not happen under normal program execution (this applies to operator--/++ but not for compare_exchange)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 238 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5v8wK9YQaVdF_10TD:-Me6MIc50pA03CG7LhDT:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L238)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 255 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5v9JP1pmBXAZHXgty:-Me6MNIuERDKK4I2yh4c:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L255)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 266 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me5v9gPDsjwX37RYzO9:-Me6MN255DH8INtbw2VW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c4f57900fa02000a18c6930639fe4e802e6cfa99/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L266)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-:-Me9cd7FETaNdvGRSAst:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @KFilipek)

**Comment by karczex** [comment]
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 159 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me9wx408xLSnNegYrUm:-Me9vFL257F38RG1dtZQ:bwv1kvy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd22c3e7dc2a941d0e9ac18c2ef44616b296712f/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L159)):*
> ```cpp
> 		if (!result) {
> 			try {
> 				expected = accessor::offset_to_pointer<T>(
> ```

as offset_to_pointer looks like this: 
   ```
    308 »       template <typename PointerType>                                                                       
    309 »       static PointerType *                                                                                  
    310 »       offset_to_pointer(difference_type offset, const access_type &obj)                                     
    311 »       {                                                                                                     
    312 »       »       auto ptr = obj.offset_to_pointer(offset);                                                     
    313 »       »       return static_cast<PointerType *>(ptr);                                                       
    314 »       } 
```

and `obj.offset_to_pointer()` is already noexcept, so maybe we may return nullptr if exception occured durinng static_cast (is it even possible?) and mark offset_to_pointer noexcept?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 159 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-Me9wx408xLSnNegYrUm:-MeA3oKsAdmqugJbqFx1:bj7lobx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fd22c3e7dc2a941d0e9ac18c2ef44616b296712f/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L159)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

as offset_to_pointer looks like this: 
   ```
    308 »       template <typename PointerType>                                                                       
    309 »       static PointerType *                                                                                  
    310 »       offset_to_pointer(difference_type offset, const access_type &obj)                                     
    311 »       {                                                                                                     
    312 »       »       auto ptr = obj.offset_to_pointer(offset);                                                     
    313 »       »       return static_cast<PointerType *>(ptr);                                                       
    314 »       } 
```

and `obj.offset_to_pointer()` is already noexcept, so maybe we may return nullptr if exception occured durinng static_cast (is it even possible?) and mark offset_to_pointer noexcept? 
</blockquote></details>

the problem here is the assignment, not offset_to_pointer

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1147#-:-MeA4m4Z5DMRJc-ldHKb:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
