### PR TITLE
Radix tree: make mt mode a template parameter

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 106 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-MdqxyqrEH-AF7j8xR8g:-MdqxyqrEH-AF7j8xR8h:b-f3kg5g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L106)):*
> ```cpp
>  * - erase and clear does not free nodes/leaves immediately, instead they are
>  * added to a garbage list which can be freed by calling garbage_collect()
>  * - insert_or_assign and iterator.assign_val do not perform in-place update,
> ```

**an** in-place update
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 110 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-Mdr4TqEERWne783Ua7P:-Mdr4TqEERWne783Ua7Q:beuzu4i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L110)):*
> ```
> MtMode enables single-writer multiple-readers
> ```
what about the default value - then you can have only one thread...? pls extend the description
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1080 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-MdqyYxZ-M8gfCRBsIfH:-MdqyYxZ-M8gfCRBsIfI:bveovs0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L1080)):*
> ```cpp
> template <bool Mt, typename Enable>
> void
> radix_tree<Key, Value, BytesView, MtMode>::runtime_initialize_mt(ebr *e)
> ```

what happens if I call this method with `MtMode=false`?
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-Mdr3oWV3tE7skCjICz5:-Mdr3oWV3tE7skCjICz6:b-bfmwg7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L2193)):*
> ```cpp
> template <typename T>
> void
> radix_tree<Key, Value, BytesView, MtMode>::free(persistent_ptr<T> ptr)
> ```

what about a separate free method for `MtMode=false`?
___
*[tests/radix_tree/radix.hpp, line 34 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-MdqwSusDHmhK05i2B09:-MdqwSusDHmhK05i2B0A:b4jolzh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/tests/radix_tree/radix.hpp#L34)):*
> ```cpp
> using container_inline_s_u8t =
> 	nvobjex::radix_tree<nvobjex::basic_inline_string<uint8_t>,
> 			    nvobjex::basic_inline_string<uint8_t>>;
> ```

I know that `MtMode` is false by default, but pls use, at least once, `false` explicitly, e.g. here

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 106 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-MdqxyqrEH-AF7j8xR8g:-Mdr4vByDCJ7vQ9fw41W:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L106)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**an** in-place update
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 110 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-Mdr4TqEERWne783Ua7P:-Mdr5Atf5KBV4Txlv381:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L110)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> ```
> MtMode enables single-writer multiple-readers
> ```
what about the default value - then you can have only one thread...? pls extend the description
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 1080 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-MdqyYxZ-M8gfCRBsIfH:-Mdr5CMmDLH38H0v6Br5:b6xl4vu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L1080)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what happens if I call this method with `MtMode=false`?
</blockquote></details>

You cannot, it won't be compiled (because of this enable_if_
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 2193 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-Mdr3oWV3tE7skCjICz5:-Mdr5HSB50OLOdg_w6XN:b-e4zewx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/include/libpmemobj++/experimental/radix_tree.hpp#L2193)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about a separate free method for `MtMode=false`?
</blockquote></details>

I don't think it's necessary, we need to check for ebr_ ptr anyway at runtime (because if someone called runtime_finalize_mt we cannot use garbage collection, e.g. in dtor).
___
*[tests/radix_tree/radix.hpp, line 34 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-MdqwSusDHmhK05i2B09:-Mdr61Dc2bNfGn9nSwgT:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5caab15fb96b6f8c9edbac47ab81c03a54c1a008/tests/radix_tree/radix.hpp#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know that `MtMode` is false by default, but pls use, at least once, `false` explicitly, e.g. here
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-:-MdrBcuy55X9ejFXduPg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1124#-:-MdrG86CDklkjX2dkSlI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
