### PR TITLE
Add skip flags for additional artifacts built/installed in dockerimages

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/659)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
> What's the purpose of this change? At first glance it looks harmful. If, for some reason you don't want to install pmdk or valgrind using install scripts, just remove invocation of install script from dockerfile.
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/659#-:-M-sBUlo4uTIC6V0fLEW:b4jsi48)_ status: 0 of 4 files reviewed, all discussions resolved

it's for our CI guys, who don't want to play with our dockerfiles, but still want to use different e.g. PMDK version

**Comment by lukaszstolarczuk** [comment]
rebased it to stable-1.7, since we want to support this branch for a while yet

**Comment by igchor** [comment]
@lukaszstolarczuk  build failed

**Comment by lukaszstolarczuk** [comment]
> @lukaszstolarczuk build failed

fixed, needed to rebase it again and force-push (as you suggested)

**Pull request merged**
