### PR TITLE
Extend CMake prints

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026#-:-MSh1-hh22YQ8qweioAj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[cmake/functions.cmake, line 177 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026#-MShHsGK-9MEJiZnr84P:-MShHsGL4r0qkx_U7sqC:b-4xsdkx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a7f923966bb2df54025150efd657882a3783b8af/cmake/functions.cmake#L177)):*
> ```CMake
> 
> 	# otherwise take it from git
> 	execute_process(COMMAND git describe
> ```

In shallow clone git describe just fails. In such case we may set version to 0.0.0-sha1 and print warning.

**Comment by lukaszstolarczuk** [comment]
> > _[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026)_ status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)
> 
> _[cmake/functions.cmake, line 177 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026#-MShHsGK-9MEJiZnr84P:-MShHsGL4r0qkx_U7sqC:b-4xsdkx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a7f923966bb2df54025150efd657882a3783b8af/cmake/functions.cmake#L177)):_
> 
> > ```cmake
> > 	# otherwise take it from git
> > 	execute_process(COMMAND git describe
> > ```
> 
> In shallow clone git describe just fails. In such case we may set version to 0.0.0-sha1 and print warning.

yes, but if you look closely then we go to the `else` statement and we read `git log -1` ;) and here we have sha commit only

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1026#-:-MShOoHM3S-jYos2R8R-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
