### PR TITLE
concurrent_map: implement lower and lower_eq methods

### PR DESCRIPTION
**Pull request by igchor**
If you have any ideas for better names, I'm open for suggestions.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861)

### CODE REVIEW

**Review by szyrom — APPROVED** [review]
implementation wise: lgtm;

regarding names:
we already have:
lower_bound
upper_bound

and find_lower is kind of equivalent to upper_bound but with negations of comparator (same like find_lower_eq is equivalent to lower_bound)

proposition (but I like both versions):
find_lower -> rupper_bound
find_lower_eq -> rlower_bound

?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-:-MHLD8_T7ySuUlL9poPb:b-odjg5x)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 2688 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp14t16DRJKGKuA9vL:-MHovo0s05lpdBESaoWn:bb7z2ju) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L2688)):*
> ```cpp
> 	 */
> 	template <typename K, typename comparator>
> 	const_iterator
> ```

As this method is template anyway, I suggest to make iterator type also template parameter instead of doing const_casts in callers.
___
*[tests/map/map_find_lower_lower_eq.cpp, line 27 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp6g-XDmi2MECVBurR:-MHp6g-XDmi2MECVBurS:bwcwah1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/tests/map/map_find_lower_lower_eq.cpp#L27)):*
> ```cpp
> template <bool IsConst>
> void
> test_find_lower(nvobj::pool<root> &pop)
> ```

Please add tests description and some comments - i.e. overall idea of splitting test into two scopes. 
___
*[tests/map/map_find_lower_lower_eq.cpp, line 130 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp6hJp17nfD01ziNEg:-MHp6hJp17nfD01ziNEh:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/tests/map/map_find_lower_lower_eq.cpp#L130)):*
> ```cpp
> template <bool IsConst>
> void
> test_find_lower_eq(nvobj::pool<root> &pop)
> ```

.
___
*[tests/map/map_find_lower_lower_eq.cpp, line 255 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp7WnLAsblNvcSxJg-:-MHp7WnLAsblNvcSxJg0:br55xgy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/tests/map/map_find_lower_lower_eq.cpp#L255)):*
> ```cpp
> 
> 		for (size_t i = 2; i < TEST_ELEMENTS * 3; i++) {
> 			auto l = m.find_lower(i);
> ```

please change variable name. In many fonts "l" looks similar to "1", and may cause confusion.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp, line 2688 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp14t16DRJKGKuA9vL:-MHp9G3pBdgj9-sKK0BQ:bxdtz7s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/include/libpmemobj++/container/detail/concurrent_skip_list_impl.hpp#L2688)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

As this method is template anyway, I suggest to make iterator type also template parameter instead of doing const_casts in callers.
</blockquote></details>

It's not so easy, because the method must also be marked as const (and that's impossible to parametrize).
___
*[tests/map/map_find_lower_lower_eq.cpp, line 27 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp6g-XDmi2MECVBurR:-MHpBJ_a55HQrxhjpmTC:bivw2zy) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/tests/map/map_find_lower_lower_eq.cpp#L27)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Please add tests description and some comments - i.e. overall idea of splitting test into two scopes. 
</blockquote></details>

Done. The spliting is just for simplicity, I don'y know what more can I write here.
___
*[tests/map/map_find_lower_lower_eq.cpp, line 130 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp6hJp17nfD01ziNEg:-MHpBQU21nBIXoPUYtIe:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/tests/map/map_find_lower_lower_eq.cpp#L130)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tests/map/map_find_lower_lower_eq.cpp, line 255 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-MHp7WnLAsblNvcSxJg-:-MHpBQyL5Bx05ukTX5RV:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e32ba01bd9a2ab62167ae47fbadc76245ecce7f4/tests/map/map_find_lower_lower_eq.cpp#L255)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

please change variable name. In many fonts "l" looks similar to "1", and may cause confusion.  
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/861#-:-MHpI6DA6oCchg4plk7k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
