### PR TITLE
transaction: expose API to control transaction behaviour on error

### PR DESCRIPTION
**Pull request by igchor**
With this patch, user can disable automatic tx abort in case of
any failure. Error handling can be then done using exceptions.

If an exception is caught inside of the transaction then the transaction
simply commits. Otherwise, exception is ignored by all inner transactions
and propagated to the outer one which calls pmemobj_tx_abort().

Requires: https://github.com/pmem/pmdk/pull/4654

Closes https://github.com/pmem/libpmemobj-cpp/issues/516

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/transaction.hpp, line 97 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIiaq82U6KJMTxTleR:-MGIiaq82U6KJMTxTleS:b-xdwav1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L97)):*
> ```cpp
> 	private:
> 		failure_behavior failure_behavior_ =
> 			failure_behavior::LIBPMEMOBJ_CPP_TX_FAILURE_EVENT;
> ```

Setting this default parameter compile time, and exposing setter to change this in runtime may cause user's confusion. 
Why not left default value always `return_error`, and left to user explicitly call setter if need to change it? 
___
*[include/libpmemobj++/transaction.hpp, line 144 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIkv4BBS8asM3EDMWd:-MGIkv4BBS8asM3EDMWe:b-nat3jm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L144)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 				if (opts.failure_behavior_ ==
> 					    failure_behavior::abort &&
> 				    pmemobj_tx_get_failure_behavior() ==
> 					    POBJ_TX_FAILURE_RETURN)
> ```
</details>


if( opts.failure_bahavior != pmemovb_tx_get_failure_bahavior)  ??
___
*[include/libpmemobj++/transaction.hpp, line 168 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIn19P35gTnfHOiKpP:-MGIn19P35gTnfHOiKpQ:bz1syw7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L168)):*
> ```cpp
> 
> 			pmemobj_tx_set_failure_behavior(
> 				(pobj_tx_failure_behavior)
> ```

why you need to cast here?

**Comment by lukaszstolarczuk** [comment]
shouldn't we require PMDK 1.9 for this to work...?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[include/libpmemobj++/transaction.hpp, line 97 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIiaq82U6KJMTxTleR:-MGmAuK-2RTuiCS4OIyc:bi20kr) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L97)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Setting this default parameter compile time, and exposing setter to change this in runtime may cause user's confusion. 
Why not left default value always `return_error`, and left to user explicitly call setter if need to change it? 

</blockquote></details>

The problem is backward compatibility. If we set this to return_error by default some old code might stop working. On the other hand, if we set it to abort by default we would have to manually use options for all our internal transaction starting. With the macro approach we also break the compatibility, but it's quite easy for user to opt-out - he just needs to add one define when compiling.
___
*[include/libpmemobj++/transaction.hpp, line 144 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIkv4BBS8asM3EDMWd:-MGmBKWrCw-LOt2B6pQO:b-7tve6m) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L144)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

> ```
> 				if (opts.failure_behavior_ ==
> 					    failure_behavior::abort &&
> 				    pmemobj_tx_get_failure_behavior() ==
> 					    POBJ_TX_FAILURE_RETURN)
> ```

if( opts.failure_bahavior != pmemovb_tx_get_failure_bahavior)  ??
</blockquote></details>

No, it's prefectly fine if you want to start "failure return" transaction inside "failure abort" transaction. The problem is only the other way around because the internal transaction would cause abort and that's conflicting with the outer one behavior. (Remember that transactions are flattened-out to if there is an abort in internal tx, it will also cause external tx abort).
___
*[include/libpmemobj++/transaction.hpp, line 168 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIn19P35gTnfHOiKpP:-MGmBt3k1SNTRHY69_aH:bxax6pw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L168)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

why you need to cast here?
</blockquote></details>

Because opts.failure_bahvior_is my enum and not C type.

**Review by igchor — COMMENTED** [review]
Yes, done.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-:-MGs9siu1n8n4_3wEjWp:b60r506)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/transaction.hpp, line 97 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIiaq82U6KJMTxTleR:-MHLsaGO7BhQEHjwj2hg:b-rgqydk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L97)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

The problem is backward compatibility. If we set this to return_error by default some old code might stop working. On the other hand, if we set it to abort by default we would have to manually use options for all our internal transaction starting. With the macro approach we also break the compatibility, but it's quite easy for user to opt-out - he just needs to add one define when compiling.
</blockquote></details>

As we talked offline: 
Consider to left default parameter  to be *abort* with deprecation warning.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/transaction.hpp, line 78 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrFk6qAmtQ1F8B3cMa:-MHrFk6qAmtQ1F8B3cMb:bwtuwuz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L78)):*
> ```cpp
> 	class manual;
> 
> 	/** Specifies failure event in case of transaction error */
> ```

of **a** transaction..
___
*[include/libpmemobj++/transaction.hpp, line 95 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrF31a7u4SkTGS4_dS:-MHrF31a7u4SkTGS4_dT:b-mqbn6t) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L95)):*
> ```cpp
> 	 */
> 	struct options {
> 		/** Controls behavior of transaction in case of errors. It can
> ```

of **a** transaction
___
*[include/libpmemobj++/transaction.hpp, line 96 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrF6Pr1CmymV1dTYOw:-MHrF6Pr1CmymV1dTYOx:bkecd8a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L96)):*
> ```cpp
> 	struct options {
> 		/** Controls behavior of transaction in case of errors. It can
> 		 * be failure_behavior::abort or failure_behavior::return_error.
> ```

add one space before the final `.` - when they are together, doxygen may not create the link
___
*[include/libpmemobj++/transaction.hpp, line 285 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrNOht2Zv2E8FcqQR5:-MHrNOht2Zv2E8FcqQR6:b-e8f633) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L285)):*
> ```cpp
> 		 *
> 		 * @param[in,out] pop pool object.
> 		 * @param[in] opts options for controlling transaction behavior
> ```

add `.` at the end
___
*[include/libpmemobj++/transaction.hpp, line 298 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrNYSP-jugFojzgtOj:-MHrNYSP-jugFojzgtOk:bvse67d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L298)):*
> ```cpp
> 		}
> 
> 		template <typename... L>
> ```

add description...?
___
*[include/libpmemobj++/transaction.hpp, line 461 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrNbUNC2BRvEsVjWMv:-MHrNbUODUgs_tHzSaTS:b-mvlem2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L461)):*
> ```cpp
> 	}
> 
> 	template <typename... Locks>
> ```

add desc...?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

___
*[include/libpmemobj++/transaction.hpp, line 97 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MGIiaq82U6KJMTxTleR:-MHklCU70yJDlFU2k2_V:bmmjzw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d1e70f48fe71167ca3f1b970afe7a5fa159b5625/include/libpmemobj++/transaction.hpp#L97)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

As we talked offline: 
Consider to left default parameter  to be *abort* with deprecation warning. 
</blockquote></details>

Decided to go with the current approach
___
*[include/libpmemobj++/transaction.hpp, line 78 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrFk6qAmtQ1F8B3cMa:-MHtcZn16YeaPdNWa_uK:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L78)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of **a** transaction..
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 95 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrF31a7u4SkTGS4_dS:-MHtcdSW1l9PwOhv-5jw:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L95)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

of **a** transaction
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 96 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrF6Pr1CmymV1dTYOw:-MHtchfyBrDj8WErnDbK:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L96)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add one space before the final `.` - when they are together, doxygen may not create the link
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 285 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrNOht2Zv2E8FcqQR5:-MHtcp5_0i0b6mHScK6Y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L285)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add `.` at the end
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 298 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrNYSP-jugFojzgtOj:-MHtcvXS79-VyV4REtVF:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L298)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add description...?
</blockquote></details>

Done.
___
*[include/libpmemobj++/transaction.hpp, line 461 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHrNbUNC2BRvEsVjWMv:-MHtd9L25vQ-8mIDYxP5:b6p9szp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7928721654117a91c9eb51707fd036e76fd2f0ef/include/libpmemobj++/transaction.hpp#L461)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add desc...?
</blockquote></details>

I initially wanted to have a description only for version with options. But even though I wrote that options param is optional it could still be misleading so: done.

**Review by vinser52 — COMMENTED** [review]
> Reviewed 2 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[include/libpmemobj++/transaction.hpp, line 154 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723#-MHzZk8bEstdP_mltS7N:-MHzZk8bEstdP_mltS7O:btbs0q7) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8073cce9bd91ab5be638600333148551816db50d/include/libpmemobj++/transaction.hpp#L154)):*
> ```cpp
> 					    POBJ_TX_FAILURE_RETURN)
> 					throw pmem::transaction_error(
> 						"Cannot start transaction with failure_behavior::abort. Outer transaction was configured with failure_behavior::return_error");
> ```

Need to discuss how to deal with cases when nested transaction is opened in a third-party library.

**Review by vinser52 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/723)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

**Comment by igchor** [comment]
Redone https://github.com/pmem/libpmemobj-cpp/pull/932

**Pull request closed without merging**
