### PR TITLE
CI: update valgrind to 3.17

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1196)

### CODE REVIEW

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1196#-:-MiuQAgr2slSCAXkpzo2:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
I've rebased it to stable-1.13, since we require it for #1173 (and it's best suited for the last release branch, I believe)

**Review by karczex — COMMENTED** [review]
Please add some comment to commit message,  why we need this update.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1196#-:-Mj3YQliAOZ9ir4_BIIu:b3kgla1)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
@karczex, done - commit msg extended.

**Pull request merged**
