### PR TITLE
Add gdbserver support to ctest

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212)

### CODE REVIEW

**Review by KFilipek — APPROVED** [review]
Feature that everybody want, but nobody asked: :lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-:-Mkv944L512zS0UwSkNX:b-q6f16r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-:-MkvHRGVCuTsHpL5TgpJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex)

___
*[CONTRIBUTING.md, line 156 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvMGD69g2FSBP08NNE:-MkvMGD74Rh5Yl2i6dMR:bm8ngcj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L156)):*
> ```Markdown
> Test framework supports debugging under gdb.
> 
> * For remote debugging set `GDBSERVER` environment variable, which would be passed as argument to gdbserver
> ```

what should this variable contain?
___
*[CONTRIBUTING.md, line 156 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvN2JR15veJcnubjgE:-MkvN2JR15veJcnubjgF:b-2swgsd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L156)):*
> ```Markdown
> Test framework supports debugging under gdb.
> 
> * For remote debugging set `GDBSERVER` environment variable, which would be passed as argument to gdbserver
> ```

`which will be passed`
___
*[CONTRIBUTING.md, line 157 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvMWjBEmTPUNI-29Pe:-MkvMWjBEmTPUNI-29Pf:bj2qdsw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L157)):*
> ```Markdown
> 
> * For remote debugging set `GDBSERVER` environment variable, which would be passed as argument to gdbserver
> application:
> ```

perhaps:
`... application. Example usage with a single test:`
___
*[CONTRIBUTING.md, line 159 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvMNJT9w0W8WDldrRu:-MkvMNJT9w0W8WDldrRv:bpyht4s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L159)):*
> ```Markdown
> application:
> 
> ```
> ```

pls make it ` ```sh`
___
*[tests/helpers.cmake, line 136 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvAv6p-fqKzyCzmHmq:-MkvAv6p-fqKzyCzmHmr:bd0lq1y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/tests/helpers.cmake#L136)):*
> ```CMake
>     set(cmd ${TRACE} ${name} ${ARGN})
> 
>     if(DEFINED ENV{CGDB} AND DEFINED ENV{GDBSERVER})
> ```

hmm since the `DEFINED` may be quite useful to have, perhaps we should update the above `if (NOT $ENV{CGDB})`...?
and the below one, as well (` if($ENV{CGDB})`)...?
___
*[tests/helpers.cmake, line 137 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvIxH1C8UtiQo8gQV6:-MkvIxH1C8UtiQo8gQV7:bfjk25e) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/tests/helpers.cmake#L137)):*
> ```CMake
> 
>     if(DEFINED ENV{CGDB} AND DEFINED ENV{GDBSERVER})
> 	message(FATAL_ERROR "CGDB and GDBSERVER shouldn't be used at the same time."
> ```

add one more tab here please
___
*[tests/helpers.cmake, line 141 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvKsCn8trs8IVtdpA1:-MkvKsCn8trs8IVtdpA2:bsej3lj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/tests/helpers.cmake#L141)):*
> ```CMake
>     endif()
> 
>     if($ENV{CGDB})
> ```

maybe this should be `else if` to the previous `if`...? and already connect it with the next `if`

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 156 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvMGD69g2FSBP08NNE:-MkvireF5T0sxRO38eqj:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L156)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what should this variable contain?
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 156 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvN2JR15veJcnubjgE:-MkveXED-e1w6BXS84_-:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L156)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`which will be passed`
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 157 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvMWjBEmTPUNI-29Pe:-MkveVUnBZgsVAIvH-bz:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L157)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps:
`... application. Example usage with a single test:`
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 159 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvMNJT9w0W8WDldrRu:-MkveVJyC1_8F_Vg-nFQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/CONTRIBUTING.md#L159)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it ` ```sh`
</blockquote></details>

Done.
___
*[tests/helpers.cmake, line 136 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvAv6p-fqKzyCzmHmq:-Mkvn87sCbcBryqfhWaX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/tests/helpers.cmake#L136)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm since the `DEFINED` may be quite useful to have, perhaps we should update the above `if (NOT $ENV{CGDB})`...?
and the below one, as well (` if($ENV{CGDB})`)...?
</blockquote></details>

Done.
___
*[tests/helpers.cmake, line 137 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvIxH1C8UtiQo8gQV6:-Mkvn3hT0_95MIoBxQCV:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/tests/helpers.cmake#L137)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add one more tab here please
</blockquote></details>

Done.
___
*[tests/helpers.cmake, line 141 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvKsCn8trs8IVtdpA1:-MkvjBFK07P7-VKFXul8:b-pvrn7u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/fbaf8534b1af7d0be7ca4c4d085d4df0eb65fdd9/tests/helpers.cmake#L141)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe this should be `else if` to the previous `if`...? and already connect it with the next `if`
</blockquote></details>

To nested logic for such simple thing. To avoid that I added FATAL_ERROR in line 137, which should be enough.    

IMO If possible(I didn't check cmake versions in OSes), we should switch to cmake >= 3.18 and replace many `if`s with `REQUIRED` parameter to find_program.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 8 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-Mkvqulv5MeWqSyX71Qj:-Mkvt92O8yNy9yIPPEZk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/60163c1ac67d9f3b6a561b6ea4be0adfd168ba52/CONTRIBUTING.md#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add the new section link here
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 157 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-MkvqozxDLqSKfQJV64P:-Mkvt8dK-ABufcMDswWP:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/60163c1ac67d9f3b6a561b6ea4be0adfd168ba52/CONTRIBUTING.md#L157)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell - `communicate`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
thx! :lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1212#-:-Mkw2wgc62NnWKkryuMT:b-k6vq0a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
