### PR TITLE
Clean docker images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
It's a continuation of #1031

Preview with all OSes enabled:
~~https://github.com/lukaszstolarczuk/libpmemobj-cpp/actions/runs/662006158~~
new preview: https://github.com/lukaszstolarczuk/libpmemobj-cpp/actions/runs/667687106

FYI, Fedora Rawhide is using PMDK and Valgrind installed using dnf.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 11 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-:-MW3QJ5T5AqW8taz_Nfu:bnfp4nl)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-:-MW3y1N2BagS9fK9OZvI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.centos-8, line 94 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-MW8lbn2ArAx80Gv99rS:-MW8lbn4DHb2NCPqY57T:b-y0nxkn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ffa00a7c6c3b6890e351f8aff262d9991c4adad2/utils/docker/images/Dockerfile.centos-8#L94)):*
> ```
> 	${TESTS_DEPS} \
> 	${MISC_DEPS} \
>  && dnf clean all
> ```

As I can see, you update and clean dnf  cache here and there little bit inconsistently, so you end up with bigger layers to download. 
___
*[utils/docker/images/Dockerfile.debian-unstable, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-MW8nAaw6gYjI9ixp-ie:-MW8nAaxEXOgoReACs6F:br8edqw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ffa00a7c6c3b6890e351f8aff262d9991c4adad2/utils/docker/images/Dockerfile.debian-unstable#L72)):*
> ```
> 	pkg-config \
> 	sudo \
> 	whois"
> ```

Why we need this pkg in container?
___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 92 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-MW8nROh-jIYbbYlRK5T:-MW8nROh-jIYbbYlRK5U:b-x0dzd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ffa00a7c6c3b6890e351f8aff262d9991c4adad2/utils/docker/images/Dockerfile.opensuse-leap-latest#L92)):*
> ```
> 
> # Clean the package cache
> RUN zypper clean all
> ```

Cleaning  in separate layer doesn't provide any benefit

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059)* status: 9 of 16 files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[utils/docker/images/Dockerfile.centos-8, line 94 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-MW8lbn2ArAx80Gv99rS:-MW8xupiELwxoysoZPJk:b-el7z2n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ffa00a7c6c3b6890e351f8aff262d9991c4adad2/utils/docker/images/Dockerfile.centos-8#L94)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

As I can see, you update and clean dnf  cache here and there little bit inconsistently, so you end up with bigger layers to download. 
</blockquote></details>

it's not what I did, we have it for a long time, but good point.
___
*[utils/docker/images/Dockerfile.debian-unstable, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-MW8nAaw6gYjI9ixp-ie:-MW92dJ23wMtvA-L0QMw:bqyzqur) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ffa00a7c6c3b6890e351f8aff262d9991c4adad2/utils/docker/images/Dockerfile.debian-unstable#L72)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Why we need this pkg in container?
</blockquote></details>

I believe it delivers 'mkpasswd' command (used for user creation)
___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 92 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-MW8nROh-jIYbbYlRK5T:-MW92N7JBV1mXSgr_37C:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ffa00a7c6c3b6890e351f8aff262d9991c4adad2/utils/docker/images/Dockerfile.opensuse-leap-latest#L92)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Cleaning  in separate layer doesn't provide any benefit
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1059#-:-MW9cX171Nmqgk80-0YW:bnfp4nl)* status: 9 of 16 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
