### PR TITLE
cleanup in docker scripts after latest doc job changes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- update comments,
- update RELEASE_STEPS.md,
- remove unused code and variables,
- turn off benchmarks' building in run-doc-update.sh

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex and @lukaszstolarczuk)

___
*[.github/workflows/gha.yml, line 59 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855#-MGmA8TK1KgKo2fmxaRz:-MGmA8TLDI8fqwXJCl_K:bbuc3rx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/12c98c1d7a3780ca37c96fcc8124c720887066d0/.github/workflows/gha.yml#L59)):*
> ```YAML
>         DOC_UPDATE_BOT_NAME:       ${{ secrets.DOC_UPDATE_BOT_NAME }}
>         DOC_REPO_OWNER:            ${{ secrets.DOC_REPO_OWNER }}
>         GITHUB_TOKEN:              ${{ secrets.GITHUB_TOKEN }}
> ```

Why? Isn't this needed for hub?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

___
*[.github/workflows/gha.yml, line 59 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855#-MGmA8TK1KgKo2fmxaRz:-MGmBKaNBkGo3_DER55D:bln1th1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/12c98c1d7a3780ca37c96fcc8124c720887066d0/.github/workflows/gha.yml#L59)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why? Isn't this needed for hub?
</blockquote></details>

we use `DOC_UPDATE_GITHUB_TOKEN`, which is a better name (it points why we need this var), and then, in the run-doc-update.sh we have `export GITHUB_TOKEN=${DOC_UPDATE_GITHUB_TOKEN}`.
So, I believe it's not needed and not valid anymore (we don't have such secret set in GH).

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/855#-:-MHBg0OE3TuJH-udFQZ2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
