### PR TITLE
Update doxygen config

### PR DESCRIPTION
**Pull request by karczex**
This PR is build on top of https://github.com/pmem/libpmemobj-cpp/pull/1074 with some output tweaks.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
Can we change the "Module" into "Group" or something similar? Usually, module means some standalone package/unit and not a collection of different classes.

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-:-Mfc3Djq5igpmPsi2JN1:b-c75emm)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc3mny8cVpyr5O2a1Q:-Mfc3mny8cVpyr5O2a1R:b-hrlsf3) (no related file):*
Regarding modules' names, I would suggest following change:

Data residency -> Allocation
Data accessors -> Data views
Split primitives into primitives and synchronization

Also, some things are missing I think (e.g pool, ctl)

---

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 0 of 37 files reviewed, 5 unresolved discussions (waiting on @igchor and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc3M0g2YWe7ZzrSzul:-Mfc3M0g2YWe7ZzrSzum:brvg0hs) (no related file):*
pls update CONTRIBUTING.md and mention docs grouping (`@ingroup`)

---
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc4KvoCMDL8rcxZLJo:-Mfc4Kvp0oxI-GSqNXyY:bu7x22e) (no related file):*
pls add ref (in some commit msg) to #1010 

---
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc4T-q25mvbJeddhtv:-Mfc4T-q25mvbJeddhtw:b-wmjfys) (no related file):*
misspell in commit message `Increarease` -> `Increase`

---
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc3mny8cVpyr5O2a1Q:-Mfc4idG-0kPZJxiPjaw:b4nxls5) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Regarding modules' names, I would suggest following change:

Data residency -> Allocation
Data accessors -> Data views
Split primitives into primitives and synchronization

Also, some things are missing I think (e.g pool, ctl)

</blockquote></details>

do we want to have everything grouped? or just "the most important" classes...?

I guess, all public API should be assigned to some groups (so I think I agree with Igor :wink: )

---
___
*[doc/libpmemobj++.Doxyfile.in, line 872 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc3r5I4PbI7k3tybMF:-Mfc3r5I4PbI7k3tybMG:bt2ou4h) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b32385f82c1458859bbc2fa4969149350779ed92/doc/libpmemobj++.Doxyfile.in#L872)):*
> ```
> INPUT                  = @LIBPMEMOBJCPP_ROOT_DIR@/include/libpmemobj++ \
>                          @LIBPMEMOBJCPP_ROOT_DIR@/include/libpmemobj++/README.md \
>                          @LIBPMEMOBJCPP_ROOT_DIR@/doc/group_defs.dox
> ```

1. can you deliver at least a stub of this file (this '.dox' file perhaps requires some special syntax...?)
2. and please rename to e.g. `groups_definitions`

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 16 files at r1, 1 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 2 of 37 files reviewed, 5 unresolved discussions (waiting on @igchor and @karczex)

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 2 of 37 files reviewed, 6 unresolved discussions (waiting on @igchor and @karczex)

___
*[doc/libpmemobj++.Doxyfile.in, line 494 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfgNm_ADP0osfScEVbP:-MfgNm_ADP0osfScEVbQ:bnvtfjd) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b32385f82c1458859bbc2fa4969149350779ed92/doc/libpmemobj++.Doxyfile.in#L494)):*
> ```
> EXTRACT_PRIVATE        = YES
> ```
I think it should be disabled, to avoid generating documentation for garbage like helpers methods in string, output there is massive

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 1 of 43 files reviewed, 6 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc3M0g2YWe7ZzrSzul:-Mfgm7-t6S_K6W0gCuAW:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls update CONTRIBUTING.md and mention docs grouping (`@ingroup`)
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc4KvoCMDL8rcxZLJo:-Mfg-06S3UOxyoQVJaMQ:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls add ref (in some commit msg) to #1010 
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc4T-q25mvbJeddhtv:-Mfg-0UpBqX43-YSQR9A:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

misspell in commit message `Increarease` -> `Increase`
</blockquote></details>

Done.

---
___
*[doc/libpmemobj++.Doxyfile.in, line 494 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfgNm_ADP0osfScEVbP:-Mfgm4I651EMHlVvd8dy:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b32385f82c1458859bbc2fa4969149350779ed92/doc/libpmemobj++.Doxyfile.in#L494)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> EXTRACT_PRIVATE        = YES
> ```
I think it should be disabled, to avoid generating documentation for garbage like helpers methods in string, output there is massive
</blockquote></details>

Done.
___
*[doc/libpmemobj++.Doxyfile.in, line 872 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfc3r5I4PbI7k3tybMF:-Mfg-hBwE37jmftTfZML:bs7wumx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b32385f82c1458859bbc2fa4969149350779ed92/doc/libpmemobj++.Doxyfile.in#L872)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. can you deliver at least a stub of this file (this '.dox' file perhaps requires some special syntax...?)
2. and please rename to e.g. `groups_definitions`
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 6 of 16 files at r1, 33 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-:-MfgvIxs7BzZm0z2kQio:bnfp4nl)* status: 39 of 43 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[doc/libpmemobj++.Doxyfile.in, line 842 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfgu7kj8l6bct2M-1ny:-Mfgu7kj8l6bct2M-1nz:bulu288) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/doc/libpmemobj++.Doxyfile.in#L842)):*
> ```
> # or unneeded files are turned off (from doxygen)
> #WARN_AS_ERROR          = @DOXYGEN_WARN_AS_ERROR@
> WARN_AS_ERROR          = NO
> ```

Could you create an issue for this (unless we already have one)?

**Review by KFilipek — COMMENTED** [review]
> Reviewed 7 of 16 files at r1, 1 of 28 files at r2, 35 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[include/libpmemobj++/timed_mutex.hpp, line 31 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh8idy6ggI2loTe4xl:-Mfh8idy6ggI2loTe4xm:b-4s9upt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/timed_mutex.hpp#L31)):*
> ```cpp
>  * concepts. The typical usage example would be:
>  * @snippet mutex/mutex.cpp timed_mutex_example
>  * @ingorup primitives
> ```

@ingroup
___
*[include/libpmemobj++/container/segment_vector.hpp, line 661 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh8zXf2bUaEJQrYW-b:-Mfh8zXg04YP4U0zyYuX:b-4gqvfh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/container/segment_vector.hpp#L661)):*
> ```cpp
> /* Non-member swap
>  * @relates segment_vector
>  * */
> ```

replace
```cpp
 * */
```
with
```cpp
*/
```
___
*[include/libpmemobj++/container/vector.hpp, line 258 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh9C3_8_Byy0wkm14r:-Mfh9C3_8_Byy0wkm14s:b-5aoyv4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/container/vector.hpp#L258)):*
> ```cpp
> /* Non-member swap
>  * @relates vector
>  * */
> ```

same story
___
*[include/libpmemobj++/detail/temp_value.hpp, line 37 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh9WWsDg74cY4BZCtl:-Mfh9WWsDg74cY4BZCtm:bf70zqg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/detail/temp_value.hpp#L37)):*
> ```cpp
> struct temp_value;
> 
> /*
> ```

If it should be ignored by Doxygen just skip my comment

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 40 of 43 files reviewed, 7 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[doc/libpmemobj++.Doxyfile.in, line 842 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfgu7kj8l6bct2M-1ny:-MfhIsSc6cbPtj7ka4dD:boxob3y) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/doc/libpmemobj++.Doxyfile.in#L842)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you create an issue for this (unless we already have one)?
</blockquote></details>

 https://github.com/pmem/libpmemobj-cpp/issues/1182
___
*[include/libpmemobj++/timed_mutex.hpp, line 31 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh8idy6ggI2loTe4xl:-MfhCOsdEMAH2TsWH6K_:b-wyb67j) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/timed_mutex.hpp#L31)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

@ingroup
</blockquote></details>

  Good catch. Done
___
*[include/libpmemobj++/container/segment_vector.hpp, line 661 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh8zXf2bUaEJQrYW-b:-MfhCyZJ7R2yJ7TMaLtC:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/container/segment_vector.hpp#L661)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

replace
```cpp
 * */
```
with
```cpp
*/
```
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/vector.hpp, line 258 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh9C3_8_Byy0wkm14r:-MfhD3L8EEkFr2U-AXqG:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/container/vector.hpp#L258)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

same story
</blockquote></details>

Done.

**Comment by KFilipek** [comment]
```
include/libpmemobj++/make_persistent_array.hpp:1: error: wrong copyright date: (is: 2016-2020, should be: 2016-2021)
include/libpmemobj++/make_persistent_atomic.hpp:1: error: wrong copyright date: (is: 2016-2020, should be: 2016-2021)
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 8 of 16 files at r1, 30 of 35 files at r4, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: all files reviewed, 10 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[CONTRIBUTING.md, line 40 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhN-P0BL5eZ45cGNo1:-MfhN-P0BL5eZ45cGNo2:b-op1txv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/CONTRIBUTING.md#L40)):*
> ```Markdown
> * Each new feature should be documented using doxygen comment blocks.
> * Each non-member function should be added to corresponding class documentation by `@relates` tag
> * Each new API should be assigned to group by `@ingroup` tag. See `doc/groups_definitions.dox` file in the repository for details.
> ```

you can add a link to the file, actually
___
*[doc/groups_definitions.dox, line 2 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhNye15eXAreuShx6l:-MfhNye15eXAreuShx6m:b-mi1ibs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/doc/groups_definitions.dox#L2)):*
> ```
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2018-2021, Intel Corporation
> ```

`2021` should be enough
___
*[include/libpmemobj++/pool.hpp, line 49 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhPnpM-lLlN_M2HOcf:-MfhPnpM-lLlN_M2HOcg:bhcm3wm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/include/libpmemobj++/pool.hpp#L49)):*
> ```cpp
>  * The exmple of using pool with RAII idiom:
>  * @snippet pool/pool_as_class_member.cpp  pool_class_member_example
>  *
> ```

why the empty line? Did you want to add something here? perhaps it should be in the primitives group (since it's a public class)
___
*[include/libpmemobj++/detail/temp_value.hpp, line 37 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh9WWsDg74cY4BZCtl:-MfhT-Ky-P67Zzoxqfdu:b-75f66v) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/detail/temp_value.hpp#L37)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

If it should be ignored by Doxygen just skip my comment
</blockquote></details>

If I remember correctly, this comment made our lives harder and we decided to disable it in Doxygen parsing... and it's just a detail ns. 
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 26 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhTQ-F6whfsVtJYhLu:-MfhTQ-F6whfsVtJYhLv:b-rhkhcs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L26)):*
> ```cpp
>  * Doesn't automatically add itself to the transaction.
>  * The user is responsible for persisting the data.
>  *
> ```

remove this empty line (?)
___
*[utils/docker/run-doc-update.sh, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhUACp1D4DWfujIypZ:-MfhUACp1D4DWfujIyp_:b-dzqx6c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L50)):*
> ```Shell
> pushd ${REPO_DIR}
> echo "Clone repo:"
> git clone --origin Local ${LOCAL_REPO} ${REPO_DIR}
> ```

lowercase `local`, for consistency
___
*[utils/docker/run-doc-update.sh, line 52 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhULdw-LjTGWxPb5Wx:-MfhULdw-LjTGWxPb5Wy:bqgrzud) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L52)):*
> ```Shell
> git clone --origin Local ${LOCAL_REPO} ${REPO_DIR}
> cd ${REPO_DIR}
> git remote add origin ${UPSTREAM}
> ```

UPSTREAM -> ORIGIN
___
*[utils/docker/run-doc-update.sh, line 60 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhVM7I3woVPBNEG_3e:-MfhVM7I3woVPBNEG_3f:b6h36sx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L60)):*
> ```Shell
> 
> git remote update
> git checkout -B ${TARGET_BRANCH} Local/${TARGET_BRANCH}
> ```

does this change work for you? if you're not on master/stable branch this script should exit (in the `if` section on top of the file)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 8 of 43 files reviewed, 10 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 40 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhN-P0BL5eZ45cGNo1:-MfkXJXJ0vj5c0fDUkxk:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/CONTRIBUTING.md#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can add a link to the file, actually
</blockquote></details>

Done.
___
*[doc/groups_definitions.dox, line 2 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhNye15eXAreuShx6l:-MfkURxY8mcQG7Ei9c2X:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/doc/groups_definitions.dox#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`2021` should be enough
</blockquote></details>

Done.
___
*[include/libpmemobj++/pool.hpp, line 49 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhPnpM-lLlN_M2HOcf:-MfkUswA23Jds_6BOt32:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/include/libpmemobj++/pool.hpp#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why the empty line? Did you want to add something here? perhaps it should be in the primitives group (since it's a public class)
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp, line 26 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhTQ-F6whfsVtJYhLu:-MfkVo881ITDUrR1TRgI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/include/libpmemobj++/experimental/atomic_self_relative_ptr.hpp#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remove this empty line (?)
</blockquote></details>

Done.
___
*[utils/docker/run-doc-update.sh, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhUACp1D4DWfujIypZ:-MfkS58x3vqlMx1fqKEp:b76qevz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

lowercase `local`, for consistency
</blockquote></details>

:)
It cannot be done consistently. On one hand `local` is keyword in bash, on the other hand "local" is a word, which is commonly used to describe branch like this one. 
___
*[utils/docker/run-doc-update.sh, line 52 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhULdw-LjTGWxPb5Wx:-MfkRzH-1wmsbEX_Rd4D:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

UPSTREAM -> ORIGIN
</blockquote></details>

Done.
___
*[utils/docker/run-doc-update.sh, line 60 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhVM7I3woVPBNEG_3e:-MfkTdLy3dI0hgAg7VX-:bpwy3cj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L60)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

does this change work for you? if you're not on master/stable branch this script should exit (in the `if` section on top of the file)
</blockquote></details>

It works, as I'm doing changes on my local master. I don't want to change basic functionality of this script, rather make it little bit more usable.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 35 files at r9, 32 of 34 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-:-MflIuSIBGRr7WqNe1ef:bnfp4nl)* status: 42 of 43 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[utils/docker/run-doc-update.sh, line 50 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhUACp1D4DWfujIypZ:-MflHuYO4eQ3XXD-W2NY:bcy3h88) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L50)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

:)
It cannot be done consistently. On one hand `local` is keyword in bash, on the other hand "local" is a word, which is commonly used to describe branch like this one. 

</blockquote></details>

och, yeah, my bad, I forgot it's a keyword
___
*[utils/docker/run-doc-update.sh, line 60 at r6](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-MfhVM7I3woVPBNEG_3e:-MflIfIaDZbaiI0FDTXk:b9eqt9g) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5b12f9f77522cf813540a97672d3bfd993c8dda6/utils/docker/run-doc-update.sh#L60)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It works, as I'm doing changes on my local master. I don't want to change basic functionality of this script, rather make it little bit more usable. 
</blockquote></details>

ok, sure, if you make it on master then everything is clear to me

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177)* status: 42 of 43 files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[include/libpmemobj++/timed_mutex.hpp, line 31 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh8idy6ggI2loTe4xl:-MflKg4s0YOZPcK7nkjS:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/timed_mutex.hpp#L31)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

  Good catch. Done
</blockquote></details>

Done.
___
*[include/libpmemobj++/container/segment_vector.hpp, line 661 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-Mfh8zXf2bUaEJQrYW-b:-MflKeQp0ngaSFRuQ-4y:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/eda212c7bf80ff2d24498b5e0814e0abd0cf1d76/include/libpmemobj++/container/segment_vector.hpp#L661)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1177#-:-MflRDZY0_orAoOWQ0T6:bnfp4nl)* status: 42 of 43 files reviewed, all discussions resolved (waiting on @igchor and @KFilipek)

**Pull request merged**
