### PR TITLE
CI: Fix nightly build

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
There are still some issues there, but this PR cleans most of the docker related ones.

// there are some issues still, but preview with all OSes: https://github.com/lukaszstolarczuk/libpmemobj-cpp/actions/runs/2692994291

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1244)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1244#-:-MuuusDS2TcOyVxMzA-J:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
most likely some/all of these fixes are required on stable branch as well

**Comment by lukaszstolarczuk** [comment]
this PR contains a cherry-picked commit with Windows fix from stable branch

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1244#-:-N7L4izfBxkoKVPx9ozN:bnfp4nl)* status: 0 of 14 files reviewed, all discussions resolved

**Pull request merged**
