### PR TITLE
Avoid libunwind on valgrind tests

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
// tested with newest valgrind: https://github.com/lukaszstolarczuk/libpmemobj-cpp/actions/runs/1234761971

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/memcheck-libunwind.supp, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-MjcB-Ie-OYIWJaQMogR:-MjcB-Ie-OYIWJaQMogS:buxnib9) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6977a496a1c4974f70f0d010c72e7b3b3e5f40ce/tests/memcheck-libunwind.supp#L1)):*
> ```
> {
> ```

Right now I'm not sure if we want to remove it - for the debugging case, this may be useful... What do you think?

**Comment by lukaszstolarczuk** [comment]
We need this on stable-1.13 branch because we can't upgrade valgrind and our OSes (see #1173 ) without it.

**Comment by karczex** [comment]
___
*[tests/memcheck-libunwind.supp, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-MjcB-Ie-OYIWJaQMogR:-Mjhaw6AB9SAS9M3aW6J:b-35igg8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6977a496a1c4974f70f0d010c72e7b3b3e5f40ce/tests/memcheck-libunwind.supp#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Right now I'm not sure if we want to remove it - for the debugging case, this may be useful... What do you think?
</blockquote></details>

It may stop working at any time  if not tested, but yes, leave it :)

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 110 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-Mjhc4Mt8F-6V0PSP7du:-Mjhc4Mt8F-6V0PSP7dv:br4j1xt) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2772e200e94eed792c4c3e3513e678709b01d9f/utils/docker/run-build.sh#L110)):*
> ```Shell
> ###############################################################################
> function build_gcc_debug_cpp14() {
> 	VALGRIND_UNWIND=${1}
> ```

It breaks functionality of running manually 
```
bash run-build.sh build_gcc_debug_cpp14
```

You may  assign default value to VALGRIND_UNWIND and everything will work, or remove this function  from help message by removing function keyword (which is optional in bash). 

first option is probably better.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199)* status: 1 of 70 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[utils/docker/run-build.sh, line 110 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-Mjhc4Mt8F-6V0PSP7du:-MjjeX0L95bkZjx616GN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/f2772e200e94eed792c4c3e3513e678709b01d9f/utils/docker/run-build.sh#L110)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It breaks functionality of running manually 
```
bash run-build.sh build_gcc_debug_cpp14
```

You may  assign default value to VALGRIND_UNWIND and everything will work, or remove this function  from help message by removing function keyword (which is optional in bash). 

first option is probably better. 
</blockquote></details>

Done.
___
*[tests/memcheck-libunwind.supp, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-MjcB-Ie-OYIWJaQMogR:-MjjeTMN3HTyxRnUikwD:byxorcc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/6977a496a1c4974f70f0d010c72e7b3b3e5f40ce/tests/memcheck-libunwind.supp#L1)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It may stop working at any time  if not tested, but yes, leave it :) 
</blockquote></details>

I've dropped that commit.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-:-MjmuMmx-Anp3bQdnzGx:bnfp4nl)* status: 1 of 70 files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, 1 of 66 files at r3, 65 of 65 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-:-Mjmve630ZPTBCWnMs34:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1199#-:-Mjn2VfZ9n1lmtqlrjFN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
