### PR TITLE
Add example for using pool as a class member

### PR DESCRIPTION
**Pull request by karczex**
I added example for this, as it's not obvious at the first glance how
to handle pool as class member, and how to access it's data.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[examples/pool/pool_as_class_member.cpp, line 26 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT1CIiuC6XoazhXhmsW:-MT1CIiuC6XoazhXhmsX:b3kre) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L26)):*
> ```cpp
> 	/* pool object */
> 	pmem::obj::pool<persistent_data> pop;
> 	/* Pointer to data. */
> ```

?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4tih03qHRfbakuUlr:-MT4tih03qHRfbakuUls:b-7w51l1) (no related file):*
in the commit message:
1. Please drop "I added" ;) (and re-phrase I guess)
2. `it's data` -> `its data`

---
___
*[examples/pool/pool_as_class_member.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4sLYiDCB3p8WpKP1G:-MT4sLYj-P9drAnV3fSc:brnowxu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L40)):*
> ```cpp
> 			std::cerr << "Cannot open pool: " << e.what()
> 				  << std::endl
> 				  << "Trying to create new one " << std::endl;
> ```

a new one
___
*[examples/pool/pool_as_class_member.cpp, line 44 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4sMUq5lT_-g_D-yyy:-MT4sMUr5iYkuHDZuykI:b-upu498) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L44)):*
> ```cpp
> 							    PMEMOBJ_MIN_POOL);
> 		}
> 		/* Assign persistent poiner to root object. */
> ```

1. pointer (misspell)
2. to the root object
___
*[examples/pool/pool_as_class_member.cpp, line 64 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4t1Ya648xuSJpRaeN:-MT4t1Ya648xuSJpRaeO:b-6r4u2c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L64)):*
> ```cpp
> 	increment()
> 	{
> 		auto root_obj = pop.root();
> ```

maybe don't duplicate code - use `set(x+1)`
___
*[examples/pool/pool_as_class_member.cpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4tEXaEwieJs9h_xqZ:-MT4tEXb3A9j7aJhF_p8:b-6t3g25) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L72)):*
> ```cpp
> 	print()
> 	{
> 		auto root_obj = pop.root();
> ```

you don't need this line, just use it below

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: all files reviewed, 9 unresolved discussions (waiting on @karczex)

___
*[examples/pool/pool_as_class_member.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT58zqMCWyGGOLMAFx0:-MT58zqMCWyGGOLMAFx1:bb24flm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L28)):*
> ```cpp
> 	/* Pointer to data. */
> 
> 	static constexpr const char *layout = "pool_layout";
> ```

const char* is not enough?
___
*[examples/pool/pool_as_class_member.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT59x0N4tWyvRL4LgEa:-MT59x0N4tWyvRL4LgEb:b-xmaf3a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L41)):*
> ```
> 			pop = pool<persistent_data>::create("poolfile", layout,
> 							    PMEMOBJ_MIN_POOL);
> ```
if pop is still nullptr then try to create instead of doing work under risk in catch clause outside of try block
___
*[examples/pool/pool_as_class_member.cpp, line 46 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT58WDEDB5rifvmRCxg:-MT58WDEDB5rifvmRCxh:b-vs59w1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L46)):*
> ```cpp
> 		/* Assign persistent poiner to root object. */
> 	}
> ```

Foo() = delete;

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 72 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4tEXaEwieJs9h_xqZ:-MT6j-Os1PDp3WeliU28:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L72)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you don't need this line, just use it below
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 64 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4t1Ya648xuSJpRaeN:-MT6iykYCdw_kCrtTkO2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L64)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe don't duplicate code - use `set(x+1)`
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 46 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT58WDEDB5rifvmRCxg:-MT6hYJ1EhmbWtqSTLfN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L46)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Foo() = delete;
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT59x0N4tWyvRL4LgEa:-MT6qiGb6bOPBjzeO-sr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L41)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> 			pop = pool<persistent_data>::create("poolfile", layout,
> 							    PMEMOBJ_MIN_POOL);
> ```
if pop is still nullptr then try to create instead of doing work under risk in catch clause outside of try block
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4sLYiDCB3p8WpKP1G:-MT6hCpY8AF00YJghuFR:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L40)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

a new one
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 28 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT58zqMCWyGGOLMAFx0:-MT6i7VXELcWyfSzQY1K:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L28)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

const char* is not enough?
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[examples/pool/pool_as_class_member.cpp, line 26 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT1CIiuC6XoazhXhmsW:-MT6h5FoE_sdT5dwYuJ2:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L26)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Comment by karczex** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4tih03qHRfbakuUlr:-MVqwZBW4J_WyHcPQvwb:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in the commit message:
1. Please drop "I added" ;) (and re-phrase I guess)
2. `it's data` -> `its data`
</blockquote></details>

Done.

---

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[include/libpmemobj++/pool.hpp, line 47 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MVrDs0T7kh9kY-ZrPFb:-MVrDs0T7kh9kY-ZrPFc:b-7p15uh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f86e17724e7df1fe9c0c4c4f40be62cc5e57b8b/include/libpmemobj++/pool.hpp#L47)):*
> ```cpp
>  * @snippet pool/pool.cpp pool_base_example
>  *
>  * The exmple of using pool with RAII idom:
> ```

idiom

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[examples/pool/pool_as_class_member.cpp, line 44 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MT4sMUq5lT_-g_D-yyy:-MT6hRN7-j8Dkl0Tso3t:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e48fce5369e1619bddbf7891604da0e1792312fb/examples/pool/pool_as_class_member.cpp#L44)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. pointer (misspell)
2. to the root object
</blockquote></details>

Done.
___
*[include/libpmemobj++/pool.hpp, line 47 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-MVrDs0T7kh9kY-ZrPFb:-MWO2V2R5bujszTZnVbi:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/4f86e17724e7df1fe9c0c4c4f40be62cc5e57b8b/include/libpmemobj++/pool.hpp#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

idiom
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-:-MWOAJ3mAEurAS4xDzJz:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032#-:-MWcnk0l2VfbQLP4Eyas:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1032)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
