### PR TITLE
update Doxygen config and run auto doc update on F34

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
A new config file format is updated automatically using Doxygen 1.9.1 (`doxygen -u <file>` command).
And additional extra changes to fix some docs issues.

Preview: https://lukaszstolarczuk.github.io/libpmemobj-cpp/master/doxygen/index.html

- [x] merge #1073 first
- [x] drop 2 first commits
- [x] check generated docs

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[doc/libpmemobj++.Doxyfile.in, line 154 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZx5G_q3S8LOndOfJPV:-MZx5G_q3S8LOndOfJPW:blaaqec) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L154)):*
> ```
> # The default value is: NO.
> 
> INLINE_INHERITED_MEMB  = NO
> ```

We probably should enable it to properly display documentation for pool.
___
*[doc/libpmemobj++.Doxyfile.in, line 474 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZx7dEf3E1FMPSjwKLE:-MZx7dEf3E1FMPSjwKLF:b69frk6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L474)):*
> ```
> # Minimum value: 0, maximum value: 32, default value: 1.
> 
> NUM_PROC_THREADS       = 1
> ```

Did you test, how setting it to 0 fits into libpmemobj-cpp build system when building 
```
make -j$(nproc)
```
?
___
*[doc/libpmemobj++.Doxyfile.in, line 552 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZx8fll3KlS1eaOKZ5O:-MZx8fll3KlS1eaOKZ5P:bdn9j7u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L552)):*
> ```
> # The default value is: NO.
> 
> HIDE_UNDOC_MEMBERS     = YES
> ```

Are you sure it should be enabled?
___
*[doc/libpmemobj++.Doxyfile.in, line 1119 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZxBraH0BJUHpnQ_8hi:-MZxBraH0BJUHpnQ_8hj:b-dt1ovx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L1119)):*
> ```
> # The default value is: NO.
> 
> CLANG_ASSISTED_PARSING = NO
> ```

Probably not for this PR, but it may be good idea to enable this option. 
___
*[doc/libpmemobj++.Doxyfile.in, line 2316 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZxEzet-reZHhF7Etvk:-MZxEzet-reZHhF7Etvl:b2xoibv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L2316)):*
> ```
> # The default value is: NO.
> 
> HAVE_DOT               = NO
> ```

We should check what happened if we enable this, and some related options

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[doc/libpmemobj++.Doxyfile.in, line 154 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZx5G_q3S8LOndOfJPV:-MaYIzqU7PfbTjsmMfrp:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L154)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

We probably should enable it to properly display documentation for pool.
</blockquote></details>

Done.
___
*[doc/libpmemobj++.Doxyfile.in, line 474 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZx7dEf3E1FMPSjwKLE:-MaYJ-sU6ojkhf598GIe:b-g1oueq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L474)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Did you test, how setting it to 0 fits into libpmemobj-cpp build system when building 
```
make -j$(nproc)
```
?
</blockquote></details>

I'm not sure if we can do anything to make "-j" speed our docs building, but:
- I've set the above variable to 0, so it should take all the available cores
- docs are built within 10 seconds, so it's not a biggie, I believe 
___
*[doc/libpmemobj++.Doxyfile.in, line 552 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZx8fll3KlS1eaOKZ5O:-MaYJGpSCQz_-Iktpbmu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L552)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Are you sure it should be enabled?
</blockquote></details>

Done.
___
*[doc/libpmemobj++.Doxyfile.in, line 1119 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZxBraH0BJUHpnQ_8hi:-MaYJIV96OjnGhn6Vo2C:b-w1yqm2) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L1119)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Probably not for this PR, but it may be good idea to enable this option. 
</blockquote></details>

I've tried and:
- there were so many issues with this approach
- when I finally made it work, it wasn't worth it - I didn't see any improvements
___
*[doc/libpmemobj++.Doxyfile.in, line 2316 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MZxEzet-reZHhF7Etvk:-MaYJYeQ34uIh69MbT9h:b55ghut) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5aa793bf3a5a7bc903af1f02ad66d88c7e24bec5/doc/libpmemobj++.Doxyfile.in#L2316)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

We should check what happened if we enable this, and some related options
</blockquote></details>

graphs look ok, enabled it
___
*[doc/libpmemobj++.Doxyfile.in, line 841 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MaYJenEBiAjhkhxNJr4:-MaYJenEBiAjhkhxNJr5:bgq8bs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4b82b3edae51da67581212a473e16a890079765/doc/libpmemobj++.Doxyfile.in#L841)):*
> ```
> # XXX: temporarily disabled, until all members are documented
> # or unneeded files are turned off (from doxygen)
> #WARN_AS_ERROR          = @DOXYGEN_WARN_AS_ERROR@
> ```

temporarily disabled, until we skip all the docs we don't want to include or we add all the missing docs :)
___
*[doc/libpmemobj++.Doxyfile.in, line 1546 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-MaYK2dc6wB5GyYERtRf:-MaYK2dc6wB5GyYERtRg:b-auq1v5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/e4b82b3edae51da67581212a473e16a890079765/doc/libpmemobj++.Doxyfile.in#L1546)):*
> ```
> # This tag requires that the tag GENERATE_HTML is set to YES.
> 
> GENERATE_TREEVIEW      = YES
> ```

this is the new tree on the left-hand side of the docs - pls let me know if we want to keep it...

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-:-Mcsh1QQEW4HHOL22wnO:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

**Review by igchor — APPROVED** [review]
:lgtm:, please just rebase to include changes in inline_string

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1074#-:-MfCPP7_4-TnK4wvJsfR:byevkt9)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

**Comment by lukaszstolarczuk** [comment]
continued in linked (above) PR

**Pull request closed without merging**
