### PR TITLE
Update version of ndctl in install-libndctl.sh script

### PR DESCRIPTION
**Pull request by ldorau**
1) Update ndctl to v64.1
2) ndctl v64.1 depends on 'bash-completion' packages,
   so add 'bash-completion' to all Docker files

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/512)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
Actually I just realized, do we need this installation from sources? Can't we just use (lib)ndctl-devel & (lib)daxctl-devel packages? (Fed31 and Ub19.10 already has proper versions)

**Comment by ldorau** [comment]
> Actually I just realized, do we need this installation from sources? Can't we just use (lib)ndctl-devel & (lib)daxctl-devel packages? (Fed31 and Ub19.10 already has proper versions)

See https://github.com/pmem/libpmemobj-cpp/pull/519

**Comment by ldorau** [comment]
Marked as DRAFT, because it depends on https://github.com/pmem/libpmemobj-cpp/pull/517 and https://github.com/pmem/libpmemobj-cpp/pull/519 now

**Comment by ldorau** [comment]
Depends on https://github.com/pmem/libpmemobj-cpp/pull/517

**Comment by ldorau** [comment]
It is ready for review.

**Comment by ldorau** [comment]
@lukaszstolarczuk please review

**Pull request merged**
