### PR TITLE
Adjust radix_tree to template inline_string as key

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 14 of 15 files reviewed, 9 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpFIsx-vSy4zY_2j1R:-MHpFIsx-vSy4zY_2j1S:bfljwfn) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/include/libpmemobj++/string_view.hpp#L124)):*
> ```cpp
> template <typename CharT, typename Traits>
> inline basic_string_view<CharT, Traits>::basic_string_view(const CharT *data)
>     : data_(data), size_(std::char_traits<CharT>::length(data))
> ```

This should actually be Traits, not std::char_traits<...>
___
*[include/libpmemobj++/string_view.hpp, line 180 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpFNneAXlIyIbwDOzA:-MHpFNneAXlIyIbwDOzB:bp4oa1x) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/include/libpmemobj++/string_view.hpp#L180)):*
> ```cpp
> 	const basic_string_view &other) noexcept
> {
> 	int ret = std::char_traits<CharT>::compare(
> ```

Similarly here, it should be Traits, could you fix that in separate commit?
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 294 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpFVjk4yrS-Kqdc0Xc:-MHpFVjk4yrS-Kqdc0Xd:b-iz9lo3) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/include/libpmemobj++/experimental/inline_string.hpp#L294)):*
> ```cpp
>  * of the data itself.
>  */
> template <typename CharT>
> ```

You should probably also expose Traits as template parameter here.
___
*[tests/external/libcxx/map/is_transparent.h, line 129 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpOpFpA5U-OCTVTbz4:-MHpOpFpA5U-OCTVTbz5:bqicueq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/is_transparent.h#L129)):*
> ```objc
>     }
> 
> 	heterogenous_bytes_view(const std::string *value) 
> ```

I don't this this should be done in this heterogenous_bytes_view. I think we could even implement a bytes_view specialization for pmem::obj::basic_string in radix tree (the implementation could be the same as for inline_string). This way, we can just have one more macro like TRANSPARENT_COMPARE_STRING which for concurrent_map would be the same as TRANSPARENT_COMPARE and for radix would be detail::bytes_view.
___
*[tests/external/libcxx/map/map.modifiers/erase_key.pass.cpp, line 30 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpOj_-5W5jq5Ajmx05:-MHpOj_-5W5jq5Ajmx06:br9gd9c) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5307351a0d5b88754e9f2f8811795dc337022ebc/tests/external/libcxx/map/map.modifiers/erase_key.pass.cpp#L30)):*
> ```cpp
> 
> using container = container_t<int, double, TRANSPARENT_COMPARE>;
> using container2 = container_t<C2Int, double, TRANSPARENT_COMPARE>;
> ```

As contianer2 maybe you could have a container with pmem::obj::string as a key (and TRANSPARENT_COMPARE_STRING)?
___
*[tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp, line 281 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpSdm13MNf1Zoc2Pnj:-MHpSdm13MNf1Zoc2Pnk:b-gxcukc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp#L281)):*
> ```cpp
> 			Moveable mv{i + 1, 10.0};
> 			auto key = std::string(j++, 'x');
> 			r = m.insert_or_assign(key, std::move(mv));
> ```

Could you also extend this test with a testcase like this:
``` m.insert_or_assign(std::move(key), ...)``` ?
___
*[tests/external/libcxx/map/map.modifiers/try.emplace.pass.cpp, line 263 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpTzopBTiiU9zF3oyk:-MHpTzopBTiiU9zF3oyl:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.modifiers/try.emplace.pass.cpp#L263)):*
> ```cpp
> 			Moveable mv{i + 1, 10.0};
> 			auto key = std::string(j++, 'x');
> 			r = m.try_emplace(key, std::move(mv));
> ```

.
___
*[tests/radix/radix_basic.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpUPVLECRzCTjOYqEh:-MHpUPVLECRzCTjOYqEi:bz1r53n) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/radix/radix_basic.cpp#L40)):*
> ```cpp
> 	});
> 
> 	container_int::const_iterator it = r->radix_int->find("a");
> ```

this could still be auto I think
___
*[tests/radix/radix_basic.cpp, line 723 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpUitFBLcBwTPfA9vl:-MHpUitFBLcBwTPfA9vm:b-lryjly) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/radix/radix_basic.cpp#L723)):*
> ```cpp
> 		UT_ASSERT(m.size() == 10);
> 	}
> ```

Could you also verify if find and erase work fine for this specialization of uint8_t?

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: all files reviewed, 10 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/external/libcxx/map/map.ops/lower_bound0.pass.cpp, line 107 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHppXky55HnHeq1hIiR:-MHppXky55HnHeq1hIiS:b-x1jxqj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.ops/lower_bound0.pass.cpp#L107)):*
> ```cpp
> 	}
> }
> ```

Please also look at lower_bound/upper_bound tests (e.g. https://github.com/JanDorniak99/libpmemobj-cpp/blob/radix_tree_inline_string_u8t/tests/external/libcxx/map/map.ops/lower_bound.pass.cpp) There are some ifdefs for radix which could be removed I think.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: all files reviewed, 10 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/external/libcxx/map/map.ops/lower_bound0.pass.cpp, line 107 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHppXky55HnHeq1hIiR:-MHpqEBO9c7Qs0pfjoOG:b-ux0do1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.ops/lower_bound0.pass.cpp#L107)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please also look at lower_bound/upper_bound tests (e.g. https://github.com/JanDorniak99/libpmemobj-cpp/blob/radix_tree_inline_string_u8t/tests/external/libcxx/map/map.ops/lower_bound.pass.cpp) There are some ifdefs for radix which could be removed I think.
</blockquote></details>

Please take a look at other tests as well, find.pass.cpp also has some oudated ifdefs. Additionally, I don't see tests for C2Int in upper_bound.pass.cpp (and I think there should be some?)

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 6 of 17 files reviewed, 10 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/string_view.hpp, line 124 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpFIsx-vSy4zY_2j1R:-MHtgUg27Jj8IKxedKpe:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/include/libpmemobj++/string_view.hpp#L124)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This should actually be Traits, not std::char_traits<...>
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 180 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpFNneAXlIyIbwDOzA:-MHtgVG43wVJvCYh4nig:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/include/libpmemobj++/string_view.hpp#L180)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Similarly here, it should be Traits, could you fix that in separate commit?
</blockquote></details>

Done.
___
*[include/libpmemobj++/experimental/inline_string.hpp, line 294 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpFVjk4yrS-Kqdc0Xc:-MHthkjE8VKd1b86mMAQ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/include/libpmemobj++/experimental/inline_string.hpp#L294)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You should probably also expose Traits as template parameter here.
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.modifiers/erase_key.pass.cpp, line 30 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpOj_-5W5jq5Ajmx05:-MHuKal3CfMuMsTqPps_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5307351a0d5b88754e9f2f8811795dc337022ebc/tests/external/libcxx/map/map.modifiers/erase_key.pass.cpp#L30)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

As contianer2 maybe you could have a container with pmem::obj::string as a key (and TRANSPARENT_COMPARE_STRING)?
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp, line 281 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpSdm13MNf1Zoc2Pnj:-MHu10M4B5zAkEsacASX:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp#L281)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you also extend this test with a testcase like this:
``` m.insert_or_assign(std::move(key), ...)``` ?
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.modifiers/try.emplace.pass.cpp, line 263 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpTzopBTiiU9zF3oyk:-MHu11DGBZEyOqJkdzj8:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.modifiers/try.emplace.pass.cpp#L263)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/radix/radix_basic.cpp, line 40 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpUPVLECRzCTjOYqEh:-MHu-jMf1Miu19RqoHc6:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/radix/radix_basic.cpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this could still be auto I think
</blockquote></details>

Done.
___
*[tests/radix/radix_basic.cpp, line 723 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpUitFBLcBwTPfA9vl:-MHu6-kOA0cXRruJZSm0:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/radix/radix_basic.cpp#L723)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you also verify if find and erase work fine for this specialization of uint8_t?
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 12 of 17 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 279 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHuRB_6EiIrpk5Ba7Yl:-MHuRB_78BBorfDE1p6G:b-adjdoe) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/include/libpmemobj++/experimental/inline_string.hpp#L279)):*
> ```cpp
>  */
> template <typename T>
> struct real_bytes {
> ```

You could also add a comment that value() return value in bytes (it might be obvious from the name, but it's better to also describe it).
___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3149 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHuRSm389mF6Bhlk-i_:-MHuRSm389mF6Bhlk-ia:b-pkg73a) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/include/libpmemobj++/experimental/radix_tree.hpp#L3149)):*
> ```cpp
> 
> template <typename CharT, typename Traits>
> struct bytes_view<obj::basic_string<CharT, Traits>> {
> ```

You can probably merge this implementation with the one for inline_string (similarly as specialization for integral types is done - using Enable)
___
*[tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp, line 281 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHpSdm13MNf1Zoc2Pnj:-MHuRrau64cHiizPOVKA:b-z83r5d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.modifiers/insert_or_assign.pass.cpp#L281)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm, in this case the string is actually not moved (since pmem::obj::string does not take std::string by rvlaue reference. It would be nice to have (it can be in future PR) some test for insert_or_assign / try_emplace where we use something like MoveableWrapper (something which is constructed from Moveable rvalue reference) as key and pass std::move(Moveable) to those methods. The we could check if the Moveable was actually moved from? Ref:https://github.com/pmem/libpmemobj-cpp/issues/828
___
*[tests/radix/radix.hpp, line 60 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHuTkP70hkev_LLjZBX:-MHuTkP70hkev_LLjZBY:bx7alfw) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/tests/radix/radix.hpp#L60)):*
> ```cpp
> 	using CharT = typename Container::mapped_type::value_type;
> 
> 	auto s = std::basic_string<CharT>();
> ```

I think it's https://en.wikipedia.org/wiki/Most_vexing_parse tl;dr change () to {}

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 10 of 22 files reviewed, 4 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/experimental/radix_tree.hpp, line 3149 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHuRSm389mF6Bhlk-i_:-MHvD1ne-erJwcnozQJ7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/include/libpmemobj++/experimental/radix_tree.hpp#L3149)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You can probably merge this implementation with the one for inline_string (similarly as specialization for integral types is done - using Enable)
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.ops/lower_bound0.pass.cpp, line 107 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHppXky55HnHeq1hIiR:-MHufcN0AwBrwLHWIFKj:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/516fddf284be5033485861a4c4ae77d2aa57ca5c/tests/external/libcxx/map/map.ops/lower_bound0.pass.cpp#L107)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please take a look at other tests as well, find.pass.cpp also has some oudated ifdefs. Additionally, I don't see tests for C2Int in upper_bound.pass.cpp (and I think there should be some?)
</blockquote></details>

Done.
___
*[tests/radix/radix.hpp, line 60 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHuTkP70hkev_LLjZBX:-MHuhb9Q0223BgfVQGcu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/tests/radix/radix.hpp#L60)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it's https://en.wikipedia.org/wiki/Most_vexing_parse tl;dr change () to {}
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/external/libcxx/map/map.ops/count.pass.cpp, line 40 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHvdw8Z5r_tqtzNUIkj:-MHvdw8_EXlX-SkY45hv:b-5d5iur) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b800c54da79e8d88cbb5aef9e3ea0a11cd195aa6/tests/external/libcxx/map/map.ops/count.pass.cpp#L40)):*
> ```cpp
> #endif
> 
> using C = container_t<int, double, TRANSPARENT_CMP>;
> ```

Actually we should not fill the third parameter for this type. This test, among other thigs, tests whether it all works with a default param.
___
*[tests/radix/radix_tx_abort.cpp, line 534 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHvgZsx9oQ1ei8q8Bdn:-MHvgZsy7Mb8A1A_gSXK:bkryp4i) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/tests/radix/radix_tx_abort.cpp#L534)):*
> ```cpp
> 	test_insert_or_assign<container_inline_s_u8t, 1>(
> 		pop, pop.root()->radix_inline_s_u8t);
> 	test_insert<container_inline_s_u8t, 1>(pop,
> ```

Is there somethin wrong with test_insert test?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/external/libcxx/map/map.ops/count.pass.cpp, line 40 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHvdw8Z5r_tqtzNUIkj:-MHvh0xp9IqqL1eHeWDt:bwixoem) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b800c54da79e8d88cbb5aef9e3ea0a11cd195aa6/tests/external/libcxx/map/map.ops/count.pass.cpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Actually we should not fill the third parameter for this type. This test, among other thigs, tests whether it all works with a default param.
</blockquote></details>

This is mainly for concurrent_map as for radix_tree we pass some special bytes_view for tests anyway.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 18 of 22 files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[include/libpmemobj++/experimental/inline_string.hpp, line 279 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHuRB_6EiIrpk5Ba7Yl:-MHypwkxEGLHLrn5mEvN:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/include/libpmemobj++/experimental/inline_string.hpp#L279)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

You could also add a comment that value() return value in bytes (it might be obvious from the name, but it's better to also describe it).
</blockquote></details>

Done.
___
*[tests/external/libcxx/map/map.ops/count.pass.cpp, line 40 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHvdw8Z5r_tqtzNUIkj:-MHyrquI4nULPOhdZ6l7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b800c54da79e8d88cbb5aef9e3ea0a11cd195aa6/tests/external/libcxx/map/map.ops/count.pass.cpp#L40)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This is mainly for concurrent_map as for radix_tree we pass some special bytes_view for tests anyway.
</blockquote></details>

Done.
___
*[tests/radix/radix_tx_abort.cpp, line 534 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHvgZsx9oQ1ei8q8Bdn:-MHz-ni9C3H4O8T2Yngr:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/tests/radix/radix_tx_abort.cpp#L534)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is there somethin wrong with test_insert test?
</blockquote></details>

Done.

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: 19 of 22 files reviewed, 1 unresolved discussion (waiting on @igchor and @JanDorniak99)

___
*[tests/radix/radix_tx_abort.cpp, line 534 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-MHvgZsx9oQ1ei8q8Bdn:-MHzFbnU8NgsHd-NF3D_:b-h5ovqm) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ebd6fafbb71132c4b82b1051044eb065e804391/tests/radix/radix_tx_abort.cpp#L534)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm, I haven't thought about inline_string being created on stack. I think in that case, it would be better to stay with your previos approach (no insert test for inline_string). The reason is that we should test insert with exactly container::value_type type.

**Review by igchor — COMMENTED** [review]
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: all files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 6 of 15 files at r1, 6 of 11 files at r2, 5 of 10 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/885#-:-MI-XdIr3GGD1OOhc8pP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
