### PR TITLE
gha: change IMG_VER from latest to tag version on release

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1024)

### CODE REVIEW

**Comment by igchor** [comment]
Build for release with rc tag: https://github.com/igchor/libpmemobj-cpp/actions/runs/534378983
and normal tag: https://github.com/igchor/libpmemobj-cpp/actions/runs/534379693

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1024)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Comment by igchor** [comment]
Run for stable branch: https://github.com/igchor/libpmemobj-cpp/actions/runs/536790622

**Comment by igchor** [comment]
Updated non rc build: https://github.com/igchor/libpmemobj-cpp/runs/1829929849?check_suite_focus=true
rc build: https://github.com/igchor/libpmemobj-cpp/runs/1829927904?check_suite_focus=true

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1024#-:-MSh3yPa95l4vCw7U9Ig:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[.github/workflows/gha.yml, line 39 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1024#-MSh3JXp2YB5Lj6paZTw:-MSh3JXp2YB5Lj6paZTx:bx3up6h) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/0862f0ae9ae42ba59fe11d90f4e9dd9027a52b96/.github/workflows/gha.yml#L39)):*
> ```YAML
>                  "TYPE=package OS=ubuntu OS_VER=20.04"]
>     steps:
>       - name: Get release version
> ```

I'm wondering if this step and the next one are even required since we have the step for stable branches.

We create stable branch right away, a moment after the release, so the CI will start on the new stable branch and it will push the new image (with -1.x suffix)... The "on release" CI wouldn't be needed then.

**Pull request merged**
