### PR TITLE
modify slice to work with output iterators

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/slice.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN-3ijf9UzKNzamJu1l:-MN-3ijf9UzKNzamJu1m:bc58o3o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c2351df2672ecc2a13b392ff1931f565d5251ff6/include/libpmemobj++/slice.hpp#L24)):*
> ```cpp
> {
> 
> namespace slice_internal
> ```

Could you make it pmem::detail to be consitent with the rest of the lib?
___
*[include/libpmemobj++/slice.hpp, line 30 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN-36BI4sRIW12iaIyZ:-MN-36BI4sRIW12iaIy_:b-r4yh7o) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c2351df2672ecc2a13b392ff1931f565d5251ff6/include/libpmemobj++/slice.hpp#L30)):*
> ```cpp
> 
> template <typename Iterator>
> struct has_subtraction<Iterator *> : std::true_type {
> ```

shouldn't it be false_type by default? Tbh, I think you can just leave the implementation below (with std::conditional), you don'y have to add separate declaration and default case.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)* status: all files reviewed, 3 unresolved discussions (waiting on @JanDorniak99)

___
*[include/libpmemobj++/slice.hpp, line 66 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN2YM2e8eHvOAZkgyXt:-MN2YM2e8eHvOAZkgyXu:be7mw0v) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c2351df2672ecc2a13b392ff1931f565d5251ff6/include/libpmemobj++/slice.hpp#L66)):*
> ```cpp
> 
> 	/**
> 	 * Constructor taking two RandomAccess iterators which define a range.
> ```

RandomAccess only?

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/slice.hpp, line 24 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN-3ijf9UzKNzamJu1l:-MN3-jXHCMllm_0wSYuT:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c2351df2672ecc2a13b392ff1931f565d5251ff6/include/libpmemobj++/slice.hpp#L24)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you make it pmem::detail to be consitent with the rest of the lib?
</blockquote></details>

Done.
___
*[include/libpmemobj++/slice.hpp, line 30 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN-36BI4sRIW12iaIyZ:-MN3-k305EA5-LqTxpcq:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c2351df2672ecc2a13b392ff1931f565d5251ff6/include/libpmemobj++/slice.hpp#L30)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldn't it be false_type by default? Tbh, I think you can just leave the implementation below (with std::conditional), you don'y have to add separate declaration and default case.
</blockquote></details>

Done.
___
*[include/libpmemobj++/slice.hpp, line 66 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN2YM2e8eHvOAZkgyXt:-MN3-mNE4vAH8uwTR8Bl:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/c2351df2672ecc2a13b392ff1931f565d5251ff6/include/libpmemobj++/slice.hpp#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

RandomAccess only?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-:-MN30SYd55LwFWvbJrxT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @JanDorniak99)

___
*[include/libpmemobj++/slice.hpp, line 25 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN7szcu1GL1BeBU25kY:-MN7szcu1GL1BeBU25kZ:b90ig6u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53e1171aefb962cb6659c29baff59953dd8ea472/include/libpmemobj++/slice.hpp#L25)):*
> ```cpp
> template <typename Iterator>
> struct has_subtraction
>     : std::conditional<std::is_same<typename std::iterator_traits<
> ```

Could you add (or just verify one-time) if this check works properly for classes which do not have operator-() implemented? (in that case, we should get message from static_assert, not some random compile time error).

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[include/libpmemobj++/slice.hpp, line 25 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-MN7szcu1GL1BeBU25kY:-MNNVmkg3eF_I0B8Pnzz:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/53e1171aefb962cb6659c29baff59953dd8ea472/include/libpmemobj++/slice.hpp#L25)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could you add (or just verify one-time) if this check works properly for classes which do not have operator-() implemented? (in that case, we should get message from static_assert, not some random compile time error).
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-:-MNNWeId4795XVbzXouA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/987#-:-MNSoyr908rAoo3pPLEC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Pull request merged**
