### PR TITLE
Update docker images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- add new images
- fix FROM path in docker's recipe (with the best registry URL).

- [x] remove temp commit

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MT_TCBv2esXVwIbVaP4:-MT_TCBw9DR1a_zsb7VM:br8g8r8) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d6ac115b4b72f37b5ed1d7b4c1ff33a03da374bc/utils/docker/images/Dockerfile.archlinux-base-latest#L11)):*
> ```
> # Pull base image
> FROM registry.hub.docker.com/archlinux/base:latest
> MAINTAINER igor.chorazewicz@intel.com
> ```

It's pretty not fair making all commits as Lukasz S. and somebody else is marked as maintainer. I think it should be changed, because all GHA/CI things are made by you.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MT_TCBv2esXVwIbVaP4:-MT_WO9x52nSJW1Uy8qD:bovhito) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d6ac115b4b72f37b5ed1d7b4c1ff33a03da374bc/utils/docker/images/Dockerfile.archlinux-base-latest#L11)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

It's pretty not fair making all commits as Lukasz S. and somebody else is marked as maintainer. I think it should be changed, because all GHA/CI things are made by you.
</blockquote></details>

nobody's stealing my contributions - it's all in the history of git.
I believe we can leave it as is, for the consistency, that our product owner is also the "owner" of the product - it's kept here more as a contact person, which for now is Igor (as it is in the README).

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MT_TCBv2esXVwIbVaP4:-MTftjP-5hHgTWOtCOQp:b-kogs5d) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/d6ac115b4b72f37b5ed1d7b4c1ff33a03da374bc/utils/docker/images/Dockerfile.archlinux-base-latest#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

nobody's stealing my contributions - it's all in the history of git.
I believe we can leave it as is, for the consistency, that our product owner is also the "owner" of the product - it's kept here more as a contact person, which for now is Igor (as it is in the README). 
</blockquote></details>

Done.
owner != maintainer, but okey.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.fedora-rawhide, line 85 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTugGqO9aOB4z1XjgYn:-MTugGqP3vlsIxwTzxf-:b-mg9r6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.fedora-rawhide#L85)):*
> ```
> 
> # Update packages and install basic tools
> # XXX --nogpg workaround, because of Fedora rawhide signing change
> ```

It's better to just disable this image.

**Review by karczex — COMMENTED** [review]
> Reviewed 4 of 16 files at r1, 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.fedora-32, line 71 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTuiOd85xwKD0OfwsgQ:-MTuiOd85xwKD0OfwsgR:b-33cjcc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.fedora-32#L71)):*
> ```
> # Misc for our builds/CI (optional)
> ARG MISC_DEPS="\
> 	clang \
> ```

Is't clang rather BASE_DEPS ?
___
*[utils/docker/images/Dockerfile.fedora-33, line 71 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTuhmyu9IcGJhh5CCtc:-MTuhmyu9IcGJhh5CCtd:b-33cjcc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.fedora-33#L71)):*
> ```
> # Misc for our builds/CI (optional)
> ARG MISC_DEPS="\
> 	clang \
> ```

Is't clang rather BASE_DEPS ?
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 79 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTujY2_--3qpCTNaxrv:-MTujY2_--3qpCTNaxrw:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.ubuntu-18.04#L79)):*
> ```
> # Misc for our builds/CI (optional)
> ARG MISC_DEPS="\
> 	clang \
> ```

.
___
*[utils/docker/images/Dockerfile.ubuntu-devel, line 40 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTupeuS3THgkusa3tPf:-MTupeuTDO4utSP20XhB:bnovdxg) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.ubuntu-devel#L40)):*
> ```
> 	debhelper \
> 	devscripts \
> 	fakeroot \
> ```


fakeroot seems to be redundant.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: 12 of 17 files reviewed, 5 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[utils/docker/images/Dockerfile.fedora-32, line 71 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTuiOd85xwKD0OfwsgQ:-MU7dziP2Iod8GmqjrN-:bxsmjxa) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.fedora-32#L71)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Is't clang rather BASE_DEPS ?
</blockquote></details>

Nope, we can compile easily without it. Just a few tests and an example (softly) requires it, but mostly we use it in our CI to check the second compiler.
___
*[utils/docker/images/Dockerfile.fedora-33, line 71 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTuhmyu9IcGJhh5CCtc:-MU7e-eAAHgMpFyC-Agx:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.fedora-33#L71)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Is't clang rather BASE_DEPS ?
</blockquote></details>

.
___
*[utils/docker/images/Dockerfile.fedora-rawhide, line 85 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTugGqO9aOB4z1XjgYn:-MU7e0R4-qTVeAHtrewl:b2o0ki6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.fedora-rawhide#L85)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's better to just disable this image. 
</blockquote></details>

I learnt it should be fixed by now, so I removed my workaround.
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 79 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTujY2_--3qpCTNaxrv:-MU7e2La-bznU8t3KiZA:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.ubuntu-18.04#L79)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[utils/docker/images/Dockerfile.ubuntu-devel, line 40 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-MTupeuS3THgkusa3tPf:-MU7e14V1jgvsLzKZyeE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/5312d834f8abf4963972737f0952ca8bb2e94e7f/utils/docker/images/Dockerfile.ubuntu-devel#L40)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

fakeroot seems to be redundant.
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> Reviewed 3 of 16 files at r1, 2 of 9 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-:-MU8l7E9EmU3LTxtdrRP:bnfp4nl)* status: 9 of 16 files reviewed, all discussions resolved (waiting on @karczex and @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-:-MU9XlnWDZntx0Ki74i5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1031#-:-MUE8PjmCev1q0dAMLQT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
