### PR TITLE
tests: run concurrent map gdb test only on gcc

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-:-MUERSDf6Xr5_DBB3syP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-:-MUIMYg29TnXPV_EVOfV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 101 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-MUIM5uZ2UqRxUpkYSHO:-MUIM5uZ2UqRxUpkYSHP:br0upzp) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3d3d70b3da6cd7f09423502903c1efaa3e5a4322/tests/CMakeLists.txt#L101)):*
> ```CMake
> 
> # Set variable if currently used compiler is Clang
> if("${CMAKE_C_COMPILER_ID}" MATCHES "Clang" OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
> ```

nit: maybe it would be better (more future-proof) to only allow running gdb tests on gcc (which we know works). If in future we will want to test with some other compiler we would probably need to change this (unlikely)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[tests/CMakeLists.txt, line 101 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-MUIM5uZ2UqRxUpkYSHO:-MUNNNgO2YsRe1BkZnxx:b32v57) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3d3d70b3da6cd7f09423502903c1efaa3e5a4322/tests/CMakeLists.txt#L101)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: maybe it would be better (more future-proof) to only allow running gdb tests on gcc (which we know works). If in future we will want to test with some other compiler we would probably need to change this (unlikely)
</blockquote></details>

+1
___
*[tests/CMakeLists.txt, line 590 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-MUNPEbt4I-MiLJQOHhx:-MUNPEbt4I-MiLJQOHhy:b-bw87aj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3d3d70b3da6cd7f09423502903c1efaa3e5a4322/tests/CMakeLists.txt#L590)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> 	if(GDB_FOUND)
> 		build_test(concurrent_hash_map_rehash_break concurrent_hash_map_rehash_break/concurrent_hash_map_rehash_break.cpp)
> 		if(NOT WIN32)
> 			# add 2 concurrent_hash_map_rehash_break tests
> 			set(CURRENT_TEST_DIR ${CMAKE_CURRENT_SOURCE_DIR}/concurrent_hash_map_rehash_break)
> 			set(CMAKE_SCRIPT ${CURRENT_TEST_DIR}/concurrent_hash_map_rehash_break)
> 			foreach(TESTCASE RANGE 1)
> 				configure_file("${CMAKE_SCRIPT}.cmake.in" "${CMAKE_SCRIPT}_${TESTCASE}.cmake" @ONLY)
> 				add_test_generic(NAME concurrent_hash_map_rehash_break CASE ${TESTCASE} TRACERS none)
> 			endforeach()
> 		endif()
> ```
</details>


It probably would be better to wrap this logic into add_test_gdb() function. 
In such function you may call build_test() and add_test_generic() if compiler is gcc and gdb is present. In addition "-DTESTS_CONCURRENT_GDB=1" may be not needed to be set manually (probably it may be good to leave option to disable those tests)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-:-MUTCR6j8RxJV-NXY0be:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @igchor, @karczex, and @KFilipek)

___
*[tests/CMakeLists.txt, line 101 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-MUIM5uZ2UqRxUpkYSHO:-MUgi6Kj62fS6XXgWLdI:b-454po5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3d3d70b3da6cd7f09423502903c1efaa3e5a4322/tests/CMakeLists.txt#L101)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

I make sure both C and CXX compilers are set to gcc.
___
*[tests/CMakeLists.txt, line 590 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048#-MUNPEbt4I-MiLJQOHhx:-MUgiGG3BrnttscpljiQ:br4njui) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3d3d70b3da6cd7f09423502903c1efaa3e5a4322/tests/CMakeLists.txt#L590)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> 	if(GDB_FOUND)
> 		build_test(concurrent_hash_map_rehash_break concurrent_hash_map_rehash_break/concurrent_hash_map_rehash_break.cpp)
> 		if(NOT WIN32)
> 			# add 2 concurrent_hash_map_rehash_break tests
> 			set(CURRENT_TEST_DIR ${CMAKE_CURRENT_SOURCE_DIR}/concurrent_hash_map_rehash_break)
> 			set(CMAKE_SCRIPT ${CURRENT_TEST_DIR}/concurrent_hash_map_rehash_break)
> 			foreach(TESTCASE RANGE 1)
> 				configure_file("${CMAKE_SCRIPT}.cmake.in" "${CMAKE_SCRIPT}_${TESTCASE}.cmake" @ONLY)
> 				add_test_generic(NAME concurrent_hash_map_rehash_break CASE ${TESTCASE} TRACERS none)
> 			endforeach()
> 		endif()
> ```

It probably would be better to wrap this logic into add_test_gdb() function. 
In such function you may call build_test() and add_test_generic() if compiler is gcc and gdb is present. In addition "-DTESTS_CONCURRENT_GDB=1" may be not needed to be set manually (probably it may be good to leave option to disable those tests)
</blockquote></details>

hmm.. I'm not sure if that's so easy. Each gdb tests (in our CMake) checks for different things (e.g. if in Debug, if not Win32,...). I'm not sure if we require all this, but this is how we do it right now. Beside, each test has their own quirks and settings.
Maybe we could implement these tests better, but this PR was suppose to be a small fix (with a pinch of improvement for other gdb tests), but the bigger change would require a thorough testing...
And lastly, TESTS_CONCURRENT_GDB flag is implemented for now, only for this one map test ;)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1048)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Pull request merged**
