### PR TITLE
string_view: implement ops API for string_view and port proper tests

### PR DESCRIPTION
**Pull request by KFilipek**
- string_view: add string_view ops API libcxx tests
- string_view: add ops API for pmem::obj::string_view
- string_view: port libcxx ops tests to use pmem::obj::string_view

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 388 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCwgOa2qBEW4OqlblG:-MLCwgOa2qBEW4OqlblH:b791bwz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L388)):*
> ```cpp
>  * @param[in] pos position of the first character
>  * @param[in] count requested length
>  *
> ```

Please add info about possible exception here.
___
*[include/libpmemobj++/string_view.hpp, line 407 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxIBo0Kp2-hBslK62:-MLCxIBpBuX8UZrWFJlQ:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L407)):*
> ```cpp
>  * Copies the substring [pos, pos + count) to the character array pointed to by
>  * dest, where rcount is the smaller of count and size()-pos.
>  *
> ```

.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp, line 85 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxwSA81nbBjajff5G:-MLCxwSA81nbBjajff5H:b-l6mwxj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1c904c10499fe31a6b909bf1cafeb0fbabda7d25/tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp#L85)):*
> ```cpp
> 	}
> 
> #if TEST_STD_VER >= 11
> ```

remove
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp, line 125 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxy-OBYp1WwAjZdgl:-MLCxy-OBYp1WwAjZdgm:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1c904c10499fe31a6b909bf1cafeb0fbabda7d25/tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp#L125)):*
> ```cpp
> #endif
> 
> #if TEST_STD_VER > 11
> ```

.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp, line 127 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxznu3tIVKWajkV_4:-MLCxznu3tIVKWajkV_5:bb7oqv5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1c904c10499fe31a6b909bf1cafeb0fbabda7d25/tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp#L127)):*
> ```cpp
> #if TEST_STD_VER > 11
> 	{
> 		typedef std::basic_string_view<char,
> ```

std?
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp, line 409 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCyD_R-sPriIBv3H2X:-MLCyD_R-sPriIBv3H2Y:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp#L409)):*
> ```cpp
> 	}
> 
> #if TEST_STD_VER >= 11
> ```

.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp, line 451 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCyEI14bzd4yPJ_N_w:-MLCyEI14bzd4yPJ_N_x:b3kqx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp#L451)):*
> ```cpp
> #endif
> 
> #if TEST_STD_VER > 11
> ```

.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp, line 453 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCyGz9-nwp_bMu5xyT:-MLCyGz9-nwp_bMu5xyU:bb7oqv5) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp#L453)):*
> ```cpp
> #if TEST_STD_VER > 11
> 	{
> 		typedef std::basic_string_view<char,
> ```

std?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 1 of 10 files reviewed, 9 unresolved discussions (waiting on @KFilipek)

___
*[include/libpmemobj++/string_view.hpp, line 398 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxnSP7s7eNklZaYEn:-MLCxnSQDQfr9itHlXwW:bigbtad) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L398)):*
> ```cpp
> {
> 	return pos > size()
> 		? (throw std::out_of_range("string_view::substr"),
> ```

Is there any reason, you have to use this notation?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 0 of 10 files reviewed, 9 unresolved discussions (waiting on @igchor and @karczex)

___
*[include/libpmemobj++/string_view.hpp, line 388 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCwgOa2qBEW4OqlblG:-MLD5XC09IhwGYAFtaMG:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L388)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add info about possible exception here.
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 398 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxnSP7s7eNklZaYEn:-MLD5ZkN0lZ7sPcd8mx4:bi5b54f) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L398)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Is there any reason, you have to use this notation? 
</blockquote></details>

I think this workaround is to compile this function as constexpr.
You have: 
return (throw sth(), cons())
to throw and meet compiler requirement for return statement
___
*[include/libpmemobj++/string_view.hpp, line 407 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxIBo0Kp2-hBslK62:-MLD6-Vb6_cyYkNEfmRJ:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L407)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp, line 85 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxwSA81nbBjajff5G:-MLD6NgV4JvM4MlP4YVA:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1c904c10499fe31a6b909bf1cafeb0fbabda7d25/tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp#L85)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp, line 125 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxy-OBYp1WwAjZdgl:-MLD6OZt-rBfaKy7Biwu:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1c904c10499fe31a6b909bf1cafeb0fbabda7d25/tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp#L125)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp, line 127 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxznu3tIVKWajkV_4:-MLD6jRO2y2txAInvLHR:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/1c904c10499fe31a6b909bf1cafeb0fbabda7d25/tests/external/libcxx/string.view/string.view.ops/compare.pointer.pass.cpp#L127)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

std?
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp, line 409 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCyD_R-sPriIBv3H2X:-MLD6vM810vXaXE1j7dB:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp#L409)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp, line 451 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCyEI14bzd4yPJ_N_w:-MLD6wDy1bxIFJKsupru:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp#L451)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp, line 453 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCyGz9-nwp_bMu5xyT:-MLD6wWc9L8WBBqAZh8q:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/tests/external/libcxx/string.view/string.view.ops/compare.pointer_size.pass.cpp#L453)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

std?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-:-MLIaiPl3Dn0k69-gQd9:bnfp4nl)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r2, 1 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIUkNy3R3O6m040P_e:-MLIUkNy3R3O6m040P_f:b-8katn7) (no related file):*
in the last commit the second line of the commit message is redundant I believe (`- port libcxx tests`)

---
___
*[include/libpmemobj++/string_view.hpp, line 412 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLITRHX7HyhZbhqtLoy:-MLITRHX7HyhZbhqtLoz:b-kmrd7s) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L412)):*
> ```cpp
> 
> /**
>  * Returns a view of the substring [pos, pos + count), where rcount is the
> ```

rcount? did you mean to have `[pos, pos + rcount)` ?
___
*[include/libpmemobj++/string_view.hpp, line 413 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLITZxw24LTpFgoyljy:-MLITZxw24LTpFgoyljz:b5p59bi) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L413)):*
> ```cpp
> /**
>  * Returns a view of the substring [pos, pos + count), where rcount is the
>  * smaller of count and size()-pos.
> ```

pls make it `size() - pos.` (pls add missing spaces)
___
*[include/libpmemobj++/string_view.hpp, line 437 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIV53Z7vb976C2JNXz:-MLIV53Z7vb976C2JNY-:b-8mpvkz) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L437)):*
> ```cpp
> /**
>  * Copies the substring [pos, pos + count) to the character array pointed to by
>  * dest, where rcount is the smaller of count and size()-pos.
> ```

. & .
___
*[include/libpmemobj++/string_view.hpp, line 485 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIVzFSDBoWmDzOy6lq:-MLIVzFSDBoWmDzOy6lr:btkmnlc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L485)):*
> ```cpp
>  * @param[in] n1 number of characters of this view to compare
>  * @param[in] pos2 position of the first character of the given view to compare
>  * @param[in] n2 number of characters of the given view to compare
> ```

you can perhaps be more precise and point `the given view (sv)` 
___
*[include/libpmemobj++/string_view.hpp, line 541 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIWzBk61S__w4TQVTl:-MLIWzBk61S__w4TQVTm:b-i3n3vu) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L541)):*
> ```cpp
>  * @param[in] pos1 position of the first character in this view to compare
>  * @param[in] n1 number of characters of this view to compare
>  * @param[in] n2 number of characters of the given view to compare
> ```

. (and actually it's not *view* per se, that's given)
___
*[tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp, line 50 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIbpxTC7UO5gc4WJsM:-MLIbpxTC7UO5gc4WJsN:b-5ibitc) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp#L50)):*
> ```cpp
> 		}
> 	} else {
> 		sv.copy(dest1, n, pos);
> ```

do we check somehow return value?

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: all files reviewed, 8 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIUkNy3R3O6m040P_e:-MLIgWV22_Mt747Sd8Nc:b-sxsj59) (no related file):*
> in the last commit the second line of the commit message is redundant I believe (- port libcxx tests)
In my every commit you have one-line description for git log --oneline and more detailed description, but this time first line talk more, I prefer to have two-part commit message to be consistent anyway.

---
___
*[include/libpmemobj++/string_view.hpp, line 412 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLITRHX7HyhZbhqtLoy:-MLIk9AoBvqj5WAivQH_:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L412)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

rcount? did you mean to have `[pos, pos + rcount)` ?
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 413 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLITZxw24LTpFgoyljy:-MLIk9by5hEYejglB788:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L413)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls make it `size() - pos.` (pls add missing spaces)
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 437 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIV53Z7vb976C2JNXz:-MLIkFfkANpD7DdLHrkW:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L437)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. & .
</blockquote></details>

Done.
___
*[include/libpmemobj++/string_view.hpp, line 485 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIVzFSDBoWmDzOy6lq:-MLIkPREDd2oWYLvtr23:b-6y6utq) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L485)):*
> you can perhaps be more precise and point the given view (sv)
Copy-pasted from (link below), so I want to leave as is.
https://en.cppreference.com/w/cpp/string/basic_string_view/compare
___
*[include/libpmemobj++/string_view.hpp, line 541 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIWzBk61S__w4TQVTl:-MLIkrlD6eV4vwMj5wC8:bmsf30r) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/include/libpmemobj++/string_view.hpp#L541)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

. (and actually it's not *view* per se, that's given)
</blockquote></details>

Done. Right.
___
*[tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp, line 50 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIbpxTC7UO5gc4WJsM:-MLIl7VS8PxDenX97Nnu:bv1m6zj) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we check somehow return value?
</blockquote></details>

I think that UT_ASSERT below does the job

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIUkNy3R3O6m040P_e:-MLIyhkB0v3akJNijOoa:b-esvcc0) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> in the last commit the second line of the commit message is redundant I believe (- port libcxx tests)
In my every commit you have one-line description for git log --oneline and more detailed description, but this time first line talk more, I prefer to have two-part commit message to be consistent anyway.
</blockquote></details>

it seems redundant, and what redundant IMHO should be removed ;) (we can wait for some other opinion or just ignore it ;) )

---
___
*[include/libpmemobj++/string_view.hpp, line 418 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIxAGq7Jk8MPnQBpo_:-MLIxAGq7Jk8MPnQBpoa:b-oikot) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/099a78bd15c0630537183170c941355e141fecfc/include/libpmemobj++/string_view.hpp#L418)):*
> ```cpp
>  * @param[in] count requested length
>  *
>  * @return view of the substring [pos, pos + count).
> ```

`rcount` too?
___
*[tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp, line 50 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIbpxTC7UO5gc4WJsM:-MLIyN-x5fG-jesFeSj1:b622bzk) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp#L50)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I think that UT_ASSERT below does the job
</blockquote></details>

I don't think so - it checks if function did proper job and copied it properly, but it actually does not test the return value itself of the copy function

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 9 files at r2, 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @karczex, @KFilipek, and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIUkNy3R3O6m040P_e:-MLJ58uhC-7wCy405TRH:b22eaua) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it seems redundant, and what redundant IMHO should be removed ;) (we can wait for some other opinion or just ignore it ;) )
</blockquote></details>

I don't want to wait for anyone, because this PR blocks my work. Now should be okey.

---
___
*[include/libpmemobj++/string_view.hpp, line 418 at r5](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIxAGq7Jk8MPnQBpo_:-MLJ3Yjy7TBFjDttxOG-:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/099a78bd15c0630537183170c941355e141fecfc/include/libpmemobj++/string_view.hpp#L418)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`rcount` too?
</blockquote></details>

Done.
___
*[tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp, line 50 at r4](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIbpxTC7UO5gc4WJsM:-MLJ6Dv9D0Vl2Jymdh32:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/a873fa45be8d7785cc4f5fc15c575e0d7297c3c6/tests/external/libcxx/string.view/string.view.ops/copy.pass.cpp#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I don't think so - it checks if function did proper job and copied it properly, but it actually does not test the return value itself of the copy function
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 398 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxnSP7s7eNklZaYEn:-MLJ7QU1CWcRrc5DzFcn:b5ypmey) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L398)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I think this workaround is to compile this function as constexpr.
You have: 
return (throw sth(), cons())
to throw and meet compiler requirement for return statement
</blockquote></details>

correct me if I'm wrong, but you don't need to  create this basic_string_view() object. 

like in example on [cppreference](https://en.cppreference.com/w/cpp/language/constexpr)

```C++
// constexpr functions signal errors by throwing exceptions
    // in C++11, they must do so from the conditional operator ?:
    constexpr char operator[](std::size_t n) const
    {
        return n < sz ? p[n] : throw std::out_of_range("");
    }
```

compilation of this succeed on gcc9.3.0 C++11 

```C++
template <typename CharT, typename Traits>
constexpr basic_string_view<CharT, Traits>
basic_string_view<CharT, Traits>::substr(
	basic_string_view<CharT, Traits>::size_type pos,
	basic_string_view<CharT, Traits>::size_type count) const
{
	return pos > size()
		? throw std::out_of_range("string_view::substr")
		: basic_string_view(data() + pos,
				    (std::min)(count, size() - pos));
}
```

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-:-MLJCeAv-oArq672iN4_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLIUkNy3R3O6m040P_e:-MLJBGUw-6dPDApTjnIG:b-eqd3gb) (no related file):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

I don't want to wait for anyone, because this PR blocks my work. Now should be okey.
</blockquote></details>

that's why I said we can ignore it, but thanks for updating :)

---

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @karczex and @lukaszstolarczuk)

___
*[include/libpmemobj++/string_view.hpp, line 398 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-MLCxnSP7s7eNklZaYEn:-MLMuq3D2hWkLJrbFLTD:b-bth9pv) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/caad1c00e9458e2a6f837c66b9e72370324aec1a/include/libpmemobj++/string_view.hpp#L398)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

correct me if I'm wrong, but you don't need to  create this basic_string_view() object. 

like in example on [cppreference](https://en.cppreference.com/w/cpp/language/constexpr)

```C++
// constexpr functions signal errors by throwing exceptions
    // in C++11, they must do so from the conditional operator ?:
    constexpr char operator[](std::size_t n) const
    {
        return n < sz ? p[n] : throw std::out_of_range("");
    }
```

compilation of this succeed on gcc9.3.0 C++11 

```C++
template <typename CharT, typename Traits>
constexpr basic_string_view<CharT, Traits>
basic_string_view<CharT, Traits>::substr(
	basic_string_view<CharT, Traits>::size_type pos,
	basic_string_view<CharT, Traits>::size_type count) const
{
	return pos > size()
		? throw std::out_of_range("string_view::substr")
		: basic_string_view(data() + pos,
				    (std::min)(count, size() - pos));
}
```
</blockquote></details>

Done.
Works also under Clang with -std=c++11/14/17, so I've changed it like you've noticed above

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964#-:-MLN1qWq-vBlL9X0do9i:bnfp4nl)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/964)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
