### PR TITLE
common: 1.5.2 release

### PR DESCRIPTION
**Pull request by szyrom**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)

___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxuz7tBOqFBf0HcQ5P:-MIxuz7tBOqFBf0HcQ5Q:b-6hue04) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L1)):*
> ```
> Tue Oct 07 2020 Szymon Romik <szymon.romik@intel.com>
> ```

either Tue or 07 ;)
___
*[ChangeLog, line 7 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvNS856PSAtZPYPjI:-MIxvNS856PSAtZPYPjJ:bbp6xty) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L7)):*
> ```
> 	This release fixes minor bugs and typos.
> 
> 	This is the last patch release for libpmemobjc-cpp 1.5 version.
> ```

**libpmemobj-cpp** ;)
___
*[ChangeLog, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvGyP6BMJBjceUq8n:-MIxvGyP6BMJBjceUq8o:b-ix6vq4) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L11)):*
> ```
> 
> 	Notable changes:
> 	- operator[] for contigous_iterator takea signed integral instead of
> ```

`takea` -> `takes`

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)* status: all files reviewed, 4 unresolved discussions (waiting on @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvg765GLxEVAT-YN6:-MIxvg765GLxEVAT-YN7:b-t4ynb4) (no related file):*
Fedora build failed as I expected, there's no image on docker hub (we can perhaps force re-building by some dummy change e.g. in utils/docker/images dir), but Ubuntu failed because of copyright headers issue ;) - fix in CMake pls

---

**Review by szyrom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvg765GLxEVAT-YN6:-MIyQs3F96BvDNxjENze:bvie5sj) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Fedora build failed as I expected, there's no image on docker hub (we can perhaps force re-building by some dummy change e.g. in utils/docker/images dir), but Ubuntu failed because of copyright headers issue ;) - fix in CMake pls
</blockquote></details>

what do you mean by dummy change? will a new comment or an endl trigger an image rebuild?

---
___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxuz7tBOqFBf0HcQ5P:-MIyQok63AMFQvnScqPE:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

either Tue or 07 ;)
</blockquote></details>

Done.
___
*[ChangeLog, line 7 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvNS856PSAtZPYPjI:-MIyQpuL22QZb8RjfdZ7:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**libpmemobj-cpp** ;)
</blockquote></details>

Done.
___
*[ChangeLog, line 11 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvGyP6BMJBjceUq8n:-MIyQqoWCD58EoVTB6KI:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L11)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`takea` -> `takes`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)* status: all files reviewed, 2 unresolved discussions (waiting on @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvg765GLxEVAT-YN6:-MIzCp7e8T-_q1L23ri0:bfd0h8b) (no related file):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

what do you mean by dummy change? will a new comment or an endl trigger an image rebuild?
</blockquote></details>

**any** change to a `utils/docker/images/*.sh` scripts or to specific image (in this case `.../images/Dockerfile.fedora-31`) will end up in re-building the image. This is our policy for re-building.

---
___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxuz7tBOqFBf0HcQ5P:-MIzCj7m3d5Fx5l3OsoB:b-927qli) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L1)):*
<details><summary><i>Previously, szyrom (Szymon Romik) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now to be updated for Wednesday release... ;)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)

___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxuz7tBOqFBf0HcQ5P:-MJ77QO45fzCcaIKsSoS:bsmfgvs) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/7bd3cddb772eeaaadca6a66a654b2292bdd35426/ChangeLog#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now to be updated for Wednesday release... ;)
</blockquote></details>

date to be updated...
___
*[ChangeLog, line 8 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MJ77CMzDfdoSTKGCROD:-MJ77CMzDfdoSTKGCROE:b-dw0u3r) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/b10078c80e6cbfc012e1b0d17a3856d4ae147694/ChangeLog#L8)):*
> ```
> 
> 	This is the last patch release for libpmemobj-cpp 1.5 version.
> 	Maintance of this version is no longer supported.
> ```

pls drop the "last patch" and "no support" info - apparently it may be not the last one ;)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920)* status: all files reviewed, 2 unresolved discussions (waiting on @szyrom)

*[a discussion](https://reviewable.io/reviews/pmem/libpmemobj-cpp/920#-MIxvg765GLxEVAT-YN6:-MJ77Yx038yIelH6E2_5:b-g07ye4) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

**any** change to a `utils/docker/images/*.sh` scripts or to specific image (in this case `.../images/Dockerfile.fedora-31`) will end up in re-building the image. This is our policy for re-building.
</blockquote></details>

it will be done some other way (changes to come in sep. PR)

---

**Comment by lukaszstolarczuk** [comment]
continued in #1092

**Pull request closed without merging**
