### PR TITLE
Add information in README about discontinuation of project

### PR DESCRIPTION
**Pull request by szadam**
Preview: https://github.com/szadam/libpmemobj-cpp/blob/master/README.md

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @szadam and @wlemkows)

___
*[`README.md` line 200 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285#-NOFXlsc6XMHOQQeKkif:-NOFXlsd6z52ajRLax17:b-le8an1) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ae30312de1970ab92614566d3d6a2a115e114ea/README.md#L200)):*
> ```Markdown
> 
> ## Contact us
> For more information on this library, contact us using dedicated email: pmdk_support@intel.com.
> ```

pls rather use a similar message to the one worked out in the pmemstream's PR

**Review by szadam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @wlemkows)

___
*[`README.md` line 200 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285#-NOFXlsc6XMHOQQeKkif:-NPXqQD65xtd6DOMkxxv:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/8ae30312de1970ab92614566d3d6a2a115e114ea/README.md#L200)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pls rather use a similar message to the one worked out in the pmemstream's PR
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285#-:-NPXvDm7Es8UIR2XE13R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wlemkows)

**Review by wlemkows — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @szadam)

**Pull request merged**
