### PR TITLE
Properly find Valgrind on OpenSUSE

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MKt47vVAYYO5M1qa5zp:-MKt47vW41vdBo6yh3E_:b56gj5u) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/397c8179a5248c03f9b4317cda69d1041a82a9d9/utils/docker/images/Dockerfile.opensuse-leap-latest#L74)):*
> ```
> COPY install-valgrind.sh install-valgrind.sh
> RUN ./install-valgrind.sh
> ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/usr/lib/pkgconfig/
> ```

perhaps instead of that, we should update CMake somehow to look in path not only `/usr/lib64/` but also in `/usr/lib/` (which is the case here, I guess)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-:-ML7ZeKT4p6idrK6x8vq:bnfp4nl)* status: 0 of 4 files reviewed, 1 unresolved discussion

**Comment by karczex** [comment]
___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MKt47vVAYYO5M1qa5zp:-MLD-zCJ-cPTFtiSMPYb:b32v57) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/397c8179a5248c03f9b4317cda69d1041a82a9d9/utils/docker/images/Dockerfile.opensuse-leap-latest#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps instead of that, we should update CMake somehow to look in path not only `/usr/lib64/` but also in `/usr/lib/` (which is the case here, I guess)
</blockquote></details>

+1

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-:-MLD05XT9EFUgHHmQLPc:bnfp4nl)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Comment by lukaszstolarczuk** [comment]
Updated as discussed, if 'TESTS_USE_VALGRIND' is ON and no Valgrind found in the system - fail the build.
Also, I've updated Valgrind checks on Windows.

**Review by szyrom — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk and @szyrom)

___
*[utils/docker/run-build.sh, line 347 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MMVJQILEiiHpBKYn1pS:-MMVJQILEiiHpBKYn1pT:b-kuot) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3576ed926f111e5596751d797a818a637a823c31/utils/docker/run-build.sh#L347)):*
> ```Shell
> 	cmake .. -DCMAKE_BUILD_TYPE=Release \
> 		-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
> 		-DTESTS_USE_VALGRIND=OFF \
> ```

actually - is it alright that there's no valgrind found in this build? I had to add this line, because it threw me "my new cmake exception" - "valgrind not found, but TESTS_USE_VAL was set to ON"...? is this expected? I'm not sure...

**Comment by karczex** [comment]
___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 76 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MMZkC82-FSuWpjZDxvK:-MMZkC82-FSuWpjZDxvL:b-s3dxr0) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3576ed926f111e5596751d797a818a637a823c31/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L76)):*
> ```
> COPY install-valgrind.sh install-valgrind.sh
> RUN ./install-valgrind.sh
> ENV PKG_CONFIG_PATH $PKG_CONFIG_PATH:/usr/lib/pkgconfig/
> ```

You probably don't need to include /usr/lib/pkgconfig. According to pkg-config man page:
```
The default directory will always be searched after searching the path; 
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @karczex, @lukaszstolarczuk, and @szyrom)

___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 76 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MMZkC82-FSuWpjZDxvK:-MMZzkFD8AeOHnDkaLgs:btnskoh) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3576ed926f111e5596751d797a818a637a823c31/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L76)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

You probably don't need to include /usr/lib/pkgconfig. According to pkg-config man page:
```
The default directory will always be searched after searching the path; 
```
</blockquote></details>

`/usr/lib/pkgconfig/` is the path that was used by Valgrind installation and it then couldn't be find in our run-build.sh. So we need to add exactly this path - the default one on this OS is lib64, I believe. Also, see my comment above

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 224 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MO0lP4r2Woa7a_MrTe_:-MO0lP4r2Woa7a_MrTea:b-opfsx) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3576ed926f111e5596751d797a818a637a823c31/utils/docker/run-build.sh#L224)):*
> ```Shell
> 	mkdir build && cd build
> 
> 	echo "---------------------------- Error expected! ------------------------------"
> ```

Shouldn't this test be created as a separate functions (instead of inside tests_gcc_release_cpp17_no_valgrind)? Not sure if n jenkins, we might want to run something which messses with the system files?
___
*[utils/docker/run-build.sh, line 347 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MMVJQILEiiHpBKYn1pS:-MO0lk7Q-lWw0-oN2BxU:bvajxql) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3576ed926f111e5596751d797a818a637a823c31/utils/docker/run-build.sh#L347)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually - is it allright that there's no valgrind found in this buikd? I had to add this line, because it threw me "my new cmake exception" - "valgrind not found, but TESTS_USE_VAL was set to ON"...? is this expected? I'm not sure...
</blockquote></details>

I guess it's OK, since valgrind is only found through pkg-config
___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MKt47vVAYYO5M1qa5zp:-MO0lrtADMYVV_TUhD3e:b-tzwr61) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/397c8179a5248c03f9b4317cda69d1041a82a9d9/utils/docker/images/Dockerfile.opensuse-leap-latest#L74)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

But we're relying on pkg-config, not cmake to find the package.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor, @karczex, @lukaszstolarczuk, and @szyrom)

___
*[utils/docker/run-build.sh, line 224 at r3](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MO0lP4r2Woa7a_MrTe_:-MOBwHS00xFs5fqNygJL:b-896fix) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/3576ed926f111e5596751d797a818a637a823c31/utils/docker/run-build.sh#L224)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Shouldn't this test be created as a separate functions (instead of inside tests_gcc_release_cpp17_no_valgrind)? Not sure if n jenkins, we might want to run something which messses with the system files?
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MKt47vVAYYO5M1qa5zp:-MOBssF5ECtWwaKmEriE:bt09n85) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/397c8179a5248c03f9b4317cda69d1041a82a9d9/utils/docker/images/Dockerfile.opensuse-leap-latest#L74)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

But we're relying on pkg-config, not cmake to find the package.
</blockquote></details>

I think we should make it possible, right now we try to find it like this (in top-level CMake):

```
# Find Valgrind
if(PKG_CONFIG_FOUND)
	pkg_check_modules(VALGRIND QUIET valgrind)
else()
	find_package(VALGRIND QUIET)
endif()
```

so I believe, I'll file an issue to try and deliver FindValgrind script, because it seems not to work without pkg-config. It could be fixed with something like this:
https://github.com/elemental/Elemental/blob/master/cmake/modules/FindValgrind.cmake

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-:-MOf4O3A5GtsLRT7vui5:bnfp4nl)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, @lukaszstolarczuk, and @szyrom)

___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 74 at r1](https://reviewable.io/reviews/pmem/libpmemobj-cpp/961#-MKt47vVAYYO5M1qa5zp:-MOf4C-O7vJwWfVRHZEB:bqlirr6) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/397c8179a5248c03f9b4317cda69d1041a82a9d9/utils/docker/images/Dockerfile.opensuse-leap-latest#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I think we should make it possible, right now we try to find it like this (in top-level CMake):

```
# Find Valgrind
if(PKG_CONFIG_FOUND)
	pkg_check_modules(VALGRIND QUIET valgrind)
else()
	find_package(VALGRIND QUIET)
endif()
```

so I believe, I'll file an issue to try and deliver FindValgrind script, because it seems not to work without pkg-config. It could be fixed with something like this:
https://github.com/elemental/Elemental/blob/master/cmake/modules/FindValgrind.cmake
</blockquote></details>

But the main reason for using cmake to find packages is windows, on all other OSes we use pkg-config. Since valgrind is not avaialble on windows I don't see a reason for that.

**Pull request merged**
