### PR TITLE
Update cmake_build_type handling and switch default to RelWithDebInfo

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044#-:-MU8kiNLE9Vnwgk2bCPM:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 57 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044#-MUJgWDx5KtdhZ5ADAV9:-MUJgWDz59oHywGyENAS:bn9qdaf) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ecc560a79e92a9261016018e6ed49261936c9c5d/CMakeLists.txt#L57)):*
> ```CMake
> 	message(STATUS "CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
> 	if(NOT CMAKE_BUILD_TYPE IN_LIST predefined_build_types)
> 		message(WARNING "Unusual build type was set, please make sure it's proper one. "
> ```

Unusual is MinSizeRel, but something from out of the list is definitely "Wrong build type"

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[CMakeLists.txt, line 57 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044#-MUJgWDx5KtdhZ5ADAV9:-MUJkX954zfje4tf9RBI:byr4ote) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ecc560a79e92a9261016018e6ed49261936c9c5d/CMakeLists.txt#L57)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Unusual is MinSizeRel, but something from out of the list is definitely "Wrong build type"
</blockquote></details>

I'd rather disagree. I understand your point, but:
- CMake make extend the list of supported build types, and I'd rather be angry if CMake (of any project) forced fail me ;)
- anyone can extend this list and define their own build type with their own compiler flags

This warning is rather for people who mistyped some name, or use uppercase where there isn't... something like this.

**Review by karczex — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044#-:-MUTBqrQ7V-FRTkDkawD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[CMakeLists.txt, line 57 at r2](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044#-MUJgWDx5KtdhZ5ADAV9:-MUTArsI5APSYArMP9Qe:bgj700h) ([raw file](https://github.com/pmem/libpmemobj-cpp/blob/ecc560a79e92a9261016018e6ed49261936c9c5d/CMakeLists.txt#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd rather disagree. I understand your point, but:
- CMake make extend the list of supported build types, and I'd rather be angry if CMake (of any project) forced fail me ;)
- anyone can extend this list and define their own build type with their own compiler flags

This warning is rather for people who mistyped some name, or use uppercase where there isn't... something like this.
</blockquote></details>

Explained in offline discussion

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/libpmemobj-cpp/1044)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
